# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _lug_side_profile(center_x, platform_top_z, arc_center_z, radius, segments=14):
    points = [(center_x - radius, platform_top_z), (center_x + radius, platform_top_z)]
    for index in range(segments + 1):
        angle = math.radians(0.0 + 180.0 * index / segments)
        points.append((center_x + radius * math.cos(angle), arc_center_z + radius * math.sin(angle)))
    return points


def build(output_path: str = None):
    b = NXBuilder()

    # Base and raised platform.
    base_length = 180.0
    base_width = 96.0
    base_thickness = 12.0
    base_outer_fillet = 4.0
    platform_length = 96.0
    platform_width = 54.0
    platform_height = 8.0
    platform_fillet = 3.0

    # Rear bulkhead.
    bulkhead_center_x = -36.0
    bulkhead_thickness_x = 16.0
    bulkhead_width_y = 76.0
    bulkhead_height_above_base = 64.0
    bulkhead_top_edge_fillet = 4.0
    bulkhead_transition_fillet = 2.5

    # Forward clevis.
    clevis_center_x = 48.0
    clevis_lug_thickness_y = 14.0
    clevis_gap_y = 18.0
    clevis_lug_length_x = 36.0
    clevis_height_above_platform = 48.0
    clevis_arc_radius = 18.0
    clevis_hole_diameter = 12.0
    clevis_hole_center_z = 56.0
    clevis_hole_chamfer = 0.6
    pin_boss_diameter = 26.0
    pin_boss_projection = 3.0
    pin_boss_fillet = 1.5

    # Holes and pockets.
    equipment_hole_diameter = 6.0
    equipment_hole_x_abs = 32.0
    equipment_hole_y_abs = 18.0
    equipment_cbore_diameter = 11.0
    equipment_cbore_depth = 4.0
    base_attachment_hole_diameter = 8.5
    base_attachment_x_abs = 72.0
    base_attachment_y_abs = 34.0
    base_countersink_major_diameter = 17.0
    base_countersink_angle_degrees = 100.0
    dowel_hole_diameter = 5.0
    dowel_y_abs = 38.0
    dowel_chamfer = 0.3
    web_pocket_length = 42.0
    web_pocket_width = 18.0
    web_pocket_center_x = -48.0
    web_pocket_center_y_abs = 23.0
    rear_window_width_y = 30.0
    rear_window_height_z = 34.0
    rear_window_center_y_abs = 22.0
    rear_window_center_z = 42.0

    # Ribs and underside relief.
    rear_rib_thickness_y = 6.0
    rear_rib_extent_x = 34.0
    rear_rib_height_z = 46.0
    rear_rib_center_y_abs = 28.0
    rear_rib_fillet = 2.0
    clevis_rib_thickness_y = 5.0
    clevis_rib_start_x = 22.0
    clevis_rib_end_x = 48.0
    clevis_rib_fillet = 1.5
    underside_pocket_length = 42.0
    underside_pocket_width = 20.0
    underside_pocket_depth = 4.0
    underside_pocket_x_centers = (-54.0, 0.0, 54.0)

    general_hole_chamfer = 0.5
    feature_overlap = 0.6
    through_overcut = 2.0

    base_top_z = base_thickness
    platform_top_z = base_top_z + platform_height
    bulkhead_min_x = bulkhead_center_x - bulkhead_thickness_x / 2.0
    bulkhead_max_x = bulkhead_center_x + bulkhead_thickness_x / 2.0
    bulkhead_top_z = base_top_z + bulkhead_height_above_base
    lug_inner_y = clevis_gap_y / 2.0
    lug_outer_y = lug_inner_y + clevis_lug_thickness_y
    lug_center_y_abs = (lug_inner_y + lug_outer_y) / 2.0
    lug_profile = _lug_side_profile(
        clevis_center_x,
        platform_top_z - feature_overlap,
        clevis_hole_center_z,
        clevis_arc_radius,
    )
    z_through_depth = base_thickness + platform_height + through_overcut * 2.0

    b.require_positive(
        base_length=base_length,
        base_width=base_width,
        base_thickness=base_thickness,
        platform_height=platform_height,
        bulkhead_height_above_base=bulkhead_height_above_base,
        clevis_hole_diameter=clevis_hole_diameter,
    )
    b.require_min_wall(clevis_lug_thickness_y, clevis_hole_diameter, min_wall=1.0, label="clevis pin hole")
    b.require_min_wall(pin_boss_diameter, clevis_hole_diameter, min_wall=3.0, label="clevis pin boss")
    b.require_edge_distance(base_length / 2.0 - base_attachment_x_abs, base_attachment_hole_diameter, min_ratio=1.0, label="base attachment X edge")
    b.require_edge_distance(base_width / 2.0 - base_attachment_y_abs, base_attachment_hole_diameter, min_ratio=1.0, label="base attachment Y edge")
    b.require_feature_budget(boolean_operations=48, patterned_features=24, max_boolean_operations=100, max_patterned_features=80)

    body = b.rounded_box(
        base_length,
        base_width,
        base_thickness,
        radius=base_outer_fillet,
        origin=(-base_length / 2.0, -base_width / 2.0, 0.0),
        vertical_only=True,
    )

    platform = b.rounded_box(
        platform_length,
        platform_width,
        platform_height + feature_overlap,
        radius=platform_fillet,
        origin=(-platform_length / 2.0, -platform_width / 2.0, base_top_z - feature_overlap),
        vertical_only=True,
    )
    b.boolean_unite(body, platform)

    bulkhead = b.rounded_box(
        bulkhead_thickness_x,
        bulkhead_width_y,
        bulkhead_height_above_base + feature_overlap,
        radius=bulkhead_top_edge_fillet,
        origin=(bulkhead_min_x, -bulkhead_width_y / 2.0, base_top_z - feature_overlap),
        vertical_only=True,
    )
    b.boolean_unite(body, bulkhead)

    for sign in (-1.0, 1.0):
        lug = b.polygon_prism_on_plane(
            lug_profile,
            clevis_lug_thickness_y,
            origin=(0.0, sign * lug_inner_y, 0.0),
            u_axis=(1, 0, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(0, sign, 0),
        )
        b.boolean_unite(body, lug)

        boss_y_start = sign * lug_outer_y
        boss = b.cylinder(
            pin_boss_diameter,
            pin_boss_projection + feature_overlap,
            origin=(clevis_center_x, boss_y_start - sign * feature_overlap, clevis_hole_center_z),
            axis=(0, sign, 0),
        )
        b.boolean_unite(body, boss)

    # Rear bulkhead ribs, front and rear of the web.
    for y_sign in (-1.0, 1.0):
        for front_side in (False, True):
            if front_side:
                root_x = bulkhead_max_x - feature_overlap
                tip_x = root_x + rear_rib_extent_x
            else:
                root_x = bulkhead_min_x + feature_overlap
                tip_x = root_x - rear_rib_extent_x
            rib_profile = [
                (root_x, platform_top_z - feature_overlap),
                (tip_x, platform_top_z - feature_overlap),
                (root_x, platform_top_z + rear_rib_height_z),
            ]
            rib = b.polygon_prism_on_plane(
                rib_profile,
                rear_rib_thickness_y,
                origin=(0.0, y_sign * rear_rib_center_y_abs - rear_rib_thickness_y / 2.0, 0.0),
                u_axis=(1, 0, 0),
                v_axis=(0, 0, 1),
                extrude_axis=(0, 1, 0),
            )
            b.boolean_unite(body, rib)

    # Clevis side ribs outside the lugs.
    for sign in (-1.0, 1.0):
        rib_profile = [
            (clevis_rib_start_x, platform_top_z - feature_overlap),
            (clevis_rib_end_x, platform_top_z - feature_overlap),
            (clevis_rib_end_x, clevis_hole_center_z),
        ]
        rib = b.polygon_prism_on_plane(
            rib_profile,
            clevis_rib_thickness_y,
            origin=(0.0, sign * lug_outer_y - sign * feature_overlap, 0.0),
            u_axis=(1, 0, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(0, sign, 0),
        )
        b.boolean_unite(body, rib)

    # Underside material relief pockets.
    for x_center in underside_pocket_x_centers:
        b.slot_cut(
            body,
            underside_pocket_length,
            underside_pocket_width,
            underside_pocket_depth,
            center=(x_center, 0.0, -through_overcut),
            axis=(1, 0, 0),
            direction=(0, 0, 1),
        )

    # Base web lightening pockets through the base.
    for y_center in (-web_pocket_center_y_abs, web_pocket_center_y_abs):
        b.slot_cut(
            body,
            web_pocket_length,
            web_pocket_width,
            base_thickness + 2.0 * through_overcut,
            center=(web_pocket_center_x, y_center, base_top_z + through_overcut),
            axis=(1, 0, 0),
            direction=(0, 0, -1),
        )

    # Rear bulkhead triangular lightening cutouts through X.
    for y_center in (-rear_window_center_y_abs, rear_window_center_y_abs):
        tri = [
            (y_center - rear_window_width_y / 2.0, rear_window_center_z - rear_window_height_z / 2.0),
            (y_center + rear_window_width_y / 2.0, rear_window_center_z - rear_window_height_z / 2.0),
            (y_center, rear_window_center_z + rear_window_height_z / 2.0),
        ]
        cutter = b.polygon_prism_on_plane(
            tri,
            bulkhead_thickness_x + 2.0 * through_overcut,
            origin=(bulkhead_max_x + through_overcut, 0.0, 0.0),
            u_axis=(0, 1, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(-1, 0, 0),
        )
        b.boolean_subtract(body, cutter)

    # Equipment mounting counterbored holes.
    for x in (-equipment_hole_x_abs, equipment_hole_x_abs):
        for y in (-equipment_hole_y_abs, equipment_hole_y_abs):
            b.counterbore_hole(
                body,
                equipment_hole_diameter,
                z_through_depth,
                equipment_cbore_diameter,
                equipment_cbore_depth,
                position=(x, y, platform_top_z + through_overcut),
                direction=(0, 0, -1),
            )

    # Base attachment holes with simplified 100 degree countersink intent.
    countersink_depth = (base_countersink_major_diameter - base_attachment_hole_diameter) / (
        2.0 * math.tan(math.radians(base_countersink_angle_degrees / 2.0))
    )
    for x in (-base_attachment_x_abs, base_attachment_x_abs):
        for y in (-base_attachment_y_abs, base_attachment_y_abs):
            hole = b.hole(
                base_attachment_hole_diameter,
                base_thickness + 2.0 * through_overcut,
                position=(x, y, base_top_z + through_overcut),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(body, hole)
            sink = b.hole(
                base_countersink_major_diameter,
                countersink_depth + through_overcut,
                position=(x, y, base_top_z + through_overcut),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(body, sink)

    # Dowel pin holes through the base.
    for y in (-dowel_y_abs, dowel_y_abs):
        dowel = b.hole(
            dowel_hole_diameter,
            base_thickness + 2.0 * through_overcut,
            position=(0.0, y, base_top_z + through_overcut),
            direction=(0, 0, -1),
        )
        b.boolean_subtract(body, dowel)

    # Clevis pin hole through both lugs and bosses.
    clevis_pin = b.hole(
        clevis_hole_diameter,
        2.0 * (lug_outer_y + pin_boss_projection + through_overcut),
        position=(clevis_center_x, -(lug_outer_y + pin_boss_projection + through_overcut), clevis_hole_center_z),
        direction=(0, 1, 0),
    )
    b.boolean_subtract(body, clevis_pin)

    # Local transition blends.
    b.fillet(
        b.get_edges_in_box(
            body,
            min_xyz=(-platform_length / 2.0 - 1.0, -platform_width / 2.0 - 1.0, base_top_z - 1.0),
            max_xyz=(platform_length / 2.0 + 1.0, platform_width / 2.0 + 1.0, base_top_z + 1.0),
        ),
        2.0,
    )
    b.fillet(
        b.get_edges_in_box(
            body,
            min_xyz=(bulkhead_min_x - 1.0, -bulkhead_width_y / 2.0 - 1.0, platform_top_z - 1.0),
            max_xyz=(bulkhead_max_x + 1.0, bulkhead_width_y / 2.0 + 1.0, platform_top_z + 2.0),
        ),
        bulkhead_transition_fillet,
    )
    for y_sign in (-1.0, 1.0):
        for x_min, x_max in ((bulkhead_min_x - rear_rib_extent_x - 1.0, bulkhead_min_x + 1.0), (bulkhead_max_x - 1.0, bulkhead_max_x + rear_rib_extent_x + 1.0)):
            b.fillet(
                b.get_edges_in_box(
                    body,
                    min_xyz=(x_min, y_sign * rear_rib_center_y_abs - rear_rib_thickness_y / 2.0 - 1.0, platform_top_z - 1.0),
                    max_xyz=(x_max, y_sign * rear_rib_center_y_abs + rear_rib_thickness_y / 2.0 + 1.0, platform_top_z + rear_rib_height_z + 1.0),
                ),
                rear_rib_fillet,
            )
        b.fillet(
            b.get_edges_in_box(
                body,
                min_xyz=(clevis_rib_start_x - 1.0, y_sign * lug_outer_y - clevis_rib_thickness_y - 1.0, platform_top_z - 1.0),
                max_xyz=(clevis_rib_end_x + 1.0, y_sign * lug_outer_y + clevis_rib_thickness_y + 1.0, clevis_hole_center_z + 1.0),
            ),
            clevis_rib_fillet,
        )
        b.fillet(
            b.get_edges_near(body, point=(clevis_center_x, y_sign * lug_outer_y, clevis_hole_center_z), tolerance=pin_boss_diameter / 2.0 + 2.0),
            pin_boss_fillet,
        )

    # Chamfer exposed circular hole openings.
    chamfer_specs = []
    for x in (-equipment_hole_x_abs, equipment_hole_x_abs):
        for y in (-equipment_hole_y_abs, equipment_hole_y_abs):
            chamfer_specs.extend([(x, y, platform_top_z), (x, y, 0.0)])
    for x in (-base_attachment_x_abs, base_attachment_x_abs):
        for y in (-base_attachment_y_abs, base_attachment_y_abs):
            chamfer_specs.extend([(x, y, base_top_z), (x, y, 0.0)])
    for y in (-dowel_y_abs, dowel_y_abs):
        chamfer_specs.extend([(0.0, y, base_top_z), (0.0, y, 0.0)])
    for point in chamfer_specs:
        offset = dowel_chamfer if abs(point[1]) == dowel_y_abs and point[0] == 0.0 else general_hole_chamfer
        b.chamfer(b.get_edges_near(body, point=point, tolerance=0.9), offset)

    for y in (-(lug_outer_y + pin_boss_projection), lug_outer_y + pin_boss_projection):
        b.chamfer(
            b.get_edges_near(body, point=(clevis_center_x, y, clevis_hole_center_z), tolerance=0.9),
            clevis_hole_chamfer,
        )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
