# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              this_script.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys


_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _ellipse_points(y_radius, z_radius, count):
    return [
        (
            y_radius * math.cos(2.0 * math.pi * index / count),
            z_radius * math.sin(2.0 * math.pi * index / count),
        )
        for index in range(count)
    ]


def build(output_path: str = None):
    b = NXBuilder()

    # Manufacturing route: compact CNC-machined aerospace injector flange from
    # a forged/plate blank, with milled oval perimeter, drilled/reamed bores,
    # counterbores, chamfered openings, and a shallow rear face seal groove.
    # Datum scheme: primary datum face is the rear mounting face at X=0;
    # secondary datum is the injector centerline / engine axis on +X through
    # Y=0,Z=0; tertiary datum is the symmetric XZ plane.
    # Feature tree / feature plan: oval flange blank, forward hub/boss, rib
    # strut feature group as upper/lower radial support gussets, central hub
    # bore and stepped sealing seats, flange fastener counterbores, dowel holes,
    # rear sealing groove, then local edge breaks. Service port feature group:
    # no oil, borescope, instrumentation, or accessory pad ports were requested,
    # so only the specified injector bore and mounting holes are modeled.

    # Independent prompt parameters, millimeters.
    flange_width_y = 86.0
    flange_height_z = 58.0
    flange_thickness_x = 12.0
    flange_outer_fillet = 3.0
    boss_diameter = 34.0
    boss_length = 32.0
    bore_diameter = 14.0
    front_seat_diameter = 22.0
    front_seat_depth = 8.0
    second_seat_diameter = 18.0
    second_seat_depth = 10.0
    mount_hole_diameter = 7.0
    mount_hole_y = 28.0
    mount_counterbore_diameter = 13.0
    mount_counterbore_depth = 5.0
    dowel_hole_diameter = 4.0
    dowel_hole_z = 20.0
    rib_thickness_y = 5.0
    rib_length_x = 24.0
    rib_rise_z = 18.0
    rear_groove_outer_diameter = 38.0
    rear_groove_inner_diameter = 30.0
    rear_groove_depth = 1.0
    boss_transition_fillet = 2.0
    rib_transition_fillet = 2.0
    bore_step_chamfer = 0.5
    exposed_hole_chamfer = 0.8

    # Derived dimensions and robustness allowances.
    flange_radius_y = flange_width_y / 2.0
    flange_radius_z = flange_height_z / 2.0
    boss_radius = boss_diameter / 2.0
    rear_x = 0.0
    flange_front_x = rear_x + flange_thickness_x
    boss_front_x = flange_front_x + boss_length
    through_overcut = 1.5
    feature_overlap = 0.6
    cutter_overlap = 0.6
    flange_profile_segments = 72
    through_depth = boss_front_x - rear_x + 2.0 * through_overcut
    flange_cut_depth = flange_thickness_x + 2.0 * through_overcut

    b.require_positive(
        flange_width_y=flange_width_y,
        flange_height_z=flange_height_z,
        flange_thickness_x=flange_thickness_x,
        boss_diameter=boss_diameter,
        boss_length=boss_length,
        bore_diameter=bore_diameter,
        rib_thickness_y=rib_thickness_y,
        rib_length_x=rib_length_x,
        rib_rise_z=rib_rise_z,
    )
    b.require_min_wall(boss_diameter, front_seat_diameter, min_wall=4.0, label="front sealing seat")
    b.require_min_wall(front_seat_diameter, second_seat_diameter, min_wall=1.0, label="stepped sealing seat")
    b.require_min_wall(boss_diameter, bore_diameter, min_wall=6.0, label="injector bore")
    b.require_min_wall(flange_height_z, rear_groove_outer_diameter, min_wall=4.0, label="rear annular groove")
    b.require_edge_distance(flange_radius_y - mount_hole_y, mount_counterbore_diameter, min_ratio=0.8, label="mounting counterbore")
    b.require_feature_budget(boolean_operations=14, micro_holes=4, patterned_features=2)

    # Primary oval flange, rear mounting face at X=0 and front face at X=12.
    flange = b.polygon_prism_on_plane(
        _ellipse_points(flange_radius_y, flange_radius_z, flange_profile_segments),
        flange_thickness_x,
        origin=(rear_x, 0.0, 0.0),
        u_axis=(0, 1, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(1, 0, 0),
    )
    for index in range(16):
        angle = 2.0 * math.pi * index / 16.0
        y = flange_radius_y * math.cos(angle)
        z = flange_radius_z * math.sin(angle)
        b.fillet(
            b.get_edges_in_box(
                flange,
                min_xyz=(rear_x - 0.5, y - 7.0, z - 7.0),
                max_xyz=(flange_front_x + 0.5, y + 7.0, z + 7.0),
            ),
            flange_outer_fillet,
        )

    # Forward injector boss, deliberately overlapped into the flange for a robust union.
    boss = b.cylinder(
        boss_diameter,
        boss_length + feature_overlap,
        origin=(flange_front_x - feature_overlap, 0.0, 0.0),
        axis=(1, 0, 0),
    )
    b.boolean_unite(flange, boss)
    b.fillet(
        b.get_edges_in_box(
            flange,
            min_xyz=(flange_front_x - 1.5, -boss_radius - 1.5, -boss_radius - 1.5),
            max_xyz=(flange_front_x + 1.5, boss_radius + 1.5, boss_radius + 1.5),
        ),
        boss_transition_fillet,
    )

    # Upper and lower triangular reinforcing ribs in the XZ plane, mirrored about XZ.
    top_rib = b.polygon_prism_on_plane(
        [(0.0, 0.0), (rib_length_x + feature_overlap, 0.0), (0.0, rib_rise_z + feature_overlap)],
        rib_thickness_y,
        origin=(flange_front_x - feature_overlap, -rib_thickness_y / 2.0, boss_radius - 1.0),
        u_axis=(1, 0, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(0, 1, 0),
    )
    b.boolean_unite(flange, top_rib)
    lower_rib = b.polygon_prism_on_plane(
        [(0.0, 0.0), (rib_length_x + feature_overlap, 0.0), (0.0, -rib_rise_z - feature_overlap)],
        rib_thickness_y,
        origin=(flange_front_x - feature_overlap, -rib_thickness_y / 2.0, -boss_radius + 1.0),
        u_axis=(1, 0, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(0, 1, 0),
    )
    b.boolean_unite(flange, lower_rib)
    b.fillet(
        b.get_edges_in_box(
            flange,
            min_xyz=(flange_front_x - 1.5, -rib_thickness_y, boss_radius - 2.0),
            max_xyz=(flange_front_x + rib_length_x + 1.0, rib_thickness_y, boss_radius + rib_rise_z + 2.0),
        ),
        rib_transition_fillet,
    )
    b.fillet(
        b.get_edges_in_box(
            flange,
            min_xyz=(flange_front_x - 1.5, -rib_thickness_y, -boss_radius - rib_rise_z - 2.0),
            max_xyz=(flange_front_x + rib_length_x + 1.0, rib_thickness_y, -boss_radius + 2.0),
        ),
        rib_transition_fillet,
    )

    # Central through bore and stepped sealing seats from the boss front face.
    bore = b.hole(
        bore_diameter,
        through_depth,
        position=(rear_x - through_overcut, 0.0, 0.0),
        direction=(1, 0, 0),
    )
    b.boolean_subtract(flange, bore)
    first_seat = b.hole(
        front_seat_diameter,
        front_seat_depth + cutter_overlap,
        position=(boss_front_x + cutter_overlap / 2.0, 0.0, 0.0),
        direction=(-1, 0, 0),
    )
    b.boolean_subtract(flange, first_seat)
    second_seat = b.hole(
        second_seat_diameter,
        second_seat_depth + cutter_overlap,
        position=(boss_front_x - front_seat_depth + cutter_overlap / 2.0, 0.0, 0.0),
        direction=(-1, 0, 0),
    )
    b.boolean_subtract(flange, second_seat)

    # Rear annular sealing groove around the central bore.
    b.annular_groove(
        flange,
        outer_diameter=rear_groove_outer_diameter,
        inner_diameter=rear_groove_inner_diameter,
        depth=rear_groove_depth,
        position=(rear_x - cutter_overlap / 2.0, 0.0, 0.0),
        direction=(1, 0, 0),
        cutter_overlap=cutter_overlap,
    )

    # Flange fasteners: two through mounting holes with front counterbores.
    for y in (-mount_hole_y, mount_hole_y):
        b.counterbore_hole(
            flange,
            mount_hole_diameter,
            flange_cut_depth,
            mount_counterbore_diameter,
            mount_counterbore_depth,
            position=(flange_front_x + through_overcut / 2.0, y, 0.0),
            direction=(-1, 0, 0),
        )

    # Dowel holes through the flange.
    for z in (-dowel_hole_z, dowel_hole_z):
        dowel = b.hole(
            dowel_hole_diameter,
            flange_cut_depth,
            position=(rear_x - through_overcut, 0.0, z),
            direction=(1, 0, 0),
        )
        b.boolean_subtract(flange, dowel)

    # Exposed opening chamfers and smaller bore-step edge breaks.
    opening_boxes = [
        ((rear_x - 0.5, -8.0, -8.0), (rear_x + 0.8, 8.0, 8.0), exposed_hole_chamfer),
        ((boss_front_x - 0.8, -12.0, -12.0), (boss_front_x + 0.8, 12.0, 12.0), exposed_hole_chamfer),
        ((boss_front_x - front_seat_depth - 0.8, -12.0, -12.0), (boss_front_x - front_seat_depth + 0.8, 12.0, 12.0), bore_step_chamfer),
        ((boss_front_x - front_seat_depth - second_seat_depth - 0.8, -10.0, -10.0), (boss_front_x - front_seat_depth - second_seat_depth + 0.8, 10.0, 10.0), bore_step_chamfer),
    ]
    for min_xyz, max_xyz, chamfer_offset in opening_boxes:
        b.chamfer(b.get_edges_in_box(flange, min_xyz=min_xyz, max_xyz=max_xyz), chamfer_offset)

    for y in (-mount_hole_y, mount_hole_y):
        for x_center, radius in ((rear_x, 5.0), (flange_front_x, 8.0), (flange_front_x - mount_counterbore_depth, 8.0)):
            b.chamfer(
                b.get_edges_in_box(
                    flange,
                    min_xyz=(x_center - 0.8, y - radius, -radius),
                    max_xyz=(x_center + 0.8, y + radius, radius),
                ),
                exposed_hole_chamfer,
            )

    for z in (-dowel_hole_z, dowel_hole_z):
        for x_center in (rear_x, flange_front_x):
            b.chamfer(
                b.get_edges_in_box(
                    flange,
                    min_xyz=(x_center - 0.8, -4.0, z - 4.0),
                    max_xyz=(x_center + 0.8, 4.0, z + 4.0),
                ),
                exposed_hole_chamfer,
            )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
