# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _unit_between(start, end):
    dx = end[0] - start[0]
    dy = end[1] - start[1]
    dz = end[2] - start[2]
    length = math.sqrt(dx * dx + dy * dy + dz * dz)
    return (dx / length, dy / length, dz / length), length


def _offset(point, direction, distance):
    return (
        point[0] + direction[0] * distance,
        point[1] + direction[1] * distance,
        point[2] + direction[2] * distance,
    )


def build(output_path: str = None):
    b = NXBuilder()

    # Manifold body and raised valve pad.
    body_length = 150.0
    body_width = 72.0
    body_height = 46.0
    body_vertical_fillet = 3.0
    body_edge_chamfer = 1.5
    pad_length = 86.0
    pad_width = 48.0
    pad_height = 4.0
    pad_fillet = 2.0

    # Valve bore and mounting holes.
    valve_bore_diameter = 24.0
    valve_bore_depth = 34.0
    valve_counterbore_diameter = 32.0
    valve_counterbore_depth = 6.0
    valve_mount_hole_diameter = 6.0
    valve_mount_hole_depth = 24.0
    valve_mount_x_abs = 32.0
    valve_mount_y_abs = 18.0
    valve_mount_cbore_diameter = 11.0
    valve_mount_cbore_depth = 5.0

    # Hydraulic passages.
    main_port_diameter = 12.0
    main_port_z = 24.0
    passage_intersection_overlap = 0.8
    side_port_diameter = 10.0
    side_port_x_values = (-38.0, 38.0)
    side_port_z = 26.0
    side_boss_diameter = 24.0
    side_boss_projection = 3.0
    side_boss_fillet = 1.5
    aux_passage_diameter = 6.0
    aux_passages = [
        ((-16.0, 0.0, 36.0), (-38.0, -18.0, 24.0)),
        ((16.0, 0.0, 36.0), (38.0, 18.0, 24.0)),
    ]

    # Top sealing features and inferred valve interface openings.
    seal_groove_width = 1.2
    seal_groove_depth = 0.8
    seal_groove_bottom_radius = 0.3
    small_interface_port_diameter = 6.0
    return_port_diameter = 8.0
    small_interface_port_depth = 18.0
    interface_port_centers = [(-22.0, -12.0), (-22.0, 12.0), (22.0, -12.0), (22.0, 12.0)]
    return_port_center = (0.0, -22.0)

    # Mounting, dowels, pockets, panels, and edge treatment.
    base_mount_hole_diameter = 8.5
    base_mount_x_abs = 60.0
    base_mount_y_abs = 26.0
    base_mount_cbore_diameter = 15.0
    base_mount_cbore_depth = 7.0
    dowel_hole_diameter = 5.0
    dowel_x_abs = 48.0
    dowel_depth = 14.0
    side_pocket_length = 72.0
    side_pocket_height = 22.0
    side_pocket_depth = 3.0
    panel_length = 24.0
    panel_width = 10.0
    panel_depth = 0.5
    panel_x_abs = 58.0
    circular_chamfer = 1.0
    dowel_chamfer = 0.3
    pocket_edge_fillet = 2.0
    feature_overlap = 0.6
    through_overcut = 2.0

    top_z = body_height
    pad_top_z = body_height + pad_height
    half_length = body_length / 2.0
    half_width = body_width / 2.0
    main_port_y_abs = (
        valve_bore_diameter / 2.0
        + main_port_diameter / 2.0
        - passage_intersection_overlap
    )
    main_port_y_values = (-main_port_y_abs, main_port_y_abs)

    b.require_positive(
        body_length=body_length,
        body_width=body_width,
        body_height=body_height,
        pad_height=pad_height,
        valve_bore_diameter=valve_bore_diameter,
        main_port_diameter=main_port_diameter,
        side_port_diameter=side_port_diameter,
    )
    b.require_min_wall(body_width, side_boss_diameter, min_wall=8.0, label="side plug boss envelope")
    b.require_edge_distance(half_length - base_mount_x_abs, base_mount_hole_diameter, min_ratio=1.0, label="base mount X edge")
    b.require_edge_distance(half_width - base_mount_y_abs, base_mount_hole_diameter, min_ratio=1.0, label="base mount Y edge")
    b.require_feature_budget(boolean_operations=58, patterned_features=28, max_boolean_operations=120, max_patterned_features=90)

    # Primary solids.
    body = b.rounded_box(
        body_length,
        body_width,
        body_height,
        radius=body_vertical_fillet,
        origin=(-half_length, -half_width, 0.0),
        vertical_only=True,
    )
    b.chamfer(b.get_top_edges(body), body_edge_chamfer)
    b.chamfer(b.get_bottom_edges(body), body_edge_chamfer)

    pad = b.rounded_box(
        pad_length,
        pad_width,
        pad_height + feature_overlap,
        radius=pad_fillet,
        origin=(-pad_length / 2.0, -pad_width / 2.0, top_z - feature_overlap),
        vertical_only=True,
    )
    b.boolean_unite(body, pad)

    # Side plug bosses.
    for x in side_port_x_values:
        for sign in (-1.0, 1.0):
            boss = b.cylinder(
                side_boss_diameter,
                side_boss_projection + feature_overlap,
                origin=(x, sign * (half_width - feature_overlap), side_port_z),
                axis=(0, sign, 0),
            )
            b.boolean_unite(body, boss)

    # Valve bore, inferred top interface ports, and sealing grooves.
    b.counterbore_hole(
        body,
        valve_bore_diameter,
        valve_bore_depth,
        valve_counterbore_diameter,
        valve_counterbore_depth,
        position=(0.0, 0.0, pad_top_z + through_overcut),
        direction=(0, 0, -1),
    )

    for x, y in interface_port_centers:
        port = b.hole(
            small_interface_port_diameter,
            small_interface_port_depth + through_overcut,
            position=(x, y, pad_top_z + through_overcut),
            direction=(0, 0, -1),
        )
        b.boolean_subtract(body, port)
    return_port = b.hole(
        return_port_diameter,
        small_interface_port_depth + through_overcut,
        position=(return_port_center[0], return_port_center[1], pad_top_z + through_overcut),
        direction=(0, 0, -1),
    )
    b.boolean_subtract(body, return_port)

    groove_specs = [
        ((0.0, 0.0), valve_counterbore_diameter + 6.0),
        ((-22.0, -12.0), small_interface_port_diameter + 7.0),
        ((-22.0, 12.0), small_interface_port_diameter + 7.0),
        ((22.0, -12.0), small_interface_port_diameter + 7.0),
        ((22.0, 12.0), small_interface_port_diameter + 7.0),
        (return_port_center, return_port_diameter + 7.0),
    ]
    for (x, y), inner_diameter in groove_specs:
        b.annular_groove(
            body,
            outer_diameter=inner_diameter + 2.0 * seal_groove_width,
            inner_diameter=inner_diameter,
            depth=seal_groove_depth,
            position=(x, y, pad_top_z + 0.2),
            direction=(0, 0, -1),
            cutter_overlap=0.2,
        )

    # Valve mounting and base mounting holes with counterbores.
    for x in (-valve_mount_x_abs, valve_mount_x_abs):
        for y in (-valve_mount_y_abs, valve_mount_y_abs):
            b.counterbore_hole(
                body,
                valve_mount_hole_diameter,
                valve_mount_hole_depth,
                valve_mount_cbore_diameter,
                valve_mount_cbore_depth,
                position=(x, y, pad_top_z + through_overcut),
                direction=(0, 0, -1),
            )

    for x in (-base_mount_x_abs, base_mount_x_abs):
        for y in (-base_mount_y_abs, base_mount_y_abs):
            b.counterbore_hole(
                body,
                base_mount_hole_diameter,
                body_height + 2.0 * through_overcut,
                base_mount_cbore_diameter,
                base_mount_cbore_depth,
                position=(x, y, top_z + through_overcut),
                direction=(0, 0, -1),
            )

    # Bottom blind dowel holes.
    for x in (-dowel_x_abs, dowel_x_abs):
        dowel = b.hole(
            dowel_hole_diameter,
            dowel_depth + through_overcut,
            position=(x, 0.0, -through_overcut),
            direction=(0, 0, 1),
        )
        b.boolean_subtract(body, dowel)

    # Hydraulic through-passages.
    for y in main_port_y_values:
        port = b.hole(
            main_port_diameter,
            body_length + 2.0 * through_overcut,
            position=(-half_length - through_overcut, y, main_port_z),
            direction=(1, 0, 0),
        )
        b.boolean_subtract(body, port)

    for x in side_port_x_values:
        port = b.hole(
            side_port_diameter,
            body_width + 2.0 * side_boss_projection + 2.0 * through_overcut,
            position=(x, -half_width - side_boss_projection - through_overcut, side_port_z),
            direction=(0, 1, 0),
        )
        b.boolean_subtract(body, port)

    for start, end in aux_passages:
        direction, center_distance = _unit_between(start, end)
        origin = _offset(start, direction, -through_overcut)
        aux = b.hole(
            aux_passage_diameter,
            center_distance + 2.0 * through_overcut,
            position=origin,
            direction=direction,
        )
        b.boolean_subtract(body, aux)

    # Long-side weight-reduction pockets and top ID panels.
    for sign in (-1.0, 1.0):
        b.slot_cut(
            body,
            side_pocket_length,
            side_pocket_height,
            side_pocket_depth,
            center=(0.0, sign * (half_width + through_overcut), body_height / 2.0),
            axis=(1, 0, 0),
            direction=(0, -sign, 0),
        )
        b.fillet(
            b.get_edges_in_box(
                body,
                min_xyz=(-side_pocket_length / 2.0 - 2.0, sign * half_width - 4.0, body_height / 2.0 - side_pocket_height / 2.0 - 2.0),
                max_xyz=(side_pocket_length / 2.0 + 2.0, sign * half_width + 4.0, body_height / 2.0 + side_pocket_height / 2.0 + 2.0),
            ),
            pocket_edge_fillet,
        )

    for x in (-panel_x_abs, panel_x_abs):
        b.slot_cut(
            body,
            panel_length,
            panel_width,
            panel_depth,
            center=(x, 0.0, top_z + through_overcut),
            axis=(1, 0, 0),
            direction=(0, 0, -1),
        )

    # Local boss transition blends.
    for x in side_port_x_values:
        for sign in (-1.0, 1.0):
            b.fillet(
                b.get_edges_near(body, point=(x, sign * half_width, side_port_z), tolerance=side_boss_diameter / 2.0 + 2.0),
                side_boss_fillet,
            )

    # Chamfer exposed circular openings.
    chamfer_points = []
    chamfer_points.extend([(0.0, 0.0, pad_top_z), (0.0, 0.0, pad_top_z - valve_counterbore_depth)])
    for x, y in interface_port_centers:
        chamfer_points.append((x, y, pad_top_z))
    chamfer_points.append((return_port_center[0], return_port_center[1], pad_top_z))
    for x in (-valve_mount_x_abs, valve_mount_x_abs):
        for y in (-valve_mount_y_abs, valve_mount_y_abs):
            chamfer_points.append((x, y, pad_top_z))
    for x in (-base_mount_x_abs, base_mount_x_abs):
        for y in (-base_mount_y_abs, base_mount_y_abs):
            chamfer_points.extend([(x, y, top_z), (x, y, 0.0)])
    for x in (-dowel_x_abs, dowel_x_abs):
        b.chamfer(b.get_edges_near(body, point=(x, 0.0, 0.0), tolerance=0.8), dowel_chamfer)
    for y in main_port_y_values:
        chamfer_points.extend([(-half_length, y, main_port_z), (half_length, y, main_port_z)])
    for x in side_port_x_values:
        chamfer_points.extend([(x, -half_width - side_boss_projection, side_port_z), (x, half_width + side_boss_projection, side_port_z)])

    for point in chamfer_points:
        b.chamfer(b.get_edges_near(body, point=point, tolerance=1.0), circular_chamfer)

    # Preserve explicit groove-bottom-radius intent in a named parameter; localized NX fillets
    # around the dense groove topology should be verified in NX before increasing detail.
    _ = seal_groove_bottom_radius

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
