# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _unit_xz(angle_degrees):
    angle = math.radians(angle_degrees)
    return (math.cos(angle), math.sin(angle))


def _xz_point(origin, u_axis, v_axis, u, v):
    return (origin[0] + u_axis[0] * u + v_axis[0] * v, origin[1] + u_axis[1] * u + v_axis[1] * v)


def _tapered_arm_points(start_u, end_u, start_width, end_width, radius_start=0.0, radius_end=0.0):
    return [
        (start_u, -start_width / 2.0 + radius_start),
        (start_u + radius_start, -start_width / 2.0),
        (end_u - radius_end, -end_width / 2.0),
        (end_u, -end_width / 2.0 + radius_end),
        (end_u, end_width / 2.0 - radius_end),
        (end_u - radius_end, end_width / 2.0),
        (start_u + radius_start, start_width / 2.0),
        (start_u, start_width / 2.0 - radius_start),
    ]


def _transform_profile(points, origin, u_axis, v_axis):
    return [_xz_point(origin, u_axis, v_axis, u, v) for u, v in points]


def build(output_path: str = None):
    b = NXBuilder()

    # Main hub and bearing geometry.
    hub_diameter = 56.0
    hub_thickness_y = 18.0
    pivot_bore_diameter = 22.0
    bearing_seat_diameter = 34.0
    bearing_seat_depth = 3.0

    # Primary arm and end lug.
    primary_length = 92.0
    primary_arm_thickness_y = 14.0
    primary_root_width_z = 34.0
    primary_end_width_z = 22.0
    primary_end_lug_diameter = 32.0
    primary_end_hole_diameter = 10.0
    primary_root_blend_radius = 10.0

    # Secondary arm and end lug.
    secondary_angle_from_positive_x = 180.0 - 38.0
    secondary_length = 72.0
    secondary_arm_thickness_y = 12.0
    secondary_root_width = 30.0
    secondary_end_width = 20.0
    secondary_end_lug_diameter = 28.0
    secondary_end_hole_diameter = 8.0
    secondary_root_blend_radius = 8.0

    # Cable clevis.
    clevis_angle_from_positive_x = 180.0 + 35.0
    clevis_ear_thickness_y = 8.0
    clevis_gap_y = 10.0
    clevis_extension_from_hub = 38.0
    clevis_end_radius = 10.0
    clevis_hole_diameter = 6.0
    clevis_hole_from_hub_surface = 30.0

    # Pockets, ribs, and edge treatment.
    primary_pocket_depth = 2.5
    primary_pocket_margin = 5.0
    primary_hole_margin = 6.0
    secondary_pocket_depth = 2.0
    secondary_pocket_margin = 5.0
    secondary_hole_margin = 6.0
    rib_width = 4.0
    rib_raise = 2.0
    rib_fillet = 2.0
    major_external_fillet = 2.0
    pocket_edge_fillet = 1.0
    hole_chamfer = 0.5
    feature_overlap = 0.6
    through_overcut = 2.0

    hub_radius = hub_diameter / 2.0
    primary_u = (1.0, 0.0)
    primary_v = (0.0, 1.0)
    secondary_u = _unit_xz(secondary_angle_from_positive_x)
    secondary_v = (-secondary_u[1], secondary_u[0])
    clevis_u = _unit_xz(clevis_angle_from_positive_x)
    clevis_v = (-clevis_u[1], clevis_u[0])

    secondary_end_xz = (secondary_u[0] * secondary_length, secondary_u[1] * secondary_length)
    clevis_root_u = hub_radius - feature_overlap
    clevis_end_u = hub_radius + clevis_extension_from_hub
    clevis_hole_u = hub_radius + clevis_hole_from_hub_surface
    clevis_hole_xz = _xz_point((0.0, 0.0), clevis_u, clevis_v, clevis_hole_u, 0.0)

    b.require_positive(
        hub_diameter=hub_diameter,
        hub_thickness_y=hub_thickness_y,
        pivot_bore_diameter=pivot_bore_diameter,
        primary_length=primary_length,
        secondary_length=secondary_length,
        clevis_extension_from_hub=clevis_extension_from_hub,
    )
    b.require_min_wall(hub_diameter, bearing_seat_diameter, min_wall=8.0, label="hub bearing seat")
    b.require_min_wall(primary_end_lug_diameter, primary_end_hole_diameter, min_wall=6.0, label="primary lug hole")
    b.require_min_wall(secondary_end_lug_diameter, secondary_end_hole_diameter, min_wall=5.0, label="secondary lug hole")
    b.require_min_wall(clevis_end_radius * 2.0, clevis_hole_diameter, min_wall=4.0, label="clevis ear hole")
    b.require_feature_budget(boolean_operations=44, patterned_features=20, max_boolean_operations=100, max_patterned_features=80)

    # Primary solids: hub, tapered arms, end lugs, and clevis ears.
    body = b.cylinder(
        hub_diameter,
        hub_thickness_y,
        origin=(0.0, -hub_thickness_y / 2.0, 0.0),
        axis=(0, 1, 0),
    )

    primary_profile = _transform_profile(
        _tapered_arm_points(
            hub_radius - feature_overlap,
            primary_length,
            primary_root_width_z,
            primary_end_width_z,
            radius_start=4.0,
            radius_end=5.0,
        ),
        (0.0, 0.0),
        primary_u,
        primary_v,
    )
    primary_arm = b.polygon_prism_on_plane(
        primary_profile,
        primary_arm_thickness_y,
        origin=(0.0, -primary_arm_thickness_y / 2.0, 0.0),
        u_axis=(1, 0, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(0, 1, 0),
    )
    b.boolean_unite(body, primary_arm)

    primary_lug = b.cylinder(
        primary_end_lug_diameter,
        primary_arm_thickness_y,
        origin=(primary_length, -primary_arm_thickness_y / 2.0, 0.0),
        axis=(0, 1, 0),
    )
    b.boolean_unite(body, primary_lug)

    secondary_profile = _transform_profile(
        _tapered_arm_points(
            hub_radius - feature_overlap,
            secondary_length,
            secondary_root_width,
            secondary_end_width,
            radius_start=4.0,
            radius_end=4.0,
        ),
        (0.0, 0.0),
        secondary_u,
        secondary_v,
    )
    secondary_arm = b.polygon_prism_on_plane(
        secondary_profile,
        secondary_arm_thickness_y,
        origin=(0.0, -secondary_arm_thickness_y / 2.0, 0.0),
        u_axis=(1, 0, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(0, 1, 0),
    )
    b.boolean_unite(body, secondary_arm)

    secondary_lug = b.cylinder(
        secondary_end_lug_diameter,
        secondary_arm_thickness_y,
        origin=(secondary_end_xz[0], -secondary_arm_thickness_y / 2.0, secondary_end_xz[1]),
        axis=(0, 1, 0),
    )
    b.boolean_unite(body, secondary_lug)

    clevis_ear_center_y_abs = clevis_gap_y / 2.0 + clevis_ear_thickness_y / 2.0
    clevis_center_u = (clevis_root_u + clevis_end_u - clevis_end_radius) / 2.0
    clevis_rect_length = clevis_end_u - clevis_root_u - clevis_end_radius
    clevis_rect_center_xz = _xz_point((0.0, 0.0), clevis_u, clevis_v, clevis_center_u, 0.0)
    clevis_tip_xz = _xz_point((0.0, 0.0), clevis_u, clevis_v, clevis_end_u - clevis_end_radius, 0.0)
    for sign in (-1.0, 1.0):
        ear_rect = b.oriented_box(
            clevis_rect_length,
            clevis_end_radius * 2.0,
            clevis_ear_thickness_y,
            center=(clevis_rect_center_xz[0], sign * clevis_ear_center_y_abs, clevis_rect_center_xz[1]),
            u_axis=(clevis_u[0], 0, clevis_u[1]),
            v_axis=(clevis_v[0], 0, clevis_v[1]),
            w_axis=(0, 1, 0),
        )
        b.boolean_unite(body, ear_rect)
        ear_end = b.cylinder(
            clevis_end_radius * 2.0,
            clevis_ear_thickness_y,
            origin=(clevis_tip_xz[0], sign * (clevis_ear_center_y_abs - clevis_ear_thickness_y / 2.0), clevis_tip_xz[1]),
            axis=(0, sign, 0),
        )
        b.boolean_unite(body, ear_end)

    # Shallow side-face lightening pockets.
    primary_pocket_profile = _transform_profile(
        _tapered_arm_points(
            hub_radius + primary_pocket_margin,
            primary_length - primary_end_lug_diameter / 2.0 - primary_hole_margin,
            primary_root_width_z - 2.0 * primary_pocket_margin,
            primary_end_width_z - 2.0 * primary_pocket_margin,
            radius_start=4.0,
            radius_end=4.0,
        ),
        (0.0, 0.0),
        primary_u,
        primary_v,
    )
    secondary_pocket_profile = _transform_profile(
        _tapered_arm_points(
            hub_radius + secondary_pocket_margin,
            secondary_length - secondary_end_lug_diameter / 2.0 - secondary_hole_margin,
            secondary_root_width - 2.0 * secondary_pocket_margin,
            secondary_end_width - 2.0 * secondary_pocket_margin,
            radius_start=3.0,
            radius_end=3.0,
        ),
        (0.0, 0.0),
        secondary_u,
        secondary_v,
    )
    for sign in (-1.0, 1.0):
        pocket_start_y = sign * (primary_arm_thickness_y / 2.0 + through_overcut)
        pocket = b.polygon_prism_on_plane(
            primary_pocket_profile,
            primary_pocket_depth + through_overcut,
            origin=(0.0, pocket_start_y, 0.0),
            u_axis=(1, 0, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(0, -sign, 0),
        )
        b.boolean_subtract(body, pocket)

        pocket_start_y = sign * (secondary_arm_thickness_y / 2.0 + through_overcut)
        pocket = b.polygon_prism_on_plane(
            secondary_pocket_profile,
            secondary_pocket_depth + through_overcut,
            origin=(0.0, pocket_start_y, 0.0),
            u_axis=(1, 0, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(0, -sign, 0),
        )
        b.boolean_subtract(body, pocket)

    # Raised radial ribs on both side faces toward the three attachment roots.
    rib_specs = [
        (0.0, hub_radius + 26.0, "primary"),
        (secondary_angle_from_positive_x, hub_radius + 20.0, "secondary"),
        (clevis_angle_from_positive_x, hub_radius + 16.0, "clevis"),
    ]
    for face_sign in (-1.0, 1.0):
        for angle_degrees, rib_len, _label in rib_specs:
            u = _unit_xz(angle_degrees)
            start = hub_radius * 0.62
            center_u = start + rib_len / 2.0
            center_xz = (u[0] * center_u, u[1] * center_u)
            rib = b.oriented_box(
                rib_len,
                rib_width,
                rib_raise + feature_overlap,
                center=(center_xz[0], face_sign * (hub_thickness_y / 2.0 + rib_raise / 2.0), center_xz[1]),
                u_axis=(u[0], 0, u[1]),
                v_axis=(-u[1], 0, u[0]),
                w_axis=(0, face_sign, 0),
            )
            b.boolean_unite(body, rib)

    # Bearing bore and explicit annular seats on both side faces.
    b.bearing_seat(
        body,
        bore_diameter=pivot_bore_diameter,
        seat_diameter=bearing_seat_diameter,
        through_depth=hub_thickness_y,
        seat_depth=bearing_seat_depth,
        position=(0.0, -(hub_thickness_y / 2.0 + through_overcut), 0.0),
        direction=(0, 1, 0),
        cutter_overlap=through_overcut,
    )
    b.bearing_seat(
        body,
        bore_diameter=pivot_bore_diameter,
        seat_diameter=bearing_seat_diameter,
        through_depth=hub_thickness_y,
        seat_depth=bearing_seat_depth,
        position=(0.0, hub_thickness_y / 2.0 + through_overcut, 0.0),
        direction=(0, -1, 0),
        cutter_overlap=through_overcut,
    )

    # Link holes through lugs and clevis ears.
    for center_x, center_z, diameter, thickness in (
        (primary_length, 0.0, primary_end_hole_diameter, primary_arm_thickness_y),
        (secondary_end_xz[0], secondary_end_xz[1], secondary_end_hole_diameter, secondary_arm_thickness_y),
        (clevis_hole_xz[0], clevis_hole_xz[1], clevis_hole_diameter, 2.0 * clevis_ear_center_y_abs + clevis_ear_thickness_y),
    ):
        hole = b.hole(
            diameter,
            thickness + 2.0 * through_overcut,
            position=(center_x, -(thickness / 2.0 + through_overcut), center_z),
            direction=(0, 1, 0),
        )
        b.boolean_subtract(body, hole)

    # Conservative local blends after booleans.
    for x_min, x_max, z_min, z_max, radius in (
        (hub_radius - 2.0, hub_radius + 14.0, -primary_root_width_z / 2.0 - 3.0, primary_root_width_z / 2.0 + 3.0, primary_root_blend_radius),
        (-hub_radius - 8.0, secondary_end_xz[0] + 8.0, -8.0, secondary_end_xz[1] + 8.0, secondary_root_blend_radius),
    ):
        b.fillet(
            b.get_edges_in_box(
                body,
                min_xyz=(x_min, -hub_thickness_y / 2.0 - 2.0, z_min),
                max_xyz=(x_max, hub_thickness_y / 2.0 + 2.0, z_max),
            ),
            radius,
        )

    # General local edge treatment on arm/lug perimeters, pocket mouths, ribs, and clevis roots.
    for point, radius, tolerance in (
        ((primary_length, 0.0, 0.0), major_external_fillet, primary_end_lug_diameter / 2.0 + 2.0),
        ((secondary_end_xz[0], 0.0, secondary_end_xz[1]), major_external_fillet, secondary_end_lug_diameter / 2.0 + 2.0),
        ((clevis_tip_xz[0], -clevis_ear_center_y_abs, clevis_tip_xz[1]), major_external_fillet, clevis_end_radius + 2.0),
        ((clevis_tip_xz[0], clevis_ear_center_y_abs, clevis_tip_xz[1]), major_external_fillet, clevis_end_radius + 2.0),
        ((primary_length * 0.56, primary_arm_thickness_y / 2.0, 0.0), pocket_edge_fillet, 20.0),
        ((primary_length * 0.56, -primary_arm_thickness_y / 2.0, 0.0), pocket_edge_fillet, 20.0),
        ((secondary_end_xz[0] * 0.56, secondary_arm_thickness_y / 2.0, secondary_end_xz[1] * 0.56), pocket_edge_fillet, 18.0),
        ((secondary_end_xz[0] * 0.56, -secondary_arm_thickness_y / 2.0, secondary_end_xz[1] * 0.56), pocket_edge_fillet, 18.0),
        ((0.0, hub_thickness_y / 2.0, 0.0), rib_fillet, hub_radius + 4.0),
        ((0.0, -hub_thickness_y / 2.0, 0.0), rib_fillet, hub_radius + 4.0),
    ):
        b.fillet(b.get_edges_near(body, point=point, tolerance=tolerance), radius)

    # Chamfer exposed circular openings.
    chamfer_points = [
        (0.0, -hub_thickness_y / 2.0, 0.0),
        (0.0, hub_thickness_y / 2.0, 0.0),
        (primary_length, -primary_arm_thickness_y / 2.0, 0.0),
        (primary_length, primary_arm_thickness_y / 2.0, 0.0),
        (secondary_end_xz[0], -secondary_arm_thickness_y / 2.0, secondary_end_xz[1]),
        (secondary_end_xz[0], secondary_arm_thickness_y / 2.0, secondary_end_xz[1]),
        (clevis_hole_xz[0], -clevis_ear_center_y_abs - clevis_ear_thickness_y / 2.0, clevis_hole_xz[1]),
        (clevis_hole_xz[0], -clevis_gap_y / 2.0, clevis_hole_xz[1]),
        (clevis_hole_xz[0], clevis_gap_y / 2.0, clevis_hole_xz[1]),
        (clevis_hole_xz[0], clevis_ear_center_y_abs + clevis_ear_thickness_y / 2.0, clevis_hole_xz[1]),
    ]
    for point in chamfer_points:
        b.chamfer(b.get_edges_near(body, point=point, tolerance=0.9), hole_chamfer)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
