# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the sibling cadnx/ folder to a machine with Siemens NX.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports precision_parallel_pneumatic_gripper.step.
# ----------------------------------------------------------------------------

import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Overall coordinate convention from prompt:
    # X gripping/rod axis, Z pneumatic piston axis, rear mounting face at X=0.
    body_x = 78.0
    body_y = 56.0
    body_z = 42.0
    body_y_min = -body_y / 2.0
    chamfer_offset = 0.5
    internal_blend_radius = 1.0

    main_bore_diameter = 25.0
    piston_diameter = 24.5
    piston_height = 28.0
    piston_z0 = 7.0
    piston_z1 = piston_z0 + piston_height
    guide_y_offsets = (-14.0, 14.0)
    guide_bore_diameter = 12.0
    guide_bore_length = 35.0
    guide_start_x = 43.0
    guide_exit_x = 78.0
    rod_diameter = 12.0
    rod_length = 92.0
    rod_inner_x0 = 43.0
    rod_outer_x1 = 92.0
    rod_z = 21.0

    # Monolithic 7075-T6 body housing.
    body = b.box(body_x, body_y, body_z, origin=(0.0, body_y_min, 0.0))

    # Main cylinder bore, represented as a vertical service bore with 8 mm lower end wall.
    bore = b.hole(main_bore_diameter, 34.0, position=(39.0, 0.0, 43.0), direction=(0, 0, -1))
    b.boolean_subtract(body, bore)

    # Top T-slot for auxiliary sensor mounting: 6 mm mouth with wider undercut.
    b.slot_cut(body, length=body_y + 2.0, width=6.0, depth=3.2, center=(39.0, 0.0, 42.5), axis=(0, 1, 0), direction=(0, 0, -1))
    t_undercut = b.box(4.0, body_y + 2.0, 2.0, origin=(37.0, body_y_min - 1.0, 38.0))
    b.boolean_subtract(body, t_undercut)

    # Rear precision dowel and mounting hole patterns.
    for y in (-20.0, 20.0):
        for z in (5.0, 37.0):
            dowel = b.hole(4.0, 7.0, position=(-1.0, y, z), direction=(1, 0, 0))
            b.boolean_subtract(body, dowel)
    for y in (-24.0, 24.0):
        for z in (1.0, 41.0):
            mount = b.hole(4.2, 13.0, position=(-1.0, y, z), direction=(1, 0, 0))
            b.boolean_subtract(body, mount)
            thread_minor = b.hole(5.0, 5.0, position=(-1.0, y, z), direction=(1, 0, 0))
            b.boolean_subtract(body, thread_minor)

    # Guide bores, counterbores for scraper seals, and felt barrier pockets.
    for y in guide_y_offsets:
        guide = b.hole(guide_bore_diameter, guide_bore_length + 1.0, position=(guide_exit_x + 1.0, y, rod_z), direction=(-1, 0, 0))
        b.boolean_subtract(body, guide)
        wiper_cbore = b.hole(18.0, 5.5, position=(guide_exit_x + 0.5, y, rod_z), direction=(-1, 0, 0))
        b.boolean_subtract(body, wiper_cbore)
        felt_cbore = b.hole(16.0, 3.2, position=(guide_exit_x - 5.0, y, rod_z), direction=(-1, 0, 0))
        b.boolean_subtract(body, felt_cbore)

    # Pneumatic G1/8 ports and angled chamber passage approximations.
    for z in (12.0, 30.0):
        port = b.hole(9.728, 7.5, position=(-1.0, 0.0, z), direction=(1, 0, 0))
        b.boolean_subtract(body, port)
        passage = b.hole(4.0, 36.0, position=(3.0, 0.0, z), direction=(1, 0, 0))
        b.boolean_subtract(body, passage)
        set_screw = b.hole(2.5, 6.5, position=(16.0, -29.0, z), direction=(0, 1, 0))
        b.boolean_subtract(body, set_screw)
        ellipse = b.box(1.2, 5.7, 4.0, origin=(38.4, -2.85, z - 2.0))
        b.boolean_subtract(body, ellipse)

    # Sensor grooves and shim storage pocket.
    for y, direction in ((28.0, (0, -1, 0)), (-28.0, (0, 1, 0))):
        groove = b.box(25.0, 4.2, 25.0, origin=(26.5, y - (4.2 if y > 0 else 0.0), 8.0))
        b.boolean_subtract(body, groove)
    shim_pocket = b.box(30.0, 20.0, 8.3, origin=(24.0, -10.0, 34.0))
    b.boolean_subtract(body, shim_pocket)

    # Spring-return blind bores from side walls.
    for y, direction in ((22.0, (0, -1, 0)), (-22.0, (0, 1, 0))):
        spring_bore = b.hole(9.0, 30.0, position=(18.0, y + (7.0 if y > 0 else -7.0), rod_z), direction=direction)
        b.boolean_subtract(body, spring_bore)

    # Machining access plug holes.
    for z, direction in ((42.5, (0, 0, -1)), (-0.5, (0, 0, 1))):
        plug_hole = b.hole(10.0, 8.8, position=(39.0, 0.0, z), direction=direction)
        b.boolean_subtract(body, plug_hole)
    for y, direction in ((-28.5, (0, 1, 0)), (28.5, (0, -1, 0))):
        side_plug = b.hole(10.0, 9.0, position=(39.0, y, rod_z), direction=direction)
        b.boolean_subtract(body, side_plug)

    # Conservative outside chamfers and internal blends.
    b.chamfer(b.get_all_edges(body), chamfer_offset)
    b.fillet(b.get_edges_by_axis(body, axis=(0, 0, 1)), internal_blend_radius)

    # Double-acting piston with seal grooves, recesses, magnet slots, and M8 top hole.
    piston = b.cylinder(piston_diameter, piston_height, origin=(39.0, 0.0, piston_z0), axis=(0, 0, 1))
    for zc in (piston_z0 + 9.0, piston_z0 + 17.0):
        groove = b.cylinder(piston_diameter + 1.0, 3.5, origin=(39.0, 0.0, zc - 1.75), axis=(0, 0, 1))
        inner_keep = b.cylinder(piston_diameter - 4.4, 4.0, origin=(39.0, 0.0, zc - 2.0), axis=(0, 0, 1))
        b.boolean_subtract(groove, inner_keep)
        b.boolean_subtract(piston, groove)
        seal = b.cylinder(piston_diameter + 0.2, 2.5, origin=(39.0, 0.0, zc - 1.25), axis=(0, 0, 1))
        backup = b.cylinder(piston_diameter + 0.05, 1.5, origin=(39.0, 0.0, zc + 1.25), axis=(0, 0, 1))
    for z, direction in ((piston_z1 + 0.2, (0, 0, -1)), (piston_z0 - 0.2, (0, 0, 1))):
        recess = b.hole(18.0, 2.2, position=(39.0, 0.0, z), direction=direction)
        b.boolean_subtract(piston, recess)
    m8_top = b.hole(6.8, 15.5, position=(39.0, 0.0, piston_z1 + 0.2), direction=(0, 0, -1))
    b.boolean_subtract(piston, m8_top)
    for y in (-12.0, 12.0):
        magnet_slot = b.box(8.0, 2.7, 3.0, origin=(35.0, y - 1.35, 19.5))
        b.boolean_subtract(piston, magnet_slot)
        b.box(7.5, 2.3, 2.8, origin=(35.25, y - 1.15, 19.6))

    # Actuation yoke, boss, fork arms, pin bores, and relief pockets.
    yoke = b.box(15.0, 20.0, 16.0, origin=(43.0, -10.0, 13.0))
    boss = b.cylinder(16.0, 10.0, origin=(50.5, 0.0, 21.0), axis=(0, 0, 1))
    b.boolean_unite(yoke, boss)
    for y in guide_y_offsets:
        arm = b.box(15.0, 8.0, 6.0, origin=(43.0, y - 4.0, 18.0))
        b.boolean_unite(yoke, arm)
        pin_bore = b.hole(4.2, 9.0, position=(50.5, y - 4.5, 21.0), direction=(0, 1, 0))
        b.boolean_subtract(yoke, pin_bore)
        relief = b.box(12.0, 0.7, 4.0, origin=(44.5, y - (4.0 if y > 0 else -4.7), 19.0))
        b.boolean_subtract(yoke, relief)
    b.fillet(b.get_edges_by_axis(yoke, axis=(0, 0, 1)), 2.0)

    # Rods, bushings, lubrication grooves, cross pins, wipers, felt rings, washers, and screws.
    for y in guide_y_offsets:
        rod = b.cylinder(rod_diameter, rod_length, origin=(rod_inner_x0, y, rod_z), axis=(1, 0, 0))
        reduced = b.cylinder(10.0, 15.0, origin=(rod_inner_x0, y, rod_z), axis=(1, 0, 0))
        b.boolean_unite(rod, reduced)
        for x in (58.0, 62.0, 66.0, 70.0):
            oil_groove = b.hole(12.4, 0.45, position=(x, y, rod_z + 6.3), direction=(0, 0, -1))
            b.boolean_subtract(rod, oil_groove)
        pin_hole = b.hole(4.0, 14.0, position=(50.5, y - 7.0, rod_z), direction=(0, 1, 0))
        b.boolean_subtract(rod, pin_hole)
        pin = b.cylinder(3.0, 22.0, origin=(50.5, y - 11.0, rod_z), axis=(0, 1, 0))
        undercut = b.cylinder(8.2, 2.0, origin=(78.0, y, rod_z), axis=(1, 0, 0))
        thread = b.cylinder(8.0, 12.0, origin=(80.0, y, rod_z), axis=(1, 0, 0))
        for x in (81.0, 83.0, 85.0, 87.0, 89.0, 91.0):
            ring = b.cylinder(8.8, 0.35, origin=(x, y, rod_z), axis=(1, 0, 0))
            b.boolean_unite(thread, ring)
        b.boolean_unite(rod, undercut)
        b.boolean_unite(rod, thread)

        bushing = b.cylinder(18.0, 25.0, origin=(53.0, y, rod_z), axis=(1, 0, 0))
        bore = b.hole(12.0, 26.0, position=(52.5, y, rod_z), direction=(1, 0, 0))
        b.boolean_subtract(bushing, bore)
        for zoff, yoff in ((6.0, 0.0), (-3.0, 5.2), (-3.0, -5.2)):
            groove = b.box(26.0, 1.5, 0.8, origin=(52.5, y + yoff - 0.75, rod_z + zoff - 0.4))
            b.boolean_subtract(bushing, groove)

        wiper = b.cylinder(18.0, 5.0, origin=(78.0, y, rod_z), axis=(1, 0, 0))
        wiper_hole = b.hole(11.5, 6.0, position=(77.5, y, rod_z), direction=(1, 0, 0))
        b.boolean_subtract(wiper, wiper_hole)
        felt = b.cylinder(16.0, 3.0, origin=(75.0, y, rod_z), axis=(1, 0, 0))
        felt_hole = b.hole(12.0, 3.5, position=(74.8, y, rod_z), direction=(1, 0, 0))
        b.boolean_subtract(felt, felt_hole)
        washer = b.cylinder(20.0, 0.5, origin=(78.0, y, rod_z), axis=(1, 0, 0))
        washer_hole = b.hole(12.5, 1.0, position=(77.8, y, rod_z), direction=(1, 0, 0))
        b.boolean_subtract(washer, washer_hole)
        for z in (rod_z - 7.0, rod_z + 7.0):
            screw = b.cylinder(2.5, 3.0, origin=(78.3, y, z), axis=(1, 0, 0))

    # Parallel fingers with tapered shanks, counterbored bases, carbide inserts, and serrations.
    for y, grip_sign in ((14.0, 1.0), (-14.0, -1.0)):
        base = b.box(25.0, 16.0, 10.0, origin=(82.0, y - 8.0, 16.0))
        shank_points = [(0.0, -8.0), (40.0, -5.0), (40.0, 5.0), (0.0, 8.0)]
        shank = b.polygon_prism_on_plane(
            shank_points,
            10.0,
            origin=(107.0, y, 16.0),
            u_axis=(1, 0, 0),
            v_axis=(0, 1, 0),
            extrude_axis=(0, 0, 1),
        )
        tip = b.box(20.0, 10.0, 10.0, origin=(147.0, y - 5.0, 16.0))
        b.boolean_unite(base, shank)
        b.boolean_unite(base, tip)
        screw_hole = b.hole(8.5, 11.0, position=(94.5, y, 27.0), direction=(0, 0, -1))
        b.boolean_subtract(base, screw_hole)
        cbore = b.hole(14.0, 6.5, position=(94.5, y, 27.0), direction=(0, 0, -1))
        b.boolean_subtract(base, cbore)
        slot = b.box(3.0, 6.0, 10.5, origin=(82.0, y - 3.0, 15.8))
        b.boolean_subtract(base, slot)
        pocket = b.box(10.1, 8.1, 3.2, origin=(157.0, y - 4.05, 19.4))
        b.boolean_subtract(base, pocket)
        insert = b.box(10.0, 8.0, 3.0, origin=(157.0, y - 4.0, 19.5))
        b.fillet(b.get_edges_by_axis(insert, axis=(0, 0, 1)), 2.0)
        for i in range(16):
            x = 157.2 + i * 0.5
            groove = b.box(0.18, 8.6, 0.25, origin=(x, y - 4.3, 22.25))
            b.boolean_subtract(insert, groove)

    # Springs and plungers.
    for y in (22.0, -22.0):
        spring_axis = (0, -1, 0) if y > 0 else (0, 1, 0)
        spring = b.cylinder(8.0, 25.0, origin=(18.0, y, rod_z), axis=spring_axis)
        core = b.hole(5.6, 25.5, position=(18.0, y, rod_z), direction=spring_axis)
        b.boolean_subtract(spring, core)
        for i in range(9):
            z = rod_z - 3.5 + i * 0.85
            coil = b.cylinder(8.2, 0.25, origin=(18.0, y, z), axis=spring_axis)
            b.boolean_unite(spring, coil)
        plunger = b.cylinder(8.0, 15.0, origin=(18.0, y - (25.0 if y > 0 else -25.0), rod_z), axis=spring_axis)

    # Ports, plugs, sensor hardware, shim set, lid, and identification plate.
    for z in (12.0, 30.0):
        port_thread = b.cylinder(9.728, 7.0, origin=(0.0, 0.0, z), axis=(1, 0, 0))
        for x in (1.0, 2.8, 4.6, 6.4):
            crest = b.cylinder(10.2, 0.25, origin=(x, 0.0, z), axis=(1, 0, 0))
            b.boolean_unite(port_thread, crest)
    for origin, axis in (
        ((39.0, 0.0, 42.0), (0, 0, 1)),
        ((39.0, 0.0, -8.0), (0, 0, 1)),
        ((39.0, -28.0, rod_z), (0, -1, 0)),
        ((39.0, 28.0, rod_z), (0, 1, 0)),
    ):
        plug = b.cylinder(10.0, 8.0, origin=origin, axis=axis)
        socket = b.hole(4.0, 2.2, position=origin, direction=axis)
        b.boolean_subtract(plug, socket)

    for y in (-28.0, 28.0):
        sensor = b.box(20.0, 4.0, 6.0, origin=(29.0, y - (4.0 if y > 0 else 0.0), 17.5))
        clip = b.box(22.0, 1.0, 8.0, origin=(28.0, y - (5.0 if y > 0 else -1.0), 16.5))
    lid = b.box(32.0, 22.0, 2.0, origin=(23.0, -11.0, 42.0))
    for idx, thickness in enumerate((0.05, 0.10, 0.20, 0.50)):
        b.box(12.0, 10.0, max(thickness, 0.08), origin=(26.0 + idx * 6.0, -5.0, 34.5 + idx * 0.25))
    plate = b.box(20.0, 10.0, 0.5, origin=(29.0, 15.0, 42.2))

    # Simple raised bars on ID plate stand in for laser-etched manufacturing data.
    for i in range(5):
        b.box(16.0 - i * 1.5, 0.25, 0.08, origin=(31.0, 16.2 + i * 1.6, 42.72))

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
