# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              centrifugal_impeller.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports centrifugal_impeller.step next to it.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _polar(radius, angle_radians):
    return (
        radius * math.cos(angle_radians),
        radius * math.sin(angle_radians),
    )


def _blade_segment_polygon(r0, r1, theta0, theta1, thickness):
    x0, y0 = _polar(r0, theta0)
    x1, y1 = _polar(r1, theta1)
    dx = x1 - x0
    dy = y1 - y0
    length = math.hypot(dx, dy)
    if length <= 0:
        raise ValueError("Blade segment length must be positive.")

    nx = -dy / length
    ny = dx / length
    half_t = thickness / 2.0
    return [
        (x0 + nx * half_t, y0 + ny * half_t),
        (x1 + nx * half_t, y1 + ny * half_t),
        (x1 - nx * half_t, y1 - ny * half_t),
        (x0 - nx * half_t, y0 - ny * half_t),
    ]


def build(output_path: str = None):
    b = NXBuilder()

    # Parameters, millimeters unless otherwise noted.
    backplate_od = 90.0
    backplate_radius = backplate_od / 2.0
    backplate_thickness = 6.0
    backplate_outer_fillet = 1.5

    hub_diameter = 26.0
    hub_height_above_backplate = 22.0
    bore_diameter = 8.0

    blade_count = 12
    blade_root_radius = 18.0
    blade_tip_radius = 43.0
    blade_thickness = 3.0
    blade_height = 16.0
    blade_curve_degrees = -45.0
    blade_segments = 8
    blade_root_fillet = 1.0

    total_height = backplate_thickness + hub_height_above_backplate

    # Backplate: centered on Z axis, bottom face at Z = 0.
    body = b.cylinder(
        backplate_od,
        backplate_thickness,
        origin=(0.0, 0.0, 0.0),
        axis=(0.0, 0.0, 1.0),
    )
    b.fillet(b.get_top_edges(body), backplate_outer_fillet)
    b.fillet(b.get_bottom_edges(body), backplate_outer_fillet)

    # Central hub on top of the backplate.
    hub = b.cylinder(
        hub_diameter,
        hub_height_above_backplate,
        origin=(0.0, 0.0, backplate_thickness),
        axis=(0.0, 0.0, 1.0),
    )
    b.fillet(b.get_bottom_edges(hub), blade_root_fillet)
    body = b.boolean_unite(body, hub)

    # Backward-curved blades. Positive rotation is assumed counterclockwise when
    # viewed from +Z, so the blade tips sweep clockwise by 45 degrees.
    curve_total = math.radians(blade_curve_degrees)
    for blade_index in range(blade_count):
        base_angle = 2.0 * math.pi * blade_index / blade_count
        blade_feature = None
        for segment_index in range(blade_segments):
            t0 = float(segment_index) / float(blade_segments)
            t1 = float(segment_index + 1) / float(blade_segments)
            r0 = blade_root_radius + (blade_tip_radius - blade_root_radius) * t0
            r1 = blade_root_radius + (blade_tip_radius - blade_root_radius) * t1
            theta0 = base_angle + curve_total * t0
            theta1 = base_angle + curve_total * t1

            segment = b.polygon_prism(
                _blade_segment_polygon(r0, r1, theta0, theta1, blade_thickness),
                blade_height,
                origin=(0.0, 0.0, backplate_thickness),
                axis=(0.0, 0.0, 1.0),
            )

            # Root fillets are applied before union so NX can select the lower
            # segment edges cleanly; failed tiny edges are skipped by NXBuilder.
            b.fillet(b.get_bottom_edges(segment), blade_root_fillet)

            if blade_feature is None:
                blade_feature = segment
            else:
                blade_feature = b.boolean_unite(blade_feature, segment)

        body = b.boolean_unite(body, blade_feature)

    # Vertical through-bore through the complete impeller.
    bore_tool = b.hole(
        bore_diameter,
        total_height + 4.0,
        position=(0.0, 0.0, total_height + 2.0),
        direction=(0.0, 0.0, -1.0),
    )
    b.boolean_subtract(body, bore_tool)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
