# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the sibling cadnx/ folder to a machine with Siemens NX.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the model and exports common_rail_accumulator_cr250_4_186.step.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _hex_points_across_flats(across_flats):
    """Return local (Y, Z) points for a hex with flats separated by across_flats."""
    circumradius = float(across_flats) / math.sqrt(3.0)
    return [
        (
            circumradius * math.cos(math.radians(30.0 + i * 60.0)),
            circumradius * math.sin(math.radians(30.0 + i * 60.0)),
        )
        for i in range(6)
    ]


def _radial_unit(angle_degrees):
    angle = math.radians(angle_degrees)
    return (0.0, math.cos(angle), math.sin(angle))


def _point_on_body(x, body_radius, angle_degrees, outward_offset=0.0):
    _, uy, uz = _radial_unit(angle_degrees)
    radius = body_radius + outward_offset
    return (x, uy * radius, uz * radius)


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters unless stated otherwise.
    body_outer_diameter = 42.0
    body_length = 186.0
    accumulator_bore_diameter = 8.0
    accumulator_bore_clearance = 0.018
    accumulator_volume_ml_nominal = 9.3
    peak_pressure_mpa = 250.0
    safety_factor = 2.5
    yield_strength_mpa = 850.0
    autofrettage_wall_fraction = 0.30

    flange_across_flats = 36.0
    flange_thickness = 12.0
    flange_bolt_count = 6
    flange_bolt_circle_diameter = 30.0
    flange_hole_diameter = 9.0
    flange_countersink_diameter = 16.0
    flange_countersink_angle = 90.0
    gasket_outer_diameter = 38.0
    gasket_inner_diameter = 12.0
    gasket_thickness = 1.2
    seal_groove_width = 1.5
    seal_groove_depth = 1.0

    inlet_x = 12.0
    inlet_angle = 90.0
    inlet_thread_major_diameter = 14.0
    inlet_engagement = 12.0
    inlet_internal_bore_diameter = 6.0
    inlet_drill_diameter = 4.0
    inlet_seat_diameter = 9.2
    inlet_seat_width = 0.5
    inlet_torque_stop_depth = 0.3

    outlet_x_positions = (48.0, 84.0, 120.0, 156.0)
    outlet_angles = (90.0, 0.0, 270.0, 180.0)
    outlet_reamed_bore_diameter = 3.0
    outlet_reamed_depth = 15.0
    outlet_orifice_diameter = 2.0
    outlet_thread_major_diameter = 10.0
    outlet_thread_depth = 10.0
    outlet_boss_diameter = 15.0
    outlet_boss_height = 10.5
    outlet_seat_diameter = 6.0

    relief_x = 172.0
    relief_pocket_diameter = 6.0
    relief_pocket_depth = 4.0
    relief_ball_diameter = 4.0
    spring_bore_diameter = 3.0
    spring_bore_depth = 20.0
    spring_wire_diameter = 2.5
    spring_free_length = 18.0
    spring_rate_n_per_mm = 45.0
    cracking_pressure_mpa = 280.0
    plug_thread_major_diameter = 6.0
    plug_engagement = 15.0
    plug_hex_across_flats = 12.0

    temperature_boss_x = 96.0
    temperature_boss_angle = 0.0
    temperature_boss_diameter = 12.0
    temperature_boss_height = 15.0
    temperature_thread_major_diameter = 8.0
    temperature_thread_depth = 10.0
    temperature_probe_diameter = 3.0
    temperature_flat_depth = 2.0

    pressure_sensor_x = 24.0
    pressure_sensor_angle = 270.0
    pressure_sensor_thread_major_diameter = 12.0
    pressure_sensor_thread_depth = 8.0
    pressure_sensor_pilot_diameter = 5.0
    pressure_sensor_cavity_diameter = 15.0
    pressure_sensor_diaph_thickness = 0.3

    damping_x = 60.0
    damping_orifice_diameter = 0.8
    damping_orifice_length = 12.0
    damping_pocket_diameter = 3.0
    damping_pocket_depth = 8.0
    damping_angle_from_radial = 30.0

    anode_x = 140.0
    anode_y_positions = (-15.0, 15.0)
    anode_thread_major_diameter = 6.0
    anode_length = 10.0

    id_ring_x = 178.0
    id_ring_width = 1.0
    id_ring_depth = 0.3
    coating_thickness = 0.025
    phosphate_min_thickness = 0.002
    phosphate_max_thickness = 0.005

    # Derived dimensions and robustness allowances.
    body_radius = body_outer_diameter / 2.0
    bolt_circle_radius = flange_bolt_circle_diameter / 2.0
    through_overcut = 3.0
    cutter_overlap = 1.0
    feature_overlap = 0.75
    edge_break = 0.45
    port_boss_overlap = 1.0
    nominal_bore_volume_ml = math.pi * (accumulator_bore_diameter / 2.0) ** 2 * body_length / 1000.0
    proof_pressure_mpa = peak_pressure_mpa * safety_factor

    b.require_positive(
        body_outer_diameter=body_outer_diameter,
        body_length=body_length,
        accumulator_bore_diameter=accumulator_bore_diameter,
        flange_thickness=flange_thickness,
        flange_hole_diameter=flange_hole_diameter,
        outlet_boss_height=outlet_boss_height,
    )
    b.require_min_wall(body_outer_diameter, accumulator_bore_diameter, min_wall=8.0, label="pressure rail wall")
    b.require_edge_distance(
        flange_across_flats / 2.0 - bolt_circle_radius,
        flange_hole_diameter,
        min_ratio=0.25,
        label="flange M8 bolt circle",
    )

    # Primary forged accumulator body: axis along X, flange face in YZ at X=0.
    body = b.cylinder(body_outer_diameter, body_length, origin=(0.0, 0.0, 0.0), axis=(1.0, 0.0, 0.0))

    flange = b.polygon_prism_on_plane(
        _hex_points_across_flats(flange_across_flats),
        flange_thickness,
        origin=(-flange_thickness, 0.0, 0.0),
        u_axis=(0.0, 1.0, 0.0),
        v_axis=(0.0, 0.0, 1.0),
        extrude_axis=(1.0, 0.0, 0.0),
    )
    b.boolean_unite(body, flange)

    # Slight coating-envelope sleeve communicates phosphate plus black epoxy coating on external surfaces.
    coating_sleeve = b.cylinder(
        body_outer_diameter + 2.0 * coating_thickness,
        body_length - 6.0,
        origin=(3.0, 0.0, 0.0),
        axis=(1.0, 0.0, 0.0),
    )
    b.boolean_unite(body, coating_sleeve)

    # Central high-pressure bore, full length, H8 clearance and autofrettage noted in metadata comments.
    bore = b.hole(
        accumulator_bore_diameter,
        body_length + flange_thickness + through_overcut,
        position=(-flange_thickness - cutter_overlap, 0.0, 0.0),
        direction=(1.0, 0.0, 0.0),
    )
    b.boolean_subtract(body, bore)

    # Copper crush gasket groove on the sealing face at X=0, represented by segmented annular slots.
    groove_radius = (gasket_inner_diameter + gasket_outer_diameter) / 4.0
    for angle in (0.0, 90.0, 180.0, 270.0):
        cy = groove_radius * math.cos(math.radians(angle))
        cz = groove_radius * math.sin(math.radians(angle))
        axis = (0.0, -math.sin(math.radians(angle)), math.cos(math.radians(angle)))
        b.slot_cut(
            body,
            length=10.0,
            width=seal_groove_width,
            depth=seal_groove_depth + cutter_overlap,
            center=(0.1, cy, cz),
            axis=axis,
            direction=(-1.0, 0.0, 0.0),
        )
    gasket = b.cylinder(gasket_outer_diameter, gasket_thickness, origin=(-gasket_thickness, 0.0, 0.0), axis=(1.0, 0.0, 0.0))
    gasket_bore = b.hole(gasket_inner_diameter, gasket_thickness + through_overcut, position=(-gasket_thickness - 0.5, 0.0, 0.0), direction=(1.0, 0.0, 0.0))
    b.boolean_subtract(gasket, gasket_bore)

    # Flange M8 clearance holes with 16 mm x 90 degree countersink intent.
    for y, z, _ in b.circular_pattern_points((0.0, 0.0, 0.0), bolt_circle_radius, flange_bolt_count, start_angle_degrees=30.0):
        b.countersink_hole(
            body,
            "M8",
            flange_thickness + through_overcut,
            position=(0.5, y, z),
            direction=(-1.0, 0.0, 0.0),
            head_diameter=flange_countersink_diameter,
            angle_degrees=flange_countersink_angle,
        )

    # High-pressure inlet port, top radial boss and 45-degree drilled cross passage.
    inlet_dir = _radial_unit(inlet_angle)
    inlet_origin = _point_on_body(inlet_x, body_radius, inlet_angle, -port_boss_overlap)
    inlet_boss = b.cylinder(inlet_thread_major_diameter + 6.0, inlet_engagement + 4.0, origin=inlet_origin, axis=inlet_dir)
    b.boolean_unite(body, inlet_boss)
    inlet_bore = b.hole(inlet_internal_bore_diameter, inlet_engagement + 5.0, position=_point_on_body(inlet_x, body_radius + inlet_engagement + 3.0, inlet_angle), direction=(0.0, -inlet_dir[1], -inlet_dir[2]))
    b.boolean_subtract(body, inlet_bore)
    inlet_thread_relief = b.hole(inlet_thread_major_diameter, inlet_engagement, position=_point_on_body(inlet_x, body_radius + inlet_engagement + 2.5, inlet_angle), direction=(0.0, -inlet_dir[1], -inlet_dir[2]))
    b.boolean_subtract(body, inlet_thread_relief)
    inlet_seat = b.hole(inlet_seat_diameter, inlet_seat_width + inlet_torque_stop_depth + 1.0, position=_point_on_body(inlet_x, body_radius + 1.5, inlet_angle), direction=(0.0, -inlet_dir[1], -inlet_dir[2]))
    b.boolean_subtract(body, inlet_seat)
    diagonal = b.hole(inlet_drill_diameter, 24.0, position=(inlet_x + 8.0, 0.0, body_radius + 3.0), direction=(-0.7071, 0.0, -0.7071))
    b.boolean_subtract(body, diagonal)

    # Four injector outlet ports, 90 degrees around the rail with reamed bores, restrictor orifices, seats and threads.
    for x, angle in zip(outlet_x_positions, outlet_angles):
        radial_dir = _radial_unit(angle)
        outward = (0.0, radial_dir[1], radial_dir[2])
        inward = (0.0, -radial_dir[1], -radial_dir[2])
        boss_origin = _point_on_body(x, body_radius, angle, -port_boss_overlap)
        boss = b.cylinder(outlet_boss_diameter, outlet_boss_height + port_boss_overlap, origin=boss_origin, axis=outward)
        b.boolean_unite(body, boss)
        thread_cut = b.hole(outlet_thread_major_diameter, outlet_thread_depth + 1.0, position=_point_on_body(x, body_radius + outlet_boss_height, angle), direction=inward)
        b.boolean_subtract(body, thread_cut)
        reamed = b.hole(outlet_reamed_bore_diameter, outlet_reamed_depth + 1.0, position=_point_on_body(x, body_radius + outlet_boss_height, angle), direction=inward)
        b.boolean_subtract(body, reamed)
        orifice = b.hole(outlet_orifice_diameter, body_radius + outlet_boss_height + cutter_overlap, position=_point_on_body(x, body_radius + outlet_boss_height, angle), direction=inward)
        b.boolean_subtract(body, orifice)
        seat = b.hole(outlet_seat_diameter, 1.2, position=_point_on_body(x, body_radius + 1.0, angle), direction=inward)
        b.boolean_subtract(body, seat)

    # Pressure relief valve seat, ball, spring bore, spring representation, and M6 plug at rail end.
    relief_pocket = b.hole(relief_pocket_diameter, relief_pocket_depth + 1.0, position=(relief_x, 0.0, body_radius + 1.0), direction=(0.0, 0.0, -1.0))
    b.boolean_subtract(body, relief_pocket)
    spring_bore = b.hole(spring_bore_diameter, spring_bore_depth, position=(relief_x, 0.0, body_radius + 1.0), direction=(0.0, 0.0, 1.0))
    b.boolean_subtract(body, spring_bore)
    ball_proxy = b.cylinder(relief_ball_diameter, relief_ball_diameter, origin=(relief_x - relief_ball_diameter / 2.0, 0.0, body_radius + 2.0), axis=(1.0, 0.0, 0.0))
    b.boolean_unite(body, ball_proxy)
    spring_proxy = b.cylinder(spring_wire_diameter, spring_free_length, origin=(relief_x, 0.0, body_radius + 4.0), axis=(0.0, 0.0, 1.0))
    b.boolean_unite(body, spring_proxy)
    plug = b.polygon_prism_on_plane(
        _hex_points_across_flats(plug_hex_across_flats),
        6.0,
        origin=(relief_x, 0.0, body_radius + spring_bore_depth - 2.0),
        u_axis=(1.0, 0.0, 0.0),
        v_axis=(0.0, 1.0, 0.0),
        extrude_axis=(0.0, 0.0, 1.0),
    )
    b.boolean_unite(body, plug)

    # Fuel temperature sensor boss on +Y and PT1000 probe bore.
    temp_dir = _radial_unit(temperature_boss_angle)
    temp_boss = b.cylinder(
        temperature_boss_diameter,
        temperature_boss_height + port_boss_overlap,
        origin=_point_on_body(temperature_boss_x, body_radius, temperature_boss_angle, -port_boss_overlap),
        axis=temp_dir,
    )
    b.boolean_unite(body, temp_boss)
    temp_thread = b.hole(temperature_thread_major_diameter, temperature_thread_depth + 1.0, position=_point_on_body(temperature_boss_x, body_radius + temperature_boss_height, temperature_boss_angle), direction=(0.0, -temp_dir[1], -temp_dir[2]))
    b.boolean_subtract(body, temp_thread)
    temp_probe = b.hole(temperature_probe_diameter, temperature_boss_height + 2.0, position=_point_on_body(temperature_boss_x, body_radius + temperature_boss_height, temperature_boss_angle), direction=(0.0, -temp_dir[1], -temp_dir[2]))
    b.boolean_subtract(body, temp_probe)
    temp_flat = b.box(
        11.0,
        temperature_flat_depth + 1.0,
        11.0,
        origin=(
            temperature_boss_x - 5.5,
            body_radius + temperature_boss_height - temperature_flat_depth,
            -5.5,
        ),
    )
    b.boolean_subtract(body, temp_flat)

    # Rail pressure sensor port on -Z.
    ps_dir = _radial_unit(pressure_sensor_angle)
    ps_boss = b.cylinder(pressure_sensor_thread_major_diameter + 5.0, 10.0, origin=_point_on_body(pressure_sensor_x, body_radius, pressure_sensor_angle, -port_boss_overlap), axis=ps_dir)
    b.boolean_unite(body, ps_boss)
    ps_thread = b.hole(pressure_sensor_thread_major_diameter, pressure_sensor_thread_depth + 1.0, position=_point_on_body(pressure_sensor_x, body_radius + 10.0, pressure_sensor_angle), direction=(0.0, -ps_dir[1], -ps_dir[2]))
    b.boolean_subtract(body, ps_thread)
    ps_pilot = b.hole(pressure_sensor_pilot_diameter, body_radius + 10.0, position=_point_on_body(pressure_sensor_x, body_radius + 10.0, pressure_sensor_angle), direction=(0.0, -ps_dir[1], -ps_dir[2]))
    b.boolean_subtract(body, ps_pilot)
    ps_cavity = b.hole(pressure_sensor_cavity_diameter, pressure_sensor_diaph_thickness + 1.0, position=_point_on_body(pressure_sensor_x, body_radius + 1.0, pressure_sensor_angle), direction=(0.0, -ps_dir[1], -ps_dir[2]))
    b.boolean_subtract(body, ps_cavity)

    # Internal damping orifice at 30 degrees from radial, terminating in a blind pocket.
    damping_dir = (0.0, -math.sin(math.radians(damping_angle_from_radial)), -math.cos(math.radians(damping_angle_from_radial)))
    damping_orifice = b.hole(damping_orifice_diameter, damping_orifice_length, position=(damping_x, 3.0, body_radius + 2.0), direction=damping_dir)
    b.boolean_subtract(body, damping_orifice)
    damping_pocket = b.hole(damping_pocket_diameter, damping_pocket_depth, position=(damping_x, 5.0, body_radius + 4.0), direction=(0.0, 0.0, -1.0))
    b.boolean_subtract(body, damping_pocket)

    # Sacrificial zinc anode plugs at X=140, Y=+/-15.
    for y in anode_y_positions:
        anode = b.cylinder(anode_thread_major_diameter, anode_length, origin=(anode_x, y, body_radius - 1.0), axis=(0.0, 0.0, 1.0))
        b.boolean_unite(body, anode)
        anode_socket = b.hole(3.0, 3.0, position=(anode_x, y, body_radius + anode_length - 0.5), direction=(0.0, 0.0, -1.0))
        b.boolean_subtract(body, anode_socket)

    # Laser-welded identification ring and traceability marks near X=178.
    # NXBuilder slot_cut is limited to axis-aligned vectors, so these diagonal
    # witness marks use shallow rectangular cutters instead of radial slots.
    for angle in (45.0, 135.0, 225.0, 315.0):
        y = (body_radius + 0.1) * math.cos(math.radians(angle))
        z = (body_radius + 0.1) * math.sin(math.radians(angle))
        mark_cut = b.box(
            8.0,
            id_ring_width,
            id_ring_width,
            origin=(id_ring_x - 4.0, y - id_ring_width / 2.0, z - id_ring_width / 2.0),
        )
        b.boolean_subtract(body, mark_cut)
    for offset in (-3.0, -1.0, 1.0, 3.0):
        mark = b.box(0.6, 0.6, 0.35, origin=(id_ring_x + offset, -body_radius - 0.35, -2.0))
        b.boolean_unite(body, mark)

    # Conservative edge breaks. Some blends may be skipped by NX if local boolean topology is too tight.
    b.chamfer(b.get_edges_near(body, point=(0.0, 0.0, 0.0), tolerance=24.0), edge_break)
    b.chamfer(b.get_edges_near(body, point=(body_length, 0.0, 0.0), tolerance=24.0), edge_break)

    # Manufacturing / specification metadata retained in source:
    # - Forged martensitic stainless steel, solution-treated and aged, 850 MPa yield.
    # - Pressure-bearing surfaces honed to Ra 0.2 um; ball seats to Ra 0.1/0.05 um where specified.
    # - Peak/proof pressure: 250 MPa / 625 MPa; autofrettage inner wall fraction: 30%.
    # - Central bore nominal volume from modeled 8 mm x 186 mm bore: %.3f mL; requested rail volume: 9.3 mL.
    # - Injector outlet concentricity target: 0.02 mm to accumulator bore.
    # - Spring: Inconel X-750, %.1f N/mm, preloaded for %.1f MPa cracking pressure.
    # - External finish: Mn phosphate %.3f-%.3f mm plus RAL 9005 epoxy %.3f mm except sealing faces.
    _ = (
        accumulator_bore_clearance,
        accumulator_volume_ml_nominal,
        nominal_bore_volume_ml,
        proof_pressure_mpa,
        yield_strength_mpa,
        autofrettage_wall_fraction,
        spring_rate_n_per_mm,
        cracking_pressure_mpa,
        plug_thread_major_diameter,
        plug_engagement,
        phosphate_min_thickness,
        phosphate_max_thickness,
    )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
