# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              compact_cnc_rotary_table.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Coordinate convention: +Z is rotary axis, +X is right, +Y is rear.
    through_overcut = 2.0
    cutter_overlap = 0.8
    feature_overlap = 0.8
    exposed_chamfer = 1.0
    hole_chamfer = 0.5
    base_outer_fillet = 3.0
    major_transition_fillet = 2.0
    worm_blend_fillet = 4.0

    # Independent prompt dimensions.
    base_diameter = 180.0
    base_height = 42.0
    base_recess_diameter = 130.0
    base_recess_depth = 4.0

    table_diameter = 140.0
    table_thickness = 18.0
    central_bore_diameter = 32.0
    centering_boss_diameter = 58.0
    centering_boss_height = 6.0

    t_slot_count = 6
    t_slot_width = 10.0
    t_slot_length = 55.0
    t_slot_undercut_width = 16.0
    t_slot_top_depth = 7.0
    t_slot_undercut_depth = 6.0

    base_mount_count = 8
    base_mount_hole_diameter = 6.6
    base_mount_bolt_circle = 150.0
    base_mount_counterbore_diameter = 12.0
    base_mount_counterbore_depth = 6.0

    worm_length_y = 72.0
    worm_width_x = 46.0
    worm_height_z = 38.0
    shaft_bore_diameter = 18.0

    motor_flange_diameter = 56.0
    motor_flange_thickness = 8.0
    motor_hole_diameter = 4.2
    motor_bolt_circle = 42.0

    index_mark_count = 36
    index_mark_width = 2.0
    index_mark_radial_length = 5.5
    index_mark_depth = 0.5

    # Derived placement.
    base_z_min = 0.0
    base_z_max = base_height
    table_z_min = base_z_max
    table_z_max = table_z_min + table_thickness
    boss_z_min = table_z_max - feature_overlap
    boss_center_z = boss_z_min + (centering_boss_height + feature_overlap) / 2.0
    table_center_z = table_z_min + table_thickness / 2.0
    base_center_z = base_z_min + base_height / 2.0
    worm_center_y = -base_diameter / 2.0 - worm_length_y / 2.0 + feature_overlap
    worm_center_z = base_z_min + worm_height_z / 2.0
    motor_flange_center_x = worm_width_x / 2.0 + motor_flange_thickness / 2.0 - feature_overlap
    t_slot_r_start = central_bore_diameter / 2.0 + 4.0
    t_slot_r_end = t_slot_r_start + t_slot_length
    t_slot_r_mid = (t_slot_r_start + t_slot_r_end) / 2.0
    index_mark_radius = table_diameter / 2.0 - index_mark_radial_length / 2.0

    b.require_positive(
        base_diameter=base_diameter,
        base_height=base_height,
        table_diameter=table_diameter,
        table_thickness=table_thickness,
        worm_length_y=worm_length_y,
        worm_width_x=worm_width_x,
        worm_height_z=worm_height_z,
    )
    b.require_min_wall(table_diameter, central_bore_diameter, min_wall=20.0, label="rotary table central bore")
    b.require_min_wall(base_diameter, base_recess_diameter, min_wall=18.0, label="base top recess")
    b.require_edge_distance((base_diameter - base_mount_bolt_circle) / 2.0, base_mount_counterbore_diameter, min_ratio=1.0, label="base mounting counterbore")
    b.require_feature_budget(boolean_operations=95, micro_holes=16, patterned_features=54)

    def cyl(diameter, height, center, axis=(0, 0, 1)):
        origin = (
            center[0] - axis[0] * height / 2.0,
            center[1] - axis[1] * height / 2.0,
            center[2] - axis[2] * height / 2.0,
        )
        return b.cylinder(diameter, height, origin=origin, axis=axis)

    def cut_cylinder(target, diameter, depth, center, axis=(0, 0, 1)):
        tool = cyl(diameter, depth, center, axis=axis)
        b.boolean_subtract(target, tool)

    def radial_axes(angle_degrees):
        angle = math.radians(angle_degrees)
        radial = (math.cos(angle), math.sin(angle), 0.0)
        tangent = (-math.sin(angle), math.cos(angle), 0.0)
        return radial, tangent

    def radial_box_cut(target, angle_degrees, radial_length, tangent_width, depth, radius, z_top):
        radial, tangent = radial_axes(angle_degrees)
        center = (radius * radial[0], radius * radial[1], z_top - depth / 2.0 + cutter_overlap)
        tool = b.oriented_box(
            radial_length,
            tangent_width,
            depth + 2.0 * cutter_overlap,
            center=center,
            u_axis=radial,
            v_axis=tangent,
            w_axis=(0, 0, 1),
        )
        b.boolean_subtract(target, tool)

    def chamfer_hole_zone(target, center, axis, diameter, length):
        radius = diameter / 2.0 + hole_chamfer + 0.8
        for sign in (-1.0, 1.0):
            face = (
                center[0] + axis[0] * sign * length / 2.0,
                center[1] + axis[1] * sign * length / 2.0,
                center[2] + axis[2] * sign * length / 2.0,
            )
            b.chamfer(
                b.get_edges_in_box(
                    target,
                    min_xyz=(face[0] - radius, face[1] - radius, face[2] - radius),
                    max_xyz=(face[0] + radius, face[1] + radius, face[2] + radius),
                ),
                hole_chamfer,
            )

    # Circular base housing with top recess and mounting counterbores.
    base = cyl(base_diameter, base_height, (0.0, 0.0, base_center_z))
    b.annular_groove(
        base,
        outer_diameter=base_recess_diameter,
        inner_diameter=central_bore_diameter + 10.0,
        depth=base_recess_depth,
        position=(0.0, 0.0, base_z_max + cutter_overlap),
        direction=(0, 0, -1),
        cutter_overlap=cutter_overlap,
    )
    for x, y, _z in b.circular_pattern_points((0.0, 0.0, base_z_max), base_mount_bolt_circle / 2.0, base_mount_count, start_angle_degrees=22.5):
        center = (x, y, base_center_z)
        b.counterbore_hole(
            base,
            base_mount_hole_diameter,
            base_height + through_overcut,
            base_mount_counterbore_diameter,
            base_mount_counterbore_depth,
            position=(x, y, base_z_max + cutter_overlap),
            direction=(0, 0, -1),
        )
        chamfer_hole_zone(base, center, (0, 0, 1), base_mount_hole_diameter, base_height)
    b.fillet(b.get_top_edges(base), base_outer_fillet)
    b.fillet(b.get_bottom_edges(base), base_outer_fillet)
    b.chamfer(b.get_top_edges(base), exposed_chamfer)

    # Front worm-drive housing protruding along -Y, blended by local edge fillets.
    worm = b.rounded_box(
        worm_width_x,
        worm_length_y + feature_overlap,
        worm_height_z,
        radius=4.0,
        origin=(-worm_width_x / 2.0, -base_diameter / 2.0 - worm_length_y, base_z_min),
    )
    b.boolean_unite(base, worm)
    cut_cylinder(base, shaft_bore_diameter, worm_width_x + through_overcut, (0.0, worm_center_y, worm_center_z), axis=(1, 0, 0))
    chamfer_hole_zone(base, (0.0, worm_center_y, worm_center_z), (1, 0, 0), shaft_bore_diameter, worm_width_x)
    b.fillet(
        b.get_edges_in_box(
            base,
            min_xyz=(-worm_width_x / 2.0 - 2.0, -base_diameter / 2.0 - 3.0, base_z_min - 1.0),
            max_xyz=(worm_width_x / 2.0 + 2.0, -base_diameter / 2.0 + 8.0, worm_height_z + 2.0),
        ),
        worm_blend_fillet,
    )

    # +X motor flange on worm housing with M4 bolt pattern.
    flange = cyl(motor_flange_diameter, motor_flange_thickness, (motor_flange_center_x, worm_center_y, worm_center_z), axis=(1, 0, 0))
    b.boolean_unite(base, flange)
    cut_cylinder(base, shaft_bore_diameter, motor_flange_thickness + worm_width_x + through_overcut, (motor_flange_center_x, worm_center_y, worm_center_z), axis=(1, 0, 0))
    for angle_degrees in (45.0, 135.0, 225.0, 315.0):
        angle = math.radians(angle_degrees)
        center = (
            motor_flange_center_x,
            worm_center_y + motor_bolt_circle / 2.0 * math.cos(angle),
            worm_center_z + motor_bolt_circle / 2.0 * math.sin(angle),
        )
        cut_cylinder(base, motor_hole_diameter, motor_flange_thickness + through_overcut, center, axis=(1, 0, 0))
        chamfer_hole_zone(base, center, (1, 0, 0), motor_hole_diameter, motor_flange_thickness)
    b.chamfer(
        b.get_edges_in_box(
            base,
            min_xyz=(motor_flange_center_x - motor_flange_thickness / 2.0 - 1.0, worm_center_y - motor_flange_diameter / 2.0 - 1.0, worm_center_z - motor_flange_diameter / 2.0 - 1.0),
            max_xyz=(motor_flange_center_x + motor_flange_thickness / 2.0 + 1.0, worm_center_y + motor_flange_diameter / 2.0 + 1.0, worm_center_z + motor_flange_diameter / 2.0 + 1.0),
        ),
        exposed_chamfer,
    )

    # Rotating table disk with central bore, T-slots, index marks, and raised centering boss.
    table = cyl(table_diameter, table_thickness, (0.0, 0.0, table_center_z))
    cut_cylinder(table, central_bore_diameter, table_thickness + through_overcut, (0.0, 0.0, table_center_z))
    for slot_index in range(t_slot_count):
        angle = slot_index * 360.0 / t_slot_count
        radial_box_cut(table, angle, t_slot_length, t_slot_width, t_slot_top_depth, t_slot_r_mid, table_z_max)
        radial_box_cut(
            table,
            angle,
            t_slot_length,
            t_slot_undercut_width,
            t_slot_undercut_depth,
            t_slot_r_mid,
            table_z_max - t_slot_top_depth + cutter_overlap,
        )
    for mark_index in range(index_mark_count):
        angle = mark_index * 360.0 / index_mark_count
        radial_box_cut(table, angle, index_mark_radial_length, index_mark_width, index_mark_depth, index_mark_radius, table_z_max)
    b.chamfer(b.get_top_edges(table), exposed_chamfer)
    b.chamfer(b.get_bottom_edges(table), exposed_chamfer)

    boss = cyl(centering_boss_diameter, centering_boss_height + feature_overlap, (0.0, 0.0, boss_center_z))
    cut_cylinder(boss, central_bore_diameter, centering_boss_height + through_overcut, (0.0, 0.0, boss_center_z))
    b.chamfer(b.get_top_edges(boss), exposed_chamfer)
    b.chamfer(b.get_bottom_edges(boss), hole_chamfer)

    # Thin visual bearing/seal rings in the top recess for machined assembly detail.
    seal_ring = cyl(118.0, 1.2, (0.0, 0.0, base_z_max + 0.6), axis=(0, 0, 1))
    cut_cylinder(seal_ring, 94.0, 3.0, (0.0, 0.0, base_z_max + 0.6), axis=(0, 0, 1))
    bearing_land = cyl(86.0, 2.0, (0.0, 0.0, base_z_max + 1.0), axis=(0, 0, 1))
    cut_cylinder(bearing_land, 60.0, 4.0, (0.0, 0.0, base_z_max + 1.0), axis=(0, 0, 1))

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
