# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the sibling cadnx/ folder to a machine with Siemens NX.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the consolidated solid and exports the STEP file next to it.
# ----------------------------------------------------------------------------

import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    body_length = 247.0
    body_width = 123.0
    body_height = 90.0
    shell_wall = 2.5
    external_fillet = 1.5
    joint_fillet = 1.0
    hole_chamfer = 0.5

    gimbal_x = 42.0
    gimbal_y = 38.0
    gimbal_z = 55.0
    lens_diameter = 10.0
    lens_protrusion = 5.0

    arm_outer_diameter = 16.0
    arm_wall = 1.8
    front_arm_length = 205.0
    rear_arm_length = 192.0
    motor_seat_x = 22.0
    motor_seat_y = 22.0
    motor_seat_z = 18.0
    motor_shaft_hole = 3.0

    prop_blade_length = 94.0
    prop_blade_width_root = 13.0
    prop_blade_width_tip = 7.0
    prop_blade_thickness = 1.2
    prop_hub_diameter = 18.0
    prop_hub_thickness = 6.0

    battery_bay_x = 86.0
    battery_bay_y = 118.0
    battery_bay_z = 42.0
    battery_lip = 2.0
    lock_boss_x = 12.0
    lock_boss_y = 3.0
    lock_boss_z = 8.0

    gps_hole_diameter = 2.5
    shock_hole_diameter = 2.0
    shock_counterbore_diameter = 4.0
    lock_pin_hole_diameter = 2.2

    gusset_thickness = 2.0
    gusset_height = 25.0
    gusset_depth = 20.0

    # Derived layout.
    body_x0 = -body_length / 2.0
    body_y0 = -body_width / 2.0
    body_z0 = 0.0
    body_top = body_height
    body_front_x = body_x0
    body_rear_x = body_length / 2.0
    arm_z = 38.0
    hinge_x_values = (-85.0, 85.0)
    front_hinge_y = 45.0
    rear_hinge_y = -45.0
    arm_inner_diameter = arm_outer_diameter - 2.0 * arm_wall
    overcut = 4.0

    def unite(base, tool):
        b.boolean_unite(base, tool)
        return base

    def subtract(target, tool):
        b.boolean_subtract(target, tool)
        return target

    def add_box(base, length, width, height, center):
        cx, cy, cz = center
        return unite(
            base,
            b.box(length, width, height, origin=(cx - length / 2.0, cy - width / 2.0, cz - height / 2.0)),
        )

    def add_cylinder(base, diameter, height, center, axis):
        return unite(base, b.cylinder(diameter, height, origin=center, axis=axis))

    body = b.rounded_box(
        body_length,
        body_width,
        body_height,
        radius=external_fillet,
        origin=(body_x0, body_y0, body_z0),
    )

    # Main shell representation: open rear battery recess and thin top service pocket.
    battery_center_x = body_rear_x - battery_bay_x / 2.0 + 1.0
    battery_cut = b.box(
        battery_bay_x + overcut,
        battery_bay_y,
        battery_bay_z,
        origin=(body_rear_x - battery_bay_x, -battery_bay_y / 2.0, body_top - battery_bay_z - battery_lip),
    )
    subtract(body, battery_cut)
    add_box(body, battery_lip, battery_bay_y + 4.0, battery_lip, (body_rear_x - battery_bay_x, 0.0, body_top - battery_bay_z - battery_lip / 2.0))
    for side in (-1.0, 1.0):
        add_box(
            body,
            lock_boss_x,
            lock_boss_y,
            lock_boss_z,
            (battery_center_x, side * (battery_bay_y / 2.0 - lock_boss_y / 2.0), body_top - battery_bay_z / 2.0),
        )

    # Front gimbal boss, yoke, triple camera blocks, and lens protrusions.
    gimbal_base_center = (body_front_x - 6.0, 0.0, 30.0)
    add_box(body, 12.0, 46.0, 32.0, gimbal_base_center)
    yoke_center = (body_front_x - gimbal_x / 2.0, 0.0, 30.0)
    add_box(body, gimbal_x, gimbal_y, 8.0, (yoke_center[0], yoke_center[1], yoke_center[2] + gimbal_z / 2.0 - 4.0))
    add_box(body, 8.0, 5.0, gimbal_z, (body_front_x - 14.0, -gimbal_y / 2.0 + 2.5, 30.0))
    add_box(body, 8.0, 5.0, gimbal_z, (body_front_x - 14.0, gimbal_y / 2.0 - 2.5, 30.0))
    for cy, cz, dia in ((0.0, 39.0, 18.0), (-10.5, 26.0, 12.0), (10.5, 26.0, 12.0)):
        add_box(body, 16.0, 13.0, 11.0, (body_front_x - 24.0, cy, cz))
        add_cylinder(body, dia, lens_protrusion, (body_front_x - 42.0, cy, cz), axis=(-1, 0, 0))

    # Arms, hinges, motor seats, propeller hubs, and blade solids.
    motor_centers = []
    for hx in hinge_x_values:
        for hy, length, direction in ((front_hinge_y, front_arm_length, 1.0), (rear_hinge_y, rear_arm_length, -1.0)):
            hinge_center = (hx, hy, arm_z)
            end_y = hy + direction * length
            motor_center = (hx, end_y, arm_z)
            motor_centers.append(motor_center)

            add_cylinder(body, 26.0, 18.0, hinge_center, axis=(0, 0, 1))
            add_cylinder(body, arm_outer_diameter, length, hinge_center, axis=(0, direction, 0))
            inner = b.hole(arm_inner_diameter, length + overcut, position=(hx, hy - direction * overcut / 2.0, arm_z), direction=(0, direction, 0))
            subtract(body, inner)
            add_box(body, motor_seat_x, motor_seat_y, motor_seat_z, motor_center)
            add_cylinder(body, prop_hub_diameter, prop_hub_thickness, (hx, end_y, arm_z + motor_seat_z / 2.0), axis=(0, 0, 1))

            blade_z = arm_z + motor_seat_z / 2.0 + prop_hub_thickness / 2.0 - prop_blade_thickness / 2.0
            for sx, sy in ((1.0, 1.0), (-1.0, -1.0)):
                blade_origin = (hx, end_y, blade_z)
                blade = b.polygon_prism_on_plane(
                    points=[
                        (0.0, -prop_blade_width_root / 2.0),
                        (prop_blade_length, -prop_blade_width_tip / 2.0),
                        (prop_blade_length, prop_blade_width_tip / 2.0),
                        (0.0, prop_blade_width_root / 2.0),
                    ],
                    distance=prop_blade_thickness,
                    origin=blade_origin,
                    u_axis=(sx, 0, 0),
                    v_axis=(0, sy, 0),
                    extrude_axis=(0, 0, 1),
                )
                unite(body, blade)

            shaft = b.hole(motor_shaft_hole, motor_seat_z + prop_hub_thickness + overcut, position=(hx, end_y, arm_z + motor_seat_z + prop_hub_thickness), direction=(0, 0, -1))
            subtract(body, shaft)

            pin = b.hole(lock_pin_hole_diameter, 34.0, position=(hx - 17.0, hy, arm_z), direction=(1, 0, 0))
            subtract(body, pin)

    # GPS top platform and four symmetric fixing holes at X +/-32, Y +/-8.
    add_box(body, 78.0, 30.0, 3.0, (0.0, 0.0, body_top + 1.5))
    for x in (-32.0, 32.0):
        for y in (-8.0, 8.0):
            gps_hole = b.hole(gps_hole_diameter, 8.0, position=(x, y, body_top + 5.0), direction=(0, 0, -1))
            subtract(body, gps_hole)

    # Six front shock counterbore holes on the gimbal boss.
    for y in (-18.0, 0.0, 18.0):
        for z in (12.0, 24.0):
            b.counterbore_hole(
                body,
                shock_hole_diameter,
                14.0,
                shock_counterbore_diameter,
                2.0,
                position=(-112.0, y, z),
                direction=(-1, 0, 0),
            )

    # Triangular reinforcing gussets at all fuselage-arm roots.
    for x in hinge_x_values:
        for y, sign in ((front_hinge_y, 1.0), (rear_hinge_y, -1.0)):
            for side in (-1.0, 1.0):
                gusset = b.polygon_prism_on_plane(
                    points=[(0.0, 0.0), (gusset_depth * sign, 0.0), (0.0, gusset_height)],
                    distance=gusset_thickness,
                    origin=(x + side * gusset_thickness / 2.0, y, 12.0),
                    u_axis=(0, 1, 0),
                    v_axis=(0, 0, 1),
                    extrude_axis=(side, 0, 0),
                )
                unite(body, gusset)

    # Conservative finish features. Hole entry chamfers are applied to local edge
    # boxes around critical holes where edge selection is predictable.
    b.fillet(b.get_edges_in_box(body, (-105, -75, 20), (105, 75, 52)), joint_fillet)
    for x, y, z, tol in [
        *( (mx, my, arm_z + motor_seat_z / 2.0, 13.0) for mx, my, _ in motor_centers ),
        *[(x, y, body_top, 5.0) for x in (-32.0, 32.0) for y in (-8.0, 8.0)],
    ]:
        b.chamfer(
            b.get_edges_in_box(body, (x - tol, y - tol, z - tol), (x + tol, y + tol, z + tol)),
            hole_chamfer,
        )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
