# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the sibling cadnx/ folder to a Siemens NX machine.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports dual_spool_turbofan_hpc_rear_frame.step.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _xy(radius, angle_degrees):
    angle = math.radians(angle_degrees)
    return radius * math.cos(angle), radius * math.sin(angle)


def _unit(angle_degrees):
    angle = math.radians(angle_degrees)
    return math.cos(angle), math.sin(angle), 0.0


def _tangent(angle_degrees):
    angle = math.radians(angle_degrees)
    return -math.sin(angle), math.cos(angle), 0.0


def _sector_points(inner_radius, outer_radius, half_angle_degrees, lean_degrees=0.0):
    return [
        _xy(inner_radius, -half_angle_degrees + lean_degrees),
        _xy(outer_radius, -half_angle_degrees),
        _xy(outer_radius, half_angle_degrees),
        _xy(inner_radius, half_angle_degrees + lean_degrees),
    ]


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    outer_ring_od = 486.0
    outer_ring_id = 312.0
    hub_od = 196.0
    hub_id = 85.0
    frame_length = 145.0
    front_z = 0.0
    rear_z = front_z + frame_length
    strut_count = 36
    strut_pitch_degrees = 360.0 / strut_count
    strut_aft_lean_degrees = 3.0
    outer_strut_radius = outer_ring_od / 2.0
    inner_strut_radius = hub_od / 2.0
    manifold_z = 72.0
    through_overcut = 4.0
    feature_overlap = 0.8
    cutter_overlap = 1.0
    edge_break = 0.3
    cosmetic_fillet = 0.8

    # Bearing, diffuser, combustion, and accessory parameters.
    front_bearing_bore = 85.0
    front_bearing_depth = 65.0
    rear_bearing_bore = 75.0
    rear_counterbore_depth = 25.0
    rear_counterbore_z = 120.0
    silver_sleeve_od = 86.0
    silver_sleeve_id = 85.0
    silver_sleeve_length = 60.0
    oil_hole_count = 8
    oil_hole_diameter = 2.0
    fuel_boss_count = 18
    fuel_boss_length = 28.0
    fuel_boss_width = 22.0
    fuel_boss_height = 10.0
    fuel_bore_diameter = 14.0
    fuel_bore_depth = 18.0
    tie_bolt_count = 24
    tie_bolt_circle = 460.0
    anti_rotation_count = 12
    acoustic_cavity_count = 36
    instrumentation_count = 6

    # Derived dimensions and sanity checks.
    outer_radius = outer_ring_od / 2.0
    outer_inner_radius = outer_ring_id / 2.0
    hub_outer_radius = hub_od / 2.0
    hub_inner_radius = hub_id / 2.0
    radial_span = outer_inner_radius - hub_outer_radius
    strut_half_angle = 3.7
    diffuser_gap_half_angle = strut_pitch_degrees / 2.0 - strut_half_angle - 0.35
    b.require_positive(
        outer_ring_od=outer_ring_od,
        outer_ring_id=outer_ring_id,
        hub_od=hub_od,
        hub_id=hub_id,
        frame_length=frame_length,
        radial_span=radial_span,
        diffuser_gap_half_angle=diffuser_gap_half_angle,
    )
    b.require_min_wall(outer_ring_od, outer_ring_id, min_wall=20.0, label="outer ring radial wall")
    b.require_min_wall(hub_od, hub_id, min_wall=20.0, label="hub bearing wall")
    b.require_feature_budget(
        boolean_operations=220,
        micro_holes=acoustic_cavity_count * 12,
        patterned_features=strut_count + fuel_boss_count + acoustic_cavity_count + tie_bolt_count,
        max_boolean_operations=260,
        max_micro_holes=480,
        max_patterned_features=140,
    )

    # Main Inconel 718 outer ring and central hub.
    outer_ring = b.cylinder(outer_ring_od, frame_length, origin=(0, 0, front_z), axis=(0, 0, 1))
    outer_bore = b.hole(outer_ring_id, frame_length + through_overcut, position=(0, 0, rear_z + through_overcut / 2.0), direction=(0, 0, -1))
    b.boolean_subtract(outer_ring, outer_bore)
    b.chamfer(b.get_top_edges(outer_ring), edge_break)
    b.chamfer(b.get_bottom_edges(outer_ring), edge_break)

    hub = b.cylinder(hub_od, frame_length, origin=(0, 0, front_z), axis=(0, 0, 1))
    hub_through = b.hole(hub_id, frame_length + through_overcut, position=(0, 0, rear_z + through_overcut / 2.0), direction=(0, 0, -1))
    b.boolean_subtract(hub, hub_through)
    b.boolean_unite(outer_ring, hub)

    # Bearing details: front H6 bore, silver sleeve, retaining groove, rear roller seat, circlip.
    front_lead_in = b.hole(front_bearing_bore + 3.0, 1.5 + cutter_overlap, position=(0, 0, front_z - cutter_overlap), direction=(0, 0, 1))
    b.boolean_subtract(outer_ring, front_lead_in)
    front_bearing_relief = b.hole(front_bearing_bore, front_bearing_depth + cutter_overlap, position=(0, 0, front_z - cutter_overlap), direction=(0, 0, 1))
    b.boolean_subtract(outer_ring, front_bearing_relief)
    sleeve = b.cylinder(silver_sleeve_od, silver_sleeve_length, origin=(0, 0, front_z + feature_overlap), axis=(0, 0, 1))
    sleeve_bore = b.hole(silver_sleeve_id, silver_sleeve_length + through_overcut, position=(0, 0, front_z + silver_sleeve_length + through_overcut / 2.0), direction=(0, 0, -1))
    b.boolean_subtract(sleeve, sleeve_bore)
    b.boolean_unite(outer_ring, sleeve)
    retaining_groove = b.hole(front_bearing_bore + 15.0, 2.0, position=(0, 0, front_z + front_bearing_depth - 15.0), direction=(0, 0, 1))
    b.boolean_subtract(outer_ring, retaining_groove)
    rear_seat = b.hole(rear_bearing_bore, rear_counterbore_depth + cutter_overlap, position=(0, 0, rear_counterbore_z), direction=(0, 0, 1))
    b.boolean_subtract(outer_ring, rear_seat)
    circlip_groove = b.hole(rear_bearing_bore + 2.0, 0.4 + cutter_overlap, position=(0, 0, 142.0), direction=(0, 0, 1))
    b.boolean_subtract(outer_ring, circlip_groove)

    # Radial struts, manifold groove, cooling passages, return bends, inlet holes, and TE sawtooth notches.
    manifold = b.hole(outer_ring_id + 24.0, 12.0, position=(0, 0, manifold_z - 6.0), direction=(0, 0, 1))
    b.boolean_subtract(outer_ring, manifold)
    for index in range(strut_count):
        angle = index * strut_pitch_degrees
        points = _sector_points(hub_outer_radius - feature_overlap, outer_inner_radius + feature_overlap, strut_half_angle, strut_aft_lean_degrees)
        ca = math.cos(math.radians(angle))
        sa = math.sin(math.radians(angle))
        rotated = [(x * ca - y * sa, x * sa + y * ca) for x, y in points]
        strut = b.polygon_prism(rotated, frame_length, origin=(0, 0, front_z), axis=(0, 0, 1))
        b.boolean_unite(outer_ring, strut)

        rx, ry, _ = _unit(angle)
        tx, ty, _ = _tangent(angle)
        # Two long cooling passages plus a shallow 180-degree return representation at the hub end.
        for offset in (-3.0, 3.0):
            sx = outer_inner_radius * rx + offset * tx
            sy = outer_inner_radius * ry + offset * ty
            passage = b.hole(4.0, radial_span + 2.0, position=(sx, sy, manifold_z), direction=(-rx, -ry, 0))
            b.boolean_subtract(outer_ring, passage)
        return_bend = b.hole(8.0, 8.0, position=((hub_outer_radius + 9.0) * rx, (hub_outer_radius + 9.0) * ry, manifold_z), direction=(0, 0, 1))
        b.boolean_subtract(outer_ring, return_bend)
        inlet = b.hole(6.0, 18.0, position=(outer_radius * rx, outer_radius * ry, manifold_z), direction=(-rx, -ry, 0))
        b.boolean_subtract(outer_ring, inlet)
        for tooth in range(3):
            zc = 96.0 + tooth * 15.0
            notch = b.box(1.2, 0.3, 3.0, origin=((outer_inner_radius - 22.0) * rx + tooth * 1.5 * tx, (outer_inner_radius - 22.0) * ry + tooth * 1.5 * ty, zc))
            b.boolean_subtract(outer_ring, notch)

    # Diffuser passages between struts and TBC/glass-seal raised bands on pressure side.
    for index in range(strut_count):
        angle = index * strut_pitch_degrees + strut_pitch_degrees / 2.0
        gap_points = _sector_points(hub_outer_radius + 2.0, outer_inner_radius - 2.0, diffuser_gap_half_angle)
        ca = math.cos(math.radians(angle))
        sa = math.sin(math.radians(angle))
        gap_rot = [(x * ca - y * sa, x * sa + y * ca) for x, y in gap_points]
        diffuser = b.polygon_prism(gap_rot, frame_length + through_overcut, origin=(0, 0, front_z - through_overcut / 2.0), axis=(0, 0, 1))
        b.boolean_subtract(outer_ring, diffuser)
        if index % 2 == 0:
            rx, ry, _ = _unit(angle - diffuser_gap_half_angle)
            tx, ty, _ = _tangent(angle - diffuser_gap_half_angle)
            coat_center_radius = (hub_outer_radius + outer_inner_radius) / 2.0
            cx = coat_center_radius * rx
            cy = coat_center_radius * ry
            coat = b.box(42.0, 0.8, 105.0, origin=(cx - 21.0 + tx * 0.4, cy - 0.4 + ty * 0.4, 20.0))
            b.boolean_unite(outer_ring, coat)

    # Fuel nozzle bosses every other strut with H7 bore, four M6 holes, cast passage and orifice.
    for index in range(fuel_boss_count):
        angle = index * 20.0 + 5.0
        rx, ry, _ = _unit(angle)
        tx, ty, _ = _tangent(angle)
        cx = 176.0 * rx
        cy = 176.0 * ry
        boss = b.box(
            fuel_boss_length,
            fuel_boss_width,
            fuel_boss_height + feature_overlap,
            origin=(cx - fuel_boss_length / 2.0, cy - fuel_boss_width / 2.0, front_z - feature_overlap),
        )
        b.boolean_unite(outer_ring, boss)
        bore = b.hole(fuel_bore_diameter, fuel_bore_depth + cutter_overlap, position=(cx, cy, front_z - cutter_overlap), direction=(0, 0, 1))
        b.boolean_subtract(outer_ring, bore)
        for sx, sy in ((1, 1), (-1, 1), (-1, -1), (1, -1)):
            px = cx + sx * 10.0 * tx + sy * 10.0 * rx
            py = cy + sx * 10.0 * ty + sy * 10.0 * ry
            b.screw_clearance_hole(outer_ring, "M6", fuel_boss_height + through_overcut, position=(px, py, front_z - cutter_overlap), direction=(0, 0, 1))
        cast_passage = b.hole(8.0, 45.0, position=(cx, cy, front_z + 5.0), direction=(-rx, -ry, 0))
        b.boolean_subtract(outer_ring, cast_passage)
        orifice = b.hole(6.0, 12.0, position=((hub_outer_radius + 12.0) * rx, (hub_outer_radius + 12.0) * ry, front_z + 5.0), direction=(rx, ry, 0))
        b.boolean_subtract(outer_ring, orifice)

    # Instrumentation ports: radial M10 x 1.5/tapped equivalent with counterbore pads.
    for index in range(instrumentation_count):
        angle = 90.0 + index * 60.0
        rx, ry, _ = _unit(angle)
        px = outer_radius * rx
        py = outer_radius * ry
        counterbore = b.hole(12.0, 18.0, position=(px, py, 110.0), direction=(-rx, -ry, 0))
        b.boolean_subtract(outer_ring, counterbore)
        tap = b.hole(8.5, 22.0, position=(px - 8.0 * rx, py - 8.0 * ry, 110.0), direction=(-rx, -ry, 0))
        b.boolean_subtract(outer_ring, tap)

    # Tie-bolt ring groove, M12 holes, C-seal groove, anti-rotation arms.
    tie_groove = b.hole(outer_ring_od - 18.0, 12.0, position=(0, 0, rear_z - 12.0), direction=(0, 0, 1))
    b.boolean_subtract(outer_ring, tie_groove)
    cseal_groove = b.hole(470.0, 2.0, position=(0, 0, rear_z - 1.5), direction=(0, 0, 1))
    b.boolean_subtract(outer_ring, cseal_groove)
    for x, y, z in b.circular_pattern_points((0, 0, rear_z + cutter_overlap), tie_bolt_circle / 2.0, tie_bolt_count):
        b.screw_clearance_hole(outer_ring, "M12", frame_length + through_overcut, position=(x, y, rear_z + cutter_overlap), direction=(0, 0, -1))
    for index in range(anti_rotation_count):
        angle = index * 30.0
        rx, ry, _ = _unit(angle)
        tx, ty, _ = _tangent(angle + 8.0)
        cx = (outer_radius + 29.0) * rx
        cy = (outer_radius + 29.0) * ry
        arm = b.box(60.0, 25.0, 35.0, origin=(cx - 30.0, cy - 12.5, rear_z - feature_overlap))
        b.boolean_unite(outer_ring, arm)
        bore = b.hole(16.0, 70.0, position=(cx, cy, rear_z + 17.5), direction=(tx, ty, 0))
        b.boolean_subtract(outer_ring, bore)
        keyway = b.box(6.0, 20.0, 8.0, origin=(cx - 3.0, cy - 10.0, rear_z + 13.0))
        b.boolean_subtract(outer_ring, keyway)

    # Acoustic liner cavities and representative laser-hole rows.
    for index in range(acoustic_cavity_count):
        angle = index * strut_pitch_degrees + strut_pitch_degrees / 2.0
        rx, ry, _ = _unit(angle)
        tx, ty, _ = _tangent(angle)
        cx = 206.0 * rx
        cy = 206.0 * ry
        cavity = b.box(45.0, 35.0, 60.0, origin=(cx - 22.5, cy - 17.5, 30.0))
        b.boolean_subtract(outer_ring, cavity)
        for row in range(3):
            for col in range(4):
                px = cx + (col - 1.5) * 1.5 * tx + (row - 1.0) * 1.3 * rx
                py = cy + (col - 1.5) * 1.5 * ty + (row - 1.0) * 1.3 * ry
                perf = b.hole(0.6, 8.0, position=(px, py, 55.0 + row * 8.0), direction=(-rx, -ry, 0))
                b.boolean_subtract(outer_ring, perf)
        felt = b.box(40.0, 3.0, 58.0, origin=(cx - 20.0, cy - 1.5, 31.0))
        b.boolean_unite(outer_ring, felt)

    # Scavenge pump pad and local holes, offset 15 mm from center.
    pump_pad = b.box(55.0, 8.0, 10.0, origin=(-12.5, 15.0, rear_z - feature_overlap))
    b.boolean_unite(outer_ring, pump_pad)
    pump_bore = b.hole(25.0, 16.0, position=(15.0, 19.0, rear_z + 2.0), direction=(0, 0, -1))
    b.boolean_subtract(outer_ring, pump_bore)
    for sx, sy in ((1, 1), (-1, 1), (-1, -1), (1, -1)):
        b.screw_clearance_hole(outer_ring, "M5", 14.0, position=(15.0 + sx * 20.0, 19.0 + sy * 20.0, rear_z + 2.0), direction=(0, 0, -1))

    # Casting witness flash, TIG-filled core ports, UT sacrificial pad and FBH.
    flash = b.box(486.0, 0.5, 4.0, origin=(-outer_radius, -0.25, manifold_z - 2.0))
    b.boolean_unite(outer_ring, flash)
    for index in range(18):
        angle = index * 20.0 + 10.0
        rx, ry, _ = _unit(angle)
        plug = b.cylinder(6.0, 4.0, origin=(outer_radius * rx, outer_radius * ry, manifold_z), axis=(-rx, -ry, 0))
        b.boolean_unite(outer_ring, plug)
    ut_pad = b.box(30.0, 20.0, 15.0, origin=(outer_radius - feature_overlap, -10.0, manifold_z - 7.5))
    b.boolean_unite(outer_ring, ut_pad)
    fbh = b.hole(0.8, 25.0, position=(outer_radius + 15.0, 0.0, manifold_z), direction=(-1, 0, 0))
    b.boolean_subtract(outer_ring, fbh)

    # Data matrix plate at rear face, X=80, with raised cells encoding heat/HIP/NDT/max speed metadata.
    data_plate = b.box(12.0, 12.0, 0.8, origin=(80.0 - 6.0, -6.0, rear_z - feature_overlap))
    b.boolean_unite(outer_ring, data_plate)
    cell = 1.0
    matrix_pattern = [
        "111111111111",
        "100100010001",
        "101101110101",
        "100001000101",
        "111011101101",
        "101000101001",
        "101111001101",
        "100010101001",
        "111010111101",
        "100110000101",
        "101001111001",
        "111111111111",
    ]
    for row, line in enumerate(matrix_pattern):
        for col, value in enumerate(line):
            if value == "1":
                mark = b.box(0.7, 0.7, 0.6, origin=(80.0 - 5.8 + col * cell, -5.8 + row * cell, rear_z + 0.05))
                b.boolean_unite(outer_ring, mark)

    # Small local edge refinements on the rear datum ring only.
    b.chamfer(
        b.get_edges_in_box(
            outer_ring,
            min_xyz=(-outer_radius, -outer_radius, rear_z - 2.0),
            max_xyz=(outer_radius, outer_radius, rear_z + 2.0),
        ),
        edge_break,
    )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
