# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              ergonomic_carbon_fiber_gaming_chair_skeleton.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def _sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _scale(v, s):
    return (v[0] * s, v[1] * s, v[2] * s)


def _dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def _length(v):
    return math.sqrt(_dot(v, v))


def _unit(v):
    value = _length(v)
    if value <= 1e-9:
        raise ValueError("zero-length vector")
    return (v[0] / value, v[1] / value, v[2] / value)


def _rect_tube_between(b, start, end, width, depth, up_hint=(0, 0, 1)):
    axis = _unit(_sub(end, start))
    u_axis = _cross(up_hint, axis)
    if _length(u_axis) <= 1e-6:
        u_axis = _cross((1, 0, 0), axis)
    u_axis = _unit(u_axis)
    v_axis = _unit(_cross(axis, u_axis))
    points = [
        (-width / 2.0, -depth / 2.0),
        (width / 2.0, -depth / 2.0),
        (width / 2.0, depth / 2.0),
        (-width / 2.0, depth / 2.0),
    ]
    return b.polygon_prism_on_plane(
        points,
        _length(_sub(end, start)),
        origin=start,
        u_axis=u_axis,
        v_axis=v_axis,
        extrude_axis=axis,
    )


def _unite_all(b, target, tools):
    for tool in tools:
        b.boolean_unite(target, tool)
    return target


def _name_body(feature, name):
    try:
        for body in feature.GetBodies():
            body.SetName(name)
    except Exception:
        pass


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    seat_width = 480.0
    seat_depth = 520.0
    seat_tube = 25.0
    seat_wall = 3.0
    back_width = 440.0
    back_height = 620.0
    back_tube = 25.0
    back_recline_deg = 15.0
    hinge_block_width = 40.0
    hinge_block_depth = 40.0
    hinge_block_height = 30.0
    lumbar_width = 380.0
    lumbar_tube_x = 20.0
    lumbar_tube_z = 15.0
    lumbar_height_above_hinge = 180.0
    headrest_width = 200.0
    headrest_tube = 20.0
    headrest_forward = 60.0
    arm_vertical = 200.0
    arm_horizontal = 240.0
    arm_tube = 20.0
    column_outer_diameter = 60.0
    column_wall = 4.0
    column_height = 350.0
    mount_plate_size = 120.0
    mount_plate_height = 15.0
    base_arm_length = 280.0
    base_root_width = 40.0
    base_tip_width = 20.0
    base_root_height = 30.0
    caster_socket_diameter = 20.0
    caster_socket_height = 30.0

    # Derived layout.
    seat_x0 = -seat_width / 2.0
    seat_y0 = -seat_depth / 2.0
    back_y = seat_depth / 2.0 - seat_tube / 2.0
    back_half = back_width / 2.0
    rail_base_z = hinge_block_height
    recline = math.radians(back_recline_deg)
    back_axis = (0.0, -math.sin(recline), math.cos(recline))
    top_center = _add((0.0, back_y, rail_base_z), _scale(back_axis, back_height))

    # Seat frame: one hollow rectangular ring body with two cross braces.
    seat = b.box(seat_width, seat_depth, seat_tube, origin=(seat_x0, seat_y0, 0.0))
    seat_void = b.box(
        seat_width - 2.0 * seat_tube,
        seat_depth - 2.0 * seat_tube,
        seat_tube + 2.0,
        origin=(seat_x0 + seat_tube, seat_y0 + seat_tube, -1.0),
    )
    b.boolean_subtract(seat, seat_void)
    brace_offset = seat_tube * 0.85
    for x in (-brace_offset, brace_offset):
        brace = _rect_tube_between(
            b,
            (x, seat_y0 + seat_tube / 2.0, seat_tube / 2.0),
            (x, -seat_y0 - seat_tube / 2.0, seat_tube / 2.0),
            seat_tube,
            seat_tube,
        )
        b.boolean_unite(seat, brace)
    _name_body(seat, "seat frame - hollow carbon fiber ring with cross braces")

    # Backrest frame: reclined U-body with two rails, top tube, and hinge blocks.
    left_base = (-back_half, back_y, rail_base_z)
    right_base = (back_half, back_y, rail_base_z)
    left_top = _add(left_base, _scale(back_axis, back_height))
    right_top = _add(right_base, _scale(back_axis, back_height))
    back = _rect_tube_between(b, left_base, left_top, back_tube, back_tube, up_hint=(1, 0, 0))
    back_parts = [
        _rect_tube_between(b, right_base, right_top, back_tube, back_tube, up_hint=(1, 0, 0)),
        _rect_tube_between(b, left_top, right_top, back_tube, back_tube, up_hint=(0, 0, 1)),
        b.box(
            hinge_block_width,
            hinge_block_depth,
            hinge_block_height,
            origin=(-back_half - hinge_block_width / 2.0, back_y - hinge_block_depth / 2.0, 0.0),
        ),
        b.box(
            hinge_block_width,
            hinge_block_depth,
            hinge_block_height,
            origin=(back_half - hinge_block_width / 2.0, back_y - hinge_block_depth / 2.0, 0.0),
        ),
    ]
    _unite_all(b, back, back_parts)
    _name_body(back, "backrest frame - 15 degree reclined U tube and hinge blocks")

    # Lumbar support: three-segment shallow forward curve between rails.
    lumbar_center = _add((0.0, back_y, rail_base_z), _scale(back_axis, lumbar_height_above_hinge))
    lumbar_xs = [-lumbar_width / 2.0, -lumbar_width / 6.0, lumbar_width / 6.0, lumbar_width / 2.0]
    lumbar_points = []
    for x in lumbar_xs:
        normalized = abs(x) / (lumbar_width / 2.0)
        lumbar_points.append((x, lumbar_center[1] - 22.0 * (1.0 - normalized), lumbar_center[2]))
    lumbar = _rect_tube_between(b, lumbar_points[0], lumbar_points[1], lumbar_tube_x, lumbar_tube_z)
    _unite_all(
        b,
        lumbar,
        [
            _rect_tube_between(b, lumbar_points[1], lumbar_points[2], lumbar_tube_x, lumbar_tube_z),
            _rect_tube_between(b, lumbar_points[2], lumbar_points[3], lumbar_tube_x, lumbar_tube_z),
        ],
    )
    _name_body(lumbar, "lumbar support bar - shallow curved carbon fiber tube")

    # Headrest bracket: cross tube at the top and two short forward struts.
    head_center = top_center
    head_left = (-headrest_width / 2.0, head_center[1], head_center[2])
    head_right = (headrest_width / 2.0, head_center[1], head_center[2])
    head_front_left = (head_left[0], head_left[1] - headrest_forward, head_left[2])
    head_front_right = (head_right[0], head_right[1] - headrest_forward, head_right[2])
    headrest = _rect_tube_between(b, head_front_left, head_front_right, headrest_tube, headrest_tube)
    _unite_all(
        b,
        headrest,
        [
            _rect_tube_between(b, head_left, head_front_left, headrest_tube, headrest_tube),
            _rect_tube_between(b, head_right, head_front_right, headrest_tube, headrest_tube),
        ],
    )
    _name_body(headrest, "headrest bracket - forward offset carbon fiber tube")

    # Two separate L-shaped armrest bracket bodies.
    for side, x in (("left", -seat_width / 2.0), ("right", seat_width / 2.0)):
        vertical = _rect_tube_between(
            b,
            (x, -seat_depth * 0.12, 0.0),
            (x, -seat_depth * 0.12, arm_vertical),
            arm_tube,
            arm_tube,
        )
        horizontal = _rect_tube_between(
            b,
            (x, -seat_depth * 0.12, arm_vertical),
            (x, -seat_depth * 0.12 - arm_horizontal, arm_vertical),
            arm_tube,
            arm_tube,
        )
        b.boolean_unite(vertical, horizontal)
        _name_body(vertical, f"{side} armrest bracket - L shaped carbon fiber tube")

    # Center column: hollow circular tube with top mounting plate as one body.
    column = b.cylinder(column_outer_diameter, column_height, origin=(0.0, 0.0, -column_height), axis=(0, 0, 1))
    column_void = b.cylinder(
        column_outer_diameter - 2.0 * column_wall,
        column_height + 2.0,
        origin=(0.0, 0.0, -column_height - 1.0),
        axis=(0, 0, 1),
    )
    b.boolean_subtract(column, column_void)
    plate = b.box(
        mount_plate_size,
        mount_plate_size,
        mount_plate_height,
        origin=(-mount_plate_size / 2.0, -mount_plate_size / 2.0, -mount_plate_height),
    )
    b.boolean_unite(column, plate)
    _name_body(column, "center column - hollow tube with square mounting plate")

    # Five-star base: one body with five tapered trapezoid arms and caster sockets.
    base = b.cylinder(90.0, base_root_height, origin=(0.0, 0.0, -column_height), axis=(0, 0, 1))
    for index in range(5):
        angle = math.radians(index * 72.0)
        radial = (math.cos(angle), math.sin(angle), 0.0)
        tangent = (-math.sin(angle), math.cos(angle), 0.0)
        root_center = _scale(radial, 35.0)
        tip_center = _scale(radial, base_arm_length)
        p1 = _add(root_center, _scale(tangent, -base_root_width / 2.0))
        p2 = _add(root_center, _scale(tangent, base_root_width / 2.0))
        p3 = _add(tip_center, _scale(tangent, base_tip_width / 2.0))
        p4 = _add(tip_center, _scale(tangent, -base_tip_width / 2.0))
        arm = b.polygon_prism(
            [(p1[0], p1[1]), (p2[0], p2[1]), (p3[0], p3[1]), (p4[0], p4[1])],
            base_root_height,
            origin=(0.0, 0.0, -column_height),
            axis=(0, 0, 1),
        )
        socket = b.cylinder(
            caster_socket_diameter,
            caster_socket_height,
            origin=(tip_center[0], tip_center[1], -column_height - caster_socket_height / 2.0),
            axis=(0, 0, 1),
        )
        b.boolean_unite(base, arm)
        b.boolean_unite(base, socket)
    _name_body(base, "five-star base - tapered arms with caster sockets")

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
