# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              high_precision_hydraulic_manifold_block.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Coordinate convention: block centered on XY origin, bottom face at Z=0.
    through_overcut = 2.0
    cutter_overlap = 0.7
    feature_overlap = 0.6
    vertical_edge_fillet = 2.0
    pad_fillet = 1.5
    side_boss_fillet = 1.5
    top_bottom_chamfer = 1.0
    hole_chamfer = 0.5

    # Independent prompt dimensions.
    body_length_x = 120.0
    body_width_y = 60.0
    body_height_z = 45.0

    valve_pad_length_x = 70.0
    valve_pad_width_y = 42.0
    valve_pad_height_z = 4.0

    valve_bore_diameter = 22.0
    valve_bore_depth = 32.0
    valve_counterbore_diameter = 32.0
    valve_counterbore_depth = 6.0

    valve_mount_hole_diameter = 6.6
    valve_mount_hole_depth = 24.0
    valve_mount_counterbore_diameter = 12.0
    valve_mount_counterbore_depth = 5.0
    valve_mount_x = 25.0
    valve_mount_y = 14.0

    main_port_diameter = 10.0
    main_port_y_locations = (-14.0, 14.0)
    main_port_z = 24.0

    cross_port_diameter = 8.0
    cross_port_x_locations = (-32.0, 32.0)
    cross_port_z = 26.0

    side_boss_diameter = 22.0
    side_boss_protrusion = 3.0

    base_mount_hole_diameter = 8.5
    base_mount_counterbore_diameter = 15.0
    base_mount_counterbore_depth = 6.0
    base_mount_x = 48.0
    base_mount_y = 22.0

    dowel_hole_diameter = 5.0
    dowel_hole_depth = 12.0
    dowel_x = 36.0

    side_pocket_length_x = 60.0
    side_pocket_height_z = 18.0
    side_pocket_depth = 3.0
    side_pocket_corner_radius = 4.0

    # Derived placement.
    body_x_min = -body_length_x / 2.0
    body_y_min = -body_width_y / 2.0
    body_z_min = 0.0
    body_top_z = body_height_z
    pad_top_z = body_top_z + valve_pad_height_z
    body_center_z = body_height_z / 2.0
    port_x_depth = body_length_x + 2.0 * through_overcut
    port_y_depth = body_width_y + 2.0 * side_boss_protrusion + 2.0 * through_overcut

    b.require_positive(
        body_length_x=body_length_x,
        body_width_y=body_width_y,
        body_height_z=body_height_z,
        valve_pad_length_x=valve_pad_length_x,
        valve_pad_width_y=valve_pad_width_y,
        valve_pad_height_z=valve_pad_height_z,
    )
    b.require_min_wall(body_width_y, side_pocket_depth * 2.0, min_wall=20.0, label="opposed side pockets")
    b.require_min_wall(valve_counterbore_diameter, valve_bore_diameter, min_wall=3.0, label="valve bore counterbore")
    b.require_edge_distance(valve_pad_width_y / 2.0 - valve_mount_y, valve_mount_counterbore_diameter, min_ratio=0.55, label="valve mount counterbore Y edge")
    b.require_edge_distance(body_length_x / 2.0 - base_mount_x, base_mount_counterbore_diameter, min_ratio=0.75, label="base mounting X edge")
    b.require_edge_distance(body_width_y / 2.0 - base_mount_y, base_mount_counterbore_diameter, min_ratio=0.5, label="base mounting Y edge")
    b.require_feature_budget(boolean_operations=58, micro_holes=18, patterned_features=22)

    def cyl(diameter, height, center, axis=(0, 0, 1)):
        origin = (
            center[0] - axis[0] * height / 2.0,
            center[1] - axis[1] * height / 2.0,
            center[2] - axis[2] * height / 2.0,
        )
        return b.cylinder(diameter, height, origin=origin, axis=axis)

    def cut_cylinder(target, diameter, depth, center, axis):
        tool = cyl(diameter, depth, center, axis=axis)
        b.boolean_subtract(target, tool)

    def chamfer_hole_openings(target, center, axis, diameter, length):
        radius = diameter / 2.0 + hole_chamfer + 1.0
        for sign in (-1.0, 1.0):
            face = (
                center[0] + axis[0] * sign * length / 2.0,
                center[1] + axis[1] * sign * length / 2.0,
                center[2] + axis[2] * sign * length / 2.0,
            )
            b.chamfer(
                b.get_edges_in_box(
                    target,
                    min_xyz=(face[0] - radius, face[1] - radius, face[2] - radius),
                    max_xyz=(face[0] + radius, face[1] + radius, face[2] + radius),
                ),
                hole_chamfer,
            )

    # Main CNC-machined manifold body.
    manifold = b.rounded_box(
        body_length_x,
        body_width_y,
        body_height_z,
        radius=vertical_edge_fillet,
        origin=(body_x_min, body_y_min, body_z_min),
    )

    # Raised top valve pad, united into the body with overlap for robust boolean topology.
    pad = b.rounded_box(
        valve_pad_length_x,
        valve_pad_width_y,
        valve_pad_height_z + feature_overlap,
        radius=pad_fillet,
        origin=(-valve_pad_length_x / 2.0, -valve_pad_width_y / 2.0, body_top_z - feature_overlap),
    )
    b.boolean_unite(manifold, pad)
    b.fillet(
        b.get_edges_in_box(
            manifold,
            min_xyz=(-valve_pad_length_x / 2.0 - 2.0, -valve_pad_width_y / 2.0 - 2.0, body_top_z - 2.0),
            max_xyz=(valve_pad_length_x / 2.0 + 2.0, valve_pad_width_y / 2.0 + 2.0, pad_top_z + 1.0),
        ),
        pad_fillet,
    )

    # Side bosses around all cross-port openings before the port bores are cut.
    for x in cross_port_x_locations:
        for y_sign in (-1.0, 1.0):
            boss_center = (
                x,
                y_sign * (body_width_y / 2.0 + side_boss_protrusion / 2.0 - feature_overlap),
                cross_port_z,
            )
            boss = cyl(side_boss_diameter, side_boss_protrusion + feature_overlap, boss_center, axis=(0, 1, 0))
            b.boolean_unite(manifold, boss)
            b.fillet(
                b.get_edges_in_box(
                    manifold,
                    min_xyz=(x - side_boss_diameter / 2.0 - 1.0, y_sign * body_width_y / 2.0 - 2.0, cross_port_z - side_boss_diameter / 2.0 - 1.0),
                    max_xyz=(x + side_boss_diameter / 2.0 + 1.0, y_sign * (body_width_y / 2.0 + side_boss_protrusion + 1.0), cross_port_z + side_boss_diameter / 2.0 + 1.0),
                ),
                side_boss_fillet,
            )

    # Shallow weight-reduction pockets on both long side faces.
    for y_sign in (-1.0, 1.0):
        pocket_center = (0.0, y_sign * (body_width_y / 2.0 - side_pocket_depth / 2.0 + cutter_overlap), 22.0)
        pocket = b.rounded_box(
            side_pocket_length_x,
            side_pocket_depth + 2.0 * cutter_overlap,
            side_pocket_height_z,
            radius=side_pocket_corner_radius,
            origin=(
                -side_pocket_length_x / 2.0,
                pocket_center[1] - (side_pocket_depth + 2.0 * cutter_overlap) / 2.0,
                pocket_center[2] - side_pocket_height_z / 2.0,
            ),
        )
        b.boolean_subtract(manifold, pocket)

    # Top valve bore and four valve mounting holes.
    b.counterbore_hole(
        manifold,
        valve_bore_diameter,
        valve_bore_depth,
        valve_counterbore_diameter,
        valve_counterbore_depth,
        position=(0.0, 0.0, pad_top_z + cutter_overlap),
        direction=(0, 0, -1),
    )
    chamfer_hole_openings(manifold, (0.0, 0.0, pad_top_z - valve_bore_depth / 2.0), (0, 0, 1), valve_bore_diameter, valve_bore_depth)

    for x in (-valve_mount_x, valve_mount_x):
        for y in (-valve_mount_y, valve_mount_y):
            b.counterbore_hole(
                manifold,
                valve_mount_hole_diameter,
                valve_mount_hole_depth,
                valve_mount_counterbore_diameter,
                valve_mount_counterbore_depth,
                position=(x, y, pad_top_z + cutter_overlap),
                direction=(0, 0, -1),
            )
            chamfer_hole_openings(manifold, (x, y, pad_top_z - valve_mount_hole_depth / 2.0), (0, 0, 1), valve_mount_hole_diameter, valve_mount_hole_depth)

    # Intersecting hydraulic passages.
    for y in main_port_y_locations:
        cut_cylinder(manifold, main_port_diameter, port_x_depth, (0.0, y, main_port_z), axis=(1, 0, 0))
        chamfer_hole_openings(manifold, (0.0, y, main_port_z), (1, 0, 0), main_port_diameter, body_length_x)

    for x in cross_port_x_locations:
        cut_cylinder(manifold, cross_port_diameter, port_y_depth, (x, 0.0, cross_port_z), axis=(0, 1, 0))
        chamfer_hole_openings(manifold, (x, 0.0, cross_port_z), (0, 1, 0), cross_port_diameter, body_width_y + 2.0 * side_boss_protrusion)

    # Base mounting holes and bottom dowel holes.
    for x in (-base_mount_x, base_mount_x):
        for y in (-base_mount_y, base_mount_y):
            b.counterbore_hole(
                manifold,
                base_mount_hole_diameter,
                body_height_z + valve_pad_height_z + through_overcut,
                base_mount_counterbore_diameter,
                base_mount_counterbore_depth,
                position=(x, y, body_top_z + cutter_overlap),
                direction=(0, 0, -1),
            )
            chamfer_hole_openings(manifold, (x, y, body_center_z), (0, 0, 1), base_mount_hole_diameter, body_height_z)

    for x in (-dowel_x, dowel_x):
        cut_cylinder(manifold, dowel_hole_diameter, dowel_hole_depth + cutter_overlap, (x, 0.0, dowel_hole_depth / 2.0 - cutter_overlap), axis=(0, 0, 1))
        chamfer_hole_openings(manifold, (x, 0.0, dowel_hole_depth / 2.0), (0, 0, 1), dowel_hole_diameter, dowel_hole_depth)

    # Top and bottom machined edge breaks after functional cuts.
    b.chamfer(b.get_top_edges(manifold), top_bottom_chamfer)
    b.chamfer(b.get_bottom_edges(manifold), top_bottom_chamfer)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
