# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              high_precision_motor_mounting_bracket.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    base_length = 80.0
    base_width = 50.0
    base_thickness = 8.0

    wall_center_x = -30.0
    wall_thickness_x = 10.0
    wall_width_y = 50.0
    wall_height_above_base = 55.0

    pilot_bore_diameter = 22.0
    pilot_center_y = 0.0
    pilot_center_z = 34.0

    motor_screw_hole_diameter = 4.2
    motor_screw_square_pitch = 32.0

    base_mount_hole_diameter = 4.2
    base_mount_x_abs = 25.0
    base_mount_y_abs = 18.0

    rib_thickness_y = 6.0
    rib_center_y_abs = 16.0
    rib_x_extent = 28.0
    rib_height_z = 38.0

    transition_fillet_radius = 2.0
    major_outer_fillet_radius = 3.0
    chamfer_offset = 0.6

    # Derived dimensions and robustness allowances.
    base_origin = (-base_length / 2.0, -base_width / 2.0, 0.0)
    base_top_z = base_thickness
    wall_front_x = wall_center_x - wall_thickness_x / 2.0
    wall_back_x = wall_center_x + wall_thickness_x / 2.0
    wall_origin = (
        wall_front_x,
        -wall_width_y / 2.0,
        base_top_z - 0.5,
    )
    wall_total_height = wall_height_above_base + 0.5
    wall_top_z = base_top_z + wall_height_above_base

    rib_start_x = wall_back_x - 0.5
    rib_end_x = rib_start_x + rib_x_extent
    feature_overlap = 0.5
    through_overcut = 2.0
    wall_cut_depth = wall_thickness_x + 2.0 * through_overcut
    base_cut_depth = base_thickness + 2.0 * through_overcut
    motor_screw_offset = motor_screw_square_pitch / 2.0

    b.require_positive(
        base_length=base_length,
        base_width=base_width,
        base_thickness=base_thickness,
        wall_thickness_x=wall_thickness_x,
        wall_width_y=wall_width_y,
        wall_height_above_base=wall_height_above_base,
        pilot_bore_diameter=pilot_bore_diameter,
        rib_thickness_y=rib_thickness_y,
    )
    b.require_min_wall(wall_width_y, motor_screw_square_pitch + motor_screw_hole_diameter, min_wall=4.0, label="motor screw square in wall")
    b.require_edge_distance(base_length / 2.0 - base_mount_x_abs, base_mount_hole_diameter, min_ratio=1.0, label="base mounting hole X edge")
    b.require_edge_distance(base_width / 2.0 - base_mount_y_abs, base_mount_hole_diameter, min_ratio=1.0, label="base mounting hole Y edge")
    b.require_feature_budget(boolean_operations=20, patterned_features=8)

    # Primary L-bracket body.
    body = b.rounded_box(
        base_length,
        base_width,
        base_thickness,
        radius=major_outer_fillet_radius,
        origin=base_origin,
        vertical_only=True,
    )

    wall = b.rounded_box(
        wall_thickness_x,
        wall_width_y,
        wall_total_height,
        radius=major_outer_fillet_radius,
        origin=wall_origin,
        vertical_only=True,
    )
    b.boolean_unite(body, wall)

    # Two triangular reinforcing ribs extruded in Y from XZ profiles.
    rib_profile = [
        (rib_start_x, base_top_z - feature_overlap),
        (rib_end_x, base_top_z - feature_overlap),
        (rib_start_x, base_top_z + rib_height_z),
    ]
    for rib_center_y in (-rib_center_y_abs, rib_center_y_abs):
        rib = b.polygon_prism_on_plane(
            rib_profile,
            rib_thickness_y,
            origin=(0.0, rib_center_y - rib_thickness_y / 2.0, 0.0),
            u_axis=(1, 0, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(0, 1, 0),
        )
        b.boolean_unite(body, rib)

    # Motor pilot and M4 clearance holes through the vertical wall along X.
    pilot = b.hole(
        pilot_bore_diameter,
        wall_cut_depth,
        position=(wall_back_x + through_overcut, pilot_center_y, pilot_center_z),
        direction=(-1, 0, 0),
    )
    b.boolean_subtract(body, pilot)

    for hole_y in (-motor_screw_offset, motor_screw_offset):
        for hole_z in (pilot_center_z - motor_screw_offset, pilot_center_z + motor_screw_offset):
            motor_hole = b.hole(
                motor_screw_hole_diameter,
                wall_cut_depth,
                position=(wall_back_x + through_overcut, hole_y, hole_z),
                direction=(-1, 0, 0),
            )
            b.boolean_subtract(body, motor_hole)

    # Four M4 clearance holes through the base plate along Z.
    for x in (-base_mount_x_abs, base_mount_x_abs):
        for y in (-base_mount_y_abs, base_mount_y_abs):
            base_hole = b.hole(
                base_mount_hole_diameter,
                base_cut_depth,
                position=(x, y, base_top_z + through_overcut),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(body, base_hole)

    # Localized transition blends for wall/base and rib interfaces.
    b.fillet(
        b.get_edges_in_box(
            body,
            min_xyz=(wall_front_x - 1.0, -wall_width_y / 2.0 - 1.0, base_top_z - 1.0),
            max_xyz=(wall_back_x + 1.0, wall_width_y / 2.0 + 1.0, base_top_z + 1.0),
        ),
        transition_fillet_radius,
    )
    for rib_center_y in (-rib_center_y_abs, rib_center_y_abs):
        y_min = rib_center_y - rib_thickness_y / 2.0 - 1.0
        y_max = rib_center_y + rib_thickness_y / 2.0 + 1.0
        b.fillet(
            b.get_edges_in_box(
                body,
                min_xyz=(rib_start_x - 1.0, y_min, base_top_z - 1.0),
                max_xyz=(rib_end_x + 1.0, y_max, base_top_z + 2.0),
            ),
            transition_fillet_radius,
        )
        b.fillet(
            b.get_edges_in_box(
                body,
                min_xyz=(rib_start_x - 1.0, y_min, base_top_z - 1.0),
                max_xyz=(rib_start_x + 2.0, y_max, base_top_z + rib_height_z + 1.0),
            ),
            transition_fillet_radius,
        )

    # Small chamfers at all specified hole openings and selected exposed sharp edges.
    wall_face_xs = (wall_front_x, wall_back_x)
    for face_x in wall_face_xs:
        b.chamfer(b.get_edges_near(body, point=(face_x, pilot_center_y, pilot_center_z), tolerance=0.9), chamfer_offset)
        for hole_y in (-motor_screw_offset, motor_screw_offset):
            for hole_z in (pilot_center_z - motor_screw_offset, pilot_center_z + motor_screw_offset):
                b.chamfer(b.get_edges_near(body, point=(face_x, hole_y, hole_z), tolerance=0.8), chamfer_offset)

    for x in (-base_mount_x_abs, base_mount_x_abs):
        for y in (-base_mount_y_abs, base_mount_y_abs):
            b.chamfer(b.get_edges_near(body, point=(x, y, 0.0), tolerance=0.8), chamfer_offset)
            b.chamfer(b.get_edges_near(body, point=(x, y, base_top_z), tolerance=0.8), chamfer_offset)

    # Conservative exposed edge breaks where large fillets were not applied by rounded_box.
    b.chamfer(b.get_top_edges(body), chamfer_offset)
    b.chamfer(b.get_bottom_edges(body), chamfer_offset)
    for rib_center_y in (-rib_center_y_abs, rib_center_y_abs):
        b.chamfer(
            b.get_edges_in_box(
                body,
                min_xyz=(rib_start_x - 0.5, rib_center_y - rib_thickness_y / 2.0 - 0.5, base_top_z + rib_height_z - 0.5),
                max_xyz=(rib_end_x + 0.5, rib_center_y + rib_thickness_y / 2.0 + 0.5, base_top_z + rib_height_z + 0.5),
            ),
            chamfer_offset,
        )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
