# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              high_pressure_turbine_rotor_assembly.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports high_pressure_turbine_rotor_assembly.step.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder

try:
    import NXOpen
except ImportError:
    NXOpen = None


def _polar(radius, angle_degrees, z):
    angle = math.radians(angle_degrees)
    return (radius * math.cos(angle), radius * math.sin(angle), z)


def _axes(angle_degrees):
    angle = math.radians(angle_degrees)
    radial = (math.cos(angle), math.sin(angle), 0.0)
    tangential = (-math.sin(angle), math.cos(angle), 0.0)
    return radial, tangential


def _add(p, q):
    return (p[0] + q[0], p[1] + q[1], p[2] + q[2])


def _scale(v, s):
    return (v[0] * s, v[1] * s, v[2] * s)


def _feature_body(builder, feature):
    return builder._body(feature)


def _set_color(builder, features, color_index):
    """Best-effort NX display color assignment; geometry still builds if unavailable."""
    if NXOpen is None:
        return
    try:
        bodies = [_feature_body(builder, feature) for feature in features if feature is not None]
        if not bodies:
            return
        display_mod = builder.session.DisplayManager.NewDisplayModification()
        display_mod.ApplyToAllFaces = True
        display_mod.NewColor = int(color_index)
        display_mod.Apply(bodies)
        display_mod.Dispose()
    except Exception as exc:
        print(f"WARNING: color assignment skipped for NX color {color_index}: {exc}")


def _annular_cylinder(builder, outer_diameter, inner_diameter, height, z_min):
    body = builder.cylinder(outer_diameter, height, origin=(0, 0, z_min), axis=(0, 0, 1))
    bore = builder.hole(inner_diameter, height + 4.0, position=(0, 0, z_min - 2.0), direction=(0, 0, 1))
    builder.boolean_subtract(body, bore)
    return body


def _radial_box(builder, angle_degrees, radial_center, radial_depth, tangential_width, z_center, z_length):
    radial, tangential = _axes(angle_degrees)
    center = _polar(radial_center, angle_degrees, z_center)
    origin = _add(
        _add(center, _scale(radial, -radial_depth / 2.0)),
        _add(_scale(tangential, -tangential_width / 2.0), (0.0, 0.0, -z_length / 2.0)),
    )
    points = [
        (-radial_depth / 2.0, -z_length / 2.0),
        (radial_depth / 2.0, -z_length / 2.0),
        (radial_depth / 2.0, z_length / 2.0),
        (-radial_depth / 2.0, z_length / 2.0),
    ]
    return builder.polygon_prism_on_plane(
        points,
        tangential_width,
        origin=origin,
        u_axis=radial,
        v_axis=(0, 0, 1),
        extrude_axis=tangential,
    )


def _blade_airfoil_section(builder, angle_degrees, r0, r1, z_center, chord0, chord1, stagger0, stagger1, thickness):
    radial, tangential = _axes(angle_degrees)
    r_mid = (r0 + r1) / 2.0
    span = r1 - r0
    chord = (chord0 + chord1) / 2.0
    stagger = math.radians((stagger0 + stagger1) / 2.0)
    local_z = (0.0, 0.0, 1.0)
    chord_axis = _add(_scale(local_z, math.cos(stagger)), _scale(tangential, math.sin(stagger)))
    thickness_axis = _add(_scale(tangential, math.cos(stagger)), _scale(local_z, -math.sin(stagger)))
    camber = 0.08 * chord
    half_chord = chord / 2.0
    half_thick = thickness / 2.0
    root = _polar(r_mid, angle_degrees, z_center)
    origin = _add(root, _scale(chord_axis, -half_chord))
    points = [
        (0.00 * chord, -0.16 * half_thick),
        (0.20 * chord, -0.82 * half_thick),
        (0.35 * chord, -1.00 * half_thick),
        (0.78 * chord, -0.42 * half_thick),
        (1.00 * chord, 0.00 * half_thick),
        (0.78 * chord, 0.48 * half_thick + camber * 0.12),
        (0.35 * chord, 1.00 * half_thick + camber * 0.22),
        (0.18 * chord, 0.70 * half_thick),
    ]
    return builder.polygon_prism_on_plane(
        points,
        span,
        origin=origin,
        u_axis=chord_axis,
        v_axis=thickness_axis,
        extrude_axis=radial,
    )


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    shaft_diameter = 48.0
    shaft_length = 320.0
    spline_start_z = 20.0
    spline_end_z = 80.0
    spline_teeth = 48
    spline_tooth_height = 2.5
    shaft_groove_start_z = 180.0
    shaft_groove_end_z = 280.0
    shaft_groove_count = 6
    shaft_groove_width = 15.0
    shaft_groove_depth = 3.0

    blade_count = 72
    blade_pitch_degrees = 360.0 / blade_count
    blade_root_radius = 140.0
    blade_tip_radius = 205.0
    blade_root_chord = 42.0
    blade_tip_chord = 28.0
    blade_max_thickness = 6.5
    blade_root_stagger = 28.0
    blade_tip_stagger = 12.0
    blade_z_center = 200.0

    rim_outer_diameter = 280.0
    rim_inner_diameter = 220.0
    rim_thickness = 8.0
    disk_outer_diameter = 280.0
    disk_bore_diameter = 52.0
    disk_thickness = 35.0
    disk_center_z = 200.0

    disk_slot_count = 72
    disk_slot_width = 8.0
    disk_slot_depth = 15.0
    platform_radial_width = 10.0
    platform_z_length = 12.0
    platform_thickness = 3.0
    seal_radial_clearance = 1.2

    labyrinth_outer_diameter = 150.0
    labyrinth_inner_diameter = 100.0
    labyrinth_base_thickness = 4.0
    labyrinth_z_min = 182.0
    knife_count = 5
    knife_width = 0.8
    knife_height = 2.5
    knife_spacing = 6.0

    cone_front_z = 218.0
    cone_rear_z = 320.0
    cone_front_diameter = 280.0
    cone_rear_diameter = 160.0
    cone_wall_thickness = 3.0
    cooling_hole_count = 24
    cooling_hole_diameter = 4.0

    nut_flat_width = 32.0
    nut_height = 18.0
    nut_z_min = -18.0
    nut_bore_diameter = 30.0
    nut_thread_major = 48.0
    nut_thread_pitch = 1.5

    flange_diameter = 120.0
    flange_thickness = 8.0
    flange_z_min = -8.0
    bolt_hole_count = 8
    bolt_hole_diameter = 8.5
    bolt_circle_diameter = 100.0

    coating_thickness = 0.3

    steel_gray = 186
    ceramic_white = 216
    titanium_blue = 211
    copper = 125
    coating_yellow = 6

    disk_z_min = disk_center_z - disk_thickness / 2.0
    rim_z_min = disk_center_z - rim_thickness / 2.0

    shaft = b.cylinder(shaft_diameter, shaft_length, origin=(0, 0, 0), axis=(0, 0, 1))

    spline_features = []
    spline_tooth_z = (spline_start_z + spline_end_z) / 2.0
    spline_tooth_len = spline_end_z - spline_start_z
    for index in range(spline_teeth):
        angle = index * 360.0 / spline_teeth
        tooth = _radial_box(
            b,
            angle,
            shaft_diameter / 2.0 + spline_tooth_height / 2.0,
            spline_tooth_height,
            1.2,
            spline_tooth_z,
            spline_tooth_len,
        )
        b.boolean_unite(shaft, tooth)
        spline_features.append(tooth)

    shaft_groove_features = []
    shaft_groove_z = (shaft_groove_start_z + shaft_groove_end_z) / 2.0
    shaft_groove_len = shaft_groove_end_z - shaft_groove_start_z
    for index in range(shaft_groove_count):
        cutter = _radial_box(
            b,
            index * 360.0 / shaft_groove_count,
            shaft_diameter / 2.0 - shaft_groove_depth / 2.0,
            shaft_groove_depth + 2.0,
            shaft_groove_width,
            shaft_groove_z,
            shaft_groove_len,
        )
        b.boolean_subtract(shaft, cutter)
        shaft_groove_features.append(cutter)

    disk = _annular_cylinder(b, disk_outer_diameter, disk_bore_diameter, disk_thickness, disk_z_min)
    rim = _annular_cylinder(b, rim_outer_diameter, rim_inner_diameter, rim_thickness, rim_z_min)
    b.boolean_unite(disk, rim)

    disk_slot_features = []
    for index in range(disk_slot_count):
        cutter = _radial_box(
            b,
            index * blade_pitch_degrees,
            disk_bore_diameter / 2.0 + disk_slot_depth / 2.0,
            disk_slot_depth + 2.0,
            disk_slot_width,
            disk_center_z,
            disk_thickness + 4.0,
        )
        b.boolean_subtract(disk, cutter)
        disk_slot_features.append(cutter)

    labyrinth = _annular_cylinder(
        b,
        labyrinth_outer_diameter,
        labyrinth_inner_diameter,
        labyrinth_base_thickness,
        labyrinth_z_min,
    )
    b.boolean_unite(disk, labyrinth)
    knife_features = []
    first_knife_radius = labyrinth_inner_diameter / 2.0 + 8.0
    for index in range(knife_count):
        radius = first_knife_radius + index * knife_spacing
        knife = _annular_cylinder(
            b,
            2.0 * (radius + knife_width / 2.0),
            2.0 * (radius - knife_width / 2.0),
            knife_height,
            labyrinth_z_min + labyrinth_base_thickness,
        )
        b.boolean_unite(disk, knife)
        knife_features.append(knife)

    blade_features = []
    coating_features = []
    platform_features = []
    for index in range(blade_count):
        angle = index * blade_pitch_degrees
        blade_segments = [
            _blade_airfoil_section(
                b,
                angle,
                blade_root_radius,
                blade_root_radius + (blade_tip_radius - blade_root_radius) / 3.0,
                blade_z_center,
                blade_root_chord,
                37.3,
                blade_root_stagger,
                22.7,
                blade_max_thickness,
            ),
            _blade_airfoil_section(
                b,
                angle,
                blade_root_radius + (blade_tip_radius - blade_root_radius) / 3.0,
                blade_root_radius + 2.0 * (blade_tip_radius - blade_root_radius) / 3.0,
                blade_z_center,
                37.3,
                32.7,
                22.7,
                17.3,
                blade_max_thickness * 0.86,
            ),
            _blade_airfoil_section(
                b,
                angle,
                blade_root_radius + 2.0 * (blade_tip_radius - blade_root_radius) / 3.0,
                blade_tip_radius,
                blade_z_center,
                32.7,
                blade_tip_chord,
                17.3,
                blade_tip_stagger,
                blade_max_thickness * 0.70,
            ),
        ]
        blade_features.extend(blade_segments)

        coating_segments = [
            _blade_airfoil_section(
                b,
                angle,
                blade_root_radius + 1.5,
                blade_root_radius + (blade_tip_radius - blade_root_radius) / 3.0,
                blade_z_center,
                blade_root_chord + 2.0 * coating_thickness,
                37.3 + 2.0 * coating_thickness,
                blade_root_stagger,
                22.7,
                blade_max_thickness + 2.0 * coating_thickness,
            ),
            _blade_airfoil_section(
                b,
                angle,
                blade_root_radius + (blade_tip_radius - blade_root_radius) / 3.0,
                blade_root_radius + 2.0 * (blade_tip_radius - blade_root_radius) / 3.0,
                blade_z_center,
                37.3 + 2.0 * coating_thickness,
                32.7 + 2.0 * coating_thickness,
                22.7,
                17.3,
                blade_max_thickness * 0.86 + 2.0 * coating_thickness,
            ),
            _blade_airfoil_section(
                b,
                angle,
                blade_root_radius + 2.0 * (blade_tip_radius - blade_root_radius) / 3.0,
                blade_tip_radius - 1.5,
                blade_z_center,
                32.7 + 2.0 * coating_thickness,
                blade_tip_chord + 2.0 * coating_thickness,
                17.3,
                blade_tip_stagger,
                blade_max_thickness * 0.70 + 2.0 * coating_thickness,
            ),
        ]
        coating_features.extend(coating_segments)

        platform = _radial_box(
            b,
            angle,
            blade_root_radius - platform_radial_width / 2.0 - seal_radial_clearance,
            platform_radial_width,
            platform_thickness,
            blade_z_center + blade_root_chord / 2.0 - platform_z_length / 2.0,
            platform_z_length,
        )
        platform_features.append(platform)

    cone_features = []
    cone_height = cone_rear_z - cone_front_z
    panel_count = 72
    for index in range(panel_count):
        angle = index * 360.0 / panel_count
        mid_angle_span = math.radians(360.0 / panel_count)
        radial, tangential = _axes(angle)
        r_front_outer = cone_front_diameter / 2.0
        r_rear_outer = cone_rear_diameter / 2.0
        panel_width = ((r_front_outer + r_rear_outer) / 2.0) * mid_angle_span * 0.92
        origin = _add(_polar(0.0, angle, cone_front_z), _scale(tangential, -panel_width / 2.0))
        points = [
            (r_front_outer, 0.0),
            (r_front_outer - cone_wall_thickness, 0.0),
            (r_rear_outer - cone_wall_thickness, cone_height),
            (r_rear_outer, cone_height),
        ]
        panel = b.polygon_prism_on_plane(
            points,
            panel_width,
            origin=origin,
            u_axis=radial,
            v_axis=(0, 0, 1),
            extrude_axis=tangential,
        )
        cone_features.append(panel)

    for row_index, z_center in enumerate((260.0, 290.0)):
        for index in range(cooling_hole_count):
            angle = index * 360.0 / cooling_hole_count + row_index * 360.0 / cooling_hole_count / 2.0
            radius = cone_front_diameter / 2.0 + (cone_rear_diameter / 2.0 - cone_front_diameter / 2.0) * (
                (z_center - cone_front_z) / cone_height
            )
            hole = b.hole(
                cooling_hole_diameter,
                cone_wall_thickness + 6.0,
                position=_polar(radius + 2.0, angle, z_center),
                direction=_axes(angle)[0],
            )
            nearest_panel = cone_features[int(round(angle / (360.0 / panel_count))) % panel_count]
            b.boolean_subtract(nearest_panel, hole)

    nut_radius = nut_flat_width / math.sqrt(3.0)
    nut_points = [
        (nut_radius * math.cos(math.radians(60.0 * i + 30.0)), nut_radius * math.sin(math.radians(60.0 * i + 30.0)))
        for i in range(6)
    ]
    nut = b.polygon_prism(nut_points, nut_height, origin=(0, 0, nut_z_min), axis=(0, 0, 1))
    nut_bore = b.hole(nut_bore_diameter, nut_height + 4.0, position=(0, 0, nut_z_min - 2.0), direction=(0, 0, 1))
    b.boolean_subtract(nut, nut_bore)
    thread_features = []
    thread_turns = int(nut_height / nut_thread_pitch)
    for index in range(thread_turns):
        thread = _annular_cylinder(
            b,
            nut_thread_major,
            nut_thread_major - 1.0,
            0.45,
            nut_z_min + index * nut_thread_pitch,
        )
        b.boolean_unite(nut, thread)
        thread_features.append(thread)

    flange = _annular_cylinder(b, flange_diameter, shaft_diameter + 2.0, flange_thickness, flange_z_min)
    for index in range(bolt_hole_count):
        hole = b.hole(
            bolt_hole_diameter,
            flange_thickness + 4.0,
            position=_polar(bolt_circle_diameter / 2.0, index * 360.0 / bolt_hole_count, flange_z_min - 2.0),
            direction=(0, 0, 1),
        )
        b.boolean_subtract(flange, hole)

    _set_color(b, [shaft] + spline_features, steel_gray)
    _set_color(b, [disk, rim, labyrinth] + knife_features, titanium_blue)
    _set_color(b, blade_features, ceramic_white)
    _set_color(b, platform_features + [nut], copper)
    _set_color(b, coating_features, coating_yellow)
    _set_color(b, cone_features + [flange], steel_gray)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
