# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              high_precision_three_axis_drone_gimbal.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Coordinate convention: +Z vertical up, +X forward, +Y lateral/right.
    through_overcut = 2.0
    cutter_overlap = 0.7
    feature_overlap = 0.6
    hole_chamfer = 0.5
    housing_chamfer = 1.0
    frame_transition_fillet = 1.5
    structural_edge_fillet = 2.0
    pocket_depth = 0.8

    # Prompt dimensions.
    yaw_plate_diameter = 70.0
    yaw_plate_thickness = 5.0
    yaw_bolt_circle = 52.0
    m4_hole_diameter = 4.2
    cable_hole_diameter = 16.0

    yaw_housing_diameter = 42.0
    yaw_housing_height = 24.0

    roll_arm_thickness_y = 6.0
    roll_arm_width_x = 14.0
    roll_arm_length_z = 58.0
    roll_arm_spacing_y = 58.0
    roll_slot_length_z = 28.0
    roll_slot_width_x = 6.0

    roll_motor_diameter = 32.0
    roll_motor_length_y = 18.0
    bearing_boss_diameter = 24.0
    bearing_boss_length_y = 8.0

    cradle_width_y = 48.0
    cradle_height_z = 34.0
    cradle_depth_x = 36.0
    camera_opening_width_y = 34.0
    camera_opening_height_z = 22.0
    lens_clearance_diameter = 18.0
    pitch_motor_diameter = 24.0
    pitch_motor_length_y = 10.0
    m3_hole_diameter = 3.2

    # Derived placement.
    yaw_plate_top_z = 0.0
    yaw_plate_center_z = yaw_plate_top_z - yaw_plate_thickness / 2.0
    yaw_housing_top_z = yaw_plate_top_z - yaw_plate_thickness + feature_overlap
    yaw_housing_center_z = yaw_housing_top_z - yaw_housing_height / 2.0
    roll_axis_z = yaw_housing_top_z - yaw_housing_height - 35.0
    pitch_axis_z = roll_axis_z
    roll_arm_center_z = roll_axis_z - 2.0
    roll_crossbar_center_z = roll_axis_z + roll_arm_length_z / 2.0 - roll_arm_width_x / 2.0
    cradle_center = (8.0, 0.0, pitch_axis_z)
    cradle_front_x = cradle_center[0] + cradle_depth_x / 2.0
    right_y = roll_arm_spacing_y / 2.0
    left_y = -roll_arm_spacing_y / 2.0

    b.require_positive(
        yaw_plate_diameter=yaw_plate_diameter,
        yaw_plate_thickness=yaw_plate_thickness,
        yaw_housing_diameter=yaw_housing_diameter,
        yaw_housing_height=yaw_housing_height,
        roll_arm_length_z=roll_arm_length_z,
        cradle_width_y=cradle_width_y,
        cradle_height_z=cradle_height_z,
        cradle_depth_x=cradle_depth_x,
    )
    b.require_min_wall(yaw_plate_diameter, cable_hole_diameter, min_wall=12.0, label="yaw cable pass-through")
    b.require_min_wall(roll_arm_width_x, roll_slot_width_x, min_wall=3.0, label="roll arm lightening slot")
    b.require_min_wall(cradle_width_y, camera_opening_width_y, min_wall=6.0, label="front camera opening")
    b.require_feature_budget(boolean_operations=72, micro_holes=32, patterned_features=36)

    def cyl(diameter, height, center, axis=(0, 0, 1)):
        origin = (
            center[0] - axis[0] * height / 2.0,
            center[1] - axis[1] * height / 2.0,
            center[2] - axis[2] * height / 2.0,
        )
        return b.cylinder(diameter, height, origin=origin, axis=axis)

    def cut_cylinder(target, diameter, depth, center, axis):
        tool = cyl(diameter, depth, center, axis)
        b.boolean_subtract(target, tool)

    def chamfer_hole_openings(target, center, axis, diameter, depth):
        radius = diameter / 2.0 + hole_chamfer + 0.8
        for sign in (-1.0, 1.0):
            face = (
                center[0] + axis[0] * sign * depth / 2.0,
                center[1] + axis[1] * sign * depth / 2.0,
                center[2] + axis[2] * sign * depth / 2.0,
            )
            b.chamfer(
                b.get_edges_in_box(
                    target,
                    min_xyz=(face[0] - radius, face[1] - radius, face[2] - radius),
                    max_xyz=(face[0] + radius, face[1] + radius, face[2] + radius),
                ),
                hole_chamfer,
            )

    # Top yaw mounting plate.
    yaw_plate = cyl(yaw_plate_diameter, yaw_plate_thickness, (0.0, 0.0, yaw_plate_center_z), (0, 0, 1))
    for x, y, _z in b.circular_pattern_points((0.0, 0.0, yaw_plate_top_z), yaw_bolt_circle / 2.0, 4, start_angle_degrees=45.0):
        center = (x, y, yaw_plate_center_z)
        cut_cylinder(yaw_plate, m4_hole_diameter, yaw_plate_thickness + through_overcut, center, (0, 0, 1))
        chamfer_hole_openings(yaw_plate, center, (0, 0, 1), m4_hole_diameter, yaw_plate_thickness)
    cut_cylinder(yaw_plate, cable_hole_diameter, yaw_plate_thickness + through_overcut, (0.0, 0.0, yaw_plate_center_z), (0, 0, 1))
    b.rectangular_pocket(yaw_plate, 42.0, 10.0, pocket_depth, center=(0.0, 0.0, yaw_plate_top_z + cutter_overlap), direction=(0, 0, -1))
    b.rectangular_pocket(yaw_plate, 10.0, 42.0, pocket_depth, center=(0.0, 0.0, yaw_plate_top_z + cutter_overlap), direction=(0, 0, -1))
    b.chamfer(b.get_top_edges(yaw_plate), hole_chamfer)
    b.chamfer(b.get_bottom_edges(yaw_plate), hole_chamfer)

    # Yaw motor housing.
    yaw_housing = cyl(yaw_housing_diameter, yaw_housing_height, (0.0, 0.0, yaw_housing_center_z), (0, 0, 1))
    cut_cylinder(yaw_housing, cable_hole_diameter, yaw_housing_height + through_overcut, (0.0, 0.0, yaw_housing_center_z), (0, 0, 1))
    for x, y, _z in b.circular_pattern_points((0.0, 0.0, yaw_housing_top_z), 15.0, 4, start_angle_degrees=45.0):
        cut_cylinder(yaw_housing, m3_hole_diameter, yaw_housing_height + through_overcut, (x, y, yaw_housing_center_z), (0, 0, 1))
    b.fillet(
        b.get_edges_in_box(
            yaw_housing,
            min_xyz=(-yaw_housing_diameter / 2.0 - 1.0, -yaw_housing_diameter / 2.0 - 1.0, yaw_housing_top_z - 4.0),
            max_xyz=(yaw_housing_diameter / 2.0 + 1.0, yaw_housing_diameter / 2.0 + 1.0, yaw_housing_top_z + 1.0),
        ),
        structural_edge_fillet,
    )
    b.fillet(
        b.get_edges_in_box(
            yaw_housing,
            min_xyz=(-yaw_housing_diameter / 2.0 - 1.0, -yaw_housing_diameter / 2.0 - 1.0, yaw_housing_top_z - yaw_housing_height - 1.0),
            max_xyz=(yaw_housing_diameter / 2.0 + 1.0, yaw_housing_diameter / 2.0 + 1.0, yaw_housing_top_z - yaw_housing_height + 4.0),
        ),
        structural_edge_fillet,
    )
    b.chamfer(b.get_top_edges(yaw_housing), housing_chamfer)
    b.chamfer(b.get_bottom_edges(yaw_housing), housing_chamfer)

    # U-shaped roll frame with two slotted side arms and a rounded crossbar.
    roll_parts = []
    for y in (left_y, right_y):
        arm = b.rounded_box(
            roll_arm_width_x,
            roll_arm_thickness_y,
            roll_arm_length_z,
            radius=1.5,
            origin=(-roll_arm_width_x / 2.0, y - roll_arm_thickness_y / 2.0, roll_arm_center_z - roll_arm_length_z / 2.0),
        )
        b.slot_cut(arm, roll_slot_length_z, roll_slot_width_x, roll_arm_thickness_y + through_overcut, center=(0.0, y, roll_arm_center_z), axis=(0, 0, 1), direction=(0, 1, 0))
        side_sign = math.copysign(1.0, y)
        side_face_y = y + side_sign * roll_arm_thickness_y / 2.0
        if side_sign > 0:
            pocket_origin_y = side_face_y - pocket_depth
        else:
            pocket_origin_y = side_face_y - cutter_overlap
        side_pocket = b.box(
            9.0,
            pocket_depth + cutter_overlap,
            36.0,
            origin=(-4.5, pocket_origin_y, roll_arm_center_z - 18.0),
        )
        b.boolean_subtract(arm, side_pocket)
        b.fillet(
            b.get_edges_in_box(
                arm,
                min_xyz=(-roll_arm_width_x / 2.0 - 1.0, y - roll_arm_thickness_y / 2.0 - 1.0, roll_arm_center_z - roll_arm_length_z / 2.0 - 1.0),
                max_xyz=(roll_arm_width_x / 2.0 + 1.0, y + roll_arm_thickness_y / 2.0 + 1.0, roll_arm_center_z - roll_arm_length_z / 2.0 + 4.0),
            ),
            frame_transition_fillet,
        )
        b.fillet(
            b.get_edges_in_box(
                arm,
                min_xyz=(-roll_arm_width_x / 2.0 - 1.0, y - roll_arm_thickness_y / 2.0 - 1.0, roll_arm_center_z + roll_arm_length_z / 2.0 - 4.0),
                max_xyz=(roll_arm_width_x / 2.0 + 1.0, y + roll_arm_thickness_y / 2.0 + 1.0, roll_arm_center_z + roll_arm_length_z / 2.0 + 1.0),
            ),
            frame_transition_fillet,
        )
        roll_parts.append(arm)
    crossbar = cyl(roll_arm_width_x, roll_arm_spacing_y + roll_arm_thickness_y, (0.0, 0.0, roll_crossbar_center_z), (0, 1, 0))
    cut_cylinder(crossbar, roll_arm_width_x - 5.0, roll_arm_spacing_y + roll_arm_thickness_y + through_overcut, (0.0, 0.0, roll_crossbar_center_z), (0, 1, 0))

    # Roll motor on right side and bearing boss on left side, both concentric on roll axis.
    roll_motor = cyl(roll_motor_diameter, roll_motor_length_y, (0.0, right_y + roll_arm_thickness_y / 2.0 + roll_motor_length_y / 2.0 - feature_overlap, roll_axis_z), (0, 1, 0))
    roll_bearing = cyl(bearing_boss_diameter, bearing_boss_length_y, (0.0, left_y - roll_arm_thickness_y / 2.0 - bearing_boss_length_y / 2.0 + feature_overlap, roll_axis_z), (0, 1, 0))
    for part, y_face, length in (
        (roll_motor, right_y + roll_arm_thickness_y / 2.0 + roll_motor_length_y - feature_overlap, roll_motor_length_y),
        (roll_bearing, left_y - roll_arm_thickness_y / 2.0 - bearing_boss_length_y + feature_overlap, bearing_boss_length_y),
    ):
        for angle_degrees in (45.0, 135.0, 225.0, 315.0):
            angle = math.radians(angle_degrees)
            center = (8.5 * math.cos(angle), y_face, roll_axis_z + 8.5 * math.sin(angle))
            cut_cylinder(part, m3_hole_diameter, length + through_overcut, center, (0, 1, 0))
        b.chamfer(b.get_all_edges(part), 0.6)

    # Inner pitch camera cradle with front camera opening, side lugs, tabs, pockets, and lens hole.
    cradle = b.rounded_box(
        cradle_depth_x,
        cradle_width_y,
        cradle_height_z,
        radius=2.0,
        origin=(cradle_center[0] - cradle_depth_x / 2.0, -cradle_width_y / 2.0, cradle_center[2] - cradle_height_z / 2.0),
    )
    camera_opening = b.box(
        cradle_depth_x + through_overcut,
        camera_opening_width_y,
        camera_opening_height_z,
        origin=(cradle_center[0] - cradle_depth_x / 2.0 - 1.0, -camera_opening_width_y / 2.0, cradle_center[2] - camera_opening_height_z / 2.0),
    )
    b.boolean_subtract(cradle, camera_opening)
    cut_cylinder(cradle, lens_clearance_diameter, cradle_depth_x + through_overcut, (cradle_front_x - cradle_depth_x / 2.0, 0.0, pitch_axis_z), (1, 0, 0))
    for y in (-cradle_width_y / 2.0, cradle_width_y / 2.0):
        lug = cyl(28.0, 5.0, (cradle_center[0], y + math.copysign(2.5 - feature_overlap, y), pitch_axis_z), (0, 1, 0))
        b.boolean_unite(cradle, lug)
        tab = b.rounded_box(
            14.0,
            4.0,
            10.0,
            radius=1.0,
            origin=(cradle_center[0] - 7.0, y + math.copysign(-feature_overlap, y), pitch_axis_z - 17.0),
        )
        b.boolean_unite(cradle, tab)
        cut_cylinder(cradle, m3_hole_diameter, 12.0, (cradle_center[0], y, pitch_axis_z - 12.0), (0, 1, 0))
    b.rectangular_pocket(cradle, 24.0, 30.0, pocket_depth, center=(cradle_center[0], 0.0, cradle_center[2] + cradle_height_z / 2.0 + cutter_overlap), direction=(0, 0, -1))
    b.chamfer(b.get_edges_in_box(cradle, (cradle_front_x - 1.0, -20.0, pitch_axis_z - 14.0), (cradle_front_x + 1.0, 20.0, pitch_axis_z + 14.0)), hole_chamfer)

    # Pitch motor housings on both cradle sides, concentric with the pitch axis.
    for y, direction in ((cradle_width_y / 2.0 + pitch_motor_length_y / 2.0 - feature_overlap, 1), (-cradle_width_y / 2.0 - pitch_motor_length_y / 2.0 + feature_overlap, -1)):
        motor = cyl(pitch_motor_diameter, pitch_motor_length_y, (cradle_center[0], y, pitch_axis_z), (0, 1, 0))
        for angle_degrees in (45.0, 135.0, 225.0, 315.0):
            angle = math.radians(angle_degrees)
            cut_cylinder(
                motor,
                m3_hole_diameter,
                pitch_motor_length_y + through_overcut,
                (cradle_center[0] + 7.0 * math.cos(angle), y + direction * 0.5, pitch_axis_z + 7.0 * math.sin(angle)),
                (0, 1, 0),
            )
        if direction > 0:
            pocket_origin_y = y - cutter_overlap
        else:
            pocket_origin_y = y - pocket_depth
        side_pocket = b.box(
            13.0,
            pocket_depth + cutter_overlap,
            13.0,
            origin=(cradle_center[0] - 6.5, pocket_origin_y, pitch_axis_z - 6.5),
        )
        b.boolean_subtract(motor, side_pocket)
        b.chamfer(b.get_all_edges(motor), 0.6)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
