# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    body_length = 220.0
    body_width = 160.0
    body_height = 120.0
    body_origin = (0.0, -body_width / 2.0, 0.0)

    valve_bore_diameter = 80.0
    valve_bore_depth = 65.0
    valve_axis_x = 30.0
    valve_axis_z = 60.0
    groove_width = 6.0
    groove_depth = 3.0
    groove_pitch = 15.0
    main_passage_diameter = 16.0

    cartridge_thread_major = 22.0
    cartridge_core_diameter = 20.0
    cartridge_depth = 25.0
    cartridge_seat_diameter = 12.0
    pilot_orifice_diameter = 0.3
    pilot_orifice_depth = 2.0
    cartridge_x_positions = (120.0, 150.0, 180.0)
    cartridge_rows = ((-40.0, 30.0), (40.0, 90.0))

    relief_bore_diameter = 28.0
    relief_bore_depth = 35.0
    relief_axis_x = 180.0
    relief_axis_y = 0.0
    relief_axis_z = 60.0
    relief_seat_pilot_diameter = 12.0
    relief_seat_depth = 8.0

    boss_projection = 4.0
    sae_top_boss_diameter = 19.0
    sae_top_bore_diameter = 12.0
    pilot_boss_diameter = 14.0
    pilot_bore_diameter = 8.0
    gauge_boss_diameter = 16.0
    gauge_bore_diameter = 10.0

    mount_tap_drill_diameter = 14.0  # M16 x 2 simplified tap-drill geometry.
    mount_depth = 25.0
    mount_x_positions = (20.0, 200.0)
    mount_y_positions = (-60.0, 60.0)
    mount_z_positions = (20.0, 100.0)
    dowel_diameter = 10.0
    dowel_depth = 18.0

    pilot_passage_diameter = 6.0
    leakage_return_diameter = 8.0
    chamfer_offset = 1.5
    edge_break_radius = 0.5
    through_overcut = 2.0
    cutter_overlap = 0.5
    feature_overlap = 0.6

    b.require_positive(
        body_length=body_length,
        body_width=body_width,
        body_height=body_height,
        valve_bore_diameter=valve_bore_diameter,
        cartridge_core_diameter=cartridge_core_diameter,
        relief_bore_diameter=relief_bore_diameter,
    )
    b.require_feature_budget(boolean_operations=82, micro_holes=6, patterned_features=34)
    b.require_min_wall(body_width, valve_bore_diameter, min_wall=20.0, label="P80 valve cavity")
    b.require_edge_distance(min(mount_y_positions) + body_width / 2.0, mount_tap_drill_diameter, label="mounting pattern Y")

    body = b.box(body_length, body_width, body_height, origin=body_origin)

    # Optional phosphated/painted coating is represented as a very thin yellow topcoat envelope.
    # Sealing faces and bores remain cut through this envelope by subsequent features.
    coating = b.box(
        body_length + feature_overlap,
        body_width + feature_overlap,
        body_height + feature_overlap,
        origin=(-feature_overlap / 2.0, -body_width / 2.0 - feature_overlap / 2.0, -feature_overlap / 2.0),
    )
    b.boolean_unite(body, coating)

    # P80 main directional valve cavity, axis along Y, blind from the negative-Y service face.
    valve_start_y = -body_width / 2.0 - cutter_overlap
    valve_tool = b.hole(
        valve_bore_diameter,
        valve_bore_depth + cutter_overlap,
        position=(valve_axis_x, valve_start_y, valve_axis_z),
        direction=(0, 1, 0),
    )
    b.boolean_subtract(body, valve_tool)

    # Four annular porting grooves approximated as coaxial counterbores along the spool cavity.
    groove_ys = [-30.0, -15.0, 0.0, 15.0]
    for groove_y in groove_ys:
        groove_tool = b.hole(
            valve_bore_diameter + 2.0 * groove_depth,
            groove_width,
            position=(valve_axis_x, groove_y - groove_width / 2.0, valve_axis_z),
            direction=(0, 1, 0),
        )
        b.boolean_subtract(body, groove_tool)

    # Main P/T/A/B cross-drilled passages; these intentionally break through faces for plugs/ports.
    passage_labels = ("P", "T", "A", "B")
    top_port_xs = (35.0, 70.0, 105.0, 140.0)
    for index, groove_y in enumerate(groove_ys):
        top_x = top_port_xs[index]
        vertical = b.hole(
            main_passage_diameter,
            body_height + 2.0 * through_overcut,
            position=(top_x, groove_y, body_height + through_overcut),
            direction=(0, 0, -1),
        )
        b.boolean_subtract(body, vertical)
        cross = b.hole(
            main_passage_diameter,
            body_length + 2.0 * through_overcut,
            position=(-through_overcut, groove_y, valve_axis_z),
            direction=(1, 0, 0),
        )
        b.boolean_subtract(body, cross)

        boss = b.cylinder(
            sae_top_boss_diameter,
            boss_projection + feature_overlap,
            origin=(top_x, groove_y, body_height - feature_overlap),
            axis=(0, 0, 1),
        )
        b.boolean_unite(body, boss)
        port = b.hole(
            sae_top_bore_diameter,
            boss_projection + body_height + through_overcut,
            position=(top_x, groove_y, body_height + boss_projection + through_overcut),
            direction=(0, 0, -1),
        )
        b.boolean_subtract(body, port)

    # Six M22 x 1.5 cartridge bores in two offset rows of three.
    for row_y, row_z in cartridge_rows:
        for cartridge_x in cartridge_x_positions:
            boss = b.cylinder(
                cartridge_thread_major,
                boss_projection + feature_overlap,
                origin=(cartridge_x, row_y, body_height - feature_overlap),
                axis=(0, 0, 1),
            )
            b.boolean_unite(body, boss)
            bore = b.hole(
                cartridge_core_diameter,
                cartridge_depth + boss_projection + cutter_overlap,
                position=(cartridge_x, row_y, body_height + boss_projection),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(body, bore)
            seat = b.hole(
                cartridge_seat_diameter,
                relief_seat_depth + cutter_overlap,
                position=(cartridge_x, row_y, body_height + boss_projection - cartridge_depth),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(body, seat)
            orifice = b.hole(
                pilot_orifice_diameter,
                pilot_orifice_depth + cutter_overlap,
                position=(cartridge_x, row_y, body_height + boss_projection - 2.0),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(body, orifice)

            pilot_cross = b.hole(
                pilot_passage_diameter,
                body_width + 2.0 * through_overcut,
                position=(cartridge_x, -body_width / 2.0 - through_overcut, row_z),
                direction=(0, 1, 0),
            )
            b.boolean_subtract(body, pilot_cross)

    # Relief valve bore and stepped 1:4 conical-seat approximation.
    relief = b.hole(
        relief_bore_diameter,
        relief_bore_depth + cutter_overlap,
        position=(relief_axis_x, -body_width / 2.0 - cutter_overlap, relief_axis_z),
        direction=(0, 1, 0),
    )
    b.boolean_subtract(body, relief)
    relief_seat = b.hole(
        relief_seat_pilot_diameter,
        relief_seat_depth + cutter_overlap,
        position=(relief_axis_x, -body_width / 2.0 - cutter_overlap + relief_bore_depth, relief_axis_z),
        direction=(0, 1, 0),
    )
    b.boolean_subtract(body, relief_seat)
    spring_to_t = b.hole(
        3.0,
        body_width + 2.0 * through_overcut,
        position=(relief_axis_x, -body_width / 2.0 - through_overcut, relief_axis_z + 12.0),
        direction=(0, 1, 0),
    )
    b.boolean_subtract(body, spring_to_t)

    # Side pilot-line SAE bosses, two per side.
    side_port_specs = [
        (90.0, -body_width / 2.0, 35.0, (0, -1, 0)),
        (150.0, -body_width / 2.0, 85.0, (0, -1, 0)),
        (90.0, body_width / 2.0, 85.0, (0, 1, 0)),
        (150.0, body_width / 2.0, 35.0, (0, 1, 0)),
    ]
    for x, y, z, axis in side_port_specs:
        boss_origin = (x, y - axis[1] * feature_overlap, z)
        boss = b.cylinder(pilot_boss_diameter, boss_projection + feature_overlap, origin=boss_origin, axis=axis)
        b.boolean_unite(body, boss)
        bore_start = (x, y + axis[1] * (boss_projection + through_overcut), z)
        pilot_port = b.hole(pilot_bore_diameter, boss_projection + 30.0, position=bore_start, direction=(-axis[0], -axis[1], -axis[2]))
        b.boolean_subtract(body, pilot_port)

    # Front gauge/test ports on mounting face X = 0.
    gauge_positions = [(0.0, -55.0, 25.0), (0.0, 55.0, 25.0), (0.0, -55.0, 95.0), (0.0, 55.0, 95.0)]
    for x, y, z in gauge_positions:
        boss = b.cylinder(
            gauge_boss_diameter,
            boss_projection + feature_overlap,
            origin=(-boss_projection, y, z),
            axis=(1, 0, 0),
        )
        b.boolean_unite(body, boss)
        gauge = b.hole(
            gauge_bore_diameter,
            boss_projection + 35.0,
            position=(-boss_projection - through_overcut, y, z),
            direction=(1, 0, 0),
        )
        b.boolean_subtract(body, gauge)

    # Leakage return channels to T.
    for y in (-45.0, 45.0):
        leakage = b.hole(
            leakage_return_diameter,
            body_length + 2.0 * through_overcut,
            position=(-through_overcut, y, 18.0),
            direction=(1, 0, 0),
        )
        b.boolean_subtract(body, leakage)

    # Eight blind M16 x 2 mounting holes and two H7 dowel pin holes on diagonal corners.
    for mx in mount_x_positions:
        for my in mount_y_positions:
            for mz in mount_z_positions:
                mount = b.hole(
                    mount_tap_drill_diameter,
                    mount_depth + cutter_overlap,
                    position=(mx, my, -cutter_overlap),
                    direction=(0, 0, 1),
                )
                b.boolean_subtract(body, mount)
                chamfer = b.hole(
                    mount_tap_drill_diameter + 3.0,
                    chamfer_offset,
                    position=(mx, my, -cutter_overlap),
                    direction=(0, 0, 1),
                )
                b.boolean_subtract(body, chamfer)

    for dx, dy in ((20.0, -60.0), (200.0, 60.0)):
        dowel = b.hole(
            dowel_diameter,
            dowel_depth + cutter_overlap,
            position=(dx, dy, -cutter_overlap),
            direction=(0, 0, 1),
        )
        b.boolean_subtract(body, dowel)

    # Laser-marking panel on front face: part/rating lines plus simplified 2D Data Matrix cells.
    mark_depth = 0.25
    mark_zs = (110.0, 104.0, 98.0, 92.0)
    mark_widths = (46.0, 34.0, 24.0, 18.0)
    for z, width in zip(mark_zs, mark_widths):
        mark = b.box(mark_depth + cutter_overlap, width, 1.4, origin=(-cutter_overlap, -70.0, z))
        b.boolean_subtract(body, mark)

    cell = 1.2
    matrix_origin_y = -70.0
    matrix_origin_z = 78.0
    matrix_pattern = (
        "1111111111",
        "1000100011",
        "1011101101",
        "1010000101",
        "1110111101",
        "1001100001",
        "1010111011",
        "1010001001",
        "1111101111",
        "1111111111",
    )
    for row, line in enumerate(matrix_pattern):
        for col, bit in enumerate(line):
            if bit == "1":
                pocket = b.box(
                    mark_depth + cutter_overlap,
                    cell,
                    cell,
                    origin=(-cutter_overlap, matrix_origin_y + col * cell, matrix_origin_z + row * cell),
                )
                b.boolean_subtract(body, pocket)

    # Conservative machined edge breaks after functional booleans.
    b.chamfer(b.get_edges_in_box(body, min_xyz=(-1.0, -82.0, -1.0), max_xyz=(222.0, 82.0, 122.0)), offset=edge_break_radius)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
