# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              industrial_servo_motor_mounting_bracket.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    base_length = 140.0
    base_width = 80.0
    base_thickness = 12.0

    boss_x_thickness = 24.0
    boss_y_width = 70.0
    boss_height_above_base = 58.0
    boss_vertical_fillet_radius = 4.0

    pilot_bore_diameter = 42.0
    pilot_center = (0.0, 0.0, 44.0)
    motor_hole_diameter = 6.0
    motor_bolt_circle_diameter = 60.0
    motor_hole_angles_degrees = (45.0, 135.0, 225.0, 315.0)

    gusset_y_thickness = 8.0
    gusset_x_extent = 34.0
    gusset_height = 46.0
    gusset_center_y_abs = 28.0
    gusset_transition_fillet_radius = 2.0

    base_mount_hole_diameter = 9.0
    base_mount_x_abs = 50.0
    base_mount_y_abs = 28.0

    slot_length = 28.0
    slot_width = 12.0
    slot_center_x_abs = 32.0

    pad_length = 26.0
    pad_width = 18.0
    pad_height = 1.5
    pad_center_x_abs = 48.0
    pad_fillet_radius = 1.0

    base_outer_fillet_radius = 3.0
    internal_transition_fillet_radius = 2.0
    hole_chamfer_offset = 0.5

    # Derived dimensions and robustness allowances.
    base_top_z = base_thickness
    boss_total_height = boss_height_above_base + 0.5
    boss_origin = (
        -boss_x_thickness / 2.0,
        -boss_y_width / 2.0,
        base_top_z - 0.5,
    )
    boss_rear_x = boss_x_thickness / 2.0
    rear_gusset_end_x = boss_rear_x + gusset_x_extent
    feature_overlap = 0.5
    through_overcut = 2.0
    x_cut_depth = boss_x_thickness + 2.0 * through_overcut
    z_cut_depth = base_thickness + pad_height + 2.0 * through_overcut
    bolt_circle_radius = motor_bolt_circle_diameter / 2.0

    b.require_positive(
        base_length=base_length,
        base_width=base_width,
        base_thickness=base_thickness,
        boss_x_thickness=boss_x_thickness,
        boss_y_width=boss_y_width,
        boss_height_above_base=boss_height_above_base,
        pilot_bore_diameter=pilot_bore_diameter,
    )
    b.require_min_wall(boss_y_width, pilot_bore_diameter, min_wall=8.0, label="pilot bore in boss")
    b.require_min_wall(boss_y_width, motor_bolt_circle_diameter + motor_hole_diameter, min_wall=2.0, label="motor bolt circle in boss")
    b.require_edge_distance(base_length / 2.0 - base_mount_x_abs, base_mount_hole_diameter, min_ratio=1.0, label="base mounting hole X edge")
    b.require_edge_distance(base_width / 2.0 - base_mount_y_abs, base_mount_hole_diameter, min_ratio=1.0, label="base mounting hole Y edge")
    b.require_feature_budget(boolean_operations=22, patterned_features=12)

    # Primary solids.
    body = b.rounded_box(
        base_length,
        base_width,
        base_thickness,
        radius=base_outer_fillet_radius,
        origin=(-base_length / 2.0, -base_width / 2.0, 0.0),
        vertical_only=True,
    )

    boss = b.rounded_box(
        boss_x_thickness,
        boss_y_width,
        boss_total_height,
        radius=boss_vertical_fillet_radius,
        origin=boss_origin,
        vertical_only=True,
    )
    b.boolean_unite(body, boss)

    # Raised precision pads. These are united before through-slots so any prompt-specified overlap is cut through.
    for pad_center_x in (-pad_center_x_abs, pad_center_x_abs):
        pad = b.rounded_box(
            pad_length,
            pad_width,
            pad_height + feature_overlap,
            radius=pad_fillet_radius,
            origin=(
                pad_center_x - pad_length / 2.0,
                -pad_width / 2.0,
                base_top_z - feature_overlap,
            ),
            vertical_only=True,
        )
        b.boolean_unite(body, pad)

    # Triangular side gussets extruded in Y from local XZ profiles.
    gusset_profile = [
        (boss_rear_x - feature_overlap, base_top_z - feature_overlap),
        (rear_gusset_end_x, base_top_z - feature_overlap),
        (boss_rear_x - feature_overlap, base_top_z + gusset_height),
    ]
    for gusset_center_y in (-gusset_center_y_abs, gusset_center_y_abs):
        gusset = b.polygon_prism_on_plane(
            gusset_profile,
            gusset_y_thickness,
            origin=(0.0, gusset_center_y - gusset_y_thickness / 2.0, 0.0),
            u_axis=(1, 0, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(0, 1, 0),
        )
        b.boolean_unite(body, gusset)

    # Through-cuts in the vertical boss, along X.
    pilot = b.hole(
        pilot_bore_diameter,
        x_cut_depth,
        position=(boss_x_thickness / 2.0 + through_overcut, pilot_center[1], pilot_center[2]),
        direction=(-1, 0, 0),
    )
    b.boolean_subtract(body, pilot)

    for angle_degrees in motor_hole_angles_degrees:
        angle = math.radians(angle_degrees)
        hole_y = pilot_center[1] + bolt_circle_radius * math.cos(angle)
        hole_z = pilot_center[2] + bolt_circle_radius * math.sin(angle)
        motor_hole = b.hole(
            motor_hole_diameter,
            x_cut_depth,
            position=(boss_x_thickness / 2.0 + through_overcut, hole_y, hole_z),
            direction=(-1, 0, 0),
        )
        b.boolean_subtract(body, motor_hole)

    # Base holes and lightening slots, through Z.
    for x in (-base_mount_x_abs, base_mount_x_abs):
        for y in (-base_mount_y_abs, base_mount_y_abs):
            base_hole = b.hole(
                base_mount_hole_diameter,
                z_cut_depth,
                position=(x, y, base_top_z + pad_height + through_overcut),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(body, base_hole)

    for slot_center_x in (-slot_center_x_abs, slot_center_x_abs):
        b.slot_cut(
            body,
            slot_length,
            slot_width,
            z_cut_depth,
            center=(slot_center_x, 0.0, base_top_z + pad_height + through_overcut),
            axis=(1, 0, 0),
            direction=(0, 0, -1),
        )

    # Localized transition blends. These selectors are intentionally bounded to avoid hole edges.
    b.fillet(
        b.get_edges_in_box(
            body,
            min_xyz=(-boss_x_thickness / 2.0 - 1.0, -boss_y_width / 2.0 - 1.0, base_top_z - 1.0),
            max_xyz=(boss_x_thickness / 2.0 + 1.0, boss_y_width / 2.0 + 1.0, base_top_z + 1.0),
        ),
        internal_transition_fillet_radius,
    )
    for gusset_center_y in (-gusset_center_y_abs, gusset_center_y_abs):
        b.fillet(
            b.get_edges_in_box(
                body,
                min_xyz=(boss_rear_x - 1.0, gusset_center_y - gusset_y_thickness / 2.0 - 1.0, base_top_z - 1.0),
                max_xyz=(rear_gusset_end_x + 1.0, gusset_center_y + gusset_y_thickness / 2.0 + 1.0, base_top_z + 2.0),
            ),
            gusset_transition_fillet_radius,
        )
        b.fillet(
            b.get_edges_in_box(
                body,
                min_xyz=(boss_rear_x - 1.0, gusset_center_y - gusset_y_thickness / 2.0 - 1.0, base_top_z - 1.0),
                max_xyz=(boss_rear_x + 2.0, gusset_center_y + gusset_y_thickness / 2.0 + 1.0, base_top_z + gusset_height + 1.0),
            ),
            gusset_transition_fillet_radius,
        )

    # Sharp cylindrical holes with small chamfers at both openings.
    chamfer_points = [
        (boss_x_thickness / 2.0, 0.0, pilot_center[2]),
        (-boss_x_thickness / 2.0, 0.0, pilot_center[2]),
    ]
    for angle_degrees in motor_hole_angles_degrees:
        angle = math.radians(angle_degrees)
        hole_y = pilot_center[1] + bolt_circle_radius * math.cos(angle)
        hole_z = pilot_center[2] + bolt_circle_radius * math.sin(angle)
        chamfer_points.extend(
            [
                (boss_x_thickness / 2.0, hole_y, hole_z),
                (-boss_x_thickness / 2.0, hole_y, hole_z),
            ]
        )
    for x in (-base_mount_x_abs, base_mount_x_abs):
        for y in (-base_mount_y_abs, base_mount_y_abs):
            chamfer_points.extend([(x, y, 0.0), (x, y, base_top_z + pad_height)])
    for slot_center_x in (-slot_center_x_abs, slot_center_x_abs):
        chamfer_points.extend(
            [
                (slot_center_x - (slot_length - slot_width) / 2.0, 0.0, 0.0),
                (slot_center_x + (slot_length - slot_width) / 2.0, 0.0, 0.0),
                (slot_center_x - (slot_length - slot_width) / 2.0, 0.0, base_top_z + pad_height),
                (slot_center_x + (slot_length - slot_width) / 2.0, 0.0, base_top_z + pad_height),
            ]
        )
    for point in chamfer_points:
        b.chamfer(b.get_edges_near(body, point=point, tolerance=0.9), hole_chamfer_offset)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
