# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              industrial_indexing_dial_assembly.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    base_diameter = 120.0
    base_thickness = 10.0
    outside_chamfer = 1.0

    hub_diameter = 42.0
    hub_height = 28.0
    bore_diameter = 16.0

    hub_top_pocket_diameter = 30.0
    hub_top_pocket_depth = 4.0
    pocket_chamfer = 0.75

    mount_screw_size = "M5"
    mount_hole_count = 6
    mount_bolt_circle_diameter = 92.0

    detent_count = 12
    detent_bolt_circle_diameter = 76.0
    detent_diameter = 5.0
    detent_depth = 2.0

    slot_count = 4
    # The requested 52 mm radius x 24 mm slots collide with the M5
    # counterbore pattern and extend beyond the 60 mm base radius. Keep four
    # machinable lightening slots inside the bolt circle instead.
    slot_center_radius = 24.0
    slot_length = 14.0
    slot_width = 8.0

    arrow_length = 18.0
    arrow_tail_width = 8.0
    arrow_head_width = 14.0
    arrow_height = 1.5
    arrow_center_radius = 36.0
    arrow_body_overlap = 0.5

    keyway_width = 5.0
    keyway_radial_depth = 3.0
    keyway_bore_overlap = 1.0

    edge_break = 0.5
    transition_fillet = 1.0
    through_overcut = 2.0
    minimum_slot_to_mount_wall = 6.0

    # Derived dimensions.
    base_radius = base_diameter / 2.0
    base_top_z = base_thickness
    hub_top_z = base_top_z + hub_height
    hub_radius = hub_diameter / 2.0
    bore_radius = bore_diameter / 2.0
    mount_bolt_radius = mount_bolt_circle_diameter / 2.0
    detent_bolt_radius = detent_bolt_circle_diameter / 2.0
    total_height = hub_top_z
    through_depth = total_height + 2.0 * through_overcut

    m5_clearance_diameter = b.clearance_diameter(mount_screw_size)
    m5_socket_head_counterbore_diameter = 9.5
    slot_to_mount_wall = mount_bolt_radius - (slot_center_radius + slot_length / 2.0) - (
        slot_width / 2.0 + m5_socket_head_counterbore_diameter / 2.0
    )
    slot_outer_edge_distance = base_radius - (slot_center_radius + slot_length / 2.0)
    slot_inner_radius = slot_center_radius - slot_length / 2.0

    b.require_positive(
        base_diameter=base_diameter,
        base_thickness=base_thickness,
        hub_diameter=hub_diameter,
        hub_height=hub_height,
        bore_diameter=bore_diameter,
        slot_to_mount_wall=slot_to_mount_wall,
        slot_outer_edge_distance=slot_outer_edge_distance,
        slot_inner_radius=slot_inner_radius,
    )
    b.require_min_wall(hub_diameter, hub_top_pocket_diameter, min_wall=3.0, label="hub top pocket")
    b.require_edge_distance(
        base_radius - mount_bolt_radius,
        m5_socket_head_counterbore_diameter,
        min_ratio=1.0,
        label="M5 socket-head counterbore to outside edge",
    )
    b.require_edge_distance(
        slot_to_mount_wall,
        m5_socket_head_counterbore_diameter,
        min_ratio=minimum_slot_to_mount_wall / m5_socket_head_counterbore_diameter,
        label="slot to M5 counterbore",
    )

    # Primary turned/machined solids.
    body = b.cylinder(base_diameter, base_thickness, origin=(0, 0, 0))
    hub = b.cylinder(hub_diameter, hub_height, origin=(0, 0, base_top_z))
    b.boolean_unite(body, hub)

    # Keyway first, then bore. The keyway cutter intentionally overlaps into
    # the bore so the following bore cut is not tangent to a zero-wall face.
    keyway = b.box(
        keyway_width,
        keyway_radial_depth + keyway_bore_overlap,
        hub_height + 2.0 * through_overcut,
        origin=(
            -keyway_width / 2.0,
            bore_radius - keyway_bore_overlap,
            base_top_z - through_overcut,
        ),
    )
    b.boolean_subtract(body, keyway)

    bore = b.hole(
        bore_diameter,
        through_depth,
        position=(0, 0, hub_top_z + through_overcut),
        direction=(0, 0, -1),
    )
    b.boolean_subtract(body, bore)

    # Hub top recess.
    top_pocket = b.hole(
        hub_top_pocket_diameter,
        hub_top_pocket_depth + through_overcut,
        position=(0, 0, hub_top_z + through_overcut),
        direction=(0, 0, -1),
    )
    b.boolean_subtract(body, top_pocket)

    # Base flange through slots, radial at 0/90/180/270 degrees.
    for angle_degrees in range(0, 360, int(360 / slot_count)):
        angle = math.radians(angle_degrees)
        cx = slot_center_radius * math.cos(angle)
        cy = slot_center_radius * math.sin(angle)
        axis = (round(math.cos(angle)), round(math.sin(angle)), 0)
        b.slot_cut(
            body,
            slot_length,
            slot_width,
            base_thickness + 2.0 * through_overcut,
            center=(cx, cy, base_top_z + through_overcut),
            axis=axis,
            direction=(0, 0, -1),
        )

    # Standard M5 socket-head counterbored flange mounting holes.
    for point in b.circular_pattern_points(
        center=(0, 0, base_top_z + through_overcut),
        radius=mount_bolt_radius,
        count=mount_hole_count,
        start_angle_degrees=0.0,
    ):
        b.socket_head_counterbore_hole(
            body,
            mount_screw_size,
            base_thickness + 2.0 * through_overcut,
            position=point,
            direction=(0, 0, -1),
        )

    # Twelve blind indexing detents on the top face of the base flange.
    for point in b.circular_pattern_points(
        center=(0, 0, base_top_z + through_overcut),
        radius=detent_bolt_radius,
        count=detent_count,
        start_angle_degrees=0.0,
    ):
        detent = b.hole(
            detent_diameter,
            detent_depth + through_overcut,
            position=point,
            direction=(0, 0, -1),
        )
        b.boolean_subtract(body, detent)

    # Raised orientation arrow on top of base flange, pointing along +X.
    arrow_tip_x = arrow_center_radius + arrow_length / 2.0
    arrow_tail_x = arrow_center_radius - arrow_length / 2.0
    arrow_shoulder_x = arrow_tail_x + arrow_length * 0.56
    arrow_points = [
        (arrow_tail_x, -arrow_tail_width / 2.0),
        (arrow_shoulder_x, -arrow_tail_width / 2.0),
        (arrow_shoulder_x, -arrow_head_width / 2.0),
        (arrow_tip_x, 0.0),
        (arrow_shoulder_x, arrow_head_width / 2.0),
        (arrow_shoulder_x, arrow_tail_width / 2.0),
        (arrow_tail_x, arrow_tail_width / 2.0),
    ]
    arrow = b.polygon_prism(
        arrow_points,
        arrow_height + arrow_body_overlap,
        origin=(0, 0, base_top_z - arrow_body_overlap),
        axis=(0, 0, 1),
    )
    b.boolean_unite(body, arrow)

    # Conservative machined edge breaks and non-critical outside transition.
    b.chamfer(b.get_top_edges(body), edge_break)
    b.chamfer(b.get_bottom_edges(body), edge_break)
    b.chamfer(b.get_edges_near(body, point=(base_radius, 0, base_top_z), tolerance=2.0), outside_chamfer)
    b.chamfer(b.get_edges_near(body, point=(base_radius, 0, 0), tolerance=2.0), outside_chamfer)
    b.chamfer(b.get_edges_near(body, point=(hub_top_pocket_diameter / 2.0, 0, hub_top_z), tolerance=1.5), pocket_chamfer)
    b.fillet(b.get_edges_near(body, point=(hub_radius, 0, base_top_z), tolerance=1.5), transition_fillet)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
