# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _circle_yz(radius, count, start_degrees=0.0, center_y=0.0, center_z=0.0):
    points = []
    for index in range(count):
        angle = math.radians(start_degrees + 360.0 * index / count)
        points.append((center_y + radius * math.cos(angle), center_z + radius * math.sin(angle)))
    return points


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    housing_length = 280.0
    housing_width = 180.0
    housing_height = 145.0
    shaft_axis_z = 82.0
    split_plane_y = 0.0

    base_foot_length = 150.0
    base_foot_width = 80.0
    base_foot_thickness = 20.0
    mounting_slot_length = 32.0
    mounting_slot_width = 22.0
    mounting_slot_center_pitch = 40.0
    anchor_hole_diameter = 22.0
    anchor_pattern_x = 200.0
    anchor_pattern_y = 120.0

    casting_barrel_diameter = 150.0
    casting_barrel_length = 280.0
    bearing_bore_diameter = 130.0
    bearing_seat_depth = 55.0
    bearing_outer_diameter = 230.0
    bearing_width = 64.0
    bearing_inner_diameter = 130.0
    snap_ring_groove_width = 5.0
    lubrication_groove_width = 1.5
    lubrication_groove_offset = 15.0
    labyrinth_groove_width = 3.0
    labyrinth_groove_depth = 2.0

    end_cap_diameter = 180.0
    end_cap_thickness = 25.0
    end_cap_bolt_circle = 160.0
    end_cap_bolt_diameter = 13.5
    shaft_passage_diameter = 60.0
    lip_seal_seat_diameter = 80.0
    lip_seal_width = 10.0

    cap_bolt_clearance_diameter = 17.0
    cap_bolt_counterbore_diameter = 28.0
    cap_bolt_counterbore_depth = 8.0
    flange_bolt_zs = (45.0, 120.0)
    flange_bolt_xs = (-110.0, 110.0)
    flange_face_y = 90.0

    grease_nipple_diameter = 40.0
    grease_thread_diameter = 8.5
    grease_passage_diameter = 8.0
    radial_lube_diameter = 3.0
    lifting_eye_ring_outer_diameter = 42.0
    lifting_eye_ring_inner_diameter = 24.0
    lifting_eye_thickness = 10.0

    breather_tap_diameter = 8.5
    breather_mesh_diameter = 14.0
    gasket_gap = 0.3
    lead_chamfer_offset = 2.0
    cast_edge_radius = 3.0
    fillet_radius = 5.0
    through_overcut = 3.0
    cutter_overlap = 0.8
    feature_overlap = 0.8

    b.require_positive(
        housing_length=housing_length,
        housing_width=housing_width,
        housing_height=housing_height,
        bearing_bore_diameter=bearing_bore_diameter,
        end_cap_diameter=end_cap_diameter,
        grease_nipple_diameter=grease_nipple_diameter,
    )
    b.require_feature_budget(boolean_operations=94, micro_holes=8, patterned_features=36)
    b.require_edge_distance(anchor_pattern_x / 2.0, anchor_hole_diameter, min_ratio=1.0, label="anchor X")
    b.require_edge_distance(anchor_pattern_y / 2.0, anchor_hole_diameter, min_ratio=1.0, label="anchor Y")

    # Cast split housing: base, raised saddle, side flanges, and blue coating envelope.
    body = b.rounded_box(
        housing_length,
        housing_width,
        base_foot_thickness,
        radius=cast_edge_radius,
        origin=(-housing_length / 2.0, -housing_width / 2.0, 0.0),
    )
    saddle = b.cylinder(
        casting_barrel_diameter,
        casting_barrel_length + 2.0 * feature_overlap,
        origin=(-housing_length / 2.0 - feature_overlap, 0.0, shaft_axis_z),
        axis=(1, 0, 0),
    )
    b.boolean_unite(body, saddle)
    lower_web = b.box(
        housing_length,
        105.0,
        shaft_axis_z,
        origin=(-housing_length / 2.0, -52.5, base_foot_thickness - feature_overlap),
    )
    b.boolean_unite(body, lower_web)

    for side in (-1.0, 1.0):
        flange = b.box(
            220.0,
            16.0 + feature_overlap,
            125.0,
            origin=(-110.0, side * (flange_face_y - feature_overlap if side > 0 else flange_face_y - 16.0), 20.0),
        )
        b.boolean_unite(body, flange)

    coating = b.box(
        housing_length + feature_overlap,
        housing_width + feature_overlap,
        housing_height + feature_overlap,
        origin=(-housing_length / 2.0 - feature_overlap / 2.0, -housing_width / 2.0 - feature_overlap / 2.0, -feature_overlap / 2.0),
    )
    b.boolean_unite(body, coating)

    # Split-plane gasket witness: narrow reliefs on both sides of Y = 0.
    for side in (-1.0, 1.0):
        gasket_relief = b.box(
            housing_length + 2.0 * through_overcut,
            gasket_gap,
            housing_height + through_overcut,
            origin=(-housing_length / 2.0 - through_overcut, side * gasket_gap / 2.0, base_foot_thickness),
        )
        b.boolean_subtract(body, gasket_relief)

    # Coaxial bearing/shaft seat and shoulders. The 230 mm OD bearing is larger than the
    # stated 145 mm housing height, so it is modeled as an exposed reference envelope.
    shaft_bore = b.hole(
        bearing_bore_diameter,
        housing_length + 2.0 * through_overcut,
        position=(-housing_length / 2.0 - through_overcut, 0.0, shaft_axis_z),
        direction=(1, 0, 0),
    )
    b.boolean_subtract(body, shaft_bore)
    for x in (-bearing_seat_depth / 2.0, bearing_seat_depth / 2.0):
        lead = b.hole(
            bearing_bore_diameter + 2.0 * lead_chamfer_offset,
            lead_chamfer_offset + cutter_overlap,
            position=(x, 0.0, shaft_axis_z),
            direction=(1 if x < 0 else -1, 0, 0),
        )
        b.boolean_subtract(body, lead)

    for x in (-bearing_seat_depth / 2.0 + lubrication_groove_offset, bearing_seat_depth / 2.0 - lubrication_groove_offset):
        groove = b.hole(
            bearing_bore_diameter + 4.0,
            lubrication_groove_width,
            position=(x - lubrication_groove_width / 2.0, 0.0, shaft_axis_z),
            direction=(1, 0, 0),
        )
        b.boolean_subtract(body, groove)

    for x in (-bearing_width / 2.0, bearing_width / 2.0 - snap_ring_groove_width):
        snap = b.hole(
            bearing_outer_diameter,
            snap_ring_groove_width,
            position=(x, 0.0, shaft_axis_z),
            direction=(1, 0, 0),
        )
        b.boolean_subtract(body, snap)

    for side in (-1.0, 1.0):
        base_x = side * (bearing_width / 2.0 + 4.0)
        for row in range(3):
            lab = b.hole(
                bearing_bore_diameter + 2.0 * (labyrinth_groove_depth + row * 2.0),
                labyrinth_groove_width,
                position=(base_x + side * row * 5.0, 0.0, shaft_axis_z),
                direction=(1 if side > 0 else -1, 0, 0),
            )
            b.boolean_subtract(body, lab)

    # Simplified 22226-E1 spherical roller bearing envelope: outer ring, inner clearance,
    # and two roller rows. Catalog lookup found no step.parts model.
    bearing_outer = b.cylinder(
        bearing_outer_diameter,
        bearing_width,
        origin=(-bearing_width / 2.0, 0.0, shaft_axis_z),
        axis=(1, 0, 0),
    )
    bearing_inner = b.hole(
        bearing_inner_diameter,
        bearing_width + 2.0 * cutter_overlap,
        position=(-bearing_width / 2.0 - cutter_overlap, 0.0, shaft_axis_z),
        direction=(1, 0, 0),
    )
    b.boolean_subtract(bearing_outer, bearing_inner)
    roller_pitch_radius = (bearing_inner_diameter + bearing_outer_diameter) / 4.0
    for x in (-14.0, 14.0):
        for index in range(12):
            angle = math.radians(index * 30.0)
            y = roller_pitch_radius * math.cos(angle)
            z = shaft_axis_z + roller_pitch_radius * math.sin(angle)
            roller = b.cylinder(10.0, 18.0, origin=(x - 9.0, y, z), axis=(1, 0, 0))
            b.boolean_unite(bearing_outer, roller)

    # End cap on positive X side with shaft bore, lip seal, six M12 holes, and breather.
    cap = b.cylinder(
        end_cap_diameter,
        end_cap_thickness,
        origin=(housing_length / 2.0 - feature_overlap, 0.0, shaft_axis_z),
        axis=(1, 0, 0),
    )
    b.boolean_unite(body, cap)
    cap_bore = b.hole(
        shaft_passage_diameter,
        end_cap_thickness + 2.0 * through_overcut,
        position=(housing_length / 2.0 - through_overcut, 0.0, shaft_axis_z),
        direction=(1, 0, 0),
    )
    b.boolean_subtract(body, cap_bore)
    seal = b.hole(
        lip_seal_seat_diameter,
        lip_seal_width + cutter_overlap,
        position=(housing_length / 2.0 + end_cap_thickness - lip_seal_width, 0.0, shaft_axis_z),
        direction=(-1, 0, 0),
    )
    b.boolean_subtract(body, seal)
    for y, z in _circle_yz(end_cap_bolt_circle / 2.0, 6, start_degrees=30.0, center_z=shaft_axis_z):
        bolt = b.hole(
            end_cap_bolt_diameter,
            end_cap_thickness + 2.0 * through_overcut,
            position=(housing_length / 2.0 + end_cap_thickness + through_overcut, y, z),
            direction=(-1, 0, 0),
        )
        b.boolean_subtract(body, bolt)
    breather = b.hole(
        breather_tap_diameter,
        18.0,
        position=(housing_length / 2.0 + end_cap_thickness / 2.0, 0.0, shaft_axis_z + end_cap_diameter / 2.0 + through_overcut),
        direction=(0, 0, -1),
    )
    b.boolean_subtract(body, breather)
    mesh = b.hole(
        breather_mesh_diameter,
        1.5,
        position=(housing_length / 2.0 + end_cap_thickness / 2.0, 0.0, shaft_axis_z + end_cap_diameter / 2.0 + 1.0),
        direction=(0, 0, -1),
    )
    b.boolean_subtract(body, mesh)

    # M16 cap-bolt holes through vertical flanges at Y = +/-90.
    for x in flange_bolt_xs:
        for z in flange_bolt_zs:
            for side in (-1.0, 1.0):
                bolt = b.hole(
                    cap_bolt_clearance_diameter,
                    24.0 + through_overcut,
                    position=(x, side * (flange_face_y + through_overcut), z),
                    direction=(0, -side, 0),
                )
                b.boolean_subtract(body, bolt)
                counterbore = b.hole(
                    cap_bolt_counterbore_diameter,
                    cap_bolt_counterbore_depth,
                    position=(x, side * (flange_face_y + through_overcut), z),
                    direction=(0, -side, 0),
                )
                b.boolean_subtract(body, counterbore)

    # Integral foot: adjustment slots and anchor pattern.
    for x in (-mounting_slot_center_pitch / 2.0, mounting_slot_center_pitch / 2.0):
        b.slot_cut(
            body,
            mounting_slot_length,
            mounting_slot_width,
            base_foot_thickness + 2.0 * through_overcut,
            center=(x, 0.0, base_foot_thickness + through_overcut),
            axis=(1, 0, 0),
            direction=(0, 0, -1),
        )

    for x in (-anchor_pattern_x / 2.0, anchor_pattern_x / 2.0):
        for y in (-anchor_pattern_y / 2.0, anchor_pattern_y / 2.0):
            anchor = b.hole(
                anchor_hole_diameter,
                base_foot_thickness + 2.0 * through_overcut,
                position=(x, y, base_foot_thickness + through_overcut),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(body, anchor)

    # Top grease nipple, internal feed, and four radial distribution holes.
    nipple = b.cylinder(
        grease_nipple_diameter,
        18.0 + feature_overlap,
        origin=(0.0, 0.0, housing_height - feature_overlap),
        axis=(0, 0, 1),
    )
    b.boolean_unite(body, nipple)
    grease_tap = b.hole(
        grease_thread_diameter,
        24.0,
        position=(0.0, 0.0, housing_height + 18.0 + through_overcut),
        direction=(0, 0, -1),
    )
    b.boolean_subtract(body, grease_tap)
    grease_feed = b.hole(
        grease_passage_diameter,
        housing_height - shaft_axis_z + 12.0,
        position=(0.0, 0.0, housing_height + through_overcut),
        direction=(0, 0, -1),
    )
    b.boolean_subtract(body, grease_feed)
    for x in (-15.0, 15.0):
        for y_sign in (-1.0, 1.0):
            radial = b.hole(
                radial_lube_diameter,
                bearing_bore_diameter / 2.0 + 10.0,
                position=(x, 0.0, shaft_axis_z),
                direction=(0, y_sign, 0),
            )
            b.boolean_subtract(body, radial)

    # Forged lifting eye represented as a raised ring on the top center.
    eye_outer = b.cylinder(
        lifting_eye_ring_outer_diameter,
        lifting_eye_thickness,
        origin=(0.0, 0.0, housing_height + 16.0),
        axis=(0, 1, 0),
    )
    eye_inner = b.hole(
        lifting_eye_ring_inner_diameter,
        lifting_eye_thickness + 2.0 * cutter_overlap,
        position=(0.0, -lifting_eye_thickness / 2.0 - cutter_overlap, housing_height + 16.0),
        direction=(0, 1, 0),
    )
    b.boolean_subtract(eye_outer, eye_inner)
    stem = b.box(22.0, 18.0, 18.0 + feature_overlap, origin=(-11.0, -9.0, housing_height - feature_overlap))
    b.boolean_unite(body, stem)
    b.boolean_unite(body, eye_outer)

    # Conservative bearing-seat base fillet and accessible edge breaks.
    b.fillet(b.get_edges_in_box(body, min_xyz=(-40.0, -72.0, shaft_axis_z - 72.0), max_xyz=(40.0, 72.0, shaft_axis_z + 72.0)), radius=fillet_radius)
    b.chamfer(b.get_edges_in_box(body, min_xyz=(-142.0, -92.0, -1.0), max_xyz=(170.0, 92.0, 165.0)), offset=1.0)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
