# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the sibling cadnx/ folder to a machine with Siemens NX.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the model and exports precision_5_axis_cnc_turbine_blisk.step.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _polar(radius, angle_degrees, z):
    angle = math.radians(angle_degrees)
    return (radius * math.cos(angle), radius * math.sin(angle), z)


def _axes(angle_degrees):
    angle = math.radians(angle_degrees)
    radial = (math.cos(angle), math.sin(angle), 0.0)
    tangent = (-math.sin(angle), math.cos(angle), 0.0)
    return radial, tangent


def _add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def _scale(v, s):
    return (v[0] * s, v[1] * s, v[2] * s)


def _annular_cylinder(b, outer_diameter, inner_diameter, height, z_min):
    body = b.cylinder(outer_diameter, height, origin=(0.0, 0.0, z_min), axis=(0, 0, 1))
    bore = b.hole(inner_diameter, height + 4.0, position=(0.0, 0.0, z_min - 2.0), direction=(0, 0, 1))
    b.boolean_subtract(body, bore)
    return body


def _radial_prism(b, angle_degrees, radius_center, radial_depth, tangential_width, z_center, z_length):
    radial, tangent = _axes(angle_degrees)
    origin = _add(
        _add(_polar(radius_center, angle_degrees, z_center), _scale(radial, -radial_depth / 2.0)),
        _scale(tangent, -tangential_width / 2.0),
    )
    origin = _add(origin, (0.0, 0.0, -z_length / 2.0))
    points = [
        (0.0, 0.0),
        (radial_depth, 0.0),
        (radial_depth, z_length),
        (0.0, z_length),
    ]
    return b.polygon_prism_on_plane(
        points,
        tangential_width,
        origin=origin,
        u_axis=radial,
        v_axis=(0, 0, 1),
        extrude_axis=tangent,
    )


def _airfoil_polygon(chord, thickness, max_t_fraction):
    half_t = thickness / 2.0
    camber = 0.055 * chord
    return [
        (0.00 * chord, -0.12 * half_t),
        (0.08 * chord, -0.62 * half_t),
        (max_t_fraction * chord, -1.00 * half_t),
        (0.72 * chord, -0.55 * half_t),
        (1.00 * chord, -0.07 * half_t),
        (1.00 * chord, 0.07 * half_t),
        (0.72 * chord, 0.55 * half_t + 0.20 * camber),
        (max_t_fraction * chord, 1.00 * half_t + 0.55 * camber),
        (0.08 * chord, 0.64 * half_t + 0.15 * camber),
    ]


def _blade_segment(b, angle_degrees, r0, r1, z_root, chord, thickness, max_t_fraction, lean_degrees):
    radial, tangent = _axes(angle_degrees)
    radial_span = r1 - r0
    radius_mid = (r0 + r1) / 2.0
    aft_lean = math.tan(math.radians(lean_degrees)) * ((radius_mid - 93.0) / (135.0 - 93.0)) * 7.0
    stagger_degrees = 22.0 - 13.0 * ((radius_mid - 93.0) / (135.0 - 93.0))
    stagger = math.radians(stagger_degrees)
    chord_axis = _add(_scale((0, 0, 1), math.cos(stagger)), _scale(tangent, math.sin(stagger)))
    thick_axis = _add(_scale(tangent, math.cos(stagger)), _scale((0, 0, 1), -math.sin(stagger)))
    origin = _add(_polar(radius_mid, angle_degrees, z_root + aft_lean), _scale(chord_axis, -0.08 * chord))
    return b.polygon_prism_on_plane(
        _airfoil_polygon(chord, thickness, max_t_fraction),
        radial_span,
        origin=origin,
        u_axis=chord_axis,
        v_axis=thick_axis,
        extrude_axis=radial,
    )


def _metadata_notes():
    return [
        "Material: Ti-6Al-4V ELI, monolithic 5-axis CNC-machined blisk forging.",
        "General finish Ra 1.6 um; bore Ra 0.4 um H7 32.000-32.025; airfoils Ra 0.2 um.",
        "Pressure-side YSZ thermal barrier coating represented by thin surface panels: 0.15 mm, 12 percent porosity.",
        "Blade-to-disk fillets represent variable 4.0 to 2.5 mm Bezier-controlled manufacturing blend.",
        "Shot peen: Almen 0.15 mmA, 200 percent coverage; fillet polish Ra 0.8 um.",
        "Part ID: TB-186-24-01 / SN-XXXXXX / Ti-6Al-4V ELI / HT-2024-06 / 65,000 RPM.",
    ]


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters.
    blade_count = 24
    blade_pitch = 360.0 / blade_count
    disk_outer_diameter_front = 186.0
    disk_outer_diameter_rear = 176.0
    bore_diameter = 32.0
    rim_thickness = 48.0
    hub_thickness = 62.0
    blade_root_radius = 93.0
    blade_tip_radius = 135.0
    section_radii = [93.0, 100.0, 107.0, 114.0, 121.0, 128.0, 135.0]
    root_chord = 38.0
    tip_chord = 26.0
    root_thickness = 6.2
    tip_thickness = 3.8
    root_max_t = 0.32
    tip_max_t = 0.38
    blade_z_root = 0.0
    blade_lean_degrees = 18.0
    counterbore_diameter = 42.0
    counterbore_depth = 18.0
    seal_land_inner_diameter = 80.0
    seal_land_outer_diameter = 120.0
    seal_land_height = 3.0
    balance_ring_inner_diameter = 140.0
    balance_ring_outer_diameter = 170.0
    balance_ring_thickness = 6.0
    tie_bolt_count = 8
    tie_bolt_diameter = 8.5
    tie_bolt_bcd = 58.0
    cooling_hole_diameter = 1.2
    cooling_hole_depth = 15.0
    cooling_hole_z = 36.0
    threaded_balance_hole_depth = 8.0
    threaded_balance_hole_diameter = 3.3
    oil_feed_hole_diameter = 3.0

    b.require_positive(
        blade_count=blade_count,
        bore_diameter=bore_diameter,
        rim_thickness=rim_thickness,
        hub_thickness=hub_thickness,
        tie_bolt_diameter=tie_bolt_diameter,
    )

    # Primary titanium disk body: stepped annular approximation of the specified
    # logarithmic OD taper, united to a thicker hub section.
    blisk = _annular_cylinder(b, disk_outer_diameter_front, bore_diameter, 12.0, 0.0)
    for idx in range(1, 4):
        z0 = idx * 12.0
        t = z0 / rim_thickness
        radius = 93.0 - 5.0 * math.log(1.0 + 1.7 * t) / math.log(2.7)
        step = _annular_cylinder(b, 2.0 * radius, bore_diameter, 12.0, z0)
        b.boolean_unite(blisk, step)

    hub = _annular_cylinder(b, 118.0, bore_diameter, hub_thickness, 0.0)
    b.boolean_unite(blisk, hub)

    front_land = _annular_cylinder(b, seal_land_outer_diameter, seal_land_inner_diameter, seal_land_height, 0.0)
    b.boolean_unite(blisk, front_land)

    rear_balance_ring = _annular_cylinder(
        b,
        balance_ring_outer_diameter,
        balance_ring_inner_diameter,
        balance_ring_thickness,
        rim_thickness - balance_ring_thickness,
    )
    b.boolean_unite(blisk, rear_balance_ring)

    # Bore, spline, counterbore, serrations, bolt holes, balance holes, and oil feed.
    rear_counterbore = b.hole(
        counterbore_diameter,
        counterbore_depth + 1.0,
        position=(0.0, 0.0, rim_thickness + 0.5),
        direction=(0, 0, -1),
    )
    b.boolean_subtract(blisk, rear_counterbore)

    for idx in range(16):
        angle = idx * 22.5
        spline_tooth_space = _radial_prism(b, angle + 11.25, 18.3, 2.8, 2.0, 27.5, 35.0)
        b.boolean_subtract(blisk, spline_tooth_space)

    lubrication_groove = _annular_cylinder(b, 38.8, 31.0, 2.0, 26.5)
    b.boolean_subtract(blisk, lubrication_groove)

    oil_angle = blade_pitch / 2.0
    radial, _ = _axes(oil_angle)
    oil_hole = b.hole(
        oil_feed_hole_diameter,
        80.0,
        position=_polar(94.0, oil_angle, 27.5),
        direction=_scale(radial, -1.0),
    )
    b.boolean_subtract(blisk, oil_hole)

    for idx in range(tie_bolt_count):
        angle = 22.5 + idx * 45.0
        pt = _polar(tie_bolt_bcd / 2.0, angle, -1.0)
        b.boolean_subtract(blisk, b.hole(tie_bolt_diameter, rim_thickness + 4.0, position=pt, direction=(0, 0, 1)))
        b.boolean_subtract(blisk, b.hole(12.0, 2.5, position=_polar(tie_bolt_bcd / 2.0, angle, -0.5), direction=(0, 0, 1)))

    for idx in range(blade_count):
        angle = idx * blade_pitch
        balance_pt = _polar((balance_ring_inner_diameter + balance_ring_outer_diameter) / 4.0, angle, rim_thickness + 0.5)
        diameter = 5.0 if idx in (0, 12) else threaded_balance_hole_diameter
        depth = 10.0 if idx in (0, 12) else threaded_balance_hole_depth
        b.boolean_subtract(blisk, b.hole(diameter, depth + 1.0, position=balance_pt, direction=(0, 0, -1)))

    for idx in range(8):
        angle = idx * 45.0
        serration = _radial_prism(b, angle, 18.0, 10.0, 3.0, rim_thickness - counterbore_depth / 2.0, counterbore_depth)
        b.boolean_subtract(blisk, serration)

    # Blades, hub fillets/platforms, passage seal slots, stress relief grooves, cooling holes.
    blade_features = []
    coating_features = []
    for idx in range(blade_count):
        angle = idx * blade_pitch
        root_platform = _radial_prism(b, angle, 94.0, 5.5, 11.0, 36.0, 74.0)
        b.boolean_unite(blisk, root_platform)
        blade_features.append(root_platform)

        for sidx in range(len(section_radii) - 1):
            r0 = section_radii[sidx]
            r1 = section_radii[sidx + 1]
            tmid = ((r0 + r1) / 2.0 - blade_root_radius) / (blade_tip_radius - blade_root_radius)
            chord = root_chord + (tip_chord - root_chord) * tmid
            thickness = root_thickness + (tip_thickness - root_thickness) * tmid
            max_t = root_max_t + (tip_max_t - root_max_t) * tmid
            segment = _blade_segment(b, angle, r0, r1, blade_z_root, chord, thickness, max_t, blade_lean_degrees)
            b.boolean_unite(blisk, segment)
            blade_features.append(segment)

            if sidx < len(section_radii) - 2:
                coat = _blade_segment(
                    b,
                    angle + 0.16,
                    r0 + 0.08,
                    min(r1 + 0.08, blade_tip_radius - 5.0),
                    blade_z_root + 5.7,
                    chord * 0.70,
                    0.15,
                    max_t,
                    blade_lean_degrees,
                )
                coating_features.append(coat)

        passage_angle = angle + blade_pitch / 2.0
        slot = _radial_prism(b, passage_angle, 93.7, 1.8, 0.3, 27.5, 35.0)
        b.boolean_subtract(blisk, slot)
        relief = _radial_prism(b, passage_angle, 91.5, 1.5, 1.5, 36.0, 58.0)
        b.boolean_subtract(blisk, relief)

        hole_angle = passage_angle
        radial, tangent = _axes(hole_angle)
        drill_dir = _add(_scale(radial, -math.cos(math.radians(15.0))), _scale(tangent, math.sin(math.radians(15.0))))
        cooling_hole = b.hole(
            cooling_hole_diameter,
            cooling_hole_depth,
            position=_polar(93.0, hole_angle, cooling_hole_z),
            direction=drill_dir,
        )
        b.boolean_subtract(blisk, cooling_hole)

    for coat in coating_features:
        b.boolean_unite(blisk, coat)

    # Spiral seal grooves are represented as six shallow chordal fly-cut slots.
    for idx in range(6):
        angle = idx * 60.0 + 15.0
        for step in range(8):
            radius = 43.0 + step * 4.0
            groove_angle = angle + step * 15.0
            groove = _radial_prism(b, groove_angle, radius, 7.0, 0.3, 3.1, 0.35)
            b.boolean_subtract(blisk, groove)

    # Forging die witness ridges and rear laser-mark/data-matrix pads as shallow geometry.
    front_witness = _annular_cylinder(b, 150.2, 149.8, 0.1, 0.0)
    rear_witness = _annular_cylinder(b, 150.2, 149.8, 0.1, rim_thickness - 0.1)
    b.boolean_unite(blisk, front_witness)
    b.boolean_unite(blisk, rear_witness)

    mark_pad = _radial_prism(b, 0.0, 100.0, 28.0, 0.3, rim_thickness + 0.02, 14.0)
    data_matrix_pad = _radial_prism(b, 6.0, 100.0, 10.0, 0.3, rim_thickness + 0.02, 10.0)
    b.boolean_subtract(blisk, mark_pad)
    b.boolean_subtract(blisk, data_matrix_pad)

    for note in _metadata_notes():
        print("BLISK NOTE:", note)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
