# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              precision_gearbox_housing.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports precision_gearbox_housing.step.
# ----------------------------------------------------------------------------

import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent parameters, millimeters.
    body_length = 180.0
    body_width = 140.0
    body_height = 90.0
    wall = 12.0
    flange_overhang = 10.0
    flange_thickness = 12.0
    foot_size = 30.0
    foot_drop = 8.0
    web_thickness = 8.0
    rib_thickness = 6.0
    rib_z_min = 12.0
    rib_z_max = 78.0
    bearing_axis_tolerance = 0.05
    bearing_bore_roughness_ra = 0.8
    sealing_counterbore_roughness_ra = 1.6

    # Derived layout.
    x_min = -body_length / 2.0
    x_max = body_length / 2.0
    y_min = -body_width / 2.0
    y_max = body_width / 2.0
    z_min = 0.0
    z_max = body_height
    flange_length = body_length + 2.0 * flange_overhang
    flange_width = body_width + 2.0 * flange_overhang
    cavity_length = body_length - 2.0 * wall
    cavity_width = body_width - 2.0 * wall
    through_x_depth = body_length + 4.0
    through_z_depth = body_height + foot_drop + 6.0
    rib_height = rib_z_max - rib_z_min

    if wall * 2.0 >= min(body_length, body_width):
        raise ValueError("Wall thickness is too large for the housing cavity.")

    # Main body and top flange. The top is open after the cavity cut.
    housing = b.box(body_length, body_width, body_height, origin=(x_min, y_min, z_min))
    flange = b.box(
        flange_length,
        flange_width,
        flange_thickness,
        origin=(-flange_length / 2.0, -flange_width / 2.0, z_max - flange_thickness),
    )
    b.boolean_unite(housing, flange)

    cavity = b.box(
        cavity_length,
        cavity_width,
        body_height + 4.0,
        origin=(-cavity_length / 2.0, -cavity_width / 2.0, wall),
    )
    b.boolean_subtract(housing, cavity)

    # Base mounting feet.
    foot_centers = [(-75.0, -55.0), (-75.0, 55.0), (75.0, -55.0), (75.0, 55.0)]
    for fx, fy in foot_centers:
        foot = b.box(
            foot_size,
            foot_size,
            foot_drop,
            origin=(fx - foot_size / 2.0, fy - foot_size / 2.0, -foot_drop),
        )
        b.boolean_unite(housing, foot)

    # Interior ribbing, united into the housing after the cavity is opened.
    for ry in (-25.0, 25.0):
        rib = b.box(
            cavity_length,
            rib_thickness,
            rib_height,
            origin=(-cavity_length / 2.0, ry - rib_thickness / 2.0, rib_z_min),
        )
        b.boolean_unite(housing, rib)

    cross_rib = b.box(
        rib_thickness,
        50.0 + rib_thickness,
        rib_height,
        origin=(-rib_thickness / 2.0, -25.0 - rib_thickness / 2.0, rib_z_min),
    )
    b.boolean_unite(housing, cross_rib)

    # Exterior triangular reinforcing webs on side faces.
    web_points = [(-90.0, 0.0), (50.0, 0.0), (50.0, 60.0)]
    web_pos = b.polygon_prism_on_plane(
        web_points,
        web_thickness,
        origin=(0.0, y_max, 0.0),
        u_axis=(1, 0, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(0, 1, 0),
    )
    b.boolean_unite(housing, web_pos)
    web_neg = b.polygon_prism_on_plane(
        web_points,
        web_thickness,
        origin=(0.0, y_min, 0.0),
        u_axis=(1, 0, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(0, -1, 0),
    )
    b.boolean_unite(housing, web_neg)

    # Coaxial bearing bores and sealing counterbores on front and rear faces.
    bearing_specs = [
        {"name": "primary", "z": 55.0, "bore_dia": 45.0, "cbore_dia": 55.0},
        {"name": "secondary", "z": 25.0, "bore_dia": 35.0, "cbore_dia": 45.0},
    ]
    for spec in bearing_specs:
        zc = spec["z"]
        b.counterbore_hole(
            housing,
            spec["bore_dia"],
            through_x_depth,
            spec["cbore_dia"],
            3.0,
            position=(x_max + 1.0, 0.0, zc),
            direction=(-1, 0, 0),
        )
        b.counterbore_hole(
            housing,
            spec["bore_dia"],
            through_x_depth,
            spec["cbore_dia"],
            3.0,
            position=(x_min - 1.0, 0.0, zc),
            direction=(1, 0, 0),
        )

    # Top flange mounting holes with spotfaces.
    for hx in (-60.0, 0.0, 60.0):
        for hy in (-55.0, 55.0):
            b.counterbore_hole(
                housing,
                10.0,
                flange_thickness + 4.0,
                20.0,
                3.0,
                position=(hx, hy, z_max + 1.0),
                direction=(0, 0, -1),
            )

    # Base foot M8 threaded-hole pilot cuts and bolt-head counterbores.
    for fx, fy in foot_centers:
        b.counterbore_hole(
            housing,
            8.5,
            15.0,
            16.0,
            2.0,
            position=(fx, fy, -foot_drop - 1.0),
            direction=(0, 0, 1),
        )

    # Blind oil galleries.
    gallery_x = b.hole(8.0, 91.0, position=(x_min - 1.0, 40.0, 75.0), direction=(1, 0, 0))
    b.boolean_subtract(housing, gallery_x)
    gallery_z = b.hole(6.0, 83.0, position=(-30.0, 40.0, -foot_drop - 1.0), direction=(0, 0, 1))
    b.boolean_subtract(housing, gallery_z)

    # Drain and fill ports. Thread specifications are retained as manufacturing callouts below.
    b.counterbore_hole(
        housing,
        16.0,
        12.0,
        22.0,
        3.0,
        position=(50.0, 0.0, -foot_drop - 1.0),
        direction=(0, 0, 1),
    )
    b.counterbore_hole(
        housing,
        22.0,
        15.0,
        30.0,
        3.0,
        position=(-40.0, 0.0, z_max + 1.0),
        direction=(0, 0, -1),
    )

    # Conservative edge treatment. These calls may warn and skip individual edges in NX
    # if a local blend is topologically impossible after the booleans.
    b.fillet(b.get_edges_in_box(housing, (x_min - 1, y_min - 1, -0.5), (x_max + 1, y_max + 1, z_max + 0.5)), 3.0)
    b.fillet(b.get_edges_in_box(housing, (-101, -81, z_max - flange_thickness - 0.5), (101, 81, z_max + 0.5)), 3.0)
    b.fillet(b.get_edges_in_box(housing, (-91, y_max - 1, -0.5), (51, y_max + web_thickness + 1, 61)), 5.0)
    b.fillet(b.get_edges_in_box(housing, (-91, y_min - web_thickness - 1, -0.5), (51, y_min + 1, 61)), 5.0)
    b.fillet(b.get_edges_in_box(housing, (-80, -60, -foot_drop - 1), (80, 60, 1)), 3.0)
    b.fillet(b.get_edges_in_box(housing, (-79, -29, rib_z_min - 1), (79, 29, rib_z_max + 1)), 2.0)

    # Local edge breaks at bearing bores, bolt holes, feet holes, and service ports.
    for spec in bearing_specs:
        for x_face in (x_min, x_max):
            b.chamfer(b.get_edges_near(housing, (x_face, 0.0, spec["z"]), tolerance=spec["cbore_dia"] / 2.0 + 1.0), 1.0)
    for hx in (-60.0, 0.0, 60.0):
        for hy in (-55.0, 55.0):
            b.chamfer(b.get_edges_near(housing, (hx, hy, z_max), tolerance=11.0), 1.0)
    for fx, fy in foot_centers:
        b.chamfer(b.get_edges_near(housing, (fx, fy, -foot_drop), tolerance=9.0), 1.0)
    for px, py, pz, tol in ((50.0, 0.0, -foot_drop, 12.0), (-40.0, 0.0, z_max, 16.0)):
        b.chamfer(b.get_edges_near(housing, (px, py, pz), tolerance=tol), 1.0)

    # Manufacturing and inspection callouts not modeled as PMI by this wrapper:
    # - M8 internal threads in each foot: major pilot 8.5 mm, depth 15 mm.
    # - Drain port: M16x1.5 internal thread, major diameter 16 mm, depth 12 mm.
    # - Fill port: M22x1.5 internal thread, major diameter 22 mm, depth 15 mm.
    # - Bearing bore cylindrical surfaces: Ra 0.8 um.
    # - Sealing counterbore faces: Ra 1.6 um.
    # - Bearing bore axes positional tolerance: +/-0.05 mm relative to datum frame
    #   established by the four base mounting feet.
    print("CALLOUT: Bearing bore cylindrical surfaces Ra %.1f um." % bearing_bore_roughness_ra)
    print("CALLOUT: Sealing counterbore faces Ra %.1f um." % sealing_counterbore_roughness_ra)
    print("CALLOUT: Bearing bore axes positional tolerance +/-%.2f mm to base-foot datum frame." % bearing_axis_tolerance)
    print("CALLOUT: Foot holes M8, drain M16x1.5, fill M22x1.5 internal threads per modeled pilot depths.")

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
