# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              precision_cnc_rotary_table_assembly.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports precision_cnc_rotary_table_assembly.step.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder

try:
    import NXOpen
except ImportError:
    NXOpen = None


def _polar(radius, angle_degrees, z):
    angle = math.radians(angle_degrees)
    return (radius * math.cos(angle), radius * math.sin(angle), z)


def _axes(angle_degrees):
    angle = math.radians(angle_degrees)
    radial = (math.cos(angle), math.sin(angle), 0.0)
    tangential = (-math.sin(angle), math.cos(angle), 0.0)
    return radial, tangential


def _add(p, q):
    return (p[0] + q[0], p[1] + q[1], p[2] + q[2])


def _scale(v, s):
    return (v[0] * s, v[1] * s, v[2] * s)


def _name_feature(builder, feature, name):
    try:
        builder._body(feature).SetName(name)
    except Exception:
        pass
    try:
        feature.SetName(name)
    except Exception:
        pass


def _set_color(builder, features, color_index):
    """Best-effort NX display color assignment; geometry still builds if unavailable."""
    if NXOpen is None:
        return
    try:
        bodies = [builder._body(feature) for feature in features if feature is not None]
        if not bodies:
            return
        display_mod = builder.session.DisplayManager.NewDisplayModification()
        display_mod.ApplyToAllFaces = True
        display_mod.NewColor = int(color_index)
        display_mod.Apply(bodies)
        display_mod.Dispose()
    except Exception as exc:
        print(f"WARNING: color assignment skipped for NX color {color_index}: {exc}")


def _annular_cylinder(builder, outer_diameter, inner_diameter, height, z_min):
    body = builder.cylinder(outer_diameter, height, origin=(0, 0, z_min), axis=(0, 0, 1))
    bore = builder.hole(inner_diameter, height + 4.0, position=(0, 0, z_min - 2.0), direction=(0, 0, 1))
    builder.boolean_subtract(body, bore)
    return body


def _radial_prism_cut(builder, target, angle_degrees, r_start, r_end, width, z_top, depth):
    radial, tangential = _axes(angle_degrees)
    r_mid = (r_start + r_end) / 2.0
    center = _polar(r_mid, angle_degrees, z_top + 1.0)
    points = [
        (-(r_end - r_start) / 2.0, -width / 2.0),
        ((r_end - r_start) / 2.0, -width / 2.0),
        ((r_end - r_start) / 2.0, width / 2.0),
        (-(r_end - r_start) / 2.0, width / 2.0),
    ]
    tool = builder.polygon_prism_on_plane(
        points,
        depth + 2.0,
        origin=center,
        u_axis=radial,
        v_axis=tangential,
        extrude_axis=(0, 0, -1),
    )
    return builder.boolean_subtract(target, tool)


def _side_arm(builder, y_center, z_base, z_top, x_bottom_width, x_top_width, y_thickness):
    points = [
        (-x_bottom_width / 2.0, 0.0),
        (x_bottom_width / 2.0, 0.0),
        (x_top_width / 2.0, z_top - z_base),
        (-x_top_width / 2.0, z_top - z_base),
    ]
    arm = builder.polygon_prism_on_plane(
        points,
        y_thickness,
        origin=(0.0, y_center - y_thickness / 2.0, z_base),
        u_axis=(1, 0, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(0, 1, 0),
    )
    return arm


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    base_diameter = 420.0
    base_height = 95.0
    base_top_z = 95.0
    base_central_bore_diameter = 80.0
    base_central_bore_depth = 60.0
    pad_size = 40.0
    pad_height = 3.0
    pad_bolt_circle_diameter = 340.0
    pad_thread_minor_diameter = 17.5
    pad_thread_depth = 18.0

    worm_housing_outer_diameter = 380.0
    worm_housing_inner_diameter = 300.0
    worm_housing_height = 55.0
    worm_housing_center_z = 70.0
    worm_shaft_bore_diameter = 35.0
    worm_wheel_seat_diameter = 310.0
    worm_wheel_seat_width = 12.0
    worm_wheel_seat_center_z = 75.0

    table_diameter = 300.0
    table_thickness = 45.0
    table_center_z = 120.0
    t_slot_count = 8
    t_slot_width = 14.0
    t_slot_depth = 18.0
    t_slot_r_start = 35.0
    t_slot_r_end = 135.0
    taper_large_end_diameter = 39.8
    taper_depth = 60.0
    clamp_bolt_count = 6
    clamp_bolt_circle_diameter = 200.0
    clamp_thread_diameter = 12.0
    clamp_thread_depth = 20.0
    clamp_counterbore_diameter = 13.5
    clamp_counterbore_depth = 8.0

    bearing_outer_diameter = 298.0
    bearing_inner_diameter = 242.0
    bearing_height = 25.0
    bearing_center_z = 97.5
    roller_count_per_row = 24
    roller_diameter = 8.0
    roller_length = 8.0

    worm_shaft_diameter = 30.0
    worm_shaft_length = 180.0
    worm_shaft_z = 82.5
    worm_key_length = 25.0
    worm_key_width = 8.0
    worm_key_depth = 5.0
    worm_thread_minor_diameter = 18.4
    worm_thread_length = 20.0
    worm_thread_center_x = 90.0
    worm_section_width = 20.0

    arm_y_spacing = 320.0
    arm_y_thickness = 180.0
    arm_z_base = 120.0
    arm_z_top = 300.0
    arm_x_bottom_width = 280.0
    arm_x_top_width = 180.0
    trunnion_bore_diameter = 60.0
    trunnion_bore_z = 220.0
    trunnion_shoulder_diameter = 75.0
    trunnion_shoulder_width = 15.0
    motor_flange_diameter = 130.0
    motor_flange_thickness = 15.0
    motor_hole_diameter = 9.0
    motor_bolt_circle_diameter = 110.0

    piston_outer_count = 12
    piston_inner_count = 8
    piston_diameter = 16.0
    piston_z = 110.0
    hydraulic_feed_diameter = 6.0
    manifold_groove_diameter = 100.0
    manifold_groove_width = 10.0
    manifold_groove_depth = 8.0
    manifold_z = 105.0

    chip_guard_diameter = 340.0
    chip_guard_height = 25.0
    chip_guard_wall = 3.0
    reference_pin_diameter = 8.0
    reference_pin_length = 20.0
    reference_pin_x = 150.0
    detection_slot_width = 10.0
    detection_slot_depth = 5.0
    detection_slot_length = 30.0

    seal_outer_diameter = 296.0
    seal_inner_diameter = 244.0
    seal_thickness = 2.0
    seal_z = 99.0
    seal_micro_hole_count = 24
    air_groove_diameter = 270.0
    air_groove_width = 6.0
    air_groove_depth = 4.0

    # Derived dimensions.
    worm_housing_z_min = worm_housing_center_z - worm_housing_height / 2.0
    table_z_min = table_center_z - table_thickness / 2.0
    table_z_max = table_center_z + table_thickness / 2.0
    bearing_z_min = bearing_center_z - bearing_height / 2.0
    arm_y_centers = (-arm_y_spacing / 2.0, arm_y_spacing / 2.0)

    # NX approximate display color indices.
    machine_gray = 142
    ground_steel = 190
    brass = 46
    hardened_steel = 181
    cast_iron = 87
    anodized_aluminum = 104
    rubber_black = 216

    base_features = []
    table_features = []
    bearing_features = []
    worm_features = []
    trunnion_features = []
    hydraulic_features = []
    seal_features = []

    # Base casting with pads and M16 minor-diameter blind threaded holes.
    base = b.cylinder(base_diameter, base_height, origin=(0, 0, 0), axis=(0, 0, 1))
    _name_feature(b, base, "base casting - diameter 420 height 95, machine gray")
    base_bore = b.hole(base_central_bore_diameter, base_central_bore_depth + 2.0, position=(0, 0, base_top_z + 1.0), direction=(0, 0, -1))
    b.boolean_subtract(base, base_bore)
    base_features.append(base)
    for index in range(4):
        angle = index * 90.0
        x, y, _ = _polar(pad_bolt_circle_diameter / 2.0, angle, base_top_z)
        pad = b.rounded_box(pad_size, pad_size, pad_height, radius=2.0, origin=(x - pad_size / 2.0, y - pad_size / 2.0, base_top_z))
        _name_feature(b, pad, f"raised mounting pad {index + 1} - 40 x 40 x 3")
        b.boolean_unite(base, pad)
        pad_hole = b.hole(pad_thread_minor_diameter, pad_thread_depth + 1.0, position=(x, y, base_top_z + pad_height + 0.5), direction=(0, 0, -1))
        b.boolean_subtract(base, pad_hole)

    # Worm gear housing ring and machined worm wheel seat.
    housing = _annular_cylinder(b, worm_housing_outer_diameter, worm_housing_inner_diameter, worm_housing_height, worm_housing_z_min)
    _name_feature(b, housing, "worm gear housing ring - OD 380 ID 300 height 55")
    worm_bore = b.hole(worm_shaft_bore_diameter, 90.0, position=(worm_housing_outer_diameter / 2.0 + 3.0, 0, worm_shaft_z), direction=(-1, 0, 0))
    b.boolean_subtract(housing, worm_bore)
    seat_cut = _annular_cylinder(b, worm_wheel_seat_diameter + 2.0, worm_housing_inner_diameter - 2.0, worm_wheel_seat_width, worm_wheel_seat_center_z - worm_wheel_seat_width / 2.0)
    b.boolean_subtract(housing, seat_cut)
    base_features.append(housing)

    # Main rotary table with T-slots, taper bore, clamping holes, slot for reference detection, and hydraulic groove.
    table = b.cylinder(table_diameter, table_thickness, origin=(0, 0, table_z_min), axis=(0, 0, 1))
    _name_feature(b, table, "A-axis rotary table - precision ground steel")
    for index in range(t_slot_count):
        _radial_prism_cut(b, table, index * 360.0 / t_slot_count, t_slot_r_start, t_slot_r_end, t_slot_width, table_z_max, t_slot_depth)
    taper = b.hole(taper_large_end_diameter, taper_depth + 2.0, position=(0, 0, table_z_max + 1.0), direction=(0, 0, -1))
    b.boolean_subtract(table, taper)
    for index in range(clamp_bolt_count):
        x, y, _ = _polar(clamp_bolt_circle_diameter / 2.0, index * 360.0 / clamp_bolt_count, table_z_max)
        b.counterbore_hole(
            table,
            clamp_thread_diameter,
            clamp_thread_depth,
            clamp_counterbore_diameter,
            clamp_counterbore_depth,
            position=(x, y, table_z_max + 0.5),
            direction=(0, 0, -1),
        )
    b.slot_cut(
        table,
        detection_slot_length,
        detection_slot_width,
        detection_slot_depth,
        center=(reference_pin_x, 0.0, table_z_min - 0.5),
        axis=(1, 0, 0),
        direction=(0, 0, 1),
    )
    manifold = _annular_cylinder(b, manifold_groove_diameter + manifold_groove_width, manifold_groove_diameter - manifold_groove_width, manifold_groove_depth, manifold_z - manifold_groove_depth / 2.0)
    b.boolean_subtract(table, manifold)
    table_features.append(table)

    # Cross-roller bearing ring with two staggered 45-degree roller rows.
    bearing = _annular_cylinder(b, bearing_outer_diameter, bearing_inner_diameter, bearing_height, bearing_z_min)
    _name_feature(b, bearing, "cross-roller bearing ring - OD 298 ID 242 height 25")
    bearing_features.append(bearing)
    roller_pitch_radius = (bearing_outer_diameter + bearing_inner_diameter) / 4.0
    for row, z_offset, angle_offset, tilt_sign in (
        (1, -4.0, 0.0, 1.0),
        (2, 4.0, 360.0 / (roller_count_per_row * 2.0), -1.0),
    ):
        for index in range(roller_count_per_row):
            angle = angle_offset + index * 360.0 / roller_count_per_row
            radial, tangential = _axes(angle)
            axis = _add(_scale(radial, math.cos(math.radians(45.0))), (0.0, 0.0, tilt_sign * math.sin(math.radians(45.0))))
            roller = b.cylinder(roller_diameter, roller_length, origin=_polar(roller_pitch_radius, angle, bearing_center_z + z_offset), axis=axis)
            _name_feature(b, roller, f"cross roller row {row} roller {index + 1}")
            bearing_features.append(roller)

    # Worm shaft with keyed section, simplified worm/thread zones.
    shaft = b.cylinder(worm_shaft_diameter, worm_shaft_length, origin=(-worm_shaft_length / 2.0, 0, worm_shaft_z), axis=(1, 0, 0))
    _name_feature(b, shaft, "worm shaft - diameter 30 length 180 hardened steel")
    keyway = b.box(worm_key_length, worm_key_width, worm_key_depth + 2.0, origin=(60.0 - worm_key_length / 2.0, -worm_key_width / 2.0, worm_shaft_z + worm_shaft_diameter / 2.0 - worm_key_depth))
    b.boolean_subtract(shaft, keyway)
    worm_section = b.cylinder(34.0, worm_section_width, origin=(-worm_section_width / 2.0, 0, worm_shaft_z), axis=(1, 0, 0))
    _name_feature(b, worm_section, "simplified worm thread section - module 1.5, 40 teeth, 20 mm face")
    threaded_minor = b.cylinder(worm_thread_minor_diameter, worm_thread_length, origin=(worm_thread_center_x - worm_thread_length / 2.0, 0, worm_shaft_z), axis=(1, 0, 0))
    _name_feature(b, threaded_minor, "M20 x 1.5 threaded section minor diameter representation")
    worm_features.extend([shaft, worm_section, threaded_minor])

    # Trunnion cradle side arms, bores, shoulders, and motor flange.
    for side_name, y_center in (("minus Y", arm_y_centers[0]), ("plus Y", arm_y_centers[1])):
        arm = _side_arm(b, y_center, arm_z_base, arm_z_top, arm_x_bottom_width, arm_x_top_width, arm_y_thickness)
        _name_feature(b, arm, f"B-axis trunnion {side_name} tapered side arm")
        bore = b.hole(trunnion_bore_diameter, arm_y_thickness + 8.0, position=(0, y_center - arm_y_thickness / 2.0 - 4.0, trunnion_bore_z), direction=(0, 1, 0))
        b.boolean_subtract(arm, bore)
        shoulder = b.hole(trunnion_shoulder_diameter, trunnion_shoulder_width + 1.0, position=(0, y_center + arm_y_thickness / 2.0 + 0.5, trunnion_bore_z), direction=(0, -1, 0))
        b.boolean_subtract(arm, shoulder)
        trunnion_features.append(arm)
    motor_flange = b.cylinder(motor_flange_diameter, motor_flange_thickness, origin=(0, arm_y_centers[1] + arm_y_thickness / 2.0, trunnion_bore_z), axis=(0, 1, 0))
    _name_feature(b, motor_flange, "trunnion drive motor mount flange - plus Y")
    for index in range(4):
        angle = index * 90.0
        x = (motor_bolt_circle_diameter / 2.0) * math.cos(math.radians(angle))
        z = trunnion_bore_z + (motor_bolt_circle_diameter / 2.0) * math.sin(math.radians(angle))
        hole = b.hole(motor_hole_diameter, motor_flange_thickness + 2.0, position=(x, arm_y_centers[1] + arm_y_thickness / 2.0 + motor_flange_thickness + 1.0, z), direction=(0, -1, 0))
        b.boolean_subtract(motor_flange, hole)
    trunnion_features.append(motor_flange)

    # Hydraulic clamping pistons and radial feed-hole representations.
    for ring_count, ring_diameter, label in (
        (piston_outer_count, 250.0, "outer"),
        (piston_inner_count, 180.0, "inner"),
    ):
        for index in range(ring_count):
            angle = index * 360.0 / ring_count
            x, y, _ = _polar(ring_diameter / 2.0, angle, piston_z)
            piston = b.cylinder(piston_diameter, 10.0, origin=(x, y, piston_z - 5.0), axis=(0, 0, 1))
            _name_feature(b, piston, f"hydraulic clamping piston {label} ring {index + 1}")
            hydraulic_features.append(piston)
            feed_length = max(ring_diameter / 2.0 - manifold_groove_diameter / 2.0, 1.0)
            feed_center_radius = (ring_diameter / 4.0 + manifold_groove_diameter / 4.0)
            radial, _ = _axes(angle)
            feed = b.cylinder(hydraulic_feed_diameter, feed_length, origin=_polar(feed_center_radius - feed_length / 2.0, angle, manifold_z), axis=radial)
            _name_feature(b, feed, f"hydraulic radial feed hole representation {label} {index + 1}")
            hydraulic_features.append(feed)

    # Chip guard ring and zero-reference pin with hemispherical-tip representation.
    guard = _annular_cylinder(b, chip_guard_diameter, chip_guard_diameter - 2.0 * chip_guard_wall, chip_guard_height, base_top_z)
    _name_feature(b, guard, "circular chip guard ring - 340 diameter, 3 wall, mounted at Z95")
    base_features.append(guard)
    pin = b.cylinder(reference_pin_diameter, reference_pin_length, origin=(reference_pin_x, 0, base_top_z - reference_pin_length + 2.0), axis=(0, 0, 1))
    tip = b.cylinder(reference_pin_diameter, 3.0, origin=(reference_pin_x, 0, base_top_z + 2.0), axis=(0, 0, 1))
    _name_feature(b, pin, "zero-position reference pin - diameter 8")
    _name_feature(b, tip, "zero-position hemispherical tip approximation")
    base_features.extend([pin, tip])

    # Air purge nitrile seal ring, internal air groove, and 24 radial micro-hole representations.
    seal = _annular_cylinder(b, seal_outer_diameter, seal_inner_diameter, seal_thickness, seal_z - seal_thickness / 2.0)
    _name_feature(b, seal, "air purge seal ring - nitrile rubber black")
    seal_features.append(seal)
    air_channel = _annular_cylinder(b, air_groove_diameter + air_groove_width, air_groove_diameter - air_groove_width, air_groove_depth, seal_z - seal_thickness / 2.0 - 1.0)
    _name_feature(b, air_channel, "internal air channel annular groove representation")
    seal_features.append(air_channel)
    micro_radius = (seal_outer_diameter + seal_inner_diameter) / 4.0
    for index in range(seal_micro_hole_count):
        angle = index * 360.0 / seal_micro_hole_count
        radial, _ = _axes(angle)
        micro = b.cylinder(0.5, 30.0, origin=_polar(micro_radius - 15.0, angle, seal_z), axis=radial)
        _name_feature(b, micro, f"0.5 mm radial air purge micro-hole {index + 1}")
        seal_features.append(micro)

    # Conservative cosmetic blends where stable.
    b.fillet(b.get_top_edges(base), 1.5)
    b.chamfer(b.get_top_edges(table), 0.6)

    _set_color(b, base_features, machine_gray)
    _set_color(b, table_features, ground_steel)
    _set_color(b, bearing_features, brass)
    _set_color(b, worm_features, hardened_steel)
    _set_color(b, trunnion_features, cast_iron)
    _set_color(b, hydraulic_features, anodized_aluminum)
    _set_color(b, seal_features, rubber_black)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
