# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              precision_ball_screw_linear_actuator_assembly.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder

try:
    import NXOpen
except ImportError:
    NXOpen = None


def _name_feature(builder, feature, name):
    try:
        builder._body(feature).SetName(name)
    except Exception:
        pass
    try:
        feature.SetName(name)
    except Exception:
        pass


def _set_color(builder, features, color_index):
    if NXOpen is None:
        return
    try:
        bodies = [builder._body(feature) for feature in features if feature is not None]
        if not bodies:
            return
        display_mod = builder.session.DisplayManager.NewDisplayModification()
        display_mod.ApplyToAllFaces = True
        display_mod.NewColor = int(color_index)
        display_mod.Apply(bodies)
        display_mod.Dispose()
    except Exception as exc:
        print(f"WARNING: color assignment skipped for NX color {color_index}: {exc}")


def _annular_cylinder(builder, outer_diameter, inner_diameter, length, origin, axis):
    ring = builder.cylinder(outer_diameter, length, origin=origin, axis=axis)
    bore = builder.hole(inner_diameter, length + 4.0, position=origin, direction=axis)
    builder.boolean_subtract(ring, bore)
    return ring


def _box_centered(builder, length, width, height, center):
    cx, cy, cz = center
    return builder.box(
        length,
        width,
        height,
        origin=(cx - length / 2.0, cy - width / 2.0, cz - height / 2.0),
    )


def _hole_z(builder, target, diameter, depth, x, y, z_top):
    tool = builder.hole(
        diameter,
        depth + 2.0,
        position=(x, y, z_top + 1.0),
        direction=(0.0, 0.0, -1.0),
    )
    return builder.boolean_subtract(target, tool)


def _radial_hole_x(builder, target, diameter, depth, x_start, y, z, direction):
    tool = builder.hole(
        diameter,
        depth + 2.0,
        position=(x_start, y, z),
        direction=direction,
    )
    return builder.boolean_subtract(target, tool)


def _polar_yz(radius, angle_degrees, x):
    angle = math.radians(angle_degrees)
    return (x, radius * math.cos(angle), radius * math.sin(angle))


def _add_segmented_tube(builder, points, tube_outer_diameter, name_prefix, color_index=None):
    segments = []
    for index, (start, end) in enumerate(zip(points[:-1], points[1:])):
        dx = end[0] - start[0]
        dy = end[1] - start[1]
        dz = end[2] - start[2]
        length = (dx * dx + dy * dy + dz * dz) ** 0.5
        if length <= 0.001:
            continue
        feature = builder.cylinder(
            tube_outer_diameter,
            length,
            origin=start,
            axis=(dx / length, dy / length, dz / length),
        )
        _name_feature(builder, feature, f"{name_prefix}_{index:02d}")
        segments.append(feature)
    if color_index is not None:
        _set_color(builder, segments, color_index)
    return segments


def _helix_points_x(x_start, pitch, turns, radius, phase_degrees, center_y, center_z, samples):
    points = []
    total_angle = turns * 2.0 * math.pi
    total_length = pitch * turns
    phase = math.radians(phase_degrees)
    for index in range(samples + 1):
        fraction = index / float(samples)
        angle = phase + total_angle * fraction
        x = x_start + total_length * fraction
        y = center_y + radius * math.cos(angle)
        z = center_z + radius * math.sin(angle)
        points.append((x, y, z))
    return points


def _bolt_circle_holes_yz(builder, target, count, diameter, circle_diameter, x_face, y0, z0, depth, direction):
    radius = circle_diameter / 2.0
    for index in range(count):
        angle = 2.0 * math.pi * index / count
        y = y0 + radius * math.cos(angle)
        z = z0 + radius * math.sin(angle)
        _radial_hole_x(builder, target, diameter, depth, x_face, y, z, direction)


def build(output_path: str = None):
    b = NXBuilder()

    # Overall layout, millimeters.
    base_length = 680.0
    base_width = 120.0
    base_height = 85.0
    rail_surface_width = 15.0
    rail_surface_height = 5.0
    rail_center_y_values = (-35.0, 35.0)
    rail_surface_flatness_note_mm = 0.01

    foot_size = 40.0
    foot_thickness = 12.0
    foot_x_values = (-320.0, 320.0)
    foot_y_values = (-50.0, 50.0)
    foot_hole_diameter = 11.0
    foot_hole_spacing = 28.0

    screw_center_y = 0.0
    screw_center_z = 60.0
    screw_total_length = 620.0
    screw_nominal_diameter = 32.0
    fixed_journal_diameter = 25.0
    fixed_journal_length = 15.0
    floating_journal_diameter = 20.0
    floating_journal_length = 12.0
    screw_thread_x_min = -280.0
    screw_thread_x_max = 280.0
    screw_lead = 10.0
    screw_starts = 4
    screw_ball_diameter = 2.5
    screw_groove_radius = 1.3
    screw_contact_angle_degrees = 45.0

    nut_outer_diameter = 58.0
    nut_length = 72.0
    nut_flange_thickness = 12.0
    nut_flange_diameter = 85.0
    nut_flange_hole_count = 6
    nut_flange_hole_diameter = 6.5
    nut_flange_bcd = 72.0
    ball_circuit_count = 3
    balls_per_circuit = 28
    nut_ball_diameter = 2.5
    recirc_tube_outer_diameter = 4.0
    recirc_tube_pitch = 10.0
    recirc_tube_turns = 2.8
    recirc_tube_radius = 14.0

    fixed_block_length = 80.0
    fixed_block_width = 80.0
    fixed_block_height = 55.0
    fixed_block_x = -310.0
    fixed_bearing_bore = 25.0
    fixed_bearing_od = 52.0
    fixed_bearing_width = 15.0
    preload_shim_od = 52.0
    preload_shim_id = 38.0
    preload_shim_thickness = 0.05

    floating_block_length = 70.0
    floating_block_width = 70.0
    floating_block_height = 45.0
    floating_block_x = 310.0
    floating_bearing_bore = 20.0
    floating_bearing_od = 42.0
    floating_bearing_width = 12.0
    floating_axial_clearance = 0.2

    bracket_length = 120.0
    bracket_width = 100.0
    bracket_height = 40.0
    bracket_center_z = 96.0
    bracket_counterbore_diameter = 90.0
    bracket_counterbore_depth = 15.0
    carriage_hole_diameter = 9.0
    carriage_hole_depth = 20.0
    carriage_hole_x_spacing = 80.0
    carriage_hole_y_spacing = 60.0

    guide_rail_length = 650.0
    guide_rail_width = 25.0
    guide_rail_height = 23.0
    guide_rail_mount_z = 5.0
    rail_hole_diameter = 6.5
    rail_hole_depth = 12.0
    rail_hole_pitch = 150.0
    rail_straightness_note_mm = 0.005

    linear_block_length = 80.0
    linear_block_width = 48.0
    linear_block_height = 38.0
    linear_block_x_values = (-150.0, 150.0)
    linear_block_ball_diameter = 3.175
    linear_block_balls_per_circuit = 20

    bellows_x_min = -280.0
    bellows_x_max = 280.0
    bellows_outer_width = 100.0
    bellows_outer_height = 45.0
    bellows_pleat_count = 28
    bellows_pleat_depth = 8.0
    bellows_shaft_clearance = 5.0

    coupling_x = -360.0
    coupling_od = 40.0
    coupling_length = 55.0
    coupling_diaphragm_width = 10.0
    coupling_screw_bore = 25.0
    coupling_motor_bore = 19.0
    coupling_keyway_screw_width = 8.0
    coupling_keyway_screw_depth = 3.0
    coupling_keyway_motor_width = 6.0
    coupling_keyway_motor_depth = 2.5

    adapter_x = -395.0
    adapter_diameter = 130.0
    adapter_thickness = 18.0
    adapter_counterbore_diameter = 75.0
    adapter_counterbore_depth = 5.0
    adapter_motor_hole_diameter = 9.0
    adapter_motor_bcd = 110.0
    adapter_pilot_bore = 63.0
    adapter_pilot_depth = 3.0

    limit_bracket_size_x = 25.0
    limit_bracket_size_y = 20.0
    limit_bracket_size_z = 15.0
    limit_x_values = (-300.0, 300.0)
    limit_sensor_hole_diameter = 6.0
    detection_groove_width = 10.0
    detection_groove_depth = 5.0

    manifold_x = 50.0
    manifold_y = 50.0
    manifold_z = 42.0
    manifold_length = 30.0
    manifold_width = 20.0
    manifold_height = 15.0

    # Derived dimensions.
    base_origin = (-base_length / 2.0, -base_width / 2.0, 0.0)
    screw_x_min = -screw_total_length / 2.0
    screw_x_max = screw_total_length / 2.0
    screw_thread_length = screw_thread_x_max - screw_thread_x_min
    nut_x_min = -nut_length / 2.0
    nut_flange_x_min = -nut_flange_thickness / 2.0
    bellows_pitch = (bellows_x_max - bellows_x_min) / bellows_pleat_count
    rail_top_z = guide_rail_mount_z + guide_rail_height
    block_center_z = rail_top_z + linear_block_height / 2.0
    bracket_z_min = bracket_center_z - bracket_height / 2.0
    bracket_z_top = bracket_center_z + bracket_height / 2.0

    # Base housing, raised rail mounting lands, and mounting feet.
    base = b.box(base_length, base_width, base_height, origin=base_origin)
    _name_feature(b, base, "base_housing_680x120x85_bottom_Z0")
    rail_surfaces = []
    for y in rail_center_y_values:
        surface = b.box(
            base_length,
            rail_surface_width,
            rail_surface_height,
            origin=(-base_length / 2.0, y - rail_surface_width / 2.0, base_height),
        )
        _name_feature(
            b,
            surface,
            f"precision_rail_mount_surface_Y{int(y)}_flatness_{rail_surface_flatness_note_mm:.3f}mm",
        )
        rail_surfaces.append(surface)
        b.boolean_unite(base, surface)

    feet = []
    for x in foot_x_values:
        for y in foot_y_values:
            foot = b.box(
                foot_size,
                foot_size,
                foot_thickness,
                origin=(x - foot_size / 2.0, y - foot_size / 2.0, -foot_thickness),
            )
            _name_feature(b, foot, f"end_mounting_foot_X{int(x)}_Y{int(y)}")
            for hx in (x - foot_hole_spacing / 2.0, x + foot_hole_spacing / 2.0):
                _hole_z(b, foot, foot_hole_diameter, foot_thickness, hx, y, 0.0)
            feet.append(foot)
            b.boolean_unite(base, foot)

    # Precision ground ball screw, journal diameters, and symbolic thread starts.
    screw_core = b.cylinder(
        screw_nominal_diameter,
        screw_thread_length,
        origin=(screw_thread_x_min, screw_center_y, screw_center_z),
        axis=(1.0, 0.0, 0.0),
    )
    _name_feature(b, screw_core, "precision_ground_ball_screw_thread_section_D32_lead10_4_start")
    fixed_journal = b.cylinder(
        fixed_journal_diameter,
        fixed_journal_length,
        origin=(screw_x_min, screw_center_y, screw_center_z),
        axis=(1.0, 0.0, 0.0),
    )
    floating_journal = b.cylinder(
        floating_journal_diameter,
        floating_journal_length,
        origin=(screw_x_max - floating_journal_length, screw_center_y, screw_center_z),
        axis=(1.0, 0.0, 0.0),
    )
    b.boolean_unite(screw_core, fixed_journal)
    b.boolean_unite(screw_core, floating_journal)
    for start_index in range(screw_starts):
        helix = _helix_points_x(
            screw_thread_x_min,
            screw_lead,
            screw_thread_length / screw_lead,
            screw_nominal_diameter / 2.0 + screw_groove_radius * 0.35,
            90.0 * start_index,
            screw_center_y,
            screw_center_z,
            72,
        )
        _add_segmented_tube(
            b,
            helix,
            0.75,
            f"symbolic_gothic_arch_ball_groove_start_{start_index + 1}_contact_{int(screw_contact_angle_degrees)}deg",
            color_index=186,
        )

    # Ball nut body, flange, bolt pattern, lubrication ports, recirculation tubes, and balls.
    nut_body = b.cylinder(
        nut_outer_diameter,
        nut_length,
        origin=(nut_x_min, screw_center_y, screw_center_z),
        axis=(1.0, 0.0, 0.0),
    )
    _name_feature(b, nut_body, "ball_nut_body_OD58_L72_three_circuits")
    nut_bore = b.hole(
        screw_nominal_diameter + 2.0,
        nut_length + 4.0,
        position=(nut_x_min - 2.0, screw_center_y, screw_center_z),
        direction=(1.0, 0.0, 0.0),
    )
    b.boolean_subtract(nut_body, nut_bore)
    nut_flange = b.cylinder(
        nut_flange_diameter,
        nut_flange_thickness,
        origin=(nut_flange_x_min, screw_center_y, screw_center_z),
        axis=(1.0, 0.0, 0.0),
    )
    _name_feature(b, nut_flange, "ball_nut_flange_OD85_T12")
    b.boolean_unite(nut_body, nut_flange)
    _bolt_circle_holes_yz(
        b,
        nut_body,
        nut_flange_hole_count,
        nut_flange_hole_diameter,
        nut_flange_bcd,
        nut_flange_x_min - 1.0,
        screw_center_y,
        screw_center_z,
        nut_flange_thickness + 4.0,
        (1.0, 0.0, 0.0),
    )
    for angle in (0.0, 90.0):
        port_y = screw_center_y + (nut_outer_diameter / 2.0) * math.cos(math.radians(angle))
        port_z = screw_center_z + (nut_outer_diameter / 2.0) * math.sin(math.radians(angle))
        port = b.hole(5.0, 8.0, position=(0.0, port_y, port_z), direction=(0.0, -math.cos(math.radians(angle)), -math.sin(math.radians(angle))))
        b.boolean_subtract(nut_body, port)

    for circuit_index in range(ball_circuit_count):
        phase = circuit_index * 120.0
        tube_points = _helix_points_x(
            -recirc_tube_pitch * recirc_tube_turns / 2.0,
            recirc_tube_pitch,
            recirc_tube_turns,
            recirc_tube_radius,
            phase,
            screw_center_y,
            screw_center_z,
            32,
        )
        _add_segmented_tube(
            b,
            tube_points,
            recirc_tube_outer_diameter,
            f"recirculation_tube_circuit_{circuit_index + 1}_OD4_ID2p8",
            color_index=36,
        )
        for ball_index in range(balls_per_circuit):
            if ball_index % 2 != 0:
                continue
            fraction = ball_index / float(balls_per_circuit)
            angle = math.radians(phase + 360.0 * fraction * 2.8)
            x = -25.0 + 50.0 * fraction
            y = screw_center_y + 18.0 * math.cos(angle)
            z = screw_center_z + 18.0 * math.sin(angle)
            ball = b.cylinder(nut_ball_diameter, nut_ball_diameter, origin=(x - nut_ball_diameter / 2.0, y, z), axis=(1.0, 0.0, 0.0))
            _name_feature(b, ball, f"visible_ball_circuit_{circuit_index + 1}_{ball_index:02d}_of_{balls_per_circuit}")

    # Fixed and floating bearing blocks, bearings, and preload/clearance features.
    fixed_block = _box_centered(
        b,
        fixed_block_length,
        fixed_block_width,
        fixed_block_height,
        (fixed_block_x, 0.0, screw_center_z),
    )
    _name_feature(b, fixed_block, "fixed_bearing_block_80x80x55")
    _radial_hole_x(
        b,
        fixed_block,
        fixed_bearing_od + 2.0,
        fixed_block_length + 4.0,
        fixed_block_x - fixed_block_length / 2.0 - 2.0,
        0.0,
        screw_center_z,
        (1.0, 0.0, 0.0),
    )
    for offset in (-fixed_bearing_width / 2.0, fixed_bearing_width / 2.0):
        bearing = _annular_cylinder(
            b,
            fixed_bearing_od,
            fixed_bearing_bore,
            fixed_bearing_width,
            (fixed_block_x + offset - fixed_bearing_width / 2.0, 0.0, screw_center_z),
            (1.0, 0.0, 0.0),
        )
        _name_feature(b, bearing, f"duplex_angular_contact_bearing_15deg_X{fixed_block_x + offset:.1f}")
    shim = _annular_cylinder(
        b,
        preload_shim_od,
        preload_shim_id,
        preload_shim_thickness,
        (fixed_block_x - preload_shim_thickness / 2.0, 0.0, screw_center_z),
        (1.0, 0.0, 0.0),
    )
    _name_feature(b, shim, "preload_shim_ring_T0p05_between_fixed_bearings")

    floating_block = _box_centered(
        b,
        floating_block_length,
        floating_block_width,
        floating_block_height,
        (floating_block_x, 0.0, screw_center_z),
    )
    _name_feature(b, floating_block, "floating_bearing_block_70x70x45_axial_clearance_0p2")
    _radial_hole_x(
        b,
        floating_block,
        floating_bearing_od + 2.0,
        floating_block_length + 4.0,
        floating_block_x - floating_block_length / 2.0 - 2.0,
        0.0,
        screw_center_z,
        (1.0, 0.0, 0.0),
    )
    floating_bearing = _annular_cylinder(
        b,
        floating_bearing_od,
        floating_bearing_bore,
        floating_bearing_width,
        (floating_block_x - floating_bearing_width / 2.0, 0.0, screw_center_z),
        (1.0, 0.0, 0.0),
    )
    _name_feature(b, floating_bearing, "deep_groove_floating_bearing_clearance_0p2")
    clearance_marker = _box_centered(
        b,
        floating_axial_clearance,
        floating_bearing_od,
        floating_bearing_od,
        (floating_block_x + floating_bearing_width / 2.0 + floating_axial_clearance / 2.0, 0.0, screw_center_z),
    )
    _name_feature(b, clearance_marker, "floating_bearing_axial_clearance_0p2_marker")

    # Nut bracket with counterbore, flange bolt holes, top carriage holes, and detection grooves.
    bracket = _box_centered(b, bracket_length, bracket_width, bracket_height, (0.0, 0.0, bracket_center_z))
    _name_feature(b, bracket, "rigid_nut_bracket_120x100x40")
    _radial_hole_x(
        b,
        bracket,
        bracket_counterbore_diameter,
        bracket_counterbore_depth,
        -bracket_length / 2.0 - 1.0,
        0.0,
        screw_center_z,
        (1.0, 0.0, 0.0),
    )
    _bolt_circle_holes_yz(
        b,
        bracket,
        nut_flange_hole_count,
        nut_flange_hole_diameter,
        nut_flange_bcd,
        -bracket_length / 2.0 - 1.0,
        0.0,
        screw_center_z,
        bracket_length + 2.0,
        (1.0, 0.0, 0.0),
    )
    for x in (-carriage_hole_x_spacing / 2.0, carriage_hole_x_spacing / 2.0):
        for y in (-carriage_hole_y_spacing / 2.0, carriage_hole_y_spacing / 2.0):
            _hole_z(b, bracket, carriage_hole_diameter, carriage_hole_depth, x, y, bracket_z_top)
    for x in limit_x_values:
        groove = b.box(
            detection_groove_width,
            detection_groove_depth + 2.0,
            14.0,
            origin=(x - detection_groove_width / 2.0, bracket_width / 2.0 - detection_groove_depth, screw_center_z - 7.0),
        )
        b.boolean_subtract(bracket, groove)

    # Linear guide rails, rail holes, grinding marks, and linear ball blocks.
    rail_features = []
    for y in rail_center_y_values:
        rail = b.box(
            guide_rail_length,
            guide_rail_width,
            guide_rail_height,
            origin=(-guide_rail_length / 2.0, y - guide_rail_width / 2.0, guide_rail_mount_z),
        )
        _name_feature(b, rail, f"linear_guide_rail_Y{int(y)}_straightness_{rail_straightness_note_mm:.3f}mm_per_500")
        rail_features.append(rail)
        for index in range(4):
            x = -rail_hole_pitch * 1.5 + rail_hole_pitch * index
            _hole_z(b, rail, rail_hole_diameter, rail_hole_depth, x, y, guide_rail_mount_z + guide_rail_height)
        for mark_index in range(10):
            x = -guide_rail_length / 2.0 + 40.0 + mark_index * 60.0
            mark = b.box(20.0, 0.35, 0.35, origin=(x, y - guide_rail_width / 2.0 - 0.2, guide_rail_mount_z + guide_rail_height - 0.2))
            _name_feature(b, mark, f"rail_grinding_mark_{mark_index}_Y{int(y)}")
        for x in linear_block_x_values:
            block = _box_centered(b, linear_block_length, linear_block_width, linear_block_height, (x, y, block_center_z))
            _name_feature(b, block, f"recirculating_linear_ball_block_X{int(x)}_Y{int(y)}")
            for hx in (x - 19.0, x + 19.0):
                for hy in (y - 15.0, y + 15.0):
                    _hole_z(b, block, 5.0, 10.0, hx, hy, block_center_z + linear_block_height / 2.0)
            for row_y_offset in (-11.0, 11.0):
                for row_z_offset in (-7.0, 7.0):
                    for ball_index in range(0, linear_block_balls_per_circuit, 4):
                        bx = x - 30.0 + ball_index * 3.0
                        ball = b.cylinder(
                            linear_block_ball_diameter,
                            linear_block_ball_diameter,
                            origin=(bx - linear_block_ball_diameter / 2.0, y + row_y_offset, block_center_z + row_z_offset),
                            axis=(1.0, 0.0, 0.0),
                        )
                        _name_feature(b, ball, f"visible_linear_block_ball_X{int(x)}_Y{int(y)}_{ball_index}")

    # Bellows cover as alternating pleat boxes, split around the nut bracket.
    for side_name, x_start, x_end in (
        ("left", bellows_x_min, -bracket_length / 2.0),
        ("right", bracket_length / 2.0, bellows_x_max),
    ):
        span = x_end - x_start
        pleat_count = max(1, int(abs(span) / bellows_pitch))
        local_pitch = span / pleat_count
        for index in range(pleat_count):
            depth = bellows_pleat_depth if index % 2 == 0 else bellows_pleat_depth / 2.0
            pleat = b.box(
                abs(local_pitch) * 0.72,
                bellows_outer_width,
                bellows_outer_height,
                origin=(x_start + index * local_pitch + local_pitch * 0.14, -bellows_outer_width / 2.0, screw_center_z - bellows_shaft_clearance - bellows_outer_height / 2.0 + depth * 0.08),
            )
            _name_feature(b, pleat, f"bellows_{side_name}_pleat_{index:02d}_of_{bellows_pleat_count}")

    # Coupling with bores, keyways, diaphragm, and radial flexure slots.
    coupling = b.cylinder(
        coupling_od,
        coupling_length,
        origin=(coupling_x - coupling_length / 2.0, 0.0, screw_center_z),
        axis=(1.0, 0.0, 0.0),
    )
    _name_feature(b, coupling, "motor_coupling_OD40_L55_diaphragm_section")
    _radial_hole_x(b, coupling, coupling_screw_bore, coupling_length / 2.0 + 2.0, coupling_x - coupling_length / 2.0 - 1.0, 0.0, screw_center_z, (1.0, 0.0, 0.0))
    _radial_hole_x(b, coupling, coupling_motor_bore, coupling_length / 2.0 + 2.0, coupling_x + coupling_length / 2.0 + 1.0, 0.0, screw_center_z, (-1.0, 0.0, 0.0))
    for y, width, depth in ((0.0, coupling_keyway_screw_width, coupling_keyway_screw_depth), (0.0, coupling_keyway_motor_width, coupling_keyway_motor_depth)):
        keyway = b.box(coupling_length / 2.0, width, depth + 4.0, origin=(coupling_x - coupling_length / 2.0, y - width / 2.0, screw_center_z + coupling_screw_bore / 2.0 - depth))
        b.boolean_subtract(coupling, keyway)
    diaphragm_x = coupling_x - coupling_diaphragm_width / 2.0
    for index in range(6):
        angle = index * 60.0
        slot_y = 12.0 * math.cos(math.radians(angle))
        slot_z = screw_center_z + 12.0 * math.sin(math.radians(angle))
        cutter = b.cylinder(1.5, coupling_od + 4.0, origin=(coupling_x, slot_y, slot_z), axis=(0.0, math.cos(math.radians(angle)), math.sin(math.radians(angle))))
        b.boolean_subtract(coupling, cutter)
    diaphragm_mark = b.box(coupling_diaphragm_width, coupling_od + 2.0, 0.8, origin=(diaphragm_x, -coupling_od / 2.0 - 1.0, screw_center_z - 0.4))
    _name_feature(b, diaphragm_mark, "center_diaphragm_width_10_marker")

    # Motor adapter flange.
    adapter = b.cylinder(
        adapter_diameter,
        adapter_thickness,
        origin=(adapter_x - adapter_thickness / 2.0, 0.0, screw_center_z),
        axis=(1.0, 0.0, 0.0),
    )
    _name_feature(b, adapter, "motor_adapter_flange_D130_T18")
    _radial_hole_x(b, adapter, adapter_pilot_bore, adapter_pilot_depth, adapter_x - adapter_thickness / 2.0 - 1.0, 0.0, screw_center_z, (1.0, 0.0, 0.0))
    _radial_hole_x(b, adapter, adapter_counterbore_diameter, adapter_counterbore_depth, adapter_x + adapter_thickness / 2.0 + 1.0, 0.0, screw_center_z, (-1.0, 0.0, 0.0))
    _bolt_circle_holes_yz(
        b,
        adapter,
        4,
        adapter_motor_hole_diameter,
        adapter_motor_bcd,
        adapter_x - adapter_thickness / 2.0 - 1.0,
        0.0,
        screw_center_z,
        adapter_thickness + 4.0,
        (1.0, 0.0, 0.0),
    )

    # Limit switch brackets and proximity sensor holes.
    for x in limit_x_values:
        limit = b.box(
            limit_bracket_size_x,
            limit_bracket_size_y,
            limit_bracket_size_z,
            origin=(x - limit_bracket_size_x / 2.0, 50.0 - limit_bracket_size_y / 2.0, base_height),
        )
        _name_feature(b, limit, f"limit_switch_bracket_X{int(x)}_M8_sensor_hole")
        sensor = b.hole(limit_sensor_hole_diameter, limit_bracket_size_y + 4.0, position=(x, 50.0 + limit_bracket_size_y / 2.0 + 2.0, base_height + limit_bracket_size_z / 2.0), direction=(0.0, -1.0, 0.0))
        b.boolean_subtract(limit, sensor)

    # Grease fitting manifold with inlet, outlets, and symbolic drilled passages.
    manifold = _box_centered(b, manifold_length, manifold_width, manifold_height, (manifold_x, manifold_y, manifold_z))
    _name_feature(b, manifold, "grease_fitting_manifold_M10_inlet_four_M6_outlets")
    _hole_z(b, manifold, 8.5, manifold_height, manifold_x, manifold_y, manifold_z + manifold_height / 2.0)
    for angle in (0.0, 90.0, 180.0, 270.0):
        dy = math.cos(math.radians(angle))
        dz = math.sin(math.radians(angle))
        outlet = b.hole(5.0, 12.0, position=(manifold_x, manifold_y + dy * manifold_width / 2.0, manifold_z + dz * manifold_height / 2.0), direction=(0.0, dy, dz))
        b.boolean_subtract(manifold, outlet)
        _add_segmented_tube(
            b,
            [
                (manifold_x, manifold_y, manifold_z),
                (manifold_x + 25.0 * math.sin(math.radians(angle)), manifold_y + 22.0 * dy, manifold_z + 12.0 * dz),
            ],
            3.0,
            f"internal_drilled_lube_passage_{int(angle)}deg",
            color_index=211,
        )

    # Color groups for review in NX; skipped automatically if display APIs differ.
    _set_color(b, [base] + feet + rail_surfaces, 186)
    _set_color(b, [screw_core, fixed_journal, floating_journal], 36)
    _set_color(b, [nut_body, bracket], 72)
    _set_color(b, [fixed_block, floating_block], 146)
    _set_color(b, rail_features, 78)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
