# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              radial_engine_style_cylinder.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports radial_engine_style_cylinder.step.
# ----------------------------------------------------------------------------

import math
import os
import sys

# Ensure cadnx is importable on the NX machine.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Parameters, millimeters
    barrel_diameter = 36.0
    barrel_height = 70.0

    fin_count = 12
    fin_diameter = 62.0
    fin_thickness = 2.0
    fin_first_z = 10.0
    fin_pitch = 5.0
    fin_edge_fillet = 1.0

    flange_diameter = 70.0
    flange_thickness = 8.0
    flange_edge_fillet = 1.0
    mounting_hole_diameter = 5.0
    mounting_hole_count = 6
    mounting_bolt_circle_diameter = 56.0

    top_cap_diameter = 44.0
    top_cap_height = 8.0
    top_cap_z = 70.0

    boss_diameter = 12.0
    boss_length = 24.0
    boss_hole_diameter = 5.0
    boss_angle_deg = 35.0

    boss_angle = math.radians(boss_angle_deg)
    boss_axis = (math.cos(boss_angle), 0.0, math.sin(boss_angle))
    boss_start = (20.0, 0.0, top_cap_z + top_cap_height * 0.45)

    # Main positive geometry
    body = b.cylinder(barrel_diameter, barrel_height, origin=(0.0, 0.0, 0.0))

    flange = b.cylinder(flange_diameter, flange_thickness, origin=(0.0, 0.0, 0.0))
    b.fillet(b.get_all_edges(flange), flange_edge_fillet)
    b.boolean_unite(body, flange)

    for index in range(fin_count):
        fin_z = fin_first_z + index * fin_pitch
        fin = b.cylinder(fin_diameter, fin_thickness, origin=(0.0, 0.0, fin_z))
        b.fillet(b.get_all_edges(fin), fin_edge_fillet)
        b.boolean_unite(body, fin)

    top_cap = b.cylinder(top_cap_diameter, top_cap_height, origin=(0.0, 0.0, top_cap_z))
    b.boolean_unite(body, top_cap)

    boss = b.cylinder(boss_diameter, boss_length, origin=boss_start, axis=boss_axis)
    b.boolean_unite(body, boss)

    # Mounting holes through the bottom flange.
    bolt_circle_radius = mounting_bolt_circle_diameter / 2.0
    for index in range(mounting_hole_count):
        angle = 2.0 * math.pi * index / mounting_hole_count
        x = bolt_circle_radius * math.cos(angle)
        y = bolt_circle_radius * math.sin(angle)
        hole = b.hole(
            mounting_hole_diameter,
            flange_thickness + 4.0,
            position=(x, y, flange_thickness + 2.0),
            direction=(0.0, 0.0, -1.0),
        )
        b.boolean_subtract(body, hole)

    # Through-bore along the angled boss axis, oversized to cut fully through.
    hole_start = (
        boss_start[0] - 3.0 * boss_axis[0],
        boss_start[1] - 3.0 * boss_axis[1],
        boss_start[2] - 3.0 * boss_axis[2],
    )
    boss_bore = b.hole(
        boss_hole_diameter,
        boss_length + 8.0,
        position=hole_start,
        direction=boss_axis,
    )
    b.boolean_subtract(body, boss_bore)

    # Export
    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
