# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              robotic_arm_with_gripper.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports robotic_arm_with_gripper.step.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _xz_link_points(start, end, thickness):
    """Return XZ rectangle points around a centerline segment."""
    sx, sz = start
    ex, ez = end
    dx = ex - sx
    dz = ez - sz
    length = (dx * dx + dz * dz) ** 0.5
    if length <= 1e-9:
        raise ValueError("Link length must be nonzero.")
    nx = -dz / length
    nz = dx / length
    half = thickness / 2.0
    return [
        (sx + nx * half, sz + nz * half),
        (ex + nx * half, ez + nz * half),
        (ex - nx * half, ez - nz * half),
        (sx - nx * half, sz - nz * half),
    ]


def build(output_path: str = None):
    b = NXBuilder()

    # Base and column
    base_diameter = 100.0
    base_height = 20.0
    base_edge_fillet = 2.0
    base_mount_hole_diameter = 8.0
    bolt_circle_diameter = 70.0
    bolt_circle_radius = bolt_circle_diameter / 2.0

    column_diameter = 45.0
    column_height = 80.0

    # Joint cylinders, oriented along Y
    shoulder_center = (0.0, 0.0, 105.0)
    shoulder_diameter = 55.0
    shoulder_length = 60.0
    shoulder_hole_diameter = 18.0

    elbow_center = (85.0, 0.0, 190.0)
    elbow_diameter = 45.0
    elbow_length = 55.0
    elbow_hole_diameter = 16.0

    wrist_center = (180.0, 0.0, 165.0)
    wrist_diameter = 38.0
    wrist_length = 45.0
    wrist_hole_diameter = 12.0

    # Arm links as XZ slanted prisms extruded along Y
    link_fillet = 3.0
    link1_start = (8.0, 112.0)
    link1_end = (85.0, 190.0)
    link1_width_y = 35.0
    link1_thickness_xz = 25.0

    link2_start = (88.0, 188.0)
    link2_end = (180.0, 165.0)
    link2_width_y = 30.0
    link2_thickness_xz = 22.0

    # Wrist connector and gripper
    connector_x0 = 184.0
    connector_x1 = 219.0
    connector_width_y = 28.0
    connector_height_z = 25.0
    connector_z_center = wrist_center[2]

    palm_center_x = 225.0
    palm_width_y = 45.0
    palm_thickness_x = 12.0
    palm_height_z = 35.0
    palm_center_z = wrist_center[2]

    finger_length_x = 55.0
    finger_width_y = 8.0
    finger_height_z = 12.0
    finger_center_y = 15.0
    finger_center_z = palm_center_z

    pad_length_x = 10.0
    pad_width_y = 10.0
    pad_height_z = 16.0
    pad_fillet = 1.0

    through_overcut = 2.0

    # Primary solids
    base = b.cylinder(base_diameter, base_height, origin=(0.0, 0.0, 0.0), axis=(0.0, 0.0, 1.0))
    b.fillet(b.get_top_edges(base), base_edge_fillet)
    b.fillet(b.get_bottom_edges(base), base_edge_fillet)

    for angle_deg in (45.0, 135.0, 225.0, 315.0):
        angle_rad = math.radians(angle_deg)
        hx = bolt_circle_radius * math.cos(angle_rad)
        hy = bolt_circle_radius * math.sin(angle_rad)
        hole = b.hole(
            base_mount_hole_diameter,
            base_height + through_overcut,
            position=(hx, hy, base_height + 1.0),
            direction=(0.0, 0.0, -1.0),
        )
        base = b.boolean_subtract(base, hole)

    column = b.cylinder(column_diameter, column_height, origin=(0.0, 0.0, base_height), axis=(0.0, 0.0, 1.0))
    body = b.boolean_unite(base, column)

    shoulder = b.cylinder(
        shoulder_diameter,
        shoulder_length,
        origin=(shoulder_center[0], -shoulder_length / 2.0, shoulder_center[2]),
        axis=(0.0, 1.0, 0.0),
    )
    shoulder_hole = b.hole(
        shoulder_hole_diameter,
        shoulder_length + through_overcut,
        position=(shoulder_center[0], -shoulder_length / 2.0 - 1.0, shoulder_center[2]),
        direction=(0.0, 1.0, 0.0),
    )
    shoulder = b.boolean_subtract(shoulder, shoulder_hole)
    body = b.boolean_unite(body, shoulder)

    link1 = b.polygon_prism_on_plane(
        _xz_link_points(link1_start, link1_end, link1_thickness_xz),
        link1_width_y,
        origin=(0.0, -link1_width_y / 2.0, 0.0),
        u_axis=(1.0, 0.0, 0.0),
        v_axis=(0.0, 0.0, 1.0),
        extrude_axis=(0.0, 1.0, 0.0),
    )
    b.fillet(b.get_edges_by_axis(link1, axis=(0.0, 1.0, 0.0)), link_fillet)
    body = b.boolean_unite(body, link1)

    elbow = b.cylinder(
        elbow_diameter,
        elbow_length,
        origin=(elbow_center[0], -elbow_length / 2.0, elbow_center[2]),
        axis=(0.0, 1.0, 0.0),
    )
    elbow_hole = b.hole(
        elbow_hole_diameter,
        elbow_length + through_overcut,
        position=(elbow_center[0], -elbow_length / 2.0 - 1.0, elbow_center[2]),
        direction=(0.0, 1.0, 0.0),
    )
    elbow = b.boolean_subtract(elbow, elbow_hole)
    body = b.boolean_unite(body, elbow)

    link2 = b.polygon_prism_on_plane(
        _xz_link_points(link2_start, link2_end, link2_thickness_xz),
        link2_width_y,
        origin=(0.0, -link2_width_y / 2.0, 0.0),
        u_axis=(1.0, 0.0, 0.0),
        v_axis=(0.0, 0.0, 1.0),
        extrude_axis=(0.0, 1.0, 0.0),
    )
    b.fillet(b.get_edges_by_axis(link2, axis=(0.0, 1.0, 0.0)), link_fillet)
    body = b.boolean_unite(body, link2)

    wrist = b.cylinder(
        wrist_diameter,
        wrist_length,
        origin=(wrist_center[0], -wrist_length / 2.0, wrist_center[2]),
        axis=(0.0, 1.0, 0.0),
    )
    wrist_hole = b.hole(
        wrist_hole_diameter,
        wrist_length + through_overcut,
        position=(wrist_center[0], -wrist_length / 2.0 - 1.0, wrist_center[2]),
        direction=(0.0, 1.0, 0.0),
    )
    wrist = b.boolean_subtract(wrist, wrist_hole)
    body = b.boolean_unite(body, wrist)

    connector = b.rounded_box(
        connector_x1 - connector_x0,
        connector_width_y,
        connector_height_z,
        radius=link_fillet,
        origin=(connector_x0, -connector_width_y / 2.0, connector_z_center - connector_height_z / 2.0),
    )
    body = b.boolean_unite(body, connector)

    palm_x0 = palm_center_x - palm_thickness_x / 2.0
    palm = b.rounded_box(
        palm_thickness_x,
        palm_width_y,
        palm_height_z,
        radius=link_fillet,
        origin=(palm_x0, -palm_width_y / 2.0, palm_center_z - palm_height_z / 2.0),
    )
    body = b.boolean_unite(body, palm)

    finger_x0 = palm_x0 + palm_thickness_x
    finger_z0 = finger_center_z - finger_height_z / 2.0
    pad_x0 = finger_x0 + finger_length_x - pad_length_x
    pad_z0 = finger_center_z - pad_height_z / 2.0

    for y_center in (finger_center_y, -finger_center_y):
        finger = b.rounded_box(
            finger_length_x,
            finger_width_y,
            finger_height_z,
            radius=link_fillet,
            origin=(finger_x0, y_center - finger_width_y / 2.0, finger_z0),
        )
        body = b.boolean_unite(body, finger)

        pad = b.rounded_box(
            pad_length_x,
            pad_width_y,
            pad_height_z,
            radius=pad_fillet,
            origin=(pad_x0, y_center - pad_width_y / 2.0, pad_z0),
            vertical_only=False,
        )
        body = b.boolean_unite(body, pad)

    # Export
    if output_path is None:
        output_path = os.path.join(_SCRIPT_DIR, "robotic_arm_with_gripper.step")
    b.export_step(output_path)


def main():
    default_output = os.path.join(_SCRIPT_DIR, "robotic_arm_with_gripper.step")
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
