# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              naca_6512_compressor_fan_blade.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to the journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _unit(vector):
    length = math.sqrt(sum(component * component for component in vector))
    if length <= 0.0:
        raise ValueError("zero-length vector")
    return tuple(component / length for component in vector)


def _cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def _naca_6512_section(chord, point_count=19):
    """Return a faceted NACA 6512 section with chord along local U and thickness in local V."""
    max_camber = 0.06
    camber_position = 0.5
    thickness = 0.12
    xs = [0.5 * (1.0 - math.cos(math.pi * index / (point_count - 1))) for index in range(point_count)]
    upper = []
    lower = []
    for x in xs:
        yt = 5.0 * thickness * (
            0.2969 * math.sqrt(max(x, 0.0))
            - 0.1260 * x
            - 0.3516 * x * x
            + 0.2843 * x * x * x
            - 0.1015 * x * x * x * x
        )
        if x < camber_position:
            yc = max_camber / (camber_position * camber_position) * (2.0 * camber_position * x - x * x)
            dyc = 2.0 * max_camber / (camber_position * camber_position) * (camber_position - x)
        else:
            yc = max_camber / ((1.0 - camber_position) ** 2) * (
                (1.0 - 2.0 * camber_position) + 2.0 * camber_position * x - x * x
            )
            dyc = 2.0 * max_camber / ((1.0 - camber_position) ** 2) * (camber_position - x)
        theta = math.atan(dyc)
        xu = x - yt * math.sin(theta)
        yu = yc + yt * math.cos(theta)
        xl = x + yt * math.sin(theta)
        yl = yc - yt * math.cos(theta)
        upper.append(((xu - 0.25) * chord, yu * chord))
        lower.append(((xl - 0.25) * chord, yl * chord))
    return upper + list(reversed(lower[1:-1]))


def _station_frame(twist_degrees):
    angle = math.radians(twist_degrees)
    chord_axis = (math.cos(angle), math.sin(angle), 0.0)
    span_axis = (0.0, 0.0, 1.0)
    thick_axis = _unit(_cross(span_axis, chord_axis))
    return chord_axis, thick_axis, span_axis


def _add_bar(b, target, start, end, diameter, name=None):
    sx, sy, sz = start
    ex, ey, ez = end
    axis = (ex - sx, ey - sy, ez - sz)
    length = math.sqrt(sum(component * component for component in axis))
    if length <= 0.0:
        return None
    feature = b.cylinder(diameter, length, origin=start, axis=axis)
    b.boolean_unite(target, feature)
    return feature


def _body_count(part):
    try:
        return len(list(part.Bodies))
    except Exception:
        try:
            return len(part.Bodies.ToArray())
        except Exception:
            return -1


def _fit_work_view(part):
    try:
        part.ModelingViews.WorkView.Fit()
    except Exception as exc:
        print(f"WARNING: could not fit work view: {exc}")


def build(output_path: str = None):
    b = NXBuilder()
    print(f"NX work part: {getattr(b.part, 'FullPath', '') or getattr(b.part, 'Name', '<unnamed>')}")

    # Independent parameters: printable conceptual compressor/fan blade.
    span = 118.0
    root_chord = 42.0
    tip_chord = 24.0
    naca_thickness_ratio = 0.12
    max_thickness = root_chord * naca_thickness_ratio
    root_twist_degrees = 34.0
    tip_twist_degrees = 10.0
    station_count = 13
    station_overlap = 1.2
    platform_length = 58.0
    platform_width = 30.0
    platform_height = 8.0
    platform_corner_radius = 3.0
    leading_edge_marker_diameter = 1.8
    trailing_edge_marker_diameter = 1.2
    pmi_bar_diameter = 0.9
    label_plate_height = 1.0
    label_plate_width = 5.0
    label_plate_thickness = 0.7
    feature_overlap = 0.4
    chamfer_offset = 0.7

    # Derived parameters and basic validity checks.
    blade_start_z = platform_height - feature_overlap
    station_pitch = span / (station_count - 1)
    station_depth = station_pitch + station_overlap
    b.require_positive(
        span=span,
        root_chord=root_chord,
        tip_chord=tip_chord,
        max_thickness=max_thickness,
        station_depth=station_depth,
        platform_height=platform_height,
    )
    b.require_feature_budget(boolean_operations=38, patterned_features=station_count + 18)

    # Root platform: broad printable foot for bed adhesion and orientation reference.
    body = b.rounded_box(
        platform_length,
        platform_width,
        platform_height,
        platform_corner_radius,
        origin=(-platform_length / 2.0, -platform_width / 2.0, 0.0),
    )
    b.chamfer(b.get_top_edges(body), chamfer_offset)

    # NACA 6512 blade body, approximated by overlapped faceted stations.
    leading_edge_points = []
    trailing_edge_points = []
    for index in range(station_count):
        fraction = index / (station_count - 1)
        chord = root_chord + (tip_chord - root_chord) * fraction
        twist = root_twist_degrees + (tip_twist_degrees - root_twist_degrees) * fraction
        z_center = blade_start_z + fraction * span
        chord_axis, thick_axis, span_axis = _station_frame(twist)
        section = _naca_6512_section(chord)
        station = b.polygon_prism_on_plane(
            section,
            station_depth,
            origin=(0.0, 0.0, z_center - station_depth / 2.0),
            u_axis=chord_axis,
            v_axis=thick_axis,
            extrude_axis=span_axis,
        )
        b.boolean_unite(body, station)
        leading_edge_points.append((0.75 * chord * chord_axis[0], 0.75 * chord * chord_axis[1], z_center))
        trailing_edge_points.append((-0.25 * chord * chord_axis[0], -0.25 * chord * chord_axis[1], z_center))

    # Rounded leading/trailing edge cues as small continuous overlapping cylinders.
    for points, diameter in (
        (leading_edge_points, leading_edge_marker_diameter),
        (trailing_edge_points, trailing_edge_marker_diameter),
    ):
        for start, end in zip(points[:-1], points[1:]):
            _add_bar(b, body, start, end, diameter)

    # PMI measurement bars: span, root chord, tip chord, max thickness, and twist reference.
    x_offset = platform_length / 2.0 + 8.0
    y_offset = platform_width / 2.0 + 7.0
    _add_bar(b, body, (x_offset, 0.0, platform_height), (x_offset, 0.0, platform_height + span), pmi_bar_diameter)
    _add_bar(b, body, (-root_chord * 0.25, -y_offset, platform_height + 3.0), (root_chord * 0.75, -y_offset, platform_height + 3.0), pmi_bar_diameter)
    tip_twist = math.radians(tip_twist_degrees)
    tip_axis = (math.cos(tip_twist), math.sin(tip_twist), 0.0)
    tip_z = platform_height + span
    _add_bar(
        b,
        body,
        (-tip_chord * 0.25 * tip_axis[0], -y_offset, tip_z),
        (tip_chord * 0.75 * tip_axis[0], -y_offset, tip_z),
        pmi_bar_diameter,
    )
    _add_bar(b, body, (-7.0, y_offset, platform_height + 6.0), (-7.0, y_offset + max_thickness, platform_height + 6.0), pmi_bar_diameter)
    _add_bar(b, body, (0.0, y_offset + 9.0, platform_height + 12.0), (21.0, y_offset + 9.0, platform_height + 12.0), pmi_bar_diameter)
    root_axis = _station_frame(root_twist_degrees)[0]
    _add_bar(
        b,
        body,
        (0.0, y_offset + 9.0, platform_height + 12.0),
        (21.0 * root_axis[0], y_offset + 9.0 + 21.0 * root_axis[1], platform_height + 12.0),
        pmi_bar_diameter,
    )

    # Raised leader-note plaques. Names in code carry the PMI text when NX text helpers are unavailable.
    label_specs = [
        ("AIRFOIL_NACA_6512", (-37.0, -25.0, platform_height + 8.0), 54.0),
        ("PRINT_ORIENTATION_PLATFORM_DOWN_Z_UP", (-39.0, 25.0, platform_height + 3.0), 72.0),
        ("SPAN_118_ROOT_42_TIP_24_THK_5_04_TWIST_34_TO_10_DEG", (35.0, 0.0, platform_height + 40.0), 88.0),
    ]
    for _label, center, length in label_specs:
        plaque = b.oriented_box(
            length,
            label_plate_width,
            label_plate_thickness,
            center=center,
            u_axis=(1, 0, 0),
            v_axis=(0, 1, 0),
            w_axis=(0, 0, 1),
        )
        b.boolean_unite(body, plaque)

    # Short leader lines from plaques to blade/platform references.
    _add_bar(b, body, (-10.0, -22.0, platform_height + 8.0), (-18.0, -4.0, platform_height + 34.0), pmi_bar_diameter)
    _add_bar(b, body, (-12.0, 22.0, platform_height + 3.0), (-12.0, 10.0, platform_height + 0.5), pmi_bar_diameter)
    _add_bar(b, body, (35.0, 0.0, platform_height + 40.0), (17.0, 2.5, platform_height + 72.0), pmi_bar_diameter)

    print(f"Body count before STEP export: {_body_count(b.part)}")
    _fit_work_view(b.part)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)
    print(f"Completed NACA 6512 compressor fan blade journal: {output_path}")


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    build(default_output)


if __name__ == "__main__":
    main()
