# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              servo_motor_mounting_bracket_assembly.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import os
import sys


_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    base_length = 100.0
    base_width = 70.0
    base_thickness = 10.0
    motor_plate_length_x = 70.0
    motor_plate_thickness_y = 12.0
    motor_plate_height_z = 80.0
    pilot_bore_diameter = 38.0
    pilot_center_z = 48.0
    motor_hole_diameter = 5.5
    motor_hole_square_pitch = 50.0
    base_hole_diameter = 6.6
    base_hole_x_offset = 35.0
    base_hole_y_offset = 24.0
    rib_thickness_x = 8.0
    rib_projection_y = 36.0
    rib_height_z = 46.0
    clamp_plate_length_x = 70.0
    clamp_plate_thickness_y = 8.0
    clamp_plate_height_z = 50.0
    clamp_hole_diameter = 5.5
    clamp_hole_x_offset = 20.0
    cable_slot_length_x = 28.0
    cable_slot_width_z = 9.0
    cable_slot_depth_y = 2.0
    outer_fillet_radius = 3.0
    rib_transition_fillet_radius = 2.0
    hole_chamfer_offset = 0.6

    # Derived layout and boolean robustness parameters.
    feature_overlap = 0.5
    cutter_overlap = 1.0
    through_overcut = 2.0
    base_x0 = -base_length / 2.0
    base_y0 = -base_width / 2.0
    base_z0 = 0.0
    base_top_z = base_z0 + base_thickness
    plate_x0 = -motor_plate_length_x / 2.0
    plate_y0 = base_width / 2.0 - motor_plate_thickness_y
    plate_z0 = base_top_z - feature_overlap
    plate_front_y = plate_y0
    plate_rear_y = plate_y0 + motor_plate_thickness_y
    plate_hole_depth = motor_plate_thickness_y + 2.0 * through_overcut
    plate_hole_y_start = plate_front_y - through_overcut
    base_hole_depth = base_thickness + 2.0 * through_overcut
    base_hole_z_start = base_top_z + through_overcut
    clamp_z0 = pilot_center_z - clamp_plate_height_z / 2.0
    clamp_y0 = plate_rear_y + feature_overlap
    clamp_hole_depth = clamp_plate_thickness_y + 2.0 * through_overcut
    clamp_hole_y_start = clamp_y0 + clamp_plate_thickness_y + through_overcut
    motor_offset = motor_hole_square_pitch / 2.0
    rib_centers_x = (-22.0, 22.0)
    rib_x_start_offset = -rib_thickness_x / 2.0

    b.require_positive(
        base_length=base_length,
        base_width=base_width,
        base_thickness=base_thickness,
        motor_plate_height_z=motor_plate_height_z,
        pilot_bore_diameter=pilot_bore_diameter,
        rib_thickness_x=rib_thickness_x,
        clamp_plate_height_z=clamp_plate_height_z,
    )
    b.require_min_wall(motor_plate_length_x, pilot_bore_diameter, min_wall=8.0, label="motor pilot side wall")
    b.require_edge_distance(base_length / 2.0 - base_hole_x_offset, base_hole_diameter, min_ratio=1.0, label="base X mounting holes")
    b.require_edge_distance(base_width / 2.0 - base_hole_y_offset, base_hole_diameter, min_ratio=1.0, label="base Y mounting holes")
    b.require_feature_budget(boolean_operations=28, micro_holes=10, patterned_features=10)

    # Primary aligned solids. Bodies are intentionally not united, producing
    # separate but registered solids in the exported STEP.
    base = b.box(base_length, base_width, base_thickness, origin=(base_x0, base_y0, base_z0))
    motor_plate = b.box(
        motor_plate_length_x,
        motor_plate_thickness_y,
        motor_plate_height_z + feature_overlap,
        origin=(plate_x0, plate_y0, plate_z0),
    )
    clamp_plate = b.box(
        clamp_plate_length_x,
        clamp_plate_thickness_y,
        clamp_plate_height_z,
        origin=(-clamp_plate_length_x / 2.0, clamp_y0, clamp_z0),
    )

    ribs = []
    rib_points_yz = [
        (0.0, 0.0),
        (rib_projection_y, 0.0),
        (0.0, rib_height_z),
    ]
    for rib_center_x in rib_centers_x:
        rib = b.polygon_prism_on_plane(
            rib_points_yz,
            rib_thickness_x,
            origin=(rib_center_x + rib_x_start_offset, plate_front_y + feature_overlap, base_top_z - feature_overlap),
            u_axis=(0, -1, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(1, 0, 0),
        )
        ribs.append(rib)

    # Base mounting holes through Z.
    for hole_x in (-base_hole_x_offset, base_hole_x_offset):
        for hole_y in (-base_hole_y_offset, base_hole_y_offset):
            cutter = b.hole(
                base_hole_diameter,
                base_hole_depth,
                position=(hole_x, hole_y, base_hole_z_start),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(base, cutter)

    # Motor pilot and four M5 clearance holes through the vertical plate.
    pilot = b.hole(
        pilot_bore_diameter,
        plate_hole_depth,
        position=(0.0, plate_hole_y_start, pilot_center_z),
        direction=(0, 1, 0),
    )
    b.boolean_subtract(motor_plate, pilot)
    for hole_x in (-motor_offset, motor_offset):
        for hole_z in (pilot_center_z - motor_offset, pilot_center_z + motor_offset):
            cutter = b.hole(
                motor_hole_diameter,
                plate_hole_depth,
                position=(hole_x, plate_hole_y_start, hole_z),
                direction=(0, 1, 0),
            )
            b.boolean_subtract(motor_plate, cutter)

    # Rear clamp plate: two M5 clearance holes and shallow cable relief.
    for hole_x in (-clamp_hole_x_offset, clamp_hole_x_offset):
        cutter = b.hole(
            clamp_hole_diameter,
            clamp_hole_depth,
            position=(hole_x, clamp_hole_y_start, pilot_center_z),
            direction=(0, -1, 0),
        )
        b.boolean_subtract(clamp_plate, cutter)
    b.slot_cut(
        clamp_plate,
        cable_slot_length_x,
        cable_slot_width_z,
        cable_slot_depth_y + cutter_overlap,
        center=(0.0, clamp_y0 - cutter_overlap, pilot_center_z - 15.0),
        axis=(1, 0, 0),
        direction=(0, 1, 0),
    )

    # Industrial edge treatment. Localized selectors avoid large fragile blends.
    b.fillet(
        b.get_edges_in_box(
            base,
            min_xyz=(base_x0 - 0.1, base_y0 - 0.1, base_z0 - 0.1),
            max_xyz=(-base_x0 + 0.1, -base_y0 + 0.1, base_top_z + 0.1),
        ),
        outer_fillet_radius,
    )
    b.fillet(
        b.get_edges_in_box(
            motor_plate,
            min_xyz=(plate_x0 - 0.1, plate_y0 - 0.1, plate_z0 - 0.1),
            max_xyz=(-plate_x0 + 0.1, plate_rear_y + 0.1, plate_z0 + motor_plate_height_z + 0.2),
        ),
        outer_fillet_radius,
    )
    for rib in ribs:
        b.fillet(
            b.get_edges_in_box(
                rib,
                min_xyz=(-50.0, plate_front_y - rib_projection_y - 1.0, base_top_z - 1.0),
                max_xyz=(50.0, plate_front_y + 1.0, base_top_z + rib_height_z + 1.0),
            ),
            rib_transition_fillet_radius,
        )
    b.fillet(
        b.get_edges_in_box(
            clamp_plate,
            min_xyz=(-clamp_plate_length_x / 2.0 - 0.1, clamp_y0 - 0.1, clamp_z0 - 0.1),
            max_xyz=(clamp_plate_length_x / 2.0 + 0.1, clamp_y0 + clamp_plate_thickness_y + 0.1, clamp_z0 + clamp_plate_height_z + 0.1),
        ),
        outer_fillet_radius,
    )

    # Hole-opening chamfers selected around each opening center.
    for hole_x in (-base_hole_x_offset, base_hole_x_offset):
        for hole_y in (-base_hole_y_offset, base_hole_y_offset):
            b.chamfer(b.get_edges_near(base, point=(hole_x, hole_y, base_top_z), tolerance=4.0), hole_chamfer_offset)
            b.chamfer(b.get_edges_near(base, point=(hole_x, hole_y, base_z0), tolerance=4.0), hole_chamfer_offset)
    for hole_x, hole_z, tol in [(0.0, pilot_center_z, 20.0)] + [
        (x, z, 4.0)
        for x in (-motor_offset, motor_offset)
        for z in (pilot_center_z - motor_offset, pilot_center_z + motor_offset)
    ]:
        b.chamfer(b.get_edges_near(motor_plate, point=(hole_x, plate_front_y, hole_z), tolerance=tol), hole_chamfer_offset)
        b.chamfer(b.get_edges_near(motor_plate, point=(hole_x, plate_rear_y, hole_z), tolerance=tol), hole_chamfer_offset)
    for hole_x in (-clamp_hole_x_offset, clamp_hole_x_offset):
        b.chamfer(b.get_edges_near(clamp_plate, point=(hole_x, clamp_y0, pilot_center_z), tolerance=4.0), hole_chamfer_offset)
        b.chamfer(
            b.get_edges_near(clamp_plate, point=(hole_x, clamp_y0 + clamp_plate_thickness_y, pilot_center_z), tolerance=4.0),
            hole_chamfer_offset,
        )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
