# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              naca_0012_axial_turbine_stator_vane.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to the journal.
#Sorry, your request failed. Please try again.

Client Request Id: d4a6decc-0883-49d7-b90b-bea9ab9faddb

Reason: Rate limit exceeded

{"code":"upstream_provider_rate_limit","message":"{"error":{"code":"model_not_found","message":"No available channel for model Gemini 2.5 Pro under group 按量计费 (distributor) (request id: 202607130802023419407348268d9d6mOyNzzIb)","type":"new_api_error"}}"}: ChatRateLimited: Rate limit exceeded

{"code":"upstream_provider_rate_limit","message":"{"error":{"code":"model_not_found","message":"No available channel for model Gemini 2.5 Pro under group 按量计费 (distributor) (request id: 202607130802023419407348268d9d6mOyNzzIb)","type":"new_api_error"}}"} at qG._provideLanguageModelResponse (d:\software\Microsoft VS Code\4fe60c8b1c\resources\app\extensions\copilot\dist\extension.js:1690:14303) at process.processTicksAndRejections (node:internal/process/task_queues:104:5) at async qG.provideLanguageModelResponse (d:\software\Microsoft VS Code\4fe60c8b1c\resources\app\extensions\copilot\dist\extension.js:1690:15327)
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _naca_0012_section(chord_length, point_count=25):
    """Return a closed faceted NACA 0012 section in local UV coordinates."""
    thickness_ratio = 0.12
    xs = [0.5 * (1.0 - math.cos(math.pi * index / (point_count - 1))) for index in range(point_count)]
    upper = []
    lower = []
    for x in xs:
        yt = 5.0 * thickness_ratio * (
            0.2969 * math.sqrt(max(x, 0.0))
            - 0.1260 * x
            - 0.3516 * x * x
            + 0.2843 * x * x * x
            - 0.1015 * x * x * x * x
        )
        upper.append(((x - 0.5) * chord_length, yt * chord_length))
        lower.append(((x - 0.5) * chord_length, -yt * chord_length))
    return upper + list(reversed(lower[1:-1]))


def _airfoil_frame(stagger_degrees):
    angle = math.radians(stagger_degrees)
    chord_axis = (math.cos(angle), math.sin(angle), 0.0)
    thickness_axis = (-math.sin(angle), math.cos(angle), 0.0)
    span_axis = (0.0, 0.0, 1.0)
    return chord_axis, thickness_axis, span_axis


def _add_bar(b, target, start, end, diameter):
    sx, sy, sz = start
    ex, ey, ez = end
    axis = (ex - sx, ey - sy, ez - sz)
    length = math.sqrt(sum(component * component for component in axis))
    if length <= 0.0:
        return None
    feature = b.cylinder(diameter, length, origin=start, axis=axis)
    b.boolean_unite(target, feature)
    return feature


def build(output_path: str = None):
    b = NXBuilder()

    # Independent parameters: compact 3D-printable axial turbine stator vane.
    vane_height = 92.0
    chord_length = 34.0
    stagger_angle_degrees = 18.0
    tab_thickness = 7.0
    tab_length = 48.0
    tab_width = 22.0
    tab_corner_radius = 2.5
    tab_mount_hole_diameter = 4.5
    tab_hole_spacing = 30.0
    airfoil_thickness_ratio = 0.12
    max_airfoil_thickness = chord_length * airfoil_thickness_ratio
    leading_edge_marker_diameter = 1.5
    trailing_edge_marker_diameter = 1.1
    pmi_bar_diameter = 0.8
    label_plate_width = 5.0
    label_plate_thickness = 0.6
    feature_overlap = 0.5
    through_overcut = 2.0
    chamfer_offset = 0.6

    # Derived parameters and guards.
    hub_tab_z = 0.0
    vane_start_z = tab_thickness - feature_overlap
    shroud_tab_z = tab_thickness + vane_height - feature_overlap
    total_height = tab_thickness * 2.0 + vane_height
    chord_axis, thickness_axis, span_axis = _airfoil_frame(stagger_angle_degrees)
    b.require_positive(
        vane_height=vane_height,
        chord_length=chord_length,
        tab_thickness=tab_thickness,
        tab_length=tab_length,
        tab_width=tab_width,
        max_airfoil_thickness=max_airfoil_thickness,
    )
    b.require_min_wall(tab_width, tab_mount_hole_diameter, min_wall=4.0, label="tab mounting hole")
    b.require_edge_distance((tab_length - tab_hole_spacing) / 2.0, tab_mount_hole_diameter, min_ratio=1.0, label="tab mounting hole")
    b.require_feature_budget(boolean_operations=34, patterned_features=18)

    # Hub-side mounting tab.
    body = b.rounded_box(
        tab_length,
        tab_width,
        tab_thickness,
        tab_corner_radius,
        origin=(-tab_length / 2.0, -tab_width / 2.0, hub_tab_z),
    )
    b.chamfer(b.get_top_edges(body), chamfer_offset)

    # Shroud-side mounting tab.
    shroud = b.rounded_box(
        tab_length,
        tab_width,
        tab_thickness,
        tab_corner_radius,
        origin=(-tab_length / 2.0, -tab_width / 2.0, shroud_tab_z),
    )
    b.boolean_unite(body, shroud)

    # Mounting holes through both tabs.
    for z_top, direction in ((tab_thickness + through_overcut / 2.0, (0, 0, -1)), (total_height + through_overcut / 2.0, (0, 0, -1))):
        for x in (-tab_hole_spacing / 2.0, tab_hole_spacing / 2.0):
            cutter = b.hole(
                tab_mount_hole_diameter,
                tab_thickness + through_overcut,
                position=(x, 0.0, z_top),
                direction=direction,
            )
            b.boolean_subtract(body, cutter)

    # Constant-thickness NACA 0012 vane body, extruded straight between tabs.
    airfoil_points = _naca_0012_section(chord_length)
    vane = b.polygon_prism_on_plane(
        airfoil_points,
        vane_height + 2.0 * feature_overlap,
        origin=(0.0, 0.0, vane_start_z),
        u_axis=chord_axis,
        v_axis=thickness_axis,
        extrude_axis=span_axis,
    )
    b.boolean_unite(body, vane)

    # Rounded-edge cues: small rods along leading and trailing edges.
    leading_edge_root = (0.5 * chord_length * chord_axis[0], 0.5 * chord_length * chord_axis[1], tab_thickness)
    leading_edge_tip = (0.5 * chord_length * chord_axis[0], 0.5 * chord_length * chord_axis[1], tab_thickness + vane_height)
    trailing_edge_root = (-0.5 * chord_length * chord_axis[0], -0.5 * chord_length * chord_axis[1], tab_thickness)
    trailing_edge_tip = (-0.5 * chord_length * chord_axis[0], -0.5 * chord_length * chord_axis[1], tab_thickness + vane_height)
    _add_bar(b, body, leading_edge_root, leading_edge_tip, leading_edge_marker_diameter)
    _add_bar(b, body, trailing_edge_root, trailing_edge_tip, trailing_edge_marker_diameter)

    # PMI-style physical measurement bars for vane height, chord, stagger, and tab thickness.
    pmi_x = tab_length / 2.0 + 8.0
    pmi_y = tab_width / 2.0 + 8.0
    _add_bar(b, body, (pmi_x, 0.0, tab_thickness), (pmi_x, 0.0, tab_thickness + vane_height), pmi_bar_diameter)
    _add_bar(
        b,
        body,
        (-0.5 * chord_length * chord_axis[0], -pmi_y - 1.0, tab_thickness + vane_height * 0.52),
        (0.5 * chord_length * chord_axis[0], -pmi_y - 1.0, tab_thickness + vane_height * 0.52),
        pmi_bar_diameter,
    )
    _add_bar(b, body, (-pmi_x, -tab_width / 2.0, 0.0), (-pmi_x, -tab_width / 2.0, tab_thickness), pmi_bar_diameter)
    _add_bar(b, body, (0.0, pmi_y, tab_thickness + 16.0), (20.0, pmi_y, tab_thickness + 16.0), pmi_bar_diameter)
    _add_bar(
        b,
        body,
        (0.0, pmi_y, tab_thickness + 16.0),
        (20.0 * chord_axis[0], pmi_y + 20.0 * chord_axis[1], tab_thickness + 16.0),
        pmi_bar_diameter,
    )

    # Leader lines and plaques. Plaque variable names carry intended PMI labels.
    leader_targets = {
        "LEADING_EDGE": leading_edge_tip,
        "TRAILING_EDGE": trailing_edge_tip,
        "HUB_SIDE": (0.0, 0.0, tab_thickness),
        "SHROUD_SIDE": (0.0, 0.0, tab_thickness + vane_height),
    }
    label_specs = [
        ("PMI_NACA_0012_LEADING_EDGE", (36.0, -24.0, tab_thickness + vane_height * 0.82), leader_targets["LEADING_EDGE"], 46.0),
        ("PMI_TRAILING_EDGE", (-36.0, -24.0, tab_thickness + vane_height * 0.70), leader_targets["TRAILING_EDGE"], 34.0),
        ("PMI_HUB_SIDE_TAB", (-35.0, 24.0, tab_thickness + 6.0), leader_targets["HUB_SIDE"], 34.0),
        ("PMI_SHROUD_SIDE_TAB", (-38.0, 24.0, tab_thickness + vane_height - 6.0), leader_targets["SHROUD_SIDE"], 40.0),
        ("PMI_HEIGHT_92_CHORD_34_STAGGER_18_TAB_THK_7", (42.0, 0.0, tab_thickness + vane_height * 0.40), (pmi_x, 0.0, tab_thickness + vane_height * 0.5), 76.0),
    ]
    for _label, center, target, length in label_specs:
        plaque = b.oriented_box(
            length,
            label_plate_width,
            label_plate_thickness,
            center=center,
            u_axis=(1, 0, 0),
            v_axis=(0, 1, 0),
            w_axis=(0, 0, 1),
        )
        b.boolean_unite(body, plaque)
        _add_bar(b, body, center, target, pmi_bar_diameter)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
