# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              high_precision_centrifugal_compressor_impeller.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports high_precision_centrifugal_compressor_impeller.step next to it.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _polar(radius, angle_radians):
    return (
        radius * math.cos(angle_radians),
        radius * math.sin(angle_radians),
    )


def _blend(a, b, t):
    return a + (b - a) * t


def _blade_segment_polygon(r0, r1, theta0, theta1, thickness):
    x0, y0 = _polar(r0, theta0)
    x1, y1 = _polar(r1, theta1)
    dx = x1 - x0
    dy = y1 - y0
    length = math.hypot(dx, dy)
    if length <= 0.0:
        raise ValueError("Blade segment length must be positive.")

    nx = -dy / length
    ny = dx / length
    half_t = thickness / 2.0
    return [
        (x0 + nx * half_t, y0 + ny * half_t),
        (x1 + nx * half_t, y1 + ny * half_t),
        (x1 - nx * half_t, y1 - ny * half_t),
        (x0 - nx * half_t, y0 - ny * half_t),
    ]


def build(output_path: str = None):
    b = NXBuilder()

    # Independent parameters from prompt, millimeters.
    bore_diameter = 18.0
    inlet_hub_diameter = 34.0
    outlet_hub_diameter = 72.0
    hub_total_height = 38.0
    back_disk_diameter = 120.0
    back_disk_thickness = 8.0

    blade_count = 12
    blade_inner_radius = 24.0
    blade_outer_radius = 58.0
    blade_inner_height = 28.0
    blade_outer_height = 12.0
    blade_thickness = 2.0
    blade_curve_degrees = -54.0
    blade_segments = 12

    nose_cone_base_diameter = 30.0
    nose_cone_height = 18.0
    rear_ring_od = 96.0
    rear_ring_id = 74.0
    rear_ring_height = 3.0

    blade_root_fillet = 1.5
    hub_transition_fillet = 1.0
    bore_edge_chamfer = 0.5

    # Derived robust modeling parameters.
    feature_overlap = 0.5
    through_overcut = 3.0
    hub_slice_count = 16
    nose_slice_count = 14
    z_back_top = back_disk_thickness
    z_hub_top = hub_total_height
    z_nose_top = z_hub_top + nose_cone_height
    bore_cut_depth = z_nose_top + rear_ring_height + 2.0 * through_overcut

    b.require_positive(
        bore_diameter=bore_diameter,
        back_disk_diameter=back_disk_diameter,
        back_disk_thickness=back_disk_thickness,
        hub_total_height=hub_total_height,
        blade_thickness=blade_thickness,
        nose_cone_height=nose_cone_height,
        rear_ring_height=rear_ring_height,
    )
    b.require_min_wall(inlet_hub_diameter, bore_diameter, min_wall=5.0, label="inlet hub bore wall")
    b.require_min_wall(rear_ring_od, rear_ring_id, min_wall=8.0, label="rear balancing ring")
    b.require_feature_budget(boolean_operations=210, patterned_features=blade_count * blade_segments)

    # Back disk: centered on Z axis, bottom face at Z = 0.
    body = b.cylinder(
        back_disk_diameter,
        back_disk_thickness,
        origin=(0.0, 0.0, 0.0),
        axis=(0.0, 0.0, 1.0),
    )
    b.fillet(b.get_top_edges(body), hub_transition_fillet)
    b.fillet(b.get_bottom_edges(body), hub_transition_fillet)

    # Tapered hub represented by fine coaxial slices for portable NXBuilder geometry.
    hub_height_above_disk = hub_total_height - back_disk_thickness
    for index in range(hub_slice_count):
        t0 = float(index) / float(hub_slice_count)
        t1 = float(index + 1) / float(hub_slice_count)
        z0 = z_back_top + hub_height_above_disk * t0 - feature_overlap
        h = hub_height_above_disk * (t1 - t0) + feature_overlap
        # Broad at the back disk, smaller at the inlet plane.
        diameter = _blend(outlet_hub_diameter, inlet_hub_diameter, (t0 + t1) * 0.5)
        hub_slice = b.cylinder(
            diameter,
            h,
            origin=(0.0, 0.0, z0),
            axis=(0.0, 0.0, 1.0),
        )
        body = b.boolean_unite(body, hub_slice)

    # Raised nose cone on top, approximated as a smooth stack of shrinking slices.
    for index in range(nose_slice_count):
        t0 = float(index) / float(nose_slice_count)
        t1 = float(index + 1) / float(nose_slice_count)
        z0 = z_hub_top + nose_cone_height * t0 - feature_overlap
        h = nose_cone_height * (t1 - t0) + feature_overlap
        mid_t = (t0 + t1) * 0.5
        diameter = max(bore_diameter + 2.0, nose_cone_base_diameter * (1.0 - mid_t**1.7))
        nose_slice = b.cylinder(
            diameter,
            h,
            origin=(0.0, 0.0, z0),
            axis=(0.0, 0.0, 1.0),
        )
        body = b.boolean_unite(body, nose_slice)

    # Rear balancing ring, united to underside of the disk then opened with the bore-side annulus cut.
    rear_ring = b.cylinder(
        rear_ring_od,
        rear_ring_height,
        origin=(0.0, 0.0, -rear_ring_height),
        axis=(0.0, 0.0, 1.0),
    )
    body = b.boolean_unite(body, rear_ring)
    rear_ring_inner_cut = b.hole(
        rear_ring_id,
        rear_ring_height + 2.0 * through_overcut,
        position=(0.0, 0.0, through_overcut),
        direction=(0.0, 0.0, -1.0),
    )
    b.boolean_subtract(body, rear_ring_inner_cut)

    # Backward-curved, shroud-free blades. Positive rotation is CCW from +Z;
    # negative sweep makes the blades backward-curved.
    curve_total = math.radians(blade_curve_degrees)
    for blade_index in range(blade_count):
        base_angle = 2.0 * math.pi * float(blade_index) / float(blade_count)
        blade_feature = None
        for segment_index in range(blade_segments):
            t0 = float(segment_index) / float(blade_segments)
            t1 = float(segment_index + 1) / float(blade_segments)
            r0 = _blend(blade_inner_radius, blade_outer_radius, t0)
            r1 = _blend(blade_inner_radius, blade_outer_radius, t1)

            # Slight quadratic easing gives a smoother aerodynamic-looking camber line.
            theta0 = base_angle + curve_total * (0.18 * t0 + 0.82 * t0 * t0)
            theta1 = base_angle + curve_total * (0.18 * t1 + 0.82 * t1 * t1)
            segment_height = _blend(blade_inner_height, blade_outer_height, (t0 + t1) * 0.5)

            segment = b.polygon_prism(
                _blade_segment_polygon(r0, r1, theta0, theta1, blade_thickness),
                segment_height + feature_overlap,
                origin=(0.0, 0.0, z_back_top - feature_overlap),
                axis=(0.0, 0.0, 1.0),
            )
            b.fillet(b.get_bottom_edges(segment), blade_root_fillet)
            b.fillet(b.get_top_edges(segment), 0.35)

            if blade_feature is None:
                blade_feature = segment
            else:
                blade_feature = b.boolean_unite(blade_feature, segment)

        body = b.boolean_unite(body, blade_feature)

    # Central through-bore. Chamfer selectors are local to bore entry regions.
    bore_tool = b.hole(
        bore_diameter,
        bore_cut_depth,
        position=(0.0, 0.0, z_nose_top + through_overcut),
        direction=(0.0, 0.0, -1.0),
    )
    b.boolean_subtract(body, bore_tool)
    b.chamfer(
        b.get_edges_in_box(
            body,
            min_xyz=(-bore_diameter, -bore_diameter, z_nose_top - 1.5),
            max_xyz=(bore_diameter, bore_diameter, z_nose_top + 0.5),
        ),
        bore_edge_chamfer,
    )
    b.chamfer(
        b.get_edges_in_box(
            body,
            min_xyz=(-bore_diameter, -bore_diameter, -rear_ring_height - 0.5),
            max_xyz=(bore_diameter, bore_diameter, -rear_ring_height + 1.5),
        ),
        bore_edge_chamfer,
    )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
