# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              compact_ball_screw_linear_actuator.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import os
import sys


_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    base_length = 220.0
    base_width = 48.0
    base_height = 12.0
    guide_length = 180.0
    guide_width = 8.0
    guide_height = 8.0
    guide_y_offsets = (-14.0, 14.0)
    carriage_length = 52.0
    carriage_width = 42.0
    carriage_height = 22.0
    ball_screw_diameter = 12.0
    ball_screw_length = 210.0
    ball_nut_housing_diameter = 28.0
    ball_nut_housing_length = 36.0
    bearing_block_length = 30.0
    bearing_block_width = 48.0
    bearing_block_height = 34.0
    bearing_bore_diameter = 18.0
    coupling_hub_diameter = 24.0
    coupling_hub_length = 28.0
    mounting_hole_diameter = 4.2
    block_edge_fillet = 2.0
    hole_chamfer = 0.5

    # Derived layout and robustness parameters.
    feature_overlap = 0.5
    through_overcut = 2.0
    cutter_overlap = 1.0
    base_x0 = -base_length / 2.0
    base_y0 = -base_width / 2.0
    base_z0 = 0.0
    base_top_z = base_z0 + base_height
    guide_x0 = -guide_length / 2.0
    guide_z0 = base_top_z - feature_overlap
    carriage_z0 = base_top_z + guide_height
    carriage_center_z = carriage_z0 + carriage_height / 2.0
    screw_axis_z = carriage_center_z
    screw_x0 = -ball_screw_length / 2.0
    front_block_x0 = -base_length / 2.0
    rear_block_x0 = base_length / 2.0 - bearing_block_length
    block_z0 = base_top_z
    coupling_x0 = base_length / 2.0

    rail_hole_x_offsets = (-70.0, 0.0, 70.0)
    carriage_hole_x_offsets = (-18.0, 18.0)
    carriage_hole_y_offsets = (-14.0, 14.0)
    block_hole_x_local_offsets = (-9.0, 9.0)
    block_hole_y_offsets = (-16.0, 16.0)
    rail_hole_depth = guide_height + 2.0 * through_overcut
    carriage_hole_depth = carriage_height + 2.0 * through_overcut
    block_hole_depth = bearing_block_height + 2.0 * through_overcut
    bearing_bore_depth = bearing_block_length + 2.0 * through_overcut

    b.require_positive(
        base_length=base_length,
        base_width=base_width,
        base_height=base_height,
        guide_length=guide_length,
        carriage_length=carriage_length,
        ball_screw_diameter=ball_screw_diameter,
        ball_nut_housing_diameter=ball_nut_housing_diameter,
        bearing_block_height=bearing_block_height,
        coupling_hub_diameter=coupling_hub_diameter,
    )
    b.require_min_wall(ball_nut_housing_diameter, ball_screw_diameter, min_wall=4.0, label="ball nut housing")
    b.require_min_wall(bearing_block_height, bearing_bore_diameter, min_wall=4.0, label="bearing bore vertical wall")
    b.require_edge_distance(guide_width / 2.0, mounting_hole_diameter, min_ratio=0.85, label="guide rail M4 holes")
    b.require_feature_budget(boolean_operations=40, micro_holes=24, patterned_features=24)

    # Separate aligned solids.
    base = b.box(base_length, base_width, base_height, origin=(base_x0, base_y0, base_z0))

    guides = []
    for guide_y in guide_y_offsets:
        guide = b.box(
            guide_length,
            guide_width,
            guide_height + feature_overlap,
            origin=(guide_x0, guide_y - guide_width / 2.0, guide_z0),
        )
        guides.append((guide, guide_y))

    carriage = b.box(
        carriage_length,
        carriage_width,
        carriage_height,
        origin=(-carriage_length / 2.0, -carriage_width / 2.0, carriage_z0),
    )

    ball_screw = b.cylinder(
        ball_screw_diameter,
        ball_screw_length,
        origin=(screw_x0, 0.0, screw_axis_z),
        axis=(1, 0, 0),
    )
    nut_housing = b.cylinder(
        ball_nut_housing_diameter,
        ball_nut_housing_length,
        origin=(-ball_nut_housing_length / 2.0, 0.0, screw_axis_z),
        axis=(1, 0, 0),
    )

    front_block = b.box(
        bearing_block_length,
        bearing_block_width,
        bearing_block_height,
        origin=(front_block_x0, -bearing_block_width / 2.0, block_z0),
    )
    rear_block = b.box(
        bearing_block_length,
        bearing_block_width,
        bearing_block_height,
        origin=(rear_block_x0, -bearing_block_width / 2.0, block_z0),
    )
    coupling_hub = b.cylinder(
        coupling_hub_diameter,
        coupling_hub_length,
        origin=(coupling_x0, 0.0, screw_axis_z),
        axis=(1, 0, 0),
    )

    # Functional bores and mounting holes.
    bore_front = b.hole(
        bearing_bore_diameter,
        bearing_bore_depth,
        position=(front_block_x0 - through_overcut, 0.0, screw_axis_z),
        direction=(1, 0, 0),
    )
    b.boolean_subtract(front_block, bore_front)
    bore_rear = b.hole(
        bearing_bore_diameter,
        bearing_bore_depth,
        position=(rear_block_x0 + bearing_block_length + through_overcut, 0.0, screw_axis_z),
        direction=(-1, 0, 0),
    )
    b.boolean_subtract(rear_block, bore_rear)

    for guide, guide_y in guides:
        for hole_x in rail_hole_x_offsets:
            cutter = b.hole(
                mounting_hole_diameter,
                rail_hole_depth,
                position=(hole_x, guide_y, base_top_z + guide_height + through_overcut),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(guide, cutter)

    for hole_x in carriage_hole_x_offsets:
        for hole_y in carriage_hole_y_offsets:
            cutter = b.hole(
                mounting_hole_diameter,
                carriage_hole_depth,
                position=(hole_x, hole_y, carriage_z0 + carriage_height + through_overcut),
                direction=(0, 0, -1),
            )
            b.boolean_subtract(carriage, cutter)

    for block, block_x0 in ((front_block, front_block_x0), (rear_block, rear_block_x0)):
        block_center_x = block_x0 + bearing_block_length / 2.0
        for hole_x_local in block_hole_x_local_offsets:
            for hole_y in block_hole_y_offsets:
                cutter = b.hole(
                    mounting_hole_diameter,
                    block_hole_depth,
                    position=(block_center_x + hole_x_local, hole_y, block_z0 + bearing_block_height + through_overcut),
                    direction=(0, 0, -1),
                )
                b.boolean_subtract(block, cutter)

    # 2 mm fillets to block-like edges using local body boxes, avoiding broad
    # post-pattern edge selection.
    b.fillet(
        b.get_edges_in_box(
            base,
            min_xyz=(base_x0 - 0.1, base_y0 - 0.1, base_z0 - 0.1),
            max_xyz=(-base_x0 + 0.1, -base_y0 + 0.1, base_top_z + 0.1),
        ),
        block_edge_fillet,
    )
    b.fillet(
        b.get_edges_in_box(
            carriage,
            min_xyz=(-carriage_length / 2.0 - 0.1, -carriage_width / 2.0 - 0.1, carriage_z0 - 0.1),
            max_xyz=(carriage_length / 2.0 + 0.1, carriage_width / 2.0 + 0.1, carriage_z0 + carriage_height + 0.1),
        ),
        block_edge_fillet,
    )
    for block, block_x0 in ((front_block, front_block_x0), (rear_block, rear_block_x0)):
        b.fillet(
            b.get_edges_in_box(
                block,
                min_xyz=(block_x0 - 0.1, -bearing_block_width / 2.0 - 0.1, block_z0 - 0.1),
                max_xyz=(block_x0 + bearing_block_length + 0.1, bearing_block_width / 2.0 + 0.1, block_z0 + bearing_block_height + 0.1),
            ),
            block_edge_fillet,
        )
    for guide, guide_y in guides:
        b.fillet(
            b.get_edges_in_box(
                guide,
                min_xyz=(guide_x0 - 0.1, guide_y - guide_width / 2.0 - 0.1, guide_z0 - 0.1),
                max_xyz=(guide_x0 + guide_length + 0.1, guide_y + guide_width / 2.0 + 0.1, guide_z0 + guide_height + feature_overlap + 0.1),
            ),
            block_edge_fillet,
        )

    # 0.5 mm chamfers around all specified hole openings.
    for guide, guide_y in guides:
        for hole_x in rail_hole_x_offsets:
            b.chamfer(b.get_edges_near(guide, point=(hole_x, guide_y, base_top_z + guide_height), tolerance=3.0), hole_chamfer)
            b.chamfer(b.get_edges_near(guide, point=(hole_x, guide_y, base_top_z), tolerance=3.0), hole_chamfer)

    for hole_x in carriage_hole_x_offsets:
        for hole_y in carriage_hole_y_offsets:
            b.chamfer(b.get_edges_near(carriage, point=(hole_x, hole_y, carriage_z0 + carriage_height), tolerance=3.0), hole_chamfer)
            b.chamfer(b.get_edges_near(carriage, point=(hole_x, hole_y, carriage_z0), tolerance=3.0), hole_chamfer)

    for block, block_x0 in ((front_block, front_block_x0), (rear_block, rear_block_x0)):
        block_center_x = block_x0 + bearing_block_length / 2.0
        for hole_x_local in block_hole_x_local_offsets:
            for hole_y in block_hole_y_offsets:
                hole_x = block_center_x + hole_x_local
                b.chamfer(b.get_edges_near(block, point=(hole_x, hole_y, block_z0 + bearing_block_height), tolerance=3.0), hole_chamfer)
                b.chamfer(b.get_edges_near(block, point=(hole_x, hole_y, block_z0), tolerance=3.0), hole_chamfer)
        b.chamfer(b.get_edges_near(block, point=(block_x0, 0.0, screw_axis_z), tolerance=10.0), hole_chamfer)
        b.chamfer(b.get_edges_near(block, point=(block_x0 + bearing_block_length, 0.0, screw_axis_z), tolerance=10.0), hole_chamfer)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
