# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              aerospace_fuel_nozzle_mounting_flange.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys


_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    flange_width_y = 90.0
    flange_height_z = 62.0
    flange_thickness_x = 12.0
    boss_diameter = 36.0
    boss_length_x = 30.0
    bore_diameter = 14.0
    sealing_seat_diameter = 22.0
    sealing_seat_depth = 8.0
    mount_hole_diameter = 7.0
    mount_hole_y_offset = 30.0
    counterbore_diameter = 13.0
    counterbore_depth = 5.0
    dowel_hole_diameter = 4.0
    dowel_hole_z_offset = 22.0
    rear_groove_outer_diameter = 42.0
    rear_groove_inner_diameter = 32.0
    rear_groove_depth = 1.0
    rib_thickness = 5.0
    rib_length_x = 30.0
    rib_radial_height = 11.0
    transition_fillet = 2.0
    outer_fillet = 3.0
    hole_chamfer = 0.5

    # Derived layout and robustness parameters.
    feature_overlap = 0.5
    cutter_overlap = 1.0
    through_overcut = 2.0
    rear_face_x = -flange_thickness_x
    front_face_x = 0.0
    boss_start_x = front_face_x - feature_overlap
    boss_total_length = boss_length_x + feature_overlap
    bore_start_x = rear_face_x - through_overcut
    bore_depth = flange_thickness_x + boss_length_x + 2.0 * through_overcut
    flange_half_y = flange_width_y / 2.0
    flange_half_z = flange_height_z / 2.0
    boss_radius = boss_diameter / 2.0
    oval_segments = 48
    rib_center_x = front_face_x + rib_length_x / 2.0 - feature_overlap / 2.0
    rib_center_z = boss_radius + rib_radial_height / 2.0 - feature_overlap

    b.require_positive(
        flange_width_y=flange_width_y,
        flange_height_z=flange_height_z,
        flange_thickness_x=flange_thickness_x,
        boss_diameter=boss_diameter,
        boss_length_x=boss_length_x,
        bore_diameter=bore_diameter,
        rib_thickness=rib_thickness,
    )
    b.require_min_wall(boss_diameter, sealing_seat_diameter, min_wall=4.0, label="nozzle boss sealing seat")
    b.require_min_wall(flange_width_y, rear_groove_outer_diameter, min_wall=8.0, label="rear annular groove")
    b.require_edge_distance(flange_half_y - mount_hole_y_offset, counterbore_diameter, min_ratio=0.9, label="mounting counterbore")
    b.require_feature_budget(boolean_operations=18, micro_holes=4, patterned_features=6)

    oval_points = []
    for index in range(oval_segments):
        angle = 2.0 * math.pi * float(index) / float(oval_segments)
        oval_points.append((flange_half_y * math.cos(angle), flange_half_z * math.sin(angle)))

    flange = b.polygon_prism_on_plane(
        oval_points,
        flange_thickness_x,
        origin=(rear_face_x, 0.0, 0.0),
        u_axis=(0, 1, 0),
        v_axis=(0, 0, 1),
        extrude_axis=(1, 0, 0),
    )

    boss = b.cylinder(
        boss_diameter,
        boss_total_length,
        origin=(boss_start_x, 0.0, 0.0),
        axis=(1, 0, 0),
    )
    b.boolean_unite(flange, boss)

    # Two axial reinforcing ribs on the top and bottom of the nozzle boss.
    for sign in (-1.0, 1.0):
        rib = b.oriented_box(
            rib_length_x + feature_overlap,
            rib_thickness,
            rib_radial_height + feature_overlap,
            center=(rib_center_x, 0.0, sign * rib_center_z),
            u_axis=(1, 0, 0),
            v_axis=(0, 1, 0),
            w_axis=(0, 0, 1),
        )
        b.boolean_unite(flange, rib)

    # Through bore, rear stepped sealing seat, and rear annular sealing groove.
    main_bore = b.hole(
        bore_diameter,
        bore_depth,
        position=(bore_start_x, 0.0, 0.0),
        direction=(1, 0, 0),
    )
    b.boolean_subtract(flange, main_bore)
    seat = b.hole(
        sealing_seat_diameter,
        sealing_seat_depth + cutter_overlap,
        position=(rear_face_x - cutter_overlap, 0.0, 0.0),
        direction=(1, 0, 0),
    )
    b.boolean_subtract(flange, seat)
    b.annular_groove(
        flange,
        outer_diameter=rear_groove_outer_diameter,
        inner_diameter=rear_groove_inner_diameter,
        depth=rear_groove_depth,
        position=(rear_face_x, 0.0, 0.0),
        direction=(1, 0, 0),
        cutter_overlap=cutter_overlap,
    )

    # Mounting holes with counterbores from the rear face.
    for hole_y in (-mount_hole_y_offset, mount_hole_y_offset):
        b.counterbore_hole(
            flange,
            mount_hole_diameter,
            flange_thickness_x + 2.0 * through_overcut,
            counterbore_diameter,
            counterbore_depth,
            position=(rear_face_x - through_overcut, hole_y, 0.0),
            direction=(1, 0, 0),
        )

    # Dowel holes through the flange along X.
    for hole_z in (-dowel_hole_z_offset, dowel_hole_z_offset):
        dowel = b.hole(
            dowel_hole_diameter,
            flange_thickness_x + 2.0 * through_overcut,
            position=(rear_face_x - through_overcut, 0.0, hole_z),
            direction=(1, 0, 0),
        )
        b.boolean_subtract(flange, dowel)

    # Cosmetic blends and edge breaks. Selectors are localized to avoid broad
    # post-boolean topology assumptions.
    b.fillet(
        b.get_edges_in_box(
            flange,
            min_xyz=(rear_face_x - 0.1, -flange_half_y - 0.1, -flange_half_z - 0.1),
            max_xyz=(front_face_x + boss_length_x + 0.1, flange_half_y + 0.1, flange_half_z + 0.1),
        ),
        outer_fillet,
    )
    b.fillet(
        b.get_edges_near(flange, point=(front_face_x, 0.0, boss_radius), tolerance=8.0),
        transition_fillet,
    )
    b.fillet(
        b.get_edges_near(flange, point=(front_face_x, 0.0, -boss_radius), tolerance=8.0),
        transition_fillet,
    )
    for sign in (-1.0, 1.0):
        b.fillet(
            b.get_edges_near(flange, point=(front_face_x, 0.0, sign * rib_center_z), tolerance=8.0),
            transition_fillet,
        )

    # Chamfer all specified hole openings.
    for x_face in (rear_face_x, front_face_x + boss_length_x):
        b.chamfer(b.get_edges_near(flange, point=(x_face, 0.0, 0.0), tolerance=8.0), hole_chamfer)
    b.chamfer(b.get_edges_near(flange, point=(rear_face_x, 0.0, 0.0), tolerance=14.0), hole_chamfer)
    for hole_y in (-mount_hole_y_offset, mount_hole_y_offset):
        b.chamfer(b.get_edges_near(flange, point=(rear_face_x, hole_y, 0.0), tolerance=7.0), hole_chamfer)
        b.chamfer(b.get_edges_near(flange, point=(front_face_x, hole_y, 0.0), tolerance=5.0), hole_chamfer)
    for hole_z in (-dowel_hole_z_offset, dowel_hole_z_offset):
        b.chamfer(b.get_edges_near(flange, point=(rear_face_x, 0.0, hole_z), tolerance=3.0), hole_chamfer)
        b.chamfer(b.get_edges_near(flange, point=(front_face_x, 0.0, hole_z), tolerance=3.0), hole_chamfer)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
