# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              Mp.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file.
# ----------------------------------------------------------------------------

import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Plate parameters in millimeters.
    length = 60.0
    width = 40.0
    thickness = 8.0
    hole_diameter = 5.5  # M5 normal clearance
    hole_margin_x = 10.0
    hole_margin_y = 8.0

    # Derived hole layout, centered on the plate footprint.
    hole_x = length / 2.0 - hole_margin_x
    hole_y = width / 2.0 - hole_margin_y
    hole_positions = [
        (-hole_x, -hole_y),
        (hole_x, -hole_y),
        (hole_x, hole_y),
        (-hole_x, hole_y),
    ]

    b.require_positive(length=length, width=width, thickness=thickness, hole_diameter=hole_diameter)
    b.require_feature_budget(boolean_operations=4)
    b.require_edge_distance(hole_x, hole_diameter, min_ratio=1.0, label="M5 hole X edge distance")
    b.require_edge_distance(hole_y, hole_diameter, min_ratio=1.0, label="M5 hole Y edge distance")

    plate = b.box(length, width, thickness, origin=(-length / 2.0, -width / 2.0, 0.0))

    for x, y in hole_positions:
        b.screw_clearance_hole(
            plate,
            "M5",
            thickness,
            position=(x, y, thickness),
            direction=(0, 0, -1),
        )

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
