#json
{
  "artifacts": {
    "prt": {
      "exists": true,
      "path": "D:\\Workdir\\iproot\\nx2606.1700\\test44\\workspace\\aerospace_linkage_002\\curved_bellcrank.prt",
      "size": 236753
    },
    "step": {
      "exists": true,
      "path": "D:\\Workdir\\iproot\\nx2606.1700\\test44\\workspace\\aerospace_linkage_002\\curved_bellcrank.step",
      "size": 2241
    }
  },
  "execution": {
    "actor": "user",
    "tool": "nx_ui",
    "transport": "nx_ui"
  },
  "journal": {
    "path": "D:\\Workdir\\iproot\\nx2606.1700\\test44\\workspace\\aerospace_linkage_002\\curved_bellcrank.py",
    "working_dir": "D:\\Workdir\\iproot\\nx2606.1700\\test44\\workspace\\aerospace_linkage_002"
  },
  "model": {
    "body_count": 1,
    "critical_features": {
      "arm_a_five_station_loft": true,
      "arm_b_five_station_loft": true,
      "central_bore": true,
      "central_hub": true,
      "two_end_bores": true,
      "two_end_bushing_bosses": true
    },
    "expected_body_count": 1
  },
  "nx_version": "NX 2606",
  "probe": "curved_bellcrank_repaired",
  "result": "success",
  "run_id": "run_002",
  "schema_version": 2,
  "source_sha256": "fed56943d31f055d305a368ce6b8a00145b1729e9ff3ea8ce2bd47d1c133380e",
  "warnings": []
}
#step
ISO-10303-21;
HEADER;
/* Generated by software containing ST-Developer
 * from STEP Tools, Inc. (www.steptools.com) 
 */
/* OPTION: using custom renumber hook */

FILE_DESCRIPTION(
/* description */ (
'CAx-IF Rec.Pracs.---Representation and Presentation of Product Manufa
cturing Information (PMI)---4.0---2014-10-13',
'CAx-IF Rec.Pracs.---3D Tessellated Geometry---0.4---2014-09-14','2;1'),

/* implementation_level */ '2;1');

FILE_NAME(
/* name */ 'curved_bellcrank',
/* time_stamp */ '2026-07-27T14:05:13+08:00',
/* author */ (''),
/* organization */ (''),
/* preprocessor_version */ 'ST-DEVELOPER v20.1',
/* originating_system */ 'SIEMENS PLM Software NX2606.1700',
/* authorisation */ $);

FILE_SCHEMA (('AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF { 1 0 10303 442 1 1 4 }'));
ENDSEC;

DATA;
#10=SHAPE_DEFINITION_REPRESENTATION(#21,#11);
#11=SHAPE_REPRESENTATION('curved_bellcrank',(#12),#16);
#12=AXIS2_PLACEMENT_3D('',#15,#13,#14);
#13=DIRECTION('',(0.,0.,1.));
#14=DIRECTION('',(1.,0.,0.));
#15=CARTESIAN_POINT('',(0.,0.,0.));
#16=(
GEOMETRIC_REPRESENTATION_CONTEXT(3)
GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT((#17))
GLOBAL_UNIT_ASSIGNED_CONTEXT((#20,#19,#18))
REPRESENTATION_CONTEXT('curved_bellcrank','TOP_LEVEL_ASSEMBLY_PART')
);
#17=UNCERTAINTY_MEASURE_WITH_UNIT(LENGTH_MEASURE(1.E-5),#20,
'DISTANCE_ACCURACY_VALUE','Maximum Tolerance applied to model');
#18=(
NAMED_UNIT(*)
SI_UNIT($,.STERADIAN.)
SOLID_ANGLE_UNIT()
);
#19=(
NAMED_UNIT(*)
PLANE_ANGLE_UNIT()
SI_UNIT($,.RADIAN.)
);
#20=(
LENGTH_UNIT()
NAMED_UNIT(*)
SI_UNIT(.MILLI.,.METRE.)
);
#21=PRODUCT_DEFINITION_SHAPE('','',#22);
#22=PRODUCT_DEFINITION('','',#24,#23);
#23=PRODUCT_DEFINITION_CONTEXT('',#30,'design');
#24=PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE('','',#26,
 .NOT_KNOWN.);
#25=PRODUCT_RELATED_PRODUCT_CATEGORY('','',(#26));
#26=PRODUCT('curved_bellcrank','curved_bellcrank','curved_bellcrank',(#28));
#27=PRODUCT_CATEGORY('','');
#28=PRODUCT_CONTEXT('',#30,'mechanical');
#29=APPLICATION_PROTOCOL_DEFINITION('international standard',
'ap242_managed_model_based_3d_engineering',2011,#30);
#30=APPLICATION_CONTEXT('managed model based 3d engineering');
ENDSEC;
END-ISO-10303-21;
