# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              simplified_planetary_gear_assembly.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

# Ensure cadnx is importable on the NX machine.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def external_gear_points(tooth_count, root_diameter, outside_diameter, phase=0.0):
    root_radius = root_diameter / 2.0
    outside_radius = outside_diameter / 2.0
    pitch = 2.0 * math.pi / tooth_count
    top_fraction = 0.42
    points = []

    for index in range(tooth_count):
        center = phase + index * pitch
        root_lead = center - 0.50 * pitch
        top_lead = center - 0.50 * top_fraction * pitch
        top_trail = center + 0.50 * top_fraction * pitch
        root_trail = center + 0.50 * pitch
        for angle, radius in (
            (root_lead, root_radius),
            (top_lead, outside_radius),
            (top_trail, outside_radius),
            (root_trail, root_radius),
        ):
            points.append((radius * math.cos(angle), radius * math.sin(angle)))

    return points


def internal_gear_cutout_points(tooth_count, tooth_tip_diameter, root_diameter):
    tip_radius = tooth_tip_diameter / 2.0
    root_radius = root_diameter / 2.0
    pitch = 2.0 * math.pi / tooth_count
    land_fraction = 0.42
    points = []

    for index in range(tooth_count):
        center = index * pitch
        gap_lead = center - 0.50 * pitch
        land_lead = center - 0.50 * land_fraction * pitch
        land_trail = center + 0.50 * land_fraction * pitch
        gap_trail = center + 0.50 * pitch
        for angle, radius in (
            (gap_lead, root_radius),
            (land_lead, tip_radius),
            (land_trail, tip_radius),
            (gap_trail, root_radius),
        ):
            points.append((radius * math.cos(angle), radius * math.sin(angle)))

    return points


def translated_points(points, center):
    cx, cy = center
    return [(x + cx, y + cy) for x, y in points]


def build(output_path: str = None):
    b = NXBuilder()

    # General layout
    gear_z = 0.0
    gear_thickness = 8.0
    planet_center_radius = 42.0

    # Sun gear
    sun_teeth = 24
    sun_pitch_diameter = 48.0
    sun_root_diameter = 42.0
    sun_outside_diameter = 54.0
    sun_bore_diameter = 10.0

    # Planet gears
    planet_teeth = 18
    planet_pitch_diameter = 36.0
    planet_root_diameter = 31.0
    planet_outside_diameter = 41.0

    # Ring gear
    ring_teeth = 60
    ring_internal_pitch_diameter = 120.0
    ring_internal_root_diameter = 126.0
    ring_internal_tooth_tip_diameter = 114.0
    ring_outside_diameter = 140.0

    # Carrier and pins
    carrier_diameter = 105.0
    carrier_thickness = 4.0
    carrier_z = -5.0
    pin_diameter = 6.0
    pin_height = 14.0
    pin_z = -5.0

    # Pitch diameters are retained as named dimensions for traceability.
    _pitch_reference = (
        sun_pitch_diameter,
        planet_pitch_diameter,
        ring_internal_pitch_diameter,
    )

    # Carrier plate below the gears.
    carrier = b.cylinder(
        carrier_diameter,
        carrier_thickness,
        origin=(0.0, 0.0, carrier_z),
    )

    # Sun gear with central bore.
    sun = b.polygon_prism(
        external_gear_points(sun_teeth, sun_root_diameter, sun_outside_diameter),
        gear_thickness,
        origin=(0.0, 0.0, gear_z),
    )
    sun_bore = b.hole(
        sun_bore_diameter,
        gear_thickness + 2.0,
        position=(0.0, 0.0, gear_z + gear_thickness + 1.0),
        direction=(0.0, 0.0, -1.0),
    )
    b.boolean_subtract(sun, sun_bore)

    # Ring gear: solid outer cylinder with internally toothed through cutout.
    ring = b.cylinder(
        ring_outside_diameter,
        gear_thickness,
        origin=(0.0, 0.0, gear_z),
    )
    ring_cutout = b.polygon_prism(
        internal_gear_cutout_points(
            ring_teeth,
            ring_internal_tooth_tip_diameter,
            ring_internal_root_diameter,
        ),
        gear_thickness + 2.0,
        origin=(0.0, 0.0, gear_z - 1.0),
    )
    b.boolean_subtract(ring, ring_cutout)

    # Three planet gears and vertical pins.
    for index in range(3):
        angle = index * 2.0 * math.pi / 3.0
        cx = planet_center_radius * math.cos(angle)
        cy = planet_center_radius * math.sin(angle)

        planet = b.polygon_prism(
            translated_points(
                external_gear_points(
                    planet_teeth,
                    planet_root_diameter,
                    planet_outside_diameter,
                    phase=angle / 2.0,
                ),
                (cx, cy),
            ),
            gear_thickness,
            origin=(0.0, 0.0, gear_z),
        )

        pin = b.cylinder(
            pin_diameter,
            pin_height,
            origin=(cx, cy, pin_z),
        )

        # Keep local variables live and explicit for NX journal readability.
        _separate_bodies = (carrier, sun, ring, planet, pin, _pitch_reference)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
