# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              simplified_inline4_engine_assembly.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports simplified_inline4_engine_assembly.step.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def _rod_plate_points(small_center, big_center, outer_small_radius, outer_big_radius):
    sx, sz = small_center
    bx, bz = big_center
    dx = bx - sx
    dz = bz - sz
    length = math.hypot(dx, dz)
    if length <= 0:
        raise ValueError("Rod centers must be separated.")
    ux = dx / length
    uz = dz / length
    nx = -uz
    nz = ux

    return [
        (sx + nx * outer_small_radius, sz + nz * outer_small_radius),
        (bx + nx * outer_big_radius, bz + nz * outer_big_radius),
        (bx - nx * outer_big_radius, bz - nz * outer_big_radius),
        (sx - nx * outer_small_radius, sz - nz * outer_small_radius),
    ]


def build(output_path: str = None):
    b = NXBuilder()

    # Core layout
    block_length = 320.0
    block_width = 160.0
    block_height = 180.0
    bore_diameter = 86.0
    bore_depth = 120.0
    cylinder_xs = [-120.0, -40.0, 40.0, 120.0]

    head_height = 50.0
    chamber_diameter = 82.0
    chamber_depth = 8.0

    piston_diameter = 82.0
    piston_height = 60.0
    piston_top_z = 175.0
    wrist_pin_diameter = 10.0
    wrist_pin_z = piston_top_z - piston_height + 15.0

    crank_axis_z = -20.0
    crank_axis_y = 0.0
    crankshaft_length = 340.0
    main_journal_diameter = 50.0
    crankpin_diameter = 48.0
    crank_throw = 40.0
    crankpin_width = 34.0

    rod_thickness_y = 8.0
    rod_small_bore = 10.0
    rod_big_bore = 48.0
    rod_small_outer_radius = 14.0
    rod_big_outer_radius = 32.0

    camshaft_length = 330.0
    cam_base_diameter = 25.0
    cam_lobe_diameter = cam_base_diameter + 8.0
    cam_z = 210.0

    cover_length = 316.0
    cover_width = 156.0
    cover_height = 30.0
    cover_wall = 4.0

    pan_length = 316.0
    pan_width = 156.0
    pan_depth = 60.0
    pan_wall = 4.0

    # Engine block with four vertical bores.
    block = b.box(
        block_length,
        block_width,
        block_height,
        origin=(-block_length / 2.0, -block_width / 2.0, 0.0),
    )
    for x in cylinder_xs:
        bore = b.hole(
            bore_diameter,
            bore_depth + 2.0,
            position=(x, 0.0, block_height + 1.0),
            direction=(0, 0, -1),
        )
        b.boolean_subtract(block, bore)
    b.chamfer(b.get_top_edges(block), 1.5)

    # Cylinder head with bottom combustion chamber recesses.
    head = b.box(
        block_length,
        block_width,
        head_height,
        origin=(-block_length / 2.0, -block_width / 2.0, block_height),
    )
    for x in cylinder_xs:
        chamber = b.hole(
            chamber_diameter,
            chamber_depth + 1.0,
            position=(x, 0.0, block_height - 0.5),
            direction=(0, 0, 1),
        )
        b.boolean_subtract(head, chamber)
    b.chamfer(b.get_top_edges(head), 1.0)

    # Four pistons with wrist pin bores.
    for x in cylinder_xs:
        piston = b.cylinder(
            piston_diameter,
            piston_height,
            origin=(x, 0.0, piston_top_z - piston_height),
            axis=(0, 0, 1),
        )
        wrist = b.hole(
            wrist_pin_diameter,
            block_width + 20.0,
            position=(x, -(block_width + 20.0) / 2.0, wrist_pin_z),
            direction=(0, 1, 0),
        )
        b.boolean_subtract(piston, wrist)
        b.chamfer(b.get_top_edges(piston), 1.0)
        b.chamfer(b.get_bottom_edges(piston), 0.7)

    # Crankshaft: one main journal, four offset crankpins, and simplified web discs.
    crankshaft = b.cylinder(
        main_journal_diameter,
        crankshaft_length,
        origin=(-crankshaft_length / 2.0, crank_axis_y, crank_axis_z),
        axis=(1, 0, 0),
    )
    crankpin_centers = []
    crank_angles = [0.0, 180.0, 180.0, 0.0]
    for x, angle in zip(cylinder_xs, crank_angles):
        radians = math.radians(angle)
        pin_y = crank_axis_y + crank_throw * math.cos(radians)
        pin_z = crank_axis_z + crank_throw * math.sin(radians)
        crankpin_centers.append((x, pin_y, pin_z))

        pin = b.cylinder(
            crankpin_diameter,
            crankpin_width,
            origin=(x - crankpin_width / 2.0, pin_y, pin_z),
            axis=(1, 0, 0),
        )
        b.boolean_unite(crankshaft, pin)

        web_left = b.cylinder(
            82.0,
            8.0,
            origin=(x - crankpin_width / 2.0 - 8.0, crank_axis_y, crank_axis_z),
            axis=(1, 0, 0),
        )
        web_right = b.cylinder(
            82.0,
            8.0,
            origin=(x + crankpin_width / 2.0, crank_axis_y, crank_axis_z),
            axis=(1, 0, 0),
        )
        b.boolean_unite(crankshaft, web_left)
        b.boolean_unite(crankshaft, web_right)
    b.chamfer(b.get_all_edges(crankshaft), 0.8)

    # Connecting rods as individual link plates between wrist pins and crankpins.
    for x, pin_y, pin_z in crankpin_centers:
        points = _rod_plate_points(
            (x, wrist_pin_z),
            (x, pin_z),
            rod_small_outer_radius,
            rod_big_outer_radius,
        )
        rod = b.polygon_prism_on_plane(
            points,
            rod_thickness_y,
            origin=(0.0, -rod_thickness_y / 2.0, 0.0),
            u_axis=(1, 0, 0),
            v_axis=(0, 0, 1),
            extrude_axis=(0, 1, 0),
        )
        small_bore = b.hole(
            rod_small_bore,
            rod_thickness_y + 2.0,
            position=(x, -rod_thickness_y / 2.0 - 1.0, wrist_pin_z),
            direction=(0, 1, 0),
        )
        big_bore = b.hole(
            rod_big_bore,
            rod_thickness_y + 2.0,
            position=(x, -rod_thickness_y / 2.0 - 1.0, pin_z),
            direction=(0, 1, 0),
        )
        b.boolean_subtract(rod, small_bore)
        b.boolean_subtract(rod, big_bore)
        b.chamfer(b.get_all_edges(rod), 0.5)

    # Camshaft and eight simple lobes at paired valve positions.
    camshaft = b.cylinder(
        cam_base_diameter,
        camshaft_length,
        origin=(-camshaft_length / 2.0, 0.0, cam_z),
        axis=(1, 0, 0),
    )
    valve_offsets = [-18.0, 18.0]
    for x in cylinder_xs:
        for y in valve_offsets:
            lobe = b.cylinder(
                cam_lobe_diameter,
                12.0,
                origin=(x - 6.0, y, cam_z + 4.0),
                axis=(1, 0, 0),
            )
            b.boolean_unite(camshaft, lobe)
    b.chamfer(b.get_all_edges(camshaft), 0.6)

    # Hollow valve cover, open on the bottom.
    valve_cover = b.box(
        cover_length,
        cover_width,
        cover_height,
        origin=(-cover_length / 2.0, -cover_width / 2.0, 230.0),
    )
    cover_cavity = b.box(
        cover_length - 2.0 * cover_wall,
        cover_width - 2.0 * cover_wall,
        cover_height,
        origin=(
            -cover_length / 2.0 + cover_wall,
            -cover_width / 2.0 + cover_wall,
            230.0 - 1.0,
        ),
    )
    b.boolean_subtract(valve_cover, cover_cavity)
    b.chamfer(b.get_top_edges(valve_cover), 1.5)

    # Hollow oil pan, open on the top.
    oil_pan = b.box(
        pan_length,
        pan_width,
        pan_depth,
        origin=(-pan_length / 2.0, -pan_width / 2.0, -pan_depth),
    )
    pan_cavity = b.box(
        pan_length - 2.0 * pan_wall,
        pan_width - 2.0 * pan_wall,
        pan_depth,
        origin=(
            -pan_length / 2.0 + pan_wall,
            -pan_width / 2.0 + pan_wall,
            -pan_depth + pan_wall,
        ),
    )
    b.boolean_subtract(oil_pan, pan_cavity)
    b.chamfer(b.get_bottom_edges(oil_pan), 1.5)

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
