# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              stepped_shaft_keyway.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports stepped_shaft_keyway.step.
# ----------------------------------------------------------------------------

import os
import sys

# Ensure cadnx is importable on the NX machine.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Parameters, millimeters
    total_length = 120.0
    end_section_length = 30.0
    middle_section_length = total_length - 2.0 * end_section_length

    end_diameter = 20.0
    middle_diameter = 30.0

    chamfer_offset = 1.0

    keyway_length = 50.0
    keyway_width = 8.0
    keyway_depth = 3.0
    keyway_overcut = 1.0

    x_min = -total_length / 2.0
    left_end_x = x_min
    middle_start_x = left_end_x + end_section_length
    middle_end_x = middle_start_x + middle_section_length
    right_end_x = total_length / 2.0

    end_radius = end_diameter / 2.0
    middle_radius = middle_diameter / 2.0

    # Main stepped shaft along X, centered on the origin.
    shaft = b.cylinder(
        end_diameter,
        end_section_length,
        origin=(left_end_x, 0.0, 0.0),
        axis=(1.0, 0.0, 0.0),
    )

    middle = b.cylinder(
        middle_diameter,
        middle_section_length,
        origin=(middle_start_x, 0.0, 0.0),
        axis=(1.0, 0.0, 0.0),
    )
    b.boolean_unite(shaft, middle)

    right = b.cylinder(
        end_diameter,
        end_section_length,
        origin=(middle_end_x, 0.0, 0.0),
        axis=(1.0, 0.0, 0.0),
    )
    b.boolean_unite(shaft, right)

    # Shallow rectangular keyway on top of the middle section.
    keyway = b.box(
        keyway_length + 2.0 * keyway_overcut,
        keyway_width,
        keyway_depth + keyway_overcut,
        origin=(
            -keyway_length / 2.0 - keyway_overcut,
            -keyway_width / 2.0,
            middle_radius - keyway_depth,
        ),
    )
    b.boolean_subtract(shaft, keyway)

    # Chamfer only the two exposed shaft-end circular edges.
    end_edge_margin = 0.25
    radial_margin = 0.5
    left_end_edges = b.get_edges_in_box(
        shaft,
        (
            left_end_x - end_edge_margin,
            -end_radius - radial_margin,
            -end_radius - radial_margin,
        ),
        (
            left_end_x + end_edge_margin,
            end_radius + radial_margin,
            end_radius + radial_margin,
        ),
    )
    right_end_edges = b.get_edges_in_box(
        shaft,
        (
            right_end_x - end_edge_margin,
            -end_radius - radial_margin,
            -end_radius - radial_margin,
        ),
        (
            right_end_x + end_edge_margin,
            end_radius + radial_margin,
            end_radius + radial_margin,
        ),
    )
    b.chamfer(left_end_edges + right_end_edges, chamfer_offset)

    # Export
    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
