# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              three_axis_brushless_drone_gimbal.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Coordinate convention from prompt: drone forward +X, lateral +Y, vertical Z downward.
    # The isolation plate top face is at Z=0 and the assembly extends toward negative Z.
    through_overcut = 2.0
    feature_overlap = 0.6
    chamfer_offset = 0.6

    # Main prompt parameters.
    iso_plate_length = 86.0
    iso_plate_width = 86.0
    iso_plate_thickness = 8.0
    iso_top_z = 0.0
    m3_pattern = 76.0
    wiring_hole_diameter = 40.0
    damper_ball_diameter = 14.0
    damper_socket_diameter = 12.0
    damper_radius = 45.0

    motor_frame_od = 58.0
    motor_frame_bore = 32.0
    motor_frame_height = 22.0
    stator_bcd = 52.0
    bearing_od = 37.0
    bearing_id = 20.0
    bearing_height = 9.0
    wave_spring_height = 0.3
    motor_od = 56.0
    yaw_motor_height = 18.0
    pitch_motor_height = 18.0
    roll_motor_height = 12.0

    yaw_frame_center = (0.0, 0.0, -18.0)
    yaw_frame_bottom_z = yaw_frame_center[2] - motor_frame_height / 2.0
    yaw_frame_top_z = yaw_frame_center[2] + motor_frame_height / 2.0
    pitch_center = (70.0, 0.0, -28.0)
    roll_center = (70.0, 0.0, -46.0)

    yaw_arm_length = 85.0
    yaw_arm_root_x = 0.0
    yaw_arm_tip_x = yaw_arm_root_x + yaw_arm_length
    yaw_arm_root_width = 25.0
    yaw_arm_tip_width = 18.0
    yaw_arm_thickness = 12.0
    yaw_arm_z = -28.0
    yaw_arm_bottom_z = yaw_arm_z - yaw_arm_thickness / 2.0
    yaw_arm_top_z = yaw_arm_z + yaw_arm_thickness / 2.0

    controller_length = 45.0
    controller_width = 35.0
    controller_height = 12.0
    controller_center = (35.0, 0.0, -32.0)

    camera_plate_length = 50.0
    camera_plate_width = 40.0
    camera_plate_thickness = 6.0
    camera_plate_center = (92.0, 0.0, -46.0)

    shroud_id = 65.0
    shroud_od = 75.0
    shroud_height = 90.0
    shroud_center = (105.0, 0.0, -46.0)
    shroud_slot_length = 62.0
    shroud_slot_tangent_width = 7.0
    shroud_slot_radial_overcut = 2.0

    slip_ring_od = 22.0
    slip_ring_height = 35.0
    ring_thickness = 0.5
    ring_spacing = 1.0

    b.require_positive(
        iso_plate_length=iso_plate_length,
        iso_plate_width=iso_plate_width,
        iso_plate_thickness=iso_plate_thickness,
        motor_frame_od=motor_frame_od,
        motor_frame_bore=motor_frame_bore,
        shroud_od=shroud_od,
        shroud_id=shroud_id,
    )
    b.require_min_wall(motor_frame_od, motor_frame_bore, min_wall=6.0, label="motor frame bore")
    b.require_min_wall(shroud_od, shroud_id, min_wall=2.0, label="carbon shroud wall")
    b.require_feature_budget(boolean_operations=54, micro_holes=24, patterned_features=88)

    def cyl(name_diameter, name_height, center, axis=(0, 0, 1)):
        ax = axis
        origin = (
            center[0] - ax[0] * name_height / 2.0,
            center[1] - ax[1] * name_height / 2.0,
            center[2] - ax[2] * name_height / 2.0,
        )
        return b.cylinder(name_diameter, name_height, origin=origin, axis=axis)

    def cut_cylinder(target, diameter, depth, center, axis):
        ax = axis
        origin = (
            center[0] - ax[0] * depth / 2.0,
            center[1] - ax[1] * depth / 2.0,
            center[2] - ax[2] * depth / 2.0,
        )
        tool = b.cylinder(diameter, depth, origin=origin, axis=axis)
        b.boolean_subtract(target, tool)

    def add_ring(center, od, id_diameter, height, axis=(0, 0, 1)):
        body = cyl(od, height, center, axis)
        cut_cylinder(body, id_diameter, height + through_overcut, center, axis)
        return body

    def add_circular_holes(target, center, radius, count, diameter, depth, axis, start_angle=0.0):
        for i in range(count):
            angle = math.radians(start_angle + 360.0 * i / count)
            if axis == (0, 0, 1):
                pos = (center[0] + radius * math.cos(angle), center[1] + radius * math.sin(angle), center[2])
            elif axis == (0, 1, 0):
                pos = (center[0] + radius * math.cos(angle), center[1], center[2] + radius * math.sin(angle))
            else:
                pos = (center[0], center[1] + radius * math.cos(angle), center[2] + radius * math.sin(angle))
            cut_cylinder(target, diameter, depth, pos, axis)

    # Vibration isolation plate, holes, wiring opening, conical-socket representation, and dampers.
    plate = b.rounded_box(
        iso_plate_length,
        iso_plate_width,
        iso_plate_thickness,
        radius=3.0,
        origin=(-iso_plate_length / 2.0, -iso_plate_width / 2.0, iso_top_z - iso_plate_thickness),
    )
    for x in (-m3_pattern / 2.0, m3_pattern / 2.0):
        for y in (-m3_pattern / 2.0, m3_pattern / 2.0):
            b.screw_clearance_hole(plate, "M3", iso_plate_thickness + through_overcut, position=(x, y, iso_top_z + 1.0), direction=(0, 0, -1))
    cut_cylinder(plate, wiring_hole_diameter, iso_plate_thickness + through_overcut, (0.0, 0.0, iso_top_z - iso_plate_thickness / 2.0), (0, 0, 1))
    for x, y, _z in b.circular_pattern_points((0.0, 0.0, iso_top_z), damper_radius, 4, start_angle_degrees=45.0):
        cut_cylinder(plate, damper_socket_diameter, 5.0, (x, y, iso_top_z - 2.5), (0, 0, 1))
        cyl(damper_ball_diameter, damper_ball_diameter, (x, y, -15.0), (0, 0, 1))
        b.cylinder(8.0, 10.0, origin=(x, y, -8.5), axis=(0, 0, -1))

    # Yaw motor frame, bearings, wave spring, stator, rotor, hall PCB, and slip ring.
    yaw_frame = add_ring(yaw_frame_center, motor_frame_od, motor_frame_bore, motor_frame_height, (0, 0, 1))
    add_circular_holes(yaw_frame, yaw_frame_center, stator_bcd / 2.0, 4, 2.9, motor_frame_height + through_overcut, (0, 0, 1), 45.0)
    cyl(bearing_od, bearing_height, (0.0, 0.0, yaw_frame_top_z - bearing_height / 2.0), (0, 0, 1))
    cyl(bearing_od, bearing_height, (0.0, 0.0, yaw_frame_bottom_z + bearing_height / 2.0), (0, 0, 1))
    cyl(36.0, wave_spring_height, (0.0, 0.0, yaw_frame_center[2]), (0, 0, 1))
    stator = add_ring((0.0, 0.0, -18.0), 48.0, bearing_id, 10.0, (0, 0, 1))
    for i in range(24):
        angle = math.radians(360.0 * i / 24)
        x = 18.5 * math.cos(angle)
        y = 18.5 * math.sin(angle)
        tooth = b.box(8.0, 2.2, 8.0, origin=(x - 4.0, y - 1.1, -22.0))
        b.boolean_unite(stator, tooth)
        cyl(1.4, 7.0, (22.5 * math.cos(angle), 22.5 * math.sin(angle), -18.0), (0, 0, 1))
    yaw_rotor = add_ring((0.0, 0.0, -18.0), motor_od, 50.0, yaw_motor_height, (0, 0, 1))
    for i in range(20):
        angle = math.radians(360.0 * i / 20)
        cyl(3.0, 6.0, (26.5 * math.cos(angle), 26.5 * math.sin(angle), -18.0), (0, 0, 1))
    hall_pcb = add_ring((0.0, 0.0, -7.5), 42.0, 24.0, 1.2, (0, 0, 1))
    for i in range(3):
        angle = math.radians(120.0 * i)
        b.box(4.0, 2.0, 1.0, origin=(17.0 * math.cos(angle) - 2.0, 17.0 * math.sin(angle) - 1.0, -6.8))
    slip = cyl(slip_ring_od, slip_ring_height, (0.0, 0.0, yaw_frame_center[2]), (0, 0, 1))
    for i in range(12):
        z = yaw_frame_center[2] - 8.25 + i * ring_spacing
        cyl(slip_ring_od + 1.2, ring_thickness, (0.0, 0.0, z), (0, 0, 1))
    cyl(24.0, 1.2, (0.0, 0.0, yaw_frame_top_z + 0.8), (0, 0, 1))
    cyl(24.0, 1.2, (0.0, 0.0, yaw_frame_bottom_z - 0.8), (0, 0, 1))

    # Carbon fiber yaw arm with taper approximation, 7075 root insert, keyway, and M8 attachment holes.
    arm_root = b.box(45.0, yaw_arm_root_width, yaw_arm_thickness, origin=(0.0, -yaw_arm_root_width / 2.0, yaw_arm_bottom_z))
    arm_tip = b.box(
        40.0 + feature_overlap,
        yaw_arm_tip_width,
        yaw_arm_thickness,
        origin=(45.0 - feature_overlap, -yaw_arm_tip_width / 2.0, yaw_arm_bottom_z),
    )
    b.boolean_unite(arm_root, arm_tip)
    root_insert = add_ring((10.0, 0.0, yaw_arm_z), 36.0, 20.0, 10.0, (0, 0, 1))
    key = b.box(4.0, 10.0, 10.0, origin=(18.0, -5.0, yaw_arm_z - 5.0))
    b.boolean_subtract(root_insert, key)
    for x in (65.0, 75.0):
        b.screw_clearance_hole(arm_root, "M8", yaw_arm_thickness + through_overcut, position=(x, 0.0, yaw_arm_top_z + 1.0), direction=(0, 0, -1))

    # Pitch and roll frames/motors along requested axes.
    pitch_frame = add_ring(pitch_center, motor_frame_od, motor_frame_bore, motor_frame_height, (0, 1, 0))
    add_circular_holes(pitch_frame, pitch_center, stator_bcd / 2.0, 4, 2.9, motor_frame_height + through_overcut, (0, 1, 0), 45.0)
    pitch_motor = add_ring(pitch_center, motor_od, 50.0, pitch_motor_height, (0, 1, 0))
    pitch_hub = cyl(25.0, 16.0, pitch_center, (0, 1, 0))
    add_circular_holes(pitch_hub, pitch_center, 9.0, 4, 3.4, 28.0, (0, 1, 0), 45.0)
    for x in (65.0, 75.0):
        cyl(15.5, 1.2, (x, 0.0, yaw_arm_bottom_z - 0.7), (0, 0, 1))

    roll_frame = add_ring(roll_center, motor_frame_od, motor_frame_bore, motor_frame_height, (1, 0, 0))
    add_circular_holes(roll_frame, roll_center, stator_bcd / 2.0, 4, 2.9, motor_frame_height + through_overcut, (1, 0, 0), 45.0)
    roll_motor = add_ring(roll_center, motor_od, 30.0, roll_motor_height, (1, 0, 0))
    add_circular_holes(roll_motor, roll_center, 12.0, 4, 2.9, 20.0, (1, 0, 0), 45.0)

    # Camera plate, roll hub engagement boss, dovetail rail, locking pin, and 1/4-20 holes.
    cam_plate = b.rounded_box(
        camera_plate_length,
        camera_plate_width,
        camera_plate_thickness,
        radius=2.0,
        origin=(camera_plate_center[0] - camera_plate_length / 2.0, -camera_plate_width / 2.0, camera_plate_center[2] - camera_plate_thickness / 2.0),
    )
    boss = cyl(30.0, 8.0, (camera_plate_center[0] - 18.0, 0.0, camera_plate_center[2]), (1, 0, 0))
    for i in range(4):
        angle = math.radians(45.0 + i * 90.0)
        pos = (camera_plate_center[0] - 25.0, 12.0 * math.cos(angle), camera_plate_center[2] + 12.0 * math.sin(angle))
        cut_cylinder(boss, 2.9, 12.0, pos, (1, 0, 0))
    rail = b.box(38.0, 38.0, 5.0, origin=(camera_plate_center[0] - 19.0, -19.0, camera_plate_center[2] - camera_plate_thickness / 2.0 - 5.0 + feature_overlap))
    b.boolean_unite(cam_plate, rail)
    for y in (-16.0, 16.0):
        for z in (camera_plate_center[2] - 12.0, camera_plate_center[2] + 12.0):
            cut_cylinder(cam_plate, 6.6, camera_plate_thickness + 4.0, (camera_plate_center[0], y, z), (1, 0, 0))
    cyl(4.0, 6.0, (camera_plate_center[0] + 20.0, -24.0, camera_plate_center[2] - 5.0), (0, 1, 0))

    # Controller stack with power, logic, and sensor layers plus ceramic antenna.
    for i, label_z in enumerate((-36.0, -32.0, -28.0)):
        layer = b.box(controller_length, controller_width, 3.0, origin=(controller_center[0] - controller_length / 2.0, -controller_width / 2.0, label_z - 1.5))
        if i == 0:
            for j in range(3):
                b.box(7.0, 5.0, 1.0, origin=(controller_center[0] - 18.0 + j * 12.0, -12.0, label_z + 1.5 - feature_overlap))
        elif i == 1:
            b.box(10.0, 10.0, 1.0, origin=(controller_center[0] - 5.0, -5.0, label_z + 1.5 - feature_overlap))
        else:
            b.box(7.0, 7.0, 1.0, origin=(controller_center[0] - 11.0, 5.0, label_z + 1.5 - feature_overlap))
            b.box(6.0, 6.0, 1.0, origin=(controller_center[0] + 4.0, 6.0, label_z + 1.5 - feature_overlap))
    b.box(12.0, 4.0, 1.2, origin=(controller_center[0] + 12.0, 13.0, -26.0))

    # Carbon fiber camera shroud with 12 ventilation slots, bumper ring, and optical window.
    shroud = add_ring(shroud_center, shroud_od, shroud_id, shroud_height, (1, 0, 0))
    shroud_mid_radius = (shroud_od + shroud_id) / 4.0
    shroud_slot_radial_depth = (shroud_od - shroud_id) / 2.0 + 2.0 * shroud_slot_radial_overcut
    for i in range(12):
        angle = math.radians(30.0 * i)
        radial_axis = (0.0, math.cos(angle), math.sin(angle))
        tangent_axis = (0.0, -math.sin(angle), math.cos(angle))
        slot_center = (
            shroud_center[0],
            shroud_mid_radius * math.cos(angle),
            shroud_center[2] + shroud_mid_radius * math.sin(angle),
        )
        slot = b.oriented_box(
            shroud_slot_length,
            shroud_slot_tangent_width,
            shroud_slot_radial_depth,
            center=slot_center,
            u_axis=(1.0, 0.0, 0.0),
            v_axis=tangent_axis,
            w_axis=radial_axis,
        )
        b.boolean_subtract(shroud, slot)
    cyl(shroud_od + 10.0, 3.0, (shroud_center[0] + shroud_height / 2.0 - 1.0, 0.0, shroud_center[2]), (1, 0, 0))
    cyl(25.0, 2.0, (shroud_center[0] + shroud_height / 2.0 + 1.5, 0.0, shroud_center[2]), (1, 0, 0))

    # Focus motor, gearbox, timing belt, lens gear, and encoder.
    focus_x = shroud_center[0] + 10.0
    focus_y = -45.0
    focus_z = shroud_center[2] - 8.0
    cyl(16.0, 28.0, (focus_x, focus_y, focus_z), (1, 0, 0))
    cyl(18.0, 10.0, (focus_x + 19.0, focus_y, focus_z), (1, 0, 0))
    cyl(8.0, 8.0, (focus_x + 28.0, focus_y, focus_z), (1, 0, 0))
    cyl(20.0, 6.0, (shroud_center[0] + 45.0, -30.0, focus_z), (1, 0, 0))
    for i in range(40):
        angle = math.radians(i * 9.0)
        cyl(1.0, 2.0, (shroud_center[0] + 48.0, -30.0 + 10.7 * math.cos(angle), focus_z + 10.7 * math.sin(angle)), (1, 0, 0))
    belt_top = b.box(42.0, 4.0, 1.2, origin=(focus_x + 27.0, -42.0, focus_z + 8.0))
    b.box(42.0, 4.0, 1.2, origin=(focus_x + 27.0, -42.0, focus_z - 9.2))
    cyl(9.0, 2.0, (focus_x + 35.0, focus_y, focus_z), (1, 0, 0))

    # Tungsten counterweights on M6 rods.
    for y in (-15.0, 15.0):
        cyl(6.0, 42.0, (-10.0, y, -32.0), (1, 0, 0))
        cyl(12.0, 25.0, (-31.0, y, -32.0), (1, 0, 0))

    # Three AISI 440C calibration cubes on the roll frame (+X, +Y, +Z faces).
    b.box(10.0, 10.0, 2.0, origin=(roll_center[0] + motor_frame_height / 2.0, -5.0, roll_center[2] - 5.0))
    b.box(10.0, 2.0, 10.0, origin=(roll_center[0] - 5.0, motor_frame_od / 2.0, roll_center[2] - 5.0))
    b.box(10.0, 10.0, 2.0, origin=(roll_center[0] - 5.0, -5.0, roll_center[2] + motor_frame_od / 2.0))

    # Conservative edge breaks on simple bodies.
    for feature in (plate, yaw_frame, arm_root, pitch_frame, roll_frame, cam_plate, shroud):
        try:
            b.chamfer(b.get_top_edges(feature), chamfer_offset)
        except Exception:
            pass

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
