# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              this_script.py
#              cadnx/
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Independent prompt parameters, millimeters.
    body_length_x = 280.0
    body_width_y = 195.0
    body_height_z = 142.0
    body_top_z = 0.0
    body_bottom_z = body_top_z - body_height_z

    main_bore_diameter = 85.0
    main_bore_length = 120.0
    main_bore_z = -71.0
    lead_chamfer = 2.0

    wing_lug_length_x = 65.0
    wing_lug_width_y = 95.0
    wing_lug_height_z = 85.0
    wing_lug_center_y = 71.0
    wing_lug_bore_diameter = 32.0
    wing_lug_bore_depth = 65.0
    wing_lug_fillet = 5.0

    shock_boss_diameter = 110.0
    shock_boss_height = 95.0
    shock_boss_top_z = body_bottom_z + 0.8
    shock_boss_center_z = shock_boss_top_z - shock_boss_height / 2.0
    internal_thread_nominal_diameter = 80.0
    internal_thread_minor_diameter = 78.0
    internal_thread_depth = 60.0

    side_lug_length_x = 55.0
    side_lug_width_y = 75.0
    side_lug_height_z = 60.0
    side_lug_center = (140.0, 0.0, -95.0)
    side_lug_bore_diameter = 28.0
    side_lug_cant_degrees = 12.0

    drag_ear_length_x = 40.0
    drag_ear_width_y = 60.0
    drag_ear_height_z = 50.0
    drag_ear_center = (-120.0, 0.0, -110.0)
    drag_ear_bore_diameter = 22.0
    drag_ear_incline_degrees = 8.0

    pocket_diameter = 32.0
    pocket_depth = 18.0
    pocket_floor_relief = 2.0
    pocket_centers = [
        (80.0, 50.0, -30.0),
        (80.0, -50.0, -30.0),
        (-80.0, 50.0, -30.0),
        (-80.0, -50.0, -30.0),
        (60.0, 0.0, -50.0),
        (-60.0, 0.0, -50.0),
    ]

    test_port_diameter = 8.5
    test_port_counter_diameter = 10.0
    test_port_depth = 15.0
    test_port_center = (0.0, body_width_y / 2.0 + 0.5, main_bore_z)

    bushing_outer_diameter = 32.0
    bushing_inner_diameter = 22.0
    bushing_length = 40.0

    parting_ridge_height = 0.3
    parting_ridge_width_z = 2.0
    parting_ridge_z = -35.0

    data_plate_length = 25.0
    data_plate_height = 15.0
    data_plate_thickness = 0.5

    through_overcut = 8.0
    cutter_overlap = 1.0
    feature_overlap = 0.8
    edge_break = 0.8
    radial_feed_outer_radius = main_bore_diameter / 2.0 + 54.0
    radial_feed_inner_radius = main_bore_diameter / 2.0 - 4.0

    # Process notes encoded in source for downstream CAD/PDM users:
    # Ti-6Al-4V ELI forging, HIP processed, solution treated 925 C, aged 480 C.
    # Target properties: 1100 MPa UTS, 55 MPa*sqrt(m) toughness.
    # Surfaces Ra 3.2 um; bearing bores Ra 0.8 um except honed trunnion Ra 0.4 um.
    # Corrosion protection: alkaline clean, fluoride-phosphate pretreatment,
    # MIL-PRF-85285 polyurethane primer 50 um, FS 36375 gray topcoat 75 um.
    # Bearing surfaces remain bare with MIL-PRF-81322 grease.

    b.require_positive(
        body_length_x=body_length_x,
        body_width_y=body_width_y,
        body_height_z=body_height_z,
        main_bore_diameter=main_bore_diameter,
        shock_boss_diameter=shock_boss_diameter,
    )
    b.require_min_wall(body_width_y, main_bore_length, min_wall=20.0, label="main trunnion bore length envelope")
    b.require_min_wall(wing_lug_width_y, wing_lug_bore_diameter, min_wall=8.0, label="upper wing lug bore")
    b.require_min_wall(shock_boss_diameter, internal_thread_nominal_diameter, min_wall=12.0, label="lower shock boss thread")
    b.require_feature_budget(boolean_operations=56, micro_holes=26, patterned_features=36)

    # Primary Ti forging body, top plane at Z = 0.
    body = b.rounded_box(
        body_length_x,
        body_width_y,
        body_height_z,
        radius=3.0,
        origin=(-body_length_x / 2.0, -body_width_y / 2.0, body_bottom_z),
    )

    # Upper wing lugs at Y = +/-71 mm.
    for y_sign in (-1.0, 1.0):
        lug = b.rounded_box(
            wing_lug_length_x,
            wing_lug_width_y,
            wing_lug_height_z,
            radius=wing_lug_fillet,
            origin=(
                -wing_lug_length_x / 2.0,
                y_sign * wing_lug_center_y - wing_lug_width_y / 2.0,
                -wing_lug_height_z,
            ),
        )
        b.boolean_unite(body, lug)

        bore_start_y = y_sign * (wing_lug_center_y + wing_lug_width_y / 2.0 + cutter_overlap)
        bore_direction = (0.0, -y_sign, 0.0)
        bore = b.hole(
            wing_lug_bore_diameter,
            wing_lug_bore_depth + through_overcut,
            position=(0.0, bore_start_y, -wing_lug_height_z / 2.0),
            direction=bore_direction,
        )
        b.boolean_subtract(body, bore)

        # Press-fit bushing bodies, modeled as cadmium-plated steel inserts.
        bushing_start_y = y_sign * (wing_lug_center_y - y_sign * bushing_length / 2.0)
        bushing = b.cylinder(
            bushing_outer_diameter,
            bushing_length,
            origin=(0.0, bushing_start_y, -wing_lug_height_z / 2.0),
            axis=(0.0, y_sign, 0.0),
        )
        inner = b.hole(
            bushing_inner_diameter,
            bushing_length + through_overcut,
            position=(0.0, bushing_start_y - y_sign * cutter_overlap, -wing_lug_height_z / 2.0),
            direction=(0.0, y_sign, 0.0),
        )
        b.boolean_subtract(bushing, inner)
        for channel_index in range(3):
            angle = math.radians(channel_index * 120.0)
            x = math.cos(angle) * (bushing_inner_diameter / 2.0 + 1.0)
            z = -wing_lug_height_z / 2.0 + math.sin(angle) * (bushing_inner_diameter / 2.0 + 1.0)
            channel = b.box(
                1.5,
                bushing_length + through_overcut,
                1.0,
                origin=(x - 0.75, bushing_start_y - y_sign * cutter_overlap, z - 0.5),
            )
            b.boolean_subtract(bushing, channel)

        # Serration witness on outer faces, simplified as shallow pitch grooves.
        outer_face_y = y_sign * (wing_lug_center_y + wing_lug_width_y / 2.0)
        for idx in range(9):
            x = -24.0 + idx * 6.0
            groove = b.box(
                0.8,
                1.2,
                38.0,
                origin=(x, outer_face_y - y_sign * 0.6, -62.0),
            )
            b.boolean_subtract(body, groove)

    # Main trunnion bore along Y, grease grooves, radial feed holes and lead-ins.
    main_bore = b.hole(
        main_bore_diameter,
        main_bore_length + through_overcut,
        position=(0.0, -(main_bore_length / 2.0 + through_overcut / 2.0), main_bore_z),
        direction=(0.0, 1.0, 0.0),
    )
    b.boolean_subtract(body, main_bore)
    for y in (-30.0, 30.0):
        groove = b.cylinder(
            main_bore_diameter + 4.0,
            3.0,
            origin=(0.0, y - 1.5, main_bore_z),
            axis=(0.0, 1.0, 0.0),
        )
        core = b.cylinder(
            main_bore_diameter,
            4.0,
            origin=(0.0, y - 2.0, main_bore_z),
            axis=(0.0, 1.0, 0.0),
        )
        b.boolean_subtract(groove, core)
        b.boolean_subtract(body, groove)
    for angle_degrees in range(0, 270, 45):
        angle = math.radians(angle_degrees)
        feed_outer_x = math.cos(angle) * radial_feed_outer_radius
        feed_outer_z = main_bore_z + math.sin(angle) * radial_feed_outer_radius
        feed_depth = radial_feed_outer_radius - radial_feed_inner_radius
        feed = b.cylinder(
            4.0,
            feed_depth,
            origin=(feed_outer_x, 0.0, feed_outer_z),
            axis=(-math.cos(angle), 0.0, -math.sin(angle)),
        )
        b.boolean_subtract(body, feed)
    for y in (-main_bore_length / 2.0, main_bore_length / 2.0):
        chamfer_relief = b.cylinder(
            main_bore_diameter + 2.0 * lead_chamfer,
            lead_chamfer + cutter_overlap,
            origin=(0.0, y - math.copysign(cutter_overlap, y), main_bore_z),
            axis=(0.0, math.copysign(1.0, y), 0.0),
        )
        b.boolean_subtract(body, chamfer_relief)

    # Lower shock boss with simplified M80 x 2 internal thread relief.
    shock_boss = b.cylinder(
        shock_boss_diameter,
        shock_boss_height,
        origin=(0.0, 0.0, shock_boss_top_z),
        axis=(0.0, 0.0, -1.0),
    )
    b.boolean_unite(body, shock_boss)
    thread_core = b.hole(
        internal_thread_minor_diameter,
        internal_thread_depth + cutter_overlap,
        position=(0.0, 0.0, shock_boss_top_z + cutter_overlap),
        direction=(0.0, 0.0, -1.0),
    )
    b.boolean_subtract(body, thread_core)
    for z in [shock_boss_top_z - 8.0 - 2.0 * i for i in range(12)]:
        relief = b.cylinder(
            internal_thread_nominal_diameter,
            0.6,
            origin=(0.0, 0.0, z),
            axis=(0.0, 0.0, -1.0),
        )
        b.boolean_subtract(body, relief)
    for angle_degrees in (0.0, 90.0, 180.0, 270.0):
        angle = math.radians(angle_degrees)
        x = math.cos(angle) * (shock_boss_diameter / 2.0 + cutter_overlap)
        y = math.sin(angle) * (shock_boss_diameter / 2.0 + cutter_overlap)
        lockwire = b.hole(2.0, 16.0, position=(x, y, shock_boss_top_z - shock_boss_height + 8.0), direction=(-math.cos(angle), -math.sin(angle), 0.0))
        b.boolean_subtract(body, lockwire)

    # Side brace lug, canted 12 degrees from vertical in XZ plane.
    side_lug = b.rounded_box(
        side_lug_length_x,
        side_lug_width_y,
        side_lug_height_z,
        radius=3.0,
        origin=(
            side_lug_center[0] - side_lug_length_x / 2.0,
            side_lug_center[1] - side_lug_width_y / 2.0,
            side_lug_center[2] - side_lug_height_z / 2.0,
        ),
    )
    b.boolean_unite(body, side_lug)
    side_angle = math.radians(side_lug_cant_degrees)
    side_axis = (math.sin(side_angle), 0.0, math.cos(side_angle))
    side_bore = b.hole(side_lug_bore_diameter, side_lug_height_z + through_overcut, position=side_lug_center, direction=side_axis)
    b.boolean_subtract(body, side_bore)
    circlip = b.cylinder(side_lug_bore_diameter + 3.0, 1.5, origin=(side_lug_center[0], side_lug_center[1], side_lug_center[2] + 18.0), axis=side_axis)
    b.boolean_subtract(body, circlip)

    # Drag brace ear with 8 degree forward-inclined bore and tapered transition pad.
    drag_ear = b.rounded_box(
        drag_ear_length_x,
        drag_ear_width_y,
        drag_ear_height_z,
        radius=1.5,
        origin=(
            drag_ear_center[0] - drag_ear_length_x / 2.0,
            drag_ear_center[1] - drag_ear_width_y / 2.0,
            drag_ear_center[2] - drag_ear_height_z / 2.0,
        ),
    )
    b.boolean_unite(body, drag_ear)
    transition = b.polygon_prism_on_plane(
        [(-15.0, -25.0), (15.0, -20.0), (15.0, 20.0), (-15.0, 25.0)],
        drag_ear_width_y,
        origin=(-140.0, -drag_ear_width_y / 2.0, -126.0),
        u_axis=(1.0, 0.0, 0.0),
        v_axis=(0.0, 0.0, 1.0),
        extrude_axis=(0.0, 1.0, 0.0),
    )
    b.boolean_unite(body, transition)
    drag_angle = math.radians(drag_ear_incline_degrees)
    drag_bore = b.hole(drag_ear_bore_diameter, drag_ear_width_y + through_overcut, position=drag_ear_center, direction=(math.sin(drag_angle), 1.0, 0.0))
    b.boolean_subtract(body, drag_bore)

    # EDM weight-reduction pockets on non-load faces, top-driven with floor relief indicators.
    for center in pocket_centers:
        pocket_top_z = body_top_z + cutter_overlap
        pocket_floor_z = center[2] - pocket_depth
        pocket_cut_depth = pocket_top_z - pocket_floor_z
        pocket = b.hole(
            pocket_diameter,
            pocket_cut_depth,
            position=(center[0], center[1], pocket_top_z),
            direction=(0.0, 0.0, -1.0),
        )
        b.boolean_subtract(body, pocket)
        floor = b.hole(
            pocket_diameter - 2.0 * pocket_floor_relief,
            pocket_cut_depth + 0.8,
            position=(center[0], center[1], pocket_top_z),
            direction=(0.0, 0.0, -1.0),
        )
        b.boolean_subtract(body, floor)

    # Pressurization test port and radial connection to the main bore.
    port = b.hole(
        test_port_diameter,
        test_port_depth + cutter_overlap,
        position=test_port_center,
        direction=(0.0, -1.0, 0.0),
    )
    b.boolean_subtract(body, port)
    port_counter = b.hole(
        test_port_counter_diameter,
        3.0,
        position=test_port_center,
        direction=(0.0, -1.0, 0.0),
    )
    b.boolean_subtract(body, port_counter)
    radial = b.hole(3.0, body_width_y / 2.0, position=(0.0, body_width_y / 2.0, main_bore_z), direction=(0.0, -1.0, 0.0))
    b.boolean_subtract(body, radial)

    # Forging parting-line witness ridge at Y = 0, Z = -35.
    ridge = b.box(
        body_length_x - 20.0,
        parting_ridge_height,
        parting_ridge_width_z,
        origin=(-(body_length_x - 20.0) / 2.0, -parting_ridge_height / 2.0, parting_ridge_z - parting_ridge_width_z / 2.0),
    )
    b.boolean_unite(body, ridge)

    # UT reference notch at rear side face.
    notch = b.box(
        8.0,
        1.5,
        0.5,
        origin=(-94.0, body_width_y / 2.0 - 1.0, -20.25),
    )
    b.boolean_subtract(body, notch)

    # Stainless data plate and two rivets at X = +100, Y = +98, Z = -10.
    data_plate = b.box(
        data_plate_length,
        data_plate_thickness,
        data_plate_height,
        origin=(100.0 - data_plate_length / 2.0, body_width_y / 2.0, -10.0 - data_plate_height / 2.0),
    )
    rivet_pitch = 17.0
    for x in (100.0 - rivet_pitch / 2.0, 100.0 + rivet_pitch / 2.0):
        rivet = b.cylinder(3.2, 1.4, origin=(x, body_width_y / 2.0 + data_plate_thickness, -10.0), axis=(0.0, 1.0, 0.0))
        b.boolean_unite(data_plate, rivet)

    # Small global edge break. Critical bore finish/tolerance/coating callouts are retained as comments.
    b.chamfer(b.get_edges_in_box(body, (-142.0, -99.0, -144.0), (142.0, 99.0, 2.0)), edge_break)

    # Data plate marking text represented in model source:
    # LG-TR-195-85; serial; heat lot; HIP cycle;
    # max loads: 142 kN vertical, +/-68 kN drag, +/-45 kN side.
    # Main trunnion bore: 85 H7, cylindricity 0.01, straightness 0.005, honed Ra 0.4.
    # Wing lug bores: 32 H8, 0.008 roundness, ground Ra 0.2.
    # Side brace lug bore: 28 H8 with 1.5 mm circlip groove.
    # Drag brace ear bore: 22 H9, 0.5 mm root fillet, 15 mm tapered transition.
    # M80 x 2 internal thread: 6H tolerance, 0.05 pitch accuracy, 0.4 root relief,
    # Cu-Ni anti-galling coating 8 um Cu + 2 um Ni on flanks.

    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
